kubernetes-sigs/cloud-provider-azure

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
Cherry pick change #2363 
Fixes #
```release-note
Only check response body length when request is GET. Avoids unnecessary retry when deleting an LB.
```
```docs
```
=> [release-1.1] fix: Do not retry regional when request is not GET

pkg/provider/azure.go, pkg/provider/azure_loadbalancer_test.go
/kind cleanup
fix typo and use consts in azure_loadbalancer_test.go
Fixes #
```release-note
NONE
```
```docs
```
=> fix typo and use consts in azure_loadbalancer_test.go

pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex_cache.go
/kind cleanup
Remove the node from the VMSS VM cache if it is deleted. This will help reduce the chance of conflict between aks and cloud provider azure.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: remove node from VMSS VM cache when it is deleted

pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_mock_vmsets_test.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go
(cherry picked from commit 8b53dd895e555fa0fbbe1ab8854853e086871b02)
/kind cleanup
Cherry pick of #2402: Remove the node from the VMSS VM cache if it is deleted. This will help reduce the chance of conflict between aks and cloud provider azure.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] chore: remove node from VMSS VM cache when it is deleted

pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go
(cherry picked from commit 8b53dd895e555fa0fbbe1ab8854853e086871b02)
/kind cleanup
Cherry pick of #2402: Remove the node from the VMSS VM cache if it is deleted. This will help reduce the chance of conflict between aks and cloud provider azure.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] chore: remove node from VMSS VM cache when it is deleted

pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go
(cherry picked from commit 8b53dd895e555fa0fbbe1ab8854853e086871b02)
/kind cleanup
Cherry pick of #2402: Remove the node from the VMSS VM cache if it is deleted. This will help reduce the chance of conflict between aks and cloud provider azure.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] chore: remove node from VMSS VM cache when it is deleted

.pipelines/var-e2e.yml
/kind cleanup
Update k8s version in aks pipeline to "1.24.3" because current aks doesn't support aks version "1.24.0" any more
Fixes #
```release-note
NONE
```
```docs
```
=> update k8s version in aks pipeline

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
related #2420 
```release-note
```
```docs
```
=> [release-1.23] Check flipped service in GetLoadBalancer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
related #2420 
```release-note
```
```docs
```
=> [release-1.1] Check flipped service in GetLoadBalancer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
related #2420 
```release-note
```
```docs
```
=> [release-1.25] Check flipped service in GetLoadBalancer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
related #2420 
```release-note
```
```docs
```
=> [release-1.24] Check flipped service in GetLoadBalancer

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/pod_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[release-1.23] cherrypick 1846, 1996
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] cherrypick 1846, 1996

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/pod_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[release-1.1] cherrypick 1846, 1996
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] cherrypick 1846, 1996

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/pod_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[release-1.24] cherry-pick 1846, 1996
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] cherry-pick 1846, 1996

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/private_link_service.go, tests/e2e/utils/network_utils.go
/kind testing
Fixes #
related #2153 
```release-note
NONE
```
```docs
```
=> [release-1.23] Add e2e tests to avoid redundant reconciliation

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/private_link_service.go, tests/e2e/utils/network_utils.go
/kind testing
Fixes #
related #2153 
```release-note
NONE
```
```docs
```
=> [release-1.24] Add e2e tests to avoid redundant reconciliation

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/private_link_service.go, tests/e2e/utils/network_utils.go
/kind testing
Fixes #
related #2153 
```release-note
NONE
```
```docs
```
=> [release-1.1] Add e2e tests to avoid redundant reconciliation

hack/ensure-ginkgo-v2.sh
/kind testing
Pin gingko version to v2.2.0
Fixes #
```release-note
NONE
```
```docs
```
=> Pin gingko version to v2.2.0

pkg/provider/azure_storageaccount.go
/kind bug
chore: only set accessTier when it's specified
Fixes #
```release-note
none
```
```docs
none
```
=> chore: only set accessTier when it's specified

tests/e2e/network/service_annotations.go
/kind testing
[e2e] Should clean up pip in azure-load-balancer-ip annotation test
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Should clean up pip in azure-load-balancer-ip annotation test

tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go
/kind testing
* Can avoid printing stdout and stderr when run kubectl
* Service CIDR is hardcoded to IPv4 for AKS pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> Adjust e2e tests

.github/workflows/codeql-analysis.yml, .github/workflows/release.yaml, .github/workflows/trivy.yaml
/kind cleanup
fix build error in release pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> Update go version params of github action

pkg/provider/azure_loadbalancer.go
/kind cleanup
do no use netip package in release-1.23
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23]do not use netip package

pkg/provider/azure_loadbalancer.go
/kind cleanup
remove netip dependency in release-1.1
Fixes #
```release-note
NONE
```
```docs
```
=> do not use netip package

.github/workflows/codeql-analysis.yml, .github/workflows/release.yaml, .github/workflows/trivy.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23]update go version params of github action

tests/e2e/utils/pod_utils.go
chore: describe and get pod log when it is failed to gain insight.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: describe and get pod log when it is failed

tests/e2e/network/standard_lb.go
fix: add bin/sh -s to the e2e pod command as the `curl` is not in the PATH.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: add bin/sh -s to the e2e pod command

tests/e2e/network/standard_lb.go, tests/e2e/utils/pod_utils.go
/kind testing
Refactor e2e and print more Pod info if unexpected error
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor e2e and print more Pod info if unexpected error

tests/e2e/network/standard_lb.go, tests/e2e/utils/pod_utils.go
/kind testing
[release-1.24] Refactor e2e and print more Pod info if unexpected error
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] Refactor e2e and print more Pod info if unexpected error

tests/e2e/network/standard_lb.go, tests/e2e/utils/pod_utils.go
/kind testing
[release-1.23] Refactor e2e and print more Pod info if unexpected error
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Refactor e2e and print more Pod info if unexpected error

tests/e2e/network/network_security_group.go
Use node os label to select node for ExecAgnhostPod Fix azure-deny-all-except-load-balancer-source-ranges test bug Check lb type before pip-prefix-id test
(cherry picked from commit 21a6572fca7bc25aa6a3f0672a28fc31709030d1)
Fix the bug in the e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] Dump Pod describe if WaitPodTo() fails

tests/e2e/network/network_security_group.go
Use node os label to select node for ExecAgnhostPod Fix azure-deny-all-except-load-balancer-source-ranges test bug Check lb type before pip-prefix-id test
(cherry picked from commit 21a6572fca7bc25aa6a3f0672a28fc31709030d1)
Fix the bug in the e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Dump Pod describe if WaitPodTo() fails

pkg/azureclients/snapshotclient/interface.go
/kind api-change
bump snapshot client to 2022-03-02
Fixes #
```release-note
bump snapshot client to 2022-03-02
```
```docs
```
=> bump snapshot client to 2022-03-02

tests/e2e/network/standard_lb.go, tests/e2e/utils/pod_utils.go
/kind testing
[release-1.1] Refactor e2e and print more Pod info if unexpected error
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] Refactor e2e and print more Pod info if unexpected error

tests/e2e/utils/pod_utils.go
/kind cleanup
chore: log pod info in WaitPodsToBeReady when it fails.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: log pod info in WaitPodsToBeReady

tests/e2e/utils/pod_utils.go
fix: change the curl command options when getting pod outbound IP
Fixes #
```release-note
NONE
```
```docs
```
=> fix: change the curl command options when getting pod outbound IP

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/node_utils.go
/kind testing
[e2e] Skip azure-load-balancer-resource-group test for testgrid
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Skip azure-load-balancer-resource-group test for testgrid

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/scripts/run-e2e.sh
/kind testing
Fix kubetest2-aks pipeline for release branches
Fixes #
```release-note
NONE
```
```docs
```
=> Fix kubetest2-aks pipeline for release branches

pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go
/kind bug
Assume vmssflex has backend pool [0, 1, 2, 3]
After removing backend pool 1, the actual backend pool left shouild be [0, 2, 3]
However, when getting vmss flex from cache:https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_vmssflex_cache.go#L297, the get method is a deep copy: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/cache/azure_cache.go#L128, so updating the vmssflex retrieved from the cache does not update the vmssflex in the cache.
In this case, if a new backend pool 4 is to be added, then the vmss update operation will fail because the deleted backend pool 1 is still in the cache.
The error message is like below
```
ensureVMSSFlexInPool begins to add vmss(k8sflex-mp-0) with new backendPoolID …
```
=> [VMSS Flex] refresh vmssflex cache after updating vmss flex backendpool

.pipelines/scripts/run-e2e.sh, .pipelines/templates/autoscaling.json, .pipelines/templates/basic-lb-vmas.json, .pipelines/templates/basic-lb.json, .pipelines/templates/slb-vmss.json
/kind testing
[AKS pipeline] Add basic lb vmas & slb vmss templates
Adjust run-e2e.sh to fit AKS release pipeline.
Fixes #
```release-note
NONE
```
```docs
```
=> [AKS pipeline] Add basic lb vmas & slb vmss templates

.pipelines/scripts/run-e2e.sh
/kind testing
Bound variables in run-e2e.sh
Fixes #
```release-note
NONE
```
```docs
```
=> Bound variables in run-e2e.sh

tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
/kind feature
This PR adds a customized cloud provider config for VMSS Flex E2E testing
Refer to #2731 
```release-note
NONE
```
```docs
```
=> [E2E][VMSS Flex] Add a customized cloud provider config

.pipelines/scripts/run-e2e.sh
/kind testing
[aks pipeline] CLUSTER_CONFIG_PATH can be set by users
Force download kubetest2-aks from master branch
Fixes #
```release-note
NONE
```
```docs
```
=> [aks pipeline] CLUSTER_CONFIG_PATH can be set by users

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fixes #2706 
```release-note
```
```docs
```
=> fix public ip list call reduction

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
related #2707 
```release-note
```
```docs
```
=> [release-1.1] fix public ip list call reduce

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
related #2707 
```release-note
```
```docs
```
=> [release-1.23] fix public ip list call reduce

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
related #2707 
```release-note
```
```docs
```
=> [release-1.24] fix public ip list call reduce

.pipelines/scripts/run-e2e.sh
/kind testing
Bound CLUSTER_CONFIG_PATH in run-e2e.sh
Fixes #
```release-note
NONE
```
```docs
```
=> Bound CLUSTER_CONFIG_PATH in run-e2e.sh

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss_cache.go
/kind bug
fix: reduce VMSS cache refresh in CSI driver
CSI driver does not setInformer for node add/delete (informer setting is also not valid since when csi driver starts up, nodes are already there), so `ss.GetNodeNames()` is actually invalid in 
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c905fb10cb277916fb580fef75d276f328bc0d7c/pkg/provider/azure_vmss_cache.go#L420-L422
This PR would get nodeName from vmss uniform, avset, vmss flex cache directly, that could avoid unnecessary vmss refresh.
Fixes #
```release-note
fix: reduce VMSS cache refresh in CSI driver
```
```docs
fix: reduce VMSS cache refresh in CSI driver
```
=> fix: reduce VMSS cache refresh in CSI driver

pkg/azureclients/armclient/azure_armclient.go, pkg/provider/azure.go
Signed-off-by: Fan Shang Xiang <shafan@microsoft.com>
/kind cleanup
retriable http code list is only related to armclient and should be moved to armclient package. 
in track2 sdk, autorest is deprecated and it will be removed in the future. 
Fixes #
```release-note
None
```
```docs
```
=> Refactor: move retry status code settings to armclient package

go.mod, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go
Fixes #
```release-note
None
```
```docs
```
=> Cleanup: Change the struct of vmssVMCache to use only a timedCache instead of sync.Map

pkg/provider/azure_vmss_test.go
fix: race condition in a unit test
Fixes #
```release-note
NONE
```
```docs
```
=> fix: race condition in a unit test

pkg/provider/azure_vmss_cache.go
/kind bug
Fixes a race condition in VMSS cache update when there are concurrent VM updates on a single VMMS that could result stale state for one or more of the VMs.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: fix race in VMSS cache update

kubetest2-aks/Makefile
/kind testing
Enable CGO for kubetest2-aks make deployer
Fixes #
```release-note
NONE
```
```docs
```
=> Enable CGO for kubetest2-aks make deployer

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/ip_utils.go, tests/e2e/utils/ip_utils_test.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go
/kind testing
[e2e] Support IPv6 single stack clusters
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Support IPv6 single stack clusters

tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
/kind testing
Add single stack IPv6 and dualstack CAPZ templates
Fixes #
```release-note
NONE
```
```docs
```
=> Add single stack IPv6 and dualstack CAPZ templates

helm/cloud-provider-azure/README.md
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
No documentation is currently provided for the Helm chart value `cloudControllerManager.allocateNodeCidrs`.
None.
None.
```release-note
NONE
```
None.
=> docs(helm): document allocate node cidrs value

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-node-manager/app/nodemanager.go, pkg/node/node.go, pkg/node/nodearm.go, pkg/node/nodeproviderfactory.go, pkg/provider/azure.go, pkg/provider/azure_config.go, pkg/provider/azure_config_test.go, pkg/provider/azure_controller_common_test.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache.go
/kind cleanup
cleanup: set context as parameter in cloud provider functions
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: set context as parameter in cloud provider functions

go.mod, go.sum, vendor/modules.txt
/kind cleanup
Fixes #
```release-note
fix CVE-2022-41717
```
```docs
```
=> [release-1.24]/fix CVE text

.github/workflows/test-docs.yaml, .github/workflows/trivy.yaml
chore: upgrade ubuntu to 22.04 for github actions
Fixes #
```release-note
NONE
```
```docs
```
=> chore: upgrade ubuntu to 22.04 for github actions

.github/dependabot.yml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add dependabot config for release-1.26

.pipelines/run-e2e.yml, .pipelines/scripts/run-e2e.sh, .pipelines/var-e2e.yml
/kind testing
Get latest K8s ver with branch name in aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> Get latest K8s ver with branch name in aks pipeline

site/content/en/topics/loadbalancer.md
Fixes #
```release-note
NONE
```
```docs
```
=> Add docs for no_lb_rule and no_probe_rule annotations

.pipelines/scripts/run-e2e.sh, kubetest2-aks/cluster-templates/customconfiguration-azuredisk.json, kubetest2-aks/cluster-templates/customconfiguration-azurefile.json, kubetest2-aks/cluster-templates/customconfiguration-ccm.json, kubetest2-aks/cluster-templates/customconfiguration-k8s.json, kubetest2-aks/cluster-templates/slb.json, kubetest2-aks/deployer/deployer.go, kubetest2-aks/deployer/up.go
/kind testing
[kubetest2-aks] Support more components
* Azure disk
* Azure file
* K8s components
* kube-apiserver
* kube-scheduler
* kube-proxy
* kube-controller-manager
* kubelet
Fixes #
```release-note
NONE
```
```docs
```
=> [kubetest2-aks] Support more components

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go
/kind feature
feat: add DisableUpdateCache flag
this flag could control update cache behavior in csi driver disk attach/detach
Fixes #
```release-note
feat: add DisableUpdateCache flag
```
```docs
feat: add DisableUpdateCache flag
```
=> feat: add DisableUpdateCache flag

pkg/provider/azure_storage_test.go, pkg/provider/azure_storageaccount.go
Fixes #
```release-note
```
```docs
```
=> fix: support custom storage endpoint suffix

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind cleanup
Refactor azure_loadbalancer*.go
* Use subtest in UT for clearer output
* Refactor azure_loadbalancer.go
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor azure_loadbalancer*.go

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind cleanup
* Use subtest in UT for clearer output
* Refactor azure_loadbalancer.go
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Refactor azure_loadbalancer*.go

.pipelines/scripts/run-e2e.sh
/kind testing
Update how IMAGE_TAG is set
Use $(git describe --tags) as IMAGE_TAG in run-e2e.sh
Fixes #
```release-note
NONE
```
```docs
```
=> Update how IMAGE_TAG is set

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml
/kind testing
[aks pipeline] Set IMAGE_TAG before building ccm, cnm images
Fixes #
```release-note
NONE
```
```docs
```
=> [aks pipeline] Set IMAGE_TAG before building ccm, cnm images

kubetest2-aks/deployer/build.go, kubetest2-aks/deployer/deployer.go
/kind testing
[kubetest2-aks] Print correct image tag
Fixes #
```release-note
NONE
```
```docs
```
=> [kubetest2-aks] Print correct image tag

pkg/azureclients/v2/go.mod, pkg/azureclients/v2/go.sum, pkg/azureclients/v2/recording/counter.go, pkg/azureclients/v2/recording/recorder.go, pkg/azureclients/v2/recording/transport.go
/kind cleanup
add recorder for v2 client ut cases
Fixes #
```release-note
NONE
```
```docs
```
=> azureclient v2: add recorder for v2 client ut cases

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, .pipelines/run-basic-lb-e2e.yml
/kind testing
Upgrade Go version to 1.19
Fixes #
```release-note
NONE
```
```docs
```
=> [aks pipeline] Upgrade Go version to 1.19

.pipelines/run-e2e.yml, .pipelines/scripts/run-e2e.sh, .pipelines/var-e2e.yml
/kind testing
[release-1.23] Get latest K8s ver with branch name in aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Get latest K8s ver with branch name in aks pipeline

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update image versions in readme

.pipelines/templates/customconfiguration-autoscaling.json
/kind testing
[pipeline] Wait shorter when scale down node pool
Fixes #
```release-note
NONE
```
```docs
```
=> [pipeline] Wait shorter when scale down node pool

pkg/provider/azure_privatelinkservice.go
/kind cleanup
Add metrics for pls reconcile
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Add metrics for reconciling private link service

site/content/en/topics/pls-integration.md
Update pls doc with known limitations
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update pls doc

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Follow CAPZ change:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2824
Fixes #
```release-note
NONE
```
```docs
```
=> Always use registry.k8s.io

.pipelines/templates/customconfiguration-k8s.json
/kind testing
Put K8s customconfig file to .pipelines
Fixes #
```release-note
NONE
```
```docs
```
=> Put K8s customconfig k8s file to .pipelines

.pipelines/templates/customconfiguration-k8s.json
/kind testing
[release-1.23] Put customconfig k8s file to .pipelines
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Put customconfig k8s file to .pipelines

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
Fixes #
```release-note
```
```docs
```
=> fix: make account search backward compatible

tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml
Fixes https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-ipv6-capz
Since etcd version got bumped, this workaround is no longer needed as etcd is now using the correct IP for ipv6 listen-client-urls. This follows the same PR made in CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2920.
Fixes #
```release-note
NONE
```
```docs
```
=> Remove etcd workaround in ipv6 test templates

Makefile
/kind cleanup
There are code changes/bug fixes ([Github API changes](https://github.com/orgs/community/discussions/45590)) on https://github.com/golangci/golangci-lint/blob/master/install.sh. Switch to master branch script to install golangci-lint.
Fixes #
```release-note
NONE
```
```docs
```
/assign @lzhecheng
=> build: Fix downloading golangci-lint using master branch script

hack/boilerplate/boilerplate.py, hack/boilerplate/boilerplate_test.py, hack/boilerplate/test/fail.py, hack/boilerplate/test/pass.py
/kind testing
Bump to python3
Fixes #
```release-note
NONE
```
```docs
```
=> Bump to python3

pkg/provider/azure_controller_common.go
/kind cleanup
cleanup: refine azure disk driver logging
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: refine azure disk driver logging

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go
/kind testing
[e2e] Support dual-stack - ensureloadbalancer & nsg
Fixes #
related #814
```release-note
NONE
```
```docs
```
=> [e2e] Support dual-stack - ensureloadbalancer & nsg

pkg/provider/azure.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind feature
fix: add disk attach/detach delay time to allow more batch
Fixes #
```release-note
fix: add disk attach/detach delay time to allow more batch
```
```docs
fix: add disk attach/detach delay time to allow more batch
```
=> fix: add disk attach/detach delay time to allow more batch

pkg/provider/azure_vmss_cache.go
/kind bug
Remove vmss VM from cache when deleting nodes to prevent from unexpected API call
Fixes #
```release-note
fix: remove vmss vm from cache when invalidate the cache
```
```docs
```
=> fix: remove vmss vm from cache when invalidate the cache

pkg/provider/azure_utils.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
/kind bug
Remove vmss VM from cache when deleting nodes to prevent from unexpected API call
Fixes #
```release-note
fix: remove vmss vm from cache when invalidate the cache
```
```docs
```
=> fix: remove vmss vm from cache when invalidate the cache #3299

.github/workflows/release.yaml
It is only needed in master.
/kind cleanup
[release-1.25] Remove kubetest2-aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] Remove kubetest2-aks pipeline

.github/workflows/release.yaml
/kind cleanup
[release-1.23] Remove kubetest2-aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Remove kubetest2-aks pipeline

.github/workflows/release.yaml
/kind cleanup
[release-1.24] Remove kubetest2-aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] Remove kubetest2-aks pipeline

pkg/provider/azure_loadbalancer.go
/kind bug
Fix: fix Incorrect conversion between integer types in release 1.24 in GitHub Code Scanning / CodeQL
Fixes #
```release-note
```
```docs
```
=> Fix: fix Incorrect conversion between integer types in release 1.24

pkg/provider/azure_loadbalancer.go
/kind bug
Fix: fix Incorrect conversion between integer types in GitHub Code Scanning / CodeQL
Fixes #
```release-note
```
```docs
```
=> Fix: fix Incorrect conversion between integer types

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind testing
[e2e] Support dual-stack - Service annotation
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Support dual-stack - Service annotation

pkg/provider/azure_loadbalancer.go, tests/e2e/network/service_annotations.go
/kind cleanup
Remove unnecessary probe port check. Add a e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> Remove unnecessary probe port check

.github/workflows/release.yaml, hack/generate-release-note.sh
/kind cleanup
cherry-pick #3337 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] build: Excludes previous release tag commit when generating release notes

.github/workflows/release.yaml, hack/generate-release-note.sh
/kind cleanup
cherry-pick #3337 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] build: Excludes previous release tag commit when generating release notes

.github/workflows/release.yaml, hack/generate-release-note.sh
/kind cleanup
cherry-pick #3337 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] build: Excludes previous release tag commit when generating release notes

.github/workflows/release.yaml, hack/generate-release-note.sh
/kind cleanup
cherry-pick #3337 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] build: Excludes previous release tag commit when generating release notes

go.mod, go.sum, vendor/golang.org/x/net/html/token.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/server.go, vendor/modules.txt
/kind bug
fix: CVE-2022-41723
Fixes #
```release-note
fix: CVE-2022-41723
```
```docs
fix: CVE-2022-41723
```
=> fix: CVE-2022-41723

pkg/retry/azure_error.go
/kind cleanup
chore: cleanup unused RawErrorContainer
Fixes #
```release-note
NONE
```
```docs
```
=> chore: cleanup unused RawErrorContainer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
(cherry picked from commit a894df4b98dbf35f68ecc9372d728064b2eb3d47)
/kind bug
Fixes #
```release-note
Fix: remove shared security rule when no svc with shared-nsg annotation exists
```
```docs
```
=> [release-1.26]Fix: remove shared security rule when no svc with shared-nsg annotation exists

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
(cherry picked from commit a894df4b98dbf35f68ecc9372d728064b2eb3d47)
/kind bug
Fixes #
```release-note
Fix: remove shared security rule when no svc with shared-nsg annotation exists
```
```docs
```
=> [release-1.25]Fix: remove shared security rule when no svc with shared-nsg annotation exists

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
…is deleted
(cherry picked from commit a894df4b98dbf35f68ecc9372d728064b2eb3d47)
/kind bug
Fix: remove shared security rule when no svc with shared-nsg annotation exists 
Fixes #
```release-note
Fix: remove shared security rule when no svc with shared-nsg annotation exists 
```
```docs
```
=> [release-1.23]Fix: remove shared security rule when no svc with shared-nsg annotation exists 

pkg/provider/azure_loadbalancer.go, tests/e2e/network/service_annotations.go
/kind cleanup
Remove unnecessary probe port check. GetHealthProbeConfigOfPortFromK8sSvcAnnotation() has checked. Add a e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] Remove unnecessary probe port check

pkg/azureclients/v2/go.mod, pkg/azureclients/v2/go.sum, pkg/azureclients/v2/utils/options.go, pkg/azureclients/v2/utils/transport.go
/kind cleanup
customize default transport for all of track2 clients
Fixes #
```release-note
NONE
```
```docs
```
=> azureclient track2:customize default transporter in track2 client

.github/dependabot.yml
/kind testing
Limit dependbot open pr limit to 3. CI resources are not enough with 30.
Fixes #
```release-note
NONE
```
```docs
```
=> Limit dependbot open pr limit to 3

.github/workflows/lint.yaml, Makefile, pkg/nodemanager/nodemanager.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/node_utils.go
/kind testing
Add lints for loop pointer. exportloopref and looppointer
Fixes #
```release-note
NONE
```
```docs
```
=> Add lints for loop pointer

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
Update linux-ci-version.yaml to support using vmss flex
/kind feature
Update linux-ci-version.yaml to support using vmss flex orchestration mode. If ORCHESTRATION_MODE env variable is not set, then it will use "Uniform" as default. 
This PR is a preparation of migrating Cloud-Provider-Azure VMSS Flex E2E test pipeline from Jack's branch to CAPZ main branch
Fixes #
```release-note
NONE
```
```docs
```
=> Update linux-ci-version.yaml to support using vmss flex

.github/workflows/lint.yaml, Makefile, pkg/nodemanager/nodemanager.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/node_utils.go
/kind cleanup
Add lints for loop pointer. exportloopref and looppointer
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Add lints for loop pointer

.github/workflows/lint.yaml, Makefile, pkg/nodemanager/nodemanager.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/node_utils.go
/kind cleanup
Add lints for loop pointer. exportloopref and looppointer
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] Add lints for loop pointer

.github/workflows/lint.yaml, Makefile, pkg/nodemanager/nodemanager.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/node_utils.go
/kind cleanup
Add lints for loop pointer. exportloopref and looppointer
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Add lints for loop pointer

tests/e2e/network/service_annotations.go
/kind testing
[e2e] Fix azure-load-balancer-resource-group test. pips should have IP instead of PIP name.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Fix azure-load-balancer-resource-group test

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
We should not update tags on the user-assigned public IPs.
Fixes #
```release-note
fix: do not tag user-assigned public IP
```
```docs
```
=> fix: do not tag user-assigned public IP

tests/e2e/auth/cred.go, tests/e2e/autoscaling/autoscaler.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go
/kind testing
[e2e] Delete ns and client if not nil to avoid panic
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Delete ns and client if not nil to avoid panic

Makefile
Cherry-pick of #3282 
```release-note
None
```
```docs
```
=> [Release 1.23] Disable provenance attestation to workaround docker buildx issue

tests/e2e/auth/cred.go, tests/e2e/autoscaling/autoscaler.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go
/kind testing
[e2e] Delete ns and client if not nil to avoid panic
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23][e2e] Delete ns and client if not nil to avoid panic

tests/e2e/utils/network_utils.go
/kind testing
[e2e] Print IP config IDs if subnet deletion fails
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Print IP config IDs if subnet deletion fails

.github/dependabot.yml
/kind cleanup
Limit dependbot open pr limit to 1
Fixes #
```release-note
NONE
```
```docs
```
=> Limit dependbot open pr limit to 1

tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go
/kind testing
[e2e] Add Node logs for autoscaling tests
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Add Node logs for autoscaling tests

.github/workflows/test-docs.yaml, .github/workflows/trivy.yaml
chore: upgrade ubuntu to 22.04 for github actions
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] chore: upgrade ubuntu to 22.04 for github actions

.github/workflows/test-docs.yaml, .github/workflows/trivy.yaml
chore: upgrade ubuntu to 22.04 for github actions
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] chore: upgrade ubuntu to 22.04 for github actions

.github/workflows/test-docs.yaml, .github/workflows/trivy.yaml
/kind testing
[Github action tests] Run on ubuntu-latest for trivy and doc
Fixes #
```release-note
NONE
```
```docs
```
=> [Github action tests] Run on ubuntu-latest for trivy and doc

.github/dependabot.yml
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> Add release label for prs raised by dependabot

.pipelines/templates/autoscaling-multipool.json, .pipelines/templates/autoscaling.json
/kind testing
More Nodes for autoscaling tests
Fixes #
```release-note
NONE
```
```docs
```
=> More Nodes for autoscaling tests

.github/workflows/lint.yaml, Makefile, pkg/consts/helpers.go, tests/e2e/utils/network_utils.go
/kind testing
Run go lint using github actions
Fixes #
```release-note
NONE
```
```docs
```
=> Run go lint using github actions

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind cleanup
Previously I made a PR adding pip slice to reduce listing public ips in loops. Now this is naturally avoided due to pip cache so we can clean up the code.
Fixes #
```release-note
NONE
```
```docs
```
=> clean up old pip list optimization

.github/dependabot.yml
/kind cleanup
Add dependabot config for release-1.27
Fixes #
```release-note
NONE
```
```docs
```
=> Add dependabot config for release-1.27

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go
/kind cleanup
cherry picking #3773 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] clean up old pip list optimization

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go
/kind cleanup
cherry picking #3773 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] clean up old pip list optimization

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go
/kind cleanup
cherry picking #3773 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] clean up old pip list optimization

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/vmss_utils.go
/kind testing
[e2e] Fix bugs from introducing user node pool. Current code for user node pool doesn't work for basic-lb clusters.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Fix bugs from introducing user node pool

cloudbuild.yaml
/kind testing
Use latest gcb-docker-gcloud
Fixes #
```release-note
NONE
```
```docs
```
=> Use latest gcb-docker-gcloud

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind cleanup
[Refactor] Drop RG param in getXXXID(). Resource group name can be got from az.getLoadBalancerResourceGroup().
Fixes #
```release-note
NONE
```
```docs
```
=> [Refactor] Drop RG param in getXXXID()

README.md
Updates the main README to mention the release-1.27 branch and the v1.27.1 release.
Fixes #
```release-note
NONE
```
=> Update README.md with v1.27 release branch

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
/kind testing
[CI] Add IPv6 templates modified from release-1.9 CAPZ. MachineDeployment and MachinePool
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Add IPv6 templates modified from release-1.9 CAPZ

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: update readme and examples for new image versions
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update readme and examples for new image versions

site/content/en/topics/cross-resource-group-nodes.md
chore: update docs for cross resource group nodes: added limitations for AKS.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: update docs for cross resource group nodes

pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go
/kind cleanup
Adjust UT util functions for cherrypick without DualStack support
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Adjust UT util functions for cherrypick without DualStack support

pkg/provider/azure_loadbalancer_test.go
/kind cleanup
Adjust UT util functions for cherrypick without DualStack support
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] Adjust UT util functions for cherrypick without DualStack support

pkg/provider/azure_loadbalancer.go
/kind cleanup
[Log] Print Service name and resource basename in ReconcileService(). Adding such log shows relation between Service name and its related resource name (Frontend IP config, etc.). It helps debugging.
Fixes #
```release-note
[Log] Print Service name and resource basename in ReconcileService(). Adding such log shows relation between Service name and its related resource name (Frontend IP config, etc.). It helps debugging.
```
```docs
```
=> [Log] Print Service name and resource basename in ReconcileService()

site/content/en/topics/loadbalancer.md
chore: update docs for exclude nodes from SLB
Fixes #
```release-note
None
```
```docs
```
=> chore: update docs for exclude nodes from SLB

.github/workflows/codeql-analysis.yml, .github/workflows/kubetest2-release.yml, .github/workflows/scorecards.yml, .github/workflows/trivy.yaml
/kind cleanup
add manual dispatch for all github actions
Fixes #
```release-note
NONE
```
```docs
```
=> add manual dispatch for all github actions

site/content/en/topics/loadbalancer.md
chore: fix the typo for SLB docs
Fixes #
```release-note
NONE
```
```docs
```
=> chore: fix the typo for SLB docs

pkg/azclient/virtualmachinescalesetvmclient/custom.go, pkg/azclient/virtualmachinescalesetvmclient/interface.go, pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
/kind bug
track2:update mock interface for vmssvmclient
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk:update mock interface for vmssvmclient

.github/dependabot.yml, .github/workflows/cflite_cron.yaml, .github/workflows/trivy.yaml
/kind testing
add daily fuzz test
Fixes #
```release-note
NONE
```
```docs
```
=> add daily fuzz test

pkg/azclient/virtualmachinescalesetvmclient/custom.go
/kind bug
fix copyright template error in azclient package
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: fix copyright template error in azclient package

vendor/golang.org/x/net/http2/Dockerfile
/kind cleanup
Revert change in vendor by scorecard
Fixes #
```release-note
NONE
```
```docs
```
=> Revert change in vendor by scorecard

.github/workflows/hugo.yml, site/package-lock.json, site/package.json
chore: pin the npm dependencies for the document site.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: pin the site dependencies

.github/dependabot.yml, .github/workflows/hugo.yml, .gitignore, netlify.toml, site/config/_default/config.toml, site/config/githubpage/config.toml, site/config/netlify/config.toml, site/go.mod, site/go.sum
/kind testing
Cleanup dependencies and fix cron job
Fixes #
```release-note
NONE
```
```docs
```
=> Cleanup dependencies and fix cron job

.github/workflows/hugo.yml
fix: ensure POSTCSS is installed
Fixes #
```release-note
NONE
```
```docs
```
=> fix: ensure POSTCSS is installed

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: update image versions in the doc
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update image versions in the doc

.github/workflows/codespell.yaml, pkg/azclient/auth.go, pkg/azclient/auth_test.go, pkg/azclient/azclient_suite_test.go, pkg/azclient/config.go, pkg/azclient/testdata/auth.yaml
/kind bug
track2 sdk: Apply dependency injection pattern to auth provider
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: Apply dependency injection pattern to auth provider

pkg/azclient/auth.go
/kind feature
track2 sdk: reuse cred object in auth provider
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: reuse cred object in auth provider

netlify.toml, site/content/en/_index.html, site/go.mod, site/go.sum
Fixes #
```release-note
NONE
```
```docs
```
=> chore: bump docsy to 0.7.0

pkg/azclient/factory_conf.go, pkg/azclient/utils/options.go, pkg/azclient/utils/transport.go
/kind cleanup
only set go-armbalancer for resource client
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: only set go-armbalancer for resource client

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind bug
We should remove deleted node IPs from the IP-based backend pools.
Fixes #
```release-note
fix: remove deleted node IP address from IP-based LB backend pools
```
```docs
```
=> fix: remove deleted node IP address from IP-based LB backend pools

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yaml, .github/workflows/trivy.yaml
/kind testing
fix go build version in codeql job
Fixes #
```release-note
NONE
```
```docs
```
=> Chroes: fix go build version in codeql job

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind bug
We should remove deleted node IPs from the IP-based backend pools.
Fixes #
```release-note
fix: remove deleted node IP address from IP-based LB backend pools
```
```docs
```
=> [release-1.27] fix: remove deleted node IP address from IP-based LB backend pools

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind bug
We should remove deleted node IPs from the IP-based backend pools.
Fixes #
```release-note
fix: remove deleted node IP address from IP-based LB backend pools
```
```docs
```
=> [release-1.26] fix: remove deleted node IP address from IP-based LB backend pools

pkg/azclient/client-gen/generator/genclientfactory_action.go, pkg/azclient/factory.go, pkg/azclient/factory_conf.go, pkg/azclient/factory_gen.go, pkg/azclient/factory_test.go, pkg/azclient/mock_azclient/interface.go
/kind cleanup 
move sub to config struct in client factory
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: move sub to config struct in client factory

.pipelines/templates/autoscaling-multipool.json, .pipelines/templates/autoscaling.json
/kind testing
[Pipeline] Limit max node count to 100
Origin: Cluster's upper limit node count is 3000 which exceeds the limit for Kubenet 400
Fixes #
```release-note
NONE
```
```docs
```
=> [Pipeline] Limit max node count to 100

pkg/nodeipam/ipam/cloud_cidr_allocator.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/utils/network_utils.go
/kind cleanup
pkg is being imported more than once
Fixes #
```release-note
NONE
```
```docs
```
=> chore: pkg imported more than once

.github/workflows/release.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27]chores:move docs to documentation branch

.github/workflows/release.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26]chores:move docs to documentation branch

.pipelines/scripts/run-e2e.sh
/kind testing
[Pipeline] Fix get_k8s_version failure. Output of "az aks get-versions" for aks-preview has changed. So only "az extension add" when necessary.
Fixes #
```release-note
NONE
```
```docs
```
=> [Pipeline] Fix get_k8s_version failure

.pipelines/scripts/run-e2e.sh
/kind testing
[Pipeline] Move aks-preview extension addition order
Fixes #
```release-note
NONE
```
```docs
```
=> [Pipeline] Move aks-preview extension addition order

content/en/install/azure-ccm.md
doc: fix a hyperlink error in the documentation
Fixes #3580
```release-note
NONE
```
```docs
```
=> doc: fix a hyperlink error in the documentation

kubetest2-aks/cluster-templates/autoscaling-e2e.json, kubetest2-aks/cluster-templates/autoscaling-multipool.json, kubetest2-aks/cluster-templates/autoscaling.json
/kind cleanup 
Lowers the max node count to work with latest validation.
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: ValidationError
--------------------------------------------------------------------------------
{
"code": "ValidationError",
"details": null,
"message": "Cluster's upper limit node count is 1000 which exceeds the limit for Kubenet 400. If Autoscaler is enabled, the max-count from each nodepool is counted towards this total. [https://aka.ms/aks/kubenet-networking-overview",](https://aka.ms/aks/kubenet-networking-overview%22,)
"subcode": "KubenetNodeCountTotalExceedsLimit"
}
--------------------------------------------------------------------------------
```release-note
NONE
``` …
=> fix: fixing kubetest autoscaling configs as well

config/_default/config.toml
Fixes #
```release-note
NONE
```
```docs
```
=> docs: fix edit page url broken link

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go
/kind cleanup
Use const vars to define isIPv6: false & true
Fixes #
```release-note
NONE
```
```docs
```
=> Use const vars to define isIPv6: false & true

.pipelines/scripts/run-e2e.sh, .pipelines/templates/customconfiguration-autoscaling-multipool.json
/kind testing
/kind cleanup
[AKS pipeline] Use new customconfig file for autoscaling-multipool. Use a new customconfig file to enable balance-similar-node-groups for autoscaling-multipool clusters.
Fixes #
```release-note
NONE
```
```docs
```
=> [AKS pipeline] Use new customconfig file for autoscaling-multipool

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind cleanup
Use const vars to define isIPv6: false & true
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Use const vars to define isIPv6: false & true

tests/e2e/network/ensureloadbalancer.go
/kind testing
[e2e] Adjust exclude-from-lb test for basic-lb pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Adjust exclude-from-lb test for basic-lb pipeline

content/en/topics/shared-ip.md
doc: add docs for sharing pip by name
Fixes #
```release-note
NONE
```
```docs
```
=> doc: add docs for sharing pip by name

.github/workflows/codeql-analysis.yml
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> [Release-1.24]fix vendor validation in ci job

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind testing
[release-1.26][e2e] Support dual-stack - Service annotation
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26][e2e] Support dual-stack - Service annotation

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, tests/e2e/network/ensureloadbalancer.go
/kind feature
We used to support sharing one pip across services by setting the IP address. This PR supports sharing by pip name.
Fixes #4243
```release-note
feat: support sharing IP address across services by public IP name
```
```docs
```
=> [release-1.26] feat: support sharing IP address across services by public IP name

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind testing
[e2e] Support dual-stack - Service annotation
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25][e2e] Support dual-stack - Service annotation

pkg/azclient/policy/etag/etag.go, pkg/azclient/policy/etag/etag_suite_test.go, pkg/azclient/policy/etag/etag_test.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Add etag policy

tests/e2e/network/ensureloadbalancer.go
/kind bug
/kind testing
[e2e] Fix updateServicePIPNames. Service annotation PIP name with suffix is used only for IPv6 in a dualstack setup.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Fix updateServicePIPNames

.pipelines/scripts/collect-log.sh, .pipelines/scripts/run-e2e.sh, tests/e2e/autoscaling/autoscaler.go
/kind testing
[aks pipeline] Refactor run-e2e.sh
* It supports the local testing scenario when it is unnecessary
to build kubetest2-aks, run tests, collect logs and gc.
* Print custom config and cluster config path
* Skip the e2e test "balance-node-groups" due to autoscaler bug
Fixes #
```release-note
NONE
```
```docs
```
=> [aks pipeline] Refactor run-e2e.sh

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind testing
add missing e2e tests for service annotations
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] add missing e2e tests for service annotations

tests/e2e/e2e_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/multiple_standard_lb.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/consts.go, tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-multi-slb.json, tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
/kind cleanup
chore: add e2e for multiple standard load balancers
Fixes #
Related: [4013](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4013)
```release-note
NONE
```
```docs
```
=> chore: add e2e for multiple standard load balancers

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yaml, .github/workflows/trivy.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25]fix go build version in codeql job

pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go
/kind bug
Skip unmanaged Nodes for instancesV2
Fixes #
```release-note
Skip unmanaged Nodes for instancesV2
```
```docs
```
=> [release-1.25] Skip unmanaged Nodes for instancesV2

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml
/kind cleanup
chore: add a capz cluster template without windows node pool
Fixes #
```release-note
```
```docs
```
=> chore: add a capz cluster template without windows node pool

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/consts.go, tests/e2e/utils/node_utils.go
/kind bug
/kind testing
Fix standalone VM EnsureBackendPoolDeleted
* Fix ensureBackendPoolDeleted for standalone VM
* Trigger Service reconcile for exclude-from-external-load-balancers e2e test
* Refactor e2e
* Add logs for exclude-from-external-load-balancers
Fixes #
```release-note
Fix ensureBackendPoolDeleted for standalone VM. Add logs for exclude-from-external-load-balancers
```
```docs
```
=> [release-1.27] Fix standalone VM EnsureBackendPoolDeleted

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/consts.go, tests/e2e/utils/node_utils.go
/kind bug
/kind testing
Fix standalone VM EnsureBackendPoolDeleted
* Fix ensureBackendPoolDeleted for standalone VM
* Trigger Service reconcile for exclude-from-external-load-balancers e2e test
* Refactor e2e
* Add logs for exclude-from-external-load-balancers
Fixes #
```release-note
Fix ensureBackendPoolDeleted for standalone VM. Add logs for exclude-from-external-load-balancers
```
```docs
```
=> [release-1.26] Fix standalone VM EnsureBackendPoolDeleted

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
/kind cleanup
bump ubuntu to 2204 for capz ci test, add a test template that is able to run locally.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: bump ubuntu to 2204 for capz ci test

hack/generate-release-note.sh
/kind cleanup
chore: add release script for documentation branch
Fixes #
```release-note
NONE
```
```docs
```
=> chore: add release script for documentation branch

.github/workflows/release.yaml
/kind cleanup
chore: switch to documentation branch for release notes
Fixes #
```release-note
NONE
```
```docs
```
=> chore: switch to documentation branch for release notes

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_routes.go, tests/e2e/network/node.go
/kind testing
[e2e] Use timeout for the route table test. We use a timeout for route table reconcilation considering the route reconciling interval.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Use timeout for the route table test

tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Use 2204 ubuntu image for linux-vmss-multiple-zones-ci-version.yaml
Fixes #
```release-note
NONE
```
```docs
```
=> Use 2204 ubuntu image for linux-vmss-multiple-zones-ci-version.yaml

pkg/provider/azure_privatelinkservice_repo.go, pkg/provider/azure_securitygroup_repo.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> chore: move getPrivateLinkService to pls file

pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_test.go
/kind feature
Update probe port validation and support custom health probe port(not in spec) 
Fixes #
```release-note
Health probe port can be any port assigned by customer.
```
```docs
```
=> Support for custom health probe port(not in spec) 

Dockerfile, pkg/provider/azure.go
/kind cleanup
Use correct quotation mark
Fixes #
```release-note
NONE
```
```docs
```
=> Use correct quotation mark

cloudbuild.yaml
/kind cleanup
Update gcb-docker-gcloud to v20230623-56e06d7c18
Fixes #
```release-note
NONE
```
```docs
```
=> Update gcb-docker-gcloud to v20230623-56e06d7c18

.github/dependabot.yml, .github/workflows/lint.yaml
/kind testing
do not ignore existing issues.
Fixes #
```release-note
NONE
```
```docs
```
=> Do not ignore existing issues.

tests/e2e/network/private_link_service.go, tests/e2e/node/unmanaged_node.go, tests/e2e/utils/consts.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Add unmanaged Nodes tests
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Add unmanaged Nodes tests

content/en/topics/loadbalancer.md
[docs ]Add health probe config for kube-proxy
Fixes #
```release-note
NONE
```
```docs
```
=> [docs ]Add health probe config for kube-proxy

.github/dependabot.yml
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> Update dependabot.yml for release-1.28

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
/kind deprecation
chore: update readme for release 1.28
Fixes #
```release-note
NONE
```
```docs
```
=> chore: update readme for release 1.28

examples/out-of-tree/credential-provider-config.yaml, tests/e2e/auth/cred.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/consts.go, tests/e2e/utils/container_registry_utils.go, tests/e2e/utils/pod_utils.go, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
[CI] Test OOT credential provider
* Add a template
* Add an e2e test
Fixes #
Related https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2403
```release-note
NONE
```
```docs
```
=> [CI] Test OOT credential provider

tests/e2e/auth/cred.go, tests/e2e/utils/container_registry_utils.go
/kind testing
[e2e] Skip OOT credential provider test for aks pipeline. It is failing on aks pipeline so it should be skipped before the root cause is found.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Skip OOT credential provider test for aks pipeline

cmd/acr-credential-provider/main.go, examples/out-of-tree/credential-provider-config-win.yaml, tests/e2e/auth/cred.go, tests/e2e/e2e_test.go, tests/e2e/utils/container_registry_utils.go, tests/e2e/utils/pod_utils.go, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
* Enable Windows credential provider e2e
* credential provider code: %w -> %v. Otherwise, e.g. "Failed to initialize ACR provider: %!w(*fmt.wrapError=&{failed to create service principal token: no credentials provided for Azure cloud provider 0xc0000a5620})"
* credential provider cluster template: 1. log level to 4, 2. acr-credential-provider.exe, 3. credential-provider-config-win.yaml - c:\k\azure.json
Fixes #
Related #2403
```release-note
NONE
```
```docs
```
=> Enable Windows for credential provider pipeline

tests/e2e/e2e_test.go, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
Workaround Windows credential provider binary.
Fixes #
Related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4533
```release-note
NONE
```
```docs
```
=> Workaround Windows credential provider binary

pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go
/kind bug
In case cx's subnet name or pls name is too long, pls creation would fail because frontendIPConfiguration name is too long with error `InvalidResourceName`. This PR fixes the issue by truncating the frontend name if its length exceeds Azure's limit, 80.
Fixes #
```release-note
Fix privateLinkService creation failure in case customer's subnet name or privateLinkService name is too long.
```
```docs
```
=> fix: truncate pls frontendIPConfig name if it's too long

pkg/azclient/policy/retryonregionalendpoint/retry_endpoint.go
/kind feature
track2 sdk: add retry on regional endpoint policy
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: add retry on regional endpoint policy

pkg/azclient/auth.go
/kind cleanup
enable x5c in track2 sdk
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: enable x5c in track2 sdk

content/en/development/design-docs/pls-integration.md
Update pls-integration doc to GA.
Fixes #
```release-note
NONE
```
```docs
```
=> [Doc] update pls doc to GA

kubetest2-aks/deployer/up.go, tests/e2e/network/ensureloadbalancer.go
/kind testing
[CI] AKS cluster creation longer wait. More logs for waitForNodesInLBBackendPool
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] AKS cluster creation longer wait

pkg/azclient/policy/etag/etag.go, pkg/azclient/policy/retryonregionalendpoint/retry_endpoint.go, pkg/azclient/policy/retryonregionalendpoint/retry_endpoint_test.go, pkg/azclient/policy/retryonregionalendpoint/retryonregionalendpoint_suite_test.go, pkg/azclient/policy/retryrepectthrottled/retryrepectthrottled_suite_test.go, pkg/azclient/policy/retryrepectthrottled/throttle_test.go
/kind cleanup
Track2 sdk: Add ut for armclient policies
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: Add ut for armclient policies

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind feature
support customizing probe config when ETP is local
Fixes #
```release-note
support customizing probe config when externalTrafficPolicy is local and health-probe_port annotation is defined for svc port
```
```docs
```
=> [release-1.26]support customizing probe config when ETP is local

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, tests/e2e/network/private_link_service.go
/kind feature
cherry pick
Fixes #
related #4660 
```release-note
By default, all managed private link service (PLS) are created in the resource group configured by azure config (az.privateLinkServiceResourceGroup or az.ResourceGroup).
Add `ServiceAnnotationPLSResourceGroup = "service.beta.kubernetes.io/azure-pls-resource-group"` to control a specific PLS creation resource group.
```
```docs
```
=> [release-1.26] feat: add annotation to control pls creation rg

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind feature
[release-1.25]support customizing probe config when ETP is local
Fixes #
```release-note
support customizing probe config when externalTrafficPolicy is local and health-probe_port annotation is defined for svc port
```
```docs
```
=> [release-1.25]support customizing probe config when ETP is local

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, tests/e2e/network/private_link_service.go
/kind feature
Fixes #
related #4660 
```release-note
By default, all managed private link service (PLS) are created in the resource group configured by azure config (az.privateLinkServiceResourceGroup or az.ResourceGroup).
Add `ServiceAnnotationPLSResourceGroup = "service.beta.kubernetes.io/azure-pls-resource-group"` to control a specific PLS creation resource group.
```
```docs
```
=> [release-1.25] feat: add annotation to control pls creation rg

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: release v1.28.1, v1.27.9, v1.26.15 and v1.25.19
Fixes #
```release-note
NONE
```
```docs
```
=> doc: release v1.28.1, v1.27.9, v1.26.15 and v1.25.19

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/interface.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/node_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> chore: fix typos

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/interface.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/node_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27]chore: fix typos

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/interface.go, tests/e2e/utils/node_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25]chore: fix typos

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/interface.go, tests/e2e/utils/node_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26]chore: fix typos

pkg/azclient/client-gen/generator/genclientfactory_action.go, pkg/azclient/factory_gen.go, pkg/azclient/policy/retryonregionalendpoint/retry_endpoint_test.go, pkg/azclient/policy/retryrepectthrottled/throttle_test.go
/kind cleanup
Fix: nil policy in percallpolicy option
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: Fix: nil policy in percallpolicy option

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/interface.go, pkg/provider/azure_vmss_test.go, tests/e2e/utils/node_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28]chore: fix typos

examples/out-of-tree/credential-provider-config.yaml, tests/e2e/auth/cred.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/consts.go, tests/e2e/utils/container_registry_utils.go, tests/e2e/utils/pod_utils.go, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
[CI] Test OOT credential provider
* Add a template
* Add an e2e test
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27][CI] Test OOT credential provider

.github/dependabot.yml
/kind testing
Remove stale config of dependabot in release branch.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27]Remove stale config of dependabot in release branch.

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
Use CAAPH for credential-provider-capz template
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3971
Fixes #
```release-note
NONE
```
```docs
```
=> Use CAAPH for credential-provider-capz template

tests/e2e/auth/cred.go, tests/e2e/utils/container_registry_utils.go
/kind testing
Replace docker commands with acr tasks
Fixes #
```release-note
NONE
```
```docs
```
=> Replace docker commands with acr tasks

tests/e2e/auth/cred.go, tests/e2e/utils/container_registry_utils.go
/kind testing
Login azure before update acr properties in e2e
Fixes #
```release-note
NONE
```
```docs
```
=> Login azure before update acr properties in e2e

pkg/azclient/registryclient/custom.go, pkg/azclient/registryclient/custom_test.go, pkg/azclient/registryclient/interface.go, pkg/azclient/registryclient/testdata/Registry.yaml
/kind feature
track2 sdk: add importimage function to registryclient
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: add importimage function to registryclient

pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml, pkg/azclient/registryclient/mock_registryclient/interface.go
/kind cleanup
update test mc client test data
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: update test mc client test data

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: update readme and example for new versions
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update readme and example for new versions

.github/workflows/release.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> release-1.25 Update release.yaml

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Use AZURE_BLOB_CONTAINER_NAME blob container var

content/en/blog/releases/v1.25.21.md
doc: add release note for v1.25.21
Fixes #
```release-note
NONE
```
```docs
```
=> doc: add release note for v1.25.21

tests/e2e/utils/vmss_utils.go
/kind testing
[e2e] IsSpotVMSS: Check field is nil to avoid invalid memory problem
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] IsSpotVMSS: Check field is nil to avoid invalid memory problem

pkg/consts/consts.go, tests/e2e/network/network_security_group.go
/kind cleanup
Fix annotation docstring and e2e test case for IPv6.
Fixes #
```release-note
NONE
```
```docs
```
=> Fix allowed-ip-ranges for IPv6 test scenario

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
/kind testing
Support OOT credential provider for CAPZ templates
Fixes #
related: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4110
```release-note
NONE
```
```docs
```
=> Support OOT credential provider for CAPZ templates

pkg/azclient/accountclient/custom.go, pkg/azclient/accountclient/custom_test.go, pkg/azclient/accountclient/interface.go, pkg/azclient/accountclient/mock_accountclient/interface.go, pkg/azclient/accountclient/testdata/Account.yaml
/kind feature
Track2 sdk: add listkeys func to accountclient
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add listkeys func to accountclient

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
/kind testing
Fix script in linux-vmss-ci-version-oot-credential-provider
Fixes #
```release-note
NONE
```
```docs
```
=> Fix script in linux-vmss-ci-version-oot-credential-provider

pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_vmss_cache.go
…
/kind cleanup
remove controllercommon in cloud and move configAzureClients out of configureMultiTenantClients
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: remove controllercommon in cloud and move configAzureClients out of configureMultiTenantClients

tests/e2e/auth/cred.go, tests/e2e/e2e_test.go, tests/e2e/utils/consts.go, tests/e2e/utils/container_registry_utils.go
/kind testing
[e2e] Enable ACR cache test for all pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Enable ACR cache test for all pipeline

pkg/azclient/configloader/load.go
/kind cleanup
expose configloadtype in configloader to remove similar definition in cloud provider.
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: expose configloadtype in configloader

tests/e2e/auth/cred.go, tests/e2e/utils/container_registry_utils.go
/kind testing
[e2e] Retry for acr cache create
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Retry for acr cache create

pkg/provider/azure.go, pkg/provider/azure_instance_metadata.go, pkg/provider/azure_instance_metadata_test.go, pkg/provider/azure_instances_v1.go, pkg/provider/azure_instances_v2.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_routes.go, pkg/provider/azure_zones.go, pkg/provider/azure_zones_test.go
/kind cleanup
move interface reference to implementation
Fixes #
move interface reference to header of implementation.
no behavior change.
```release-note
NONE
```
```docs
```
=> Refactor: reorg provider code: move interface reference to implementation

pkg/azclient/client-gen/generator/genclientfactory_action.go, pkg/azclient/factory_gen.go, pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml, pkg/azclient/utils/options.go, pkg/azclient/vaultclient/testdata/Vault.yaml
/kind cleanup
Track2: remove trytimeout in default settings and add custom options for clientFactory
Fixes #
```release-note
NONE
```
```docs
```
=> Track2: remove trytimeout in default settings and add custom options for clientFactory

.github/workflows/lint-ci-weekly.yaml
/kind testing
Chores: remove linter timeout and use latest golangci-lint
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: remove linter timeout

pkg/azclient/auth.go, pkg/azclient/auth_test.go
/kind cleanup
track2 sdk: remove error in response in authprovider
Fixes #
break change: error in authprovider response has been removed. 
```release-note
NONE
```
```docs
```
=> track2 sdk: remove error in response in authprovider

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
/kind testing
Use latest dualstack machinepool template
Fixes #
```release-note
NONE
```
```docs
```
=> Use latest dualstack machinepool template

hack/deploy-cluster-capz.sh, hack/ensure-clusterctl.sh, tests/e2e/e2e_test.go, tests/e2e/network/sharedhealthprobe.go, tests/e2e/utils/consts.go, tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json
/kind cleanup
chore: adding e2e test for shared health probe
Fixes #
```release-note
NONE
```
```docs
```
=> chore: adding e2e test for shared health probe

.github/workflows/lint.yaml, .golangci.yml
chore: bump golang-ci version for release-1.28 and remove the unsupported --timeout arg.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: bump golang-ci version for release-1.28

pkg/provider/azure.go, pkg/provider/azure_controller_common.go
/kind cleanup
Refactor: move getNodeVMSet to cloud struct
VMSet is a field of cloud object. getNodeVMSet should be provided by cloud object. 
getNodeVMSet is referred in managedDisk controller. 
The controller is only be used in azuredisk csi driver. 
We should move managed disk controller to azuredisk-csi-driver project.
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: move getNodeVMSet to cloud struct

pkg/azclient/recording/recorder.go, pkg/azclient/virtualmachineclient/custom.go, pkg/azclient/virtualmachineclient/custom_test.go, pkg/azclient/virtualmachineclient/interface.go, pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml, pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml, pkg/azclient/virtualmachinescalesetvmclient/custom.go, pkg/azclient/virtualmachinescalesetvmclient/custom_test.go, pkg/azclient/virtualmachinescalesetvmclient/interface.go, pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml
/kind feature
Track2 sdk: support list/get instanceview in vm/vmssvm client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: support list/get instanceview in vm/vmssvm client

tests/kubemark/configs/access-tokens/deployment.yaml
/kind testing
[CI] Use ACR for access-tokens image
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Use ACR for access-tokens image

pkg/azclient/virtualmachineclient/interface.go, pkg/azclient/virtualmachinescalesetvmclient/custom.go, pkg/azclient/virtualmachinescalesetvmclient/interface.go
/kind cleanup
Track2 sdk: expose async update function in vm/vmssvm client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: expose async update function in vm/vmssvm client

pkg/consts/consts.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind bug
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
Fixes #5194
```release-note
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
```
```docs
```
=> Truncate lengthy PIP name

tests/kubemark/configs/density/deployment.yaml, tests/kubemark/configs/density/legacy/rc.yaml, tests/kubemark/configs/experimental/storage/pod-startup/volume-types/configmap/deployment_with_configmap.yaml, tests/kubemark/configs/experimental/storage/pod-startup/volume-types/downwardapi/deployment_with_downwardapi.yaml, tests/kubemark/configs/experimental/storage/pod-startup/volume-types/emptydir/deployment_with_emptydir.yaml, tests/kubemark/configs/experimental/storage/pod-startup/volume-types/persistentvolume/deployment_with_pvc.yaml, tests/kubemark/configs/experimental/storage/pod-startup/volume-types/secret/deployment_with_secret.yaml, tests/kubemark/configs/l4ilb/dep.yaml, tests/kubemark/configs/load/config.yaml, tests/kubemark/configs/load/daemonset.yaml, tests/kubemark/configs/load/deployment.yaml, tests/kubemark/configs/load/experimental-config.yaml, tests/kubemark/configs/load/job.yaml, tests/kubemark/configs/load/legacy/rc.yaml, tests/kubemark/configs/load/simple-deployment.yaml, tests/kubemark/configs/load/statefulset.yaml, tests/kubemark/configs/node-throughput/config.yaml, tests/kubemark/configs/node-throughput/windows_override.yaml, tests/kubemark/templates/hollow-node.yaml
/kind testing
Use MCR images for ones in kubemark
Fixes #
```release-note
NONE
```
```docs
```
=> Use MCR images for ones in kubemark

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
/kind testing
[CI] Remove identity in mp dualstack template
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Remove identity in mp dualstack template

.github/workflows/lint.yaml, .golangci.yml
/kind testing
Bump golangci lint 1.27
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Bump 1.27 golangci-lint

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, .pipelines/run-basic-lb-e2e.yml, .pipelines/run-vmas-e2e.yml, kubetest2-aks/go.mod
/kind testing
Bump kubetest2 pipeline GoTool Go version. Go 1.21.5
Fixes #
```release-note
NONE
```
```docs
```
=> Bump kubetest2 pipeline GoTool Go version

.github/workflows/lint.yaml, .golangci.yml
/kind testing
[CI] Bump 1.25 golangci-lint
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Bump 1.25 golangci-lint

.github/workflows/lint.yaml, .golangci.yml
/kind testing
[CI] Bump 1.26 golangci-lint
Fixes #
```release-note
NONE
```
```docs
```
=> [CI] Bump 1.26 golangci-lint

cmd/acr-credential-provider/plugin.go, cmd/acr-credential-provider/plugin_test.go, pkg/credentialprovider/azure_credentials.go
/kind bug
chore: add cmd change for credentialprovider api-version upgrade
Fixes #5276
```release-note
chore: add cmd change for credentialprovider api-version upgrade
```
```docs
```
=> chore: upgrade credentialprovider-api-version to v1

content/en/topics/loadbalancer.md
doc: enrich doc for shared slb probe
Fixes #
```release-note
NONE
```
```docs
```
=> doc: enrich doc for shared slb probe

.github/workflows/trivy.yaml, health-probe-proxy/Dockerfile
(cherry picked from commit a804d6d518499efab91ed9c2efa849d69e9a0463)
/kind cleanup
chore: pin gcr.io/distroless/static to a hash value
Fixes #
```release-note
NONE
```
```docs
```
=> chore: pin gcr.io/distroless/static to a hash value

pkg/azclient/diskclient/custom.go, pkg/azclient/diskclient/custom_test.go, pkg/azclient/diskclient/interface.go, pkg/azclient/diskclient/mock_diskclient/interface.go, pkg/azclient/diskclient/testdata/Disk.yaml, pkg/azclient/factory.go, pkg/azclient/factory_gen.go, pkg/azclient/mock_azclient/interface.go, pkg/azclient/snapshotclient/interface.go
/kind cleanup
Refactor: add patch to diskclient and add multi-sub support for snapshotclient
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: add patch to diskclient and add multi-sub support for snapshotclient

.pipelines/templates/customconfiguration-autoscaling-multipool.json, .pipelines/templates/customconfiguration-autoscaling.json, .pipelines/templates/customconfiguration.json, kubetest2-aks/cluster-templates/customconfiguration-ccm.json, kubetest2-aks/cluster-templates/customconfiguration.json, kubetest2-aks/deployer/up.go
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> fix(kubetest2-aks): customized flags should start with --

tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml, tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml, tests/k8s-azure/manifest/linux-vmss-basic-lb.json, tests/k8s-azure/manifest/linux-vmss.json, tests/k8s-azure/manifest/linux.json
/kind cleanup
Remove feature gate MixedProtocolLBService
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#feature-gates-that-are-removed
Fixes #
```release-note
NONE
```
```docs
```
=> Remove feature gate MixedProtocolLBService

.pipelines/templates/customconfiguration-autoscaling.json, .pipelines/templates/customconfiguration-k8s.json, .pipelines/templates/customconfiguration.json
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27]fix(kubetest2-aks): customized flags should start with --

.pipelines/templates/customconfiguration-autoscaling-multipool.json, .pipelines/templates/customconfiguration-autoscaling.json, .pipelines/templates/customconfiguration-k8s.json, .pipelines/templates/customconfiguration.json
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29]fix(kubetest2-aks): customized flags should start with --

.pipelines/templates/customconfiguration-autoscaling-multipool.json, .pipelines/templates/customconfiguration-autoscaling.json, .pipelines/templates/customconfiguration-k8s.json, .pipelines/templates/customconfiguration.json
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28]fix(kubetest2-aks): customized flags should start with --

.pipelines/templates/customconfiguration-k8s.json, .pipelines/templates/customconfiguration.json
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> [relase-1.26]fix(kubetest2-aks): customized flags should start with --

.pipelines/scripts/run-e2e.sh
/kind testing
Fixes #
```release-note
NONE
```
```docs
```
=> chore(test): use differentiate component image tags

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Remove --azure-container-registry-config in templates
Follow up the [CAPZ PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4436)
Fixes #
```release-note
NONE
```
```docs
```
=> Remove --azure-container-registry-config in templates

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: Release v1.29.0.
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Release v1.29.0.

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
/kind testing
Update IPv6 template. Remove DNS workaround
Followed: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4350
Fixes #
```release-note
NONE
```
```docs
```
=> Update IPv6 template

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: remove async ops in vmset

pkg/azclient/auth_conf.go
/kind bug
Fix: AADFederatedTokenFile doesn't work
Fixes #5424
```release-note
NONE
```
```docs
```
=> Fix: AADFederatedTokenFile doesn't work

pkg/azclient/diskclient/testdata/Disk.yaml, pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml, pkg/azclient/snapshotclient/testdata/Snapshot.yaml, pkg/azclient/virtualmachineclient/interface.go, pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
/kind feature
track2 sdk: Add attach/detach method in vmclient
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: Add attach/detach method in vmclient

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap_test.go, pkg/provider/azure_zones_test.go, pkg/util/sets/string.go, pkg/util/sets/string_test.go
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
chore: Add case-insensitive string set utility
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Add case-insensitive string set utility

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml
/kind testing
Update non-ipv4 vmss job templates
* Support latest K8s ver
* Follow CAPZ templates
Related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/5400
```release-note
NONE
```
```docs
```
=> Update non-ipv4 vmss job templates

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Use CAAPH to install cloudprovider in CI templates
Fixes #5457
```release-note
NONE
```
```docs
```
=> Use CAAPH to install cloudprovider in CI templates

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: match tags issue in account search
original logic only works when the key are the same while value is different
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1713
```release-note
fix: match tags issue in account search
```
```docs
fix: match tags issue in account search
```
=> fix: match tags issue in account search

pkg/azclient/virtualmachineclient/interface.go, pkg/azclient/virtualmachineclient/mock_virtualmachineclient/interface.go
/kind feature
Track2: add beginupdate function in vmclient
Fixes #
```release-note
NONE
```
```docs
```
=> Track2: add beginupdate function in vmclient

tests/e2e/node/unmanaged_node.go
/kind testing
[e2e] Print error if unmanaged Node test fails
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Print error if unmanaged Node test fails

.github/dependabot.yml
/kind cleanup
Add group update policy
Fixes #
```release-note
NONE
```
```docs
```
=> Add group update policy

.github/dependabot.yml
/kind cleanup
Add dependabot config for health-probe-proxy
Fixes #
```release-note
NONE
```
```docs
```
=> Add dependabot config for health-probe-proxy

.github/workflows/release-azclient-trace.yml, .github/workflows/release-azclient.yml, .github/workflows/release-configloader.yml, .github/workflows/update-vendor-license.yml
/kind testing
Track2 sdk: add release pipeline for azclient
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add release pipeline for azclient

.github/dependabot.yml
/kind testing
Add dependabot job for kube-health-proxy
Fixes #
```release-note
NONE
```
```docs
```
=> Add dependabot job for kube-health-proxy

.github/workflows/release-azclient-trace.yml, .github/workflows/release-azclient.yml, .github/workflows/release-configloader.yml
/kind testing
Fix: fetch all tags in azclient update job
Fixes #
```release-note
NONE
```
```docs
```
=> Fix: fetch all tags in azclient update job

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/scripts/run-e2e.sh, hack/pkg-config.sh, hack/print-workspace-status.sh, kubetest2-aks/Makefile
/kind testing
Fix:ignore azclient tags when fetch git tags
Fixes #
```release-note
NONE
```
```docs
```
=> Fix:ignore azclient tags when fetch git tags

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
/kind bug
For dual-stack Windows case, both ipv4 and ipv6 ip address are provided and separated by comma in a string. This change is to split the ipv4 and ipv6 addresses and check whether all these provided IPs exist in the cloud provider.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: handle comma-separated provided IPs

pkg/azclient/utils/transport.go, pkg/azureclients/armclient/azure_armclient.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Add timeout setting for default transport

.github/workflows/lint.yaml
/kind cleanup
Set lint go ver with go.mod
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] Set lint go ver with go.mod

.github/workflows/lint.yaml
/kind cleanup
Set lint go ver with go.mod
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28] Set lint go ver with go.mod

.github/workflows/lint.yaml
/kind cleanup
Set lint go ver with go.mod
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Set lint go ver with go.mod

pkg/azclient/utils/options.go
/kind cleanup
Track2 sdk:enable InsecureAllowCredentialWithHTTP by default
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk:enable InsecureAllowCredentialWithHTTP by default

.github/workflows/release-azclient.yml, .github/workflows/release-configloader.yml
/kind testing
chores: update path trigger for azclient
Fixes #
```release-note
NONE
```
```docs
```
=> chores: update path trigger for azclient

Makefile
/kind testing
Skip license check test for dependabot
Fixes #
license update will be accomplished by https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/.github/workflows/update-vendor-license.yml
```release-note
NONE
```
```docs
```
=> Skip license check test for dependabot

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Surround CAAPH values strings in quotes
Follow up: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4593
Fixes #
```release-note
NONE
```
```docs
```
=> Surround CAAPH values strings in quotes

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/consts/consts.go, pkg/retry/azure_error.go, pkg/retry/azure_error_test.go
/kind bug
fix: Retry put vmss vm on preempted error
Fixes #
```release-note
fix: Retry put vmss vm on preempted error
```
```docs
```
=> fix: Retry put vmss vm on preempted error

hack/test_k8s_e2e_capz.sh, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml, tests/k8s-azure/manifest/kube-proxy/config.conf
/kind testing
Enable TrafficDistribution feature gates in multi-zones templates
Fixes #5814
```release-note
NONE
```
```docs
```
=> Enable TrafficDistribution feature gates in multi-zones templates

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
/kind testing
Use quotes for linux-vmss-ci-version template
Fixes #
```release-note
NONE
```
```docs
```
=> Use quotes for linux-vmss-ci-version template

pkg/azureclients/armclient/util.go
/kind cleanup
chore: add ARM request method and URI to logs for troubleshooting
Fixes #
```release-note
NONE
```
```docs
```
=> chore: add ARM request method and URI to logs for troubleshooting

.github/workflows/trivy.yaml
/kind testing
Chores: unblock trivy job if cve is found
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: unblock trivy job if cve is found

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/consts/consts.go, pkg/retry/azure_error.go, pkg/retry/azure_error_test.go
/kind bug
fix: Retry put vmss vm on preempted error
Fixes #
```release-note
fix: Retry put vmss vm on preempted error
```
```docs
```
=> [release-1.26] fix: Retry put vmss vm on preempted error

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/consts/consts.go, pkg/retry/azure_error.go, pkg/retry/azure_error_test.go
/kind bug
fix: Retry put vmss vm on preempted error
Fixes #
```release-note
fix: Retry put vmss vm on preempted error
```
```docs
```
=> [release-1.28] fix: Retry put vmss vm on preempted error

.github/dependabot.yml
/kind testing
Update dependabot for 1.30 release
Fixes #
```release-note
NONE
```
```docs
```
=> Update dependabot for 1.30 release

kubetest2-aks/go.mod
/kind testing
Update kubetest2 go.mod
Fixes #
```release-note
NONE
```
```docs
```
=> Update kubetest2 go.mod

pkg/provider/azure_loadbalancer_repo.go
/kind bug
Add default timeout for lb client
Fixes #5642
```release-note
NONE
```
```docs
```
=> Add default timeout for lb client

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/fnutil/slice.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go, pkg/provider/loadbalancer/securitygroup/securityrule.go, pkg/provider/loadbalancer/testutil/fixture/azure_publicip.go, pkg/provider/loadbalancer/testutil/fixture/kubernetes.go, tests/e2e/network/network_security_group.go
/kind bug
Fix the bug introduced in v1.29
How to reproduce:
``` bash
kubectl expose deployment nginx --type=LoadBalancer --port=80
kubectl expose deployment nginx --type=LoadBalancer --port=443 --name=http
s --load-balancer-ip {Copy the above service external IP}
```
Fixes #
```release-note
Fix cleaning up security rule for services with shared external-IP
```
```docs
```
=> Fix cleaning up security rule for services with shared external-IP

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/daily-gc.yml, .pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, .pipelines/run-basic-lb-e2e.yml, .pipelines/run-e2e.yml, .pipelines/run-vmas-e2e.yml, .pipelines/scripts/daily-gc.sh, .pipelines/scripts/run-e2e.sh, tests/e2e/e2e_test.go, tests/e2e/utils/azure_auth.go
/kind testing
Use managed identity for aks pipeline
Fixes #
```release-note
NONE
```
```docs
```
=> Use managed identity for aks pipeline

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
We should only check internal lbs for internal services when using multi-slb.
Fixes #
```release-note
fix: Only check internal lbs for internal services when using multi-slb
```
```docs
```
=> fix: Only check internal lbs for internal services when using multi-slb

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/daily-gc.yml, .pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, .pipelines/run-basic-lb-e2e.yml, .pipelines/run-e2e.yml, .pipelines/scripts/daily-gc.sh, .pipelines/scripts/run-e2e.sh, tests/e2e/e2e_test.go, tests/e2e/utils/azure_auth.go
/kind testing
Use managed identity for aks pipeline
* Update azure pipeline config
* Update e2e to support managed identity
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] Use managed identity for aks pipeline

.pipelines/ccm-image.yml, .pipelines/cnm-image.yml, .pipelines/daily-gc.yml, .pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, .pipelines/run-basic-lb-e2e.yml, .pipelines/run-e2e.yml, .pipelines/run-vmas-e2e.yml, .pipelines/scripts/daily-gc.sh, .pipelines/scripts/run-e2e.sh, tests/e2e/e2e_test.go, tests/e2e/utils/azure_auth.go
/kind testing
Use managed identity for aks pipeline
* Update azure pipeline config
* Update e2e to support managed identity
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28] Use managed identity for aks pipeline

pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/fnutil/slice.go, pkg/provider/loadbalancer/testutil/fixture/azure_publicip.go, pkg/provider/loadbalancer/testutil/fixture/kubernetes.go, tests/e2e/network/network_security_group.go
/kind bug
cherry-pick #6186
Fixes #
```release-note
Fix generating NSG rules while using shared BYO public IP
```
```docs
```
=> [release-1.30] Fix generating NSG rules while using shared BYO public IP

pkg/azclient/armauth/keyvault_credential.go, pkg/azclient/auth.go, pkg/azclient/auth_conf.go
/kind feature
Refined the mechanism for refreshing tokens from Azure KeyVault by adding a mutex guard to prevent concurrent modifications.
Fixes #
```release-note
NONE
```
```docs
```
=> [pkg/azclients] Add mutex guard for thread-safe token refresh

pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/fnutil/slice.go, pkg/provider/loadbalancer/testutil/fixture/azure_publicip.go, pkg/provider/loadbalancer/testutil/fixture/kubernetes.go, tests/e2e/network/network_security_group.go
/kind bug
cherry-pick #6186
Fixes #
```release-note
Fix generating NSG rules while using shared BYO public IP
```
```docs
```
=> [release-1.29] Fix generating NSG rules while using shared BYO public IP

pkg/azclient/auth.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> [pkg/azclients] Set auth provider client options

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go, tests/kubemark/configs/experimental/storage/pod-startup/config.yaml
/kind cleanup
Chores:fix spelling errors
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27]Chores:fix spelling errors

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go, tests/kubemark/configs/experimental/storage/pod-startup/config.yaml
/kind cleanup
Chores: fix spelling errors
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28]Chores: fix spelling errors

pkg/azclient/auth.go
/kind bug
The audience had been added scheme in
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/arm/runtime/runtime.go#L12-L22
Fixes #
```release-note
NONE
```
```docs
```
=> [azclients] Remove redundant URL scheme when getting TokenScope

go.mod, go.sum, pkg/provider/config/azure_auth.go, vendor/modules.txt, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Upgrade azclient pkg

go.mod, go.sum, pkg/provider/config/azure_auth.go, vendor/modules.txt, vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/auth.go
/kind cleanup
cherry-pick #6482 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29] Upgrade azclient

tests/e2e/network/network_security_group.go
/kind cleanup
close #6151 
Fixes #
```release-note
NONE
```
```docs
```
=> Add e2e test for multiple services disabling floating IP

pkg/log/logger.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go, tests/e2e/network/network_security_group.go
/kind cleanup
cherry-pick #6487 #6473
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29] Add e2e tests and refactor logging

tests/e2e/utils/container_registry_utils.go
/kind testing
[release-1.28][e2e] Replace dockerhub with MCR for nginx image
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28][e2e] Replace dockerhub with MCR for nginx image

tests/e2e/utils/container_registry_utils.go
/kind testing
[release-1.27][e2e] Replace dockerhub with MCR for nginx image
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27][e2e] Replace dockerhub with MCR for nginx image

tests/e2e/utils/container_registry_utils.go
/kind testing
[release-1.29][e2e] Replace dockerhub with MCR for nginx image
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29][e2e] Replace dockerhub with MCR for nginx image

tests/e2e/utils/container_registry_utils.go
/kind testing
[release-1.30][e2e] Replace dockerhub with MCR for nginx image
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30][e2e] Replace dockerhub with MCR for nginx image

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: add getFileServicePropertiesCache to fix throttling issue
Fixes #
```release-note
fix: add getFileServicePropertiesCache to fix throttling issue
```
```docs
fix: add getFileServicePropertiesCache to fix throttling issue
```
=> fix: add getFileServicePropertiesCache to fix throttling issue

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: Update readme and example with latest images
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Update readme and example with latest images

tests/e2e/utils/azure_auth.go
This PR enabled federated identity test profiles, which are now required for E2E flows when using CAPZ clusters built at main. 
This is due to a requirement from the k8s community infra migration effort.
Fixes #6621
```release-note
NONE
```
```docs
```
=> test: enable federated identity test profile

tests/e2e/e2e_test.go
chore: Support ginkgo failFast for e2e debugging
Fixes #
Partly #6577
```release-note
NONE
```
```docs
```
=> chore: Support ginkgo failFast for e2e debugging

tests/e2e/utils/container_registry_utils.go
/kind cleanup
This PR modifies an `az login` command invoked from the e2e tests to use a federated token when available instead of always trying to use a service principal password.
Fixes #
```release-note
NONE
```
```docs
```
=> test: login with federated token for ACR

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
chore: Exclude unwanted tags in e2e to bypass azure policies.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Exclude unwanted tags in e2e

tests/e2e/utils/azure_auth.go, tests/e2e/utils/container_registry_utils.go
/kind cleanup
This PR 
1. modifies an `az login` command invoked from the e2e tests to use a federated token when available instead of always trying to use a service principal password.
2. support workload identity in e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28] Support workload identity in e2e test

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
chore: Migrate all e2e templates to workload identity
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Migrate all e2e templates to workload identity

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml
chore: Change azure client id env in a cluster template
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Change azure client id env in a cluster template

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
fix: Fix the format of user assigned identity provider ids
Fixes #
```release-note
NONE
```
```docs
```
=> fix: Fix the format of user assigned identity provider ids

pkg/azclient/armauth/keyvault_credential.go, pkg/azclient/go.mod, pkg/azclient/go.sum
/kind cleanup
release-1.29 still uses go version 1.21, fix the min-go-version requirement of azclient
Fixes #
```release-note
NONE
```
```docs
```
=> [azclient] Downgrade module go version

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml
fix: Change azure client id env in all cluster templates
Fixes #
```release-note
NONE
```
```docs
```
=> fix: Change azure client id env in all cluster templates

hack/update-mock-clients.sh
Fix the following failure:
```
Updating mocks for /home/runner/work/cloud-provider-azure/cloud-provider-azure/pkg/azureclients/armauth
Error: hack/update-mock-clients.sh: line 36: /home/runner/work/cloud-provider-azure/cloud-provider-azure/pkg/azureclients/armauth/mockarmauth/interface.go: No such file or directory
make: *** [Makefile:380: update-mocks] Error 1
Error: Process completed with exit code 2.
```
Fixes #
```release-note
NONE
```
```docs
```
=> fix: skip mock gen for armauth

Dockerfile, cloud-node-manager.Dockerfile, e2e.Dockerfile
/kind cleanup
fix: Bump golang version to v1.22.5 to fix cves
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] fix: Bump golang version to v1.22.5 to fix cves

.golangci.yml
/kind cleanup
Exclude G115 from lint rules.
Fixes #
```release-note
NONE
```
```docs
```
=> Exclude G115 from lint rules.

pkg/azclient/accountclient/zz_generated_client.go, pkg/azclient/availabilitysetclient/zz_generated_client.go, pkg/azclient/blobcontainerclient/zz_generated_client.go, pkg/azclient/client-gen/generator/template.go, pkg/azclient/deploymentclient/zz_generated_client.go, pkg/azclient/diskclient/zz_generated_client.go, pkg/azclient/fileshareclient/zz_generated_client.go, pkg/azclient/go.mod, pkg/azclient/interfaceclient/zz_generated_client.go, pkg/azclient/ipgroupclient/zz_generated_client.go, pkg/azclient/loadbalancerclient/zz_generated_client.go, pkg/azclient/managedclusterclient/zz_generated_client.go, pkg/azclient/privateendpointclient/zz_generated_client.go, pkg/azclient/privatelinkserviceclient/zz_generated_client.go, pkg/azclient/privatezoneclient/zz_generated_client.go, pkg/azclient/publicipaddressclient/zz_generated_client.go, pkg/azclient/publicipprefixclient/zz_generated_client.go, pkg/azclient/registryclient/zz_generated_client.go, pkg/azclient/routetableclient/zz_generated_client.go, pkg/azclient/secretclient/zz_generated_client.go, pkg/azclient/securitygroupclient/zz_generated_client.go, pkg/azclient/snapshotclient/zz_generated_client.go, pkg/azclient/sshpublickeyresourceclient/zz_generated_client.go, pkg/azclient/subnetclient/zz_generated_client.go, pkg/azclient/vaultclient/zz_generated_client.go, pkg/azclient/virtualmachineclient/zz_generated_client.go, pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go, pkg/azclient/virtualmachinescalesetvmclient/zz_generated_client.go, pkg/azclient/virtualnetworkclient/zz_generated_client.go, pkg/azclient/virtualnetworklinkclient/zz_generated_client.go
/kind bug
This PR fixes the handling of metric context in the defer block, where it previously failed to catch the actual error.
Fixes #
```release-note
NONE
```
```docs
```
=> [azclient] Fix metric context handling in defer block

content/en/blog/releases/v1.28.12.md, content/en/blog/releases/v1.29.10.md, content/en/blog/releases/v1.30.6.md, content/en/blog/releases/v1.31.0.md
doc: Add release notes for new versions
Fixes #
```release-note
doc: Add release notes for new versions
```
```docs
```
=> doc: Add release notes for new versions

go.mod
/kind cleanup
chore: Bump ccm go version from 1.22.5 to 1.23.0
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Bump ccm go version from 1.22.5 to 1.23.0

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/iputil/prefix.go, pkg/provider/loadbalancer/iputil/prefix_test.go, pkg/provider/loadbalancer/iputil/prefix_tree.go, pkg/provider/loadbalancer/iputil/prefix_tree_test.go, tests/e2e/network/network_security_group.go
/kind bug
cherry-pick #6807
Fixes #
```release-note
Aggregate overlapping allowed source ranges
```
```docs
```
=> [release-1.31] Aggregate overlapping allowed source ranges

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/iputil/prefix.go, pkg/provider/loadbalancer/iputil/prefix_test.go, pkg/provider/loadbalancer/iputil/prefix_tree.go, pkg/provider/loadbalancer/iputil/prefix_tree_test.go, tests/e2e/network/network_security_group.go
/kind bug
cherry-pick #6807
Fixes #
```release-note
Aggregate overlapping allowed source ranges
```
```docs
```
=> [release-1.30] Aggregate overlapping allowed source ranges

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/iputil/prefix.go, pkg/provider/loadbalancer/iputil/prefix_test.go, pkg/provider/loadbalancer/iputil/prefix_tree.go, pkg/provider/loadbalancer/iputil/prefix_tree_test.go, tests/e2e/network/network_security_group.go
/kind bug
cherry-pick #6807
Fixes #
```release-note
Aggregate overlapping allowed source ranges
```
```docs
```
=> [release-1.29] Aggregate overlapping allowed source ranges

Dockerfile, Makefile, cloud-node-manager.Dockerfile, health-probe-proxy/Dockerfile
Enable CGO to use dynamic linking for C libraries it's necessary when we build apps through [Dalec](https://github.com/Azure/dalec-build-defs)which use dynamic linking openssl to build a Microsoft compliant app.
Fixes #
```release-note
```
```docs
```
=> enable cgo to use dynamic linking for C libraries

pkg/azclient/client-gen/generator/template.go, pkg/azclient/roledefinitionclient/roledefinitionclient_suite_test.go, pkg/azclient/roledefinitionclient/zz_generated_client.go
/kind cleanup
track2 sdk: Remove unused subscription id in roledefinition client
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: Remove unused subscription id in roledefinition client

go.mod, health-probe-proxy/go.mod, kubetest2-aks/go.mod, pkg/azclient/client-gen/go.mod, pkg/azclient/configloader/go.mod, pkg/azclient/go.mod, pkg/azclient/trace/go.mod
/kind cleanup
Chores: bump go to 1.23.1
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: bump go to 1.23.1

pkg/credentialprovider/azure_credentials.go
/kind cleanup
Chores:remove unused wrapper in credential client in credentialprovider 
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:remove unused wrapper in credential client in credentialprovider 

Dockerfile, cloud-node-manager.Dockerfile, e2e.Dockerfile
/kind bug
fix: Bump golang version to 1.23.1 to fix cves
Fixes #
```release-note
NONE
```
```docs
```
=> fix: Bump golang version to 1.23.1 to fix cves

go.mod
/kind bug
fix: CVE-2024-34156 and more
Fixes #
```release-note
NONE
```
```docs
```
=> fix: CVE-2024-34156 and more

content/en/blog/releases/v1.27.21.md, content/en/blog/releases/v1.28.13.md, content/en/blog/releases/v1.29.11.md, content/en/blog/releases/v1.30.7.md, content/en/blog/releases/v1.31.1.md
doc: add release notes for new releases
Fixes #
```release-note
NONE
```
```docs
```
=> doc: add release notes for new releases

cloud-node-manager-windows-hpc.Dockerfile, cloud-node-manager-windows.Dockerfile
/kind bug
The fix is straightfoward, and correct the binary path in the windows dockerfile entrypoint.
So far there's no case reporting this issue as the entrypoint is defined explicitly in the container manifest.
Fixes #
```release-note
NONE
```
```docs
```
=> fix cloud node manager bin path in dockerfile

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/controller-manager.go, pkg/log/flag.go, pkg/log/logger.go, pkg/log/slog.go, pkg/log/std.go
/kind cleanup
cherry-pick #7083 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30] Add support for JSON-formatted logging

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/controller-manager.go, pkg/log/flag.go, pkg/log/logger.go, pkg/log/slog.go, pkg/log/std.go
/kind cleanup
cherry-pick #7083 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29] Add support for JSON-formatted logging

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/controller-manager.go, pkg/log/flag.go, pkg/log/logger.go, pkg/log/slog.go, pkg/log/std.go
/kind cleanup
cherry-pick #7083 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.31] Add support for JSON-formatted logging

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/app/core.go, cmd/cloud-node-manager/app/nodemanager.go, pkg/nodeipam/ipam/cidr_allocator.go, pkg/nodeipam/ipam/cloud_cidr_allocator.go, pkg/nodeipam/ipam/cloud_cidr_allocator_test.go, pkg/nodeipam/ipam/range_allocator.go, pkg/nodeipam/ipam/range_allocator_test.go, pkg/nodeipam/node_ipam_controller.go, pkg/nodemanager/nodemanager.go
/kind cleanup
Chores:adopt context.Context in cloud provider#### Which issue(s) this PR fixes:
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:adopt context.Context in cloud provider

pkg/provider/loadbalancer/fnutil/slice.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go
/kind cleanup
refactor indexset: support for index mapping from any type to comparable one
Fixes #
```release-note
NONE
```
```docs
```
=> refactor indexset: support for index mapping from any type to comparable one

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go
/kind bug
cherry-pick #7167
Fixes #
```release-note
Fix checking service references from `tags` when deleting PIP
```
```docs
```
=> [release-1.28] Fix checking service references from `tags` when deleting PIP

content/en/topics/credential-provider.md
Add documentation to explain the use cases and how-to for credential provider registry mirror.
Fixes #
```release-note
None
```
```docs
```
=> doc: explain credential provider registry mirror

pkg/azclient/arm_conf_test.go, pkg/azclient/factory_conf_test.go
/kind testing 
Chores: Add ut for user agent config
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: Add ut for user agent config

content/en/blog/releases/v1.27.21.md
Update release notes for v1.27.21
Fixes #
```release-note
NONE
```
```docs
```
=> Update release notes for v1.27.21

pkg/provider/azure_loadbalancer.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/configuration.go, pkg/provider/loadbalancer/configuration_test.go, pkg/provider/loadbalancer/k8sevent.go
/kind cleanup
Tidy up the package’s boundaries and scope; and add a k8s event unit test for it.
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor nsg access control for k8s event testing

Dockerfile, Makefile, cloud-node-manager.Dockerfile
When CGO is enabled, cross-platform build failed when building arm64 binary on amd64 platform with error
```
#12 13.37 gcc: error: unrecognized command-line option '-marm'; did you mean '-mabm'?
#12 78.86 make: *** [Makefile:107: bin/azure-cloud-node-manager] Error 1
```
failed build link: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-provider-azure-push-images/1844238025572225024
Fix this by specifying cross compiler when cgo is enabled to build golang binary
Fixes #
```release-note
NONE
```
```docs
```
=>  specify cross compiler when cgo is enabled

pkg/azclient/blobservicepropertiesclient/interface.go, pkg/azclient/factory.go, pkg/azclient/factory_gen.go, pkg/azclient/fileservicepropertiesclient/interface.go, pkg/azclient/managedclusterclient/testdata/ManagedCluster.yaml, pkg/azclient/mock_azclient/interface.go, pkg/azclient/privatezoneclient/testdata/PrivateZone.yaml, pkg/azclient/virtualnetworklinkclient/custom_test.go, pkg/azclient/virtualnetworklinkclient/testdata/VirtualNetworkLink.yaml
/kind feature
Track2 sdk: enable cross sub support for file/blob service client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: enable cross sub support for file/blob service client

.github/workflows/trivy.yaml
/kind testing
chores: skip trivy db update
Fixes #
```release-note
NONE
```
```docs
```
=> chores: skip trivy db update

.github/workflows/codespell.yaml, .github/workflows/dependency-review.yml, .github/workflows/lint.yaml, .github/workflows/trivy.yaml
/kind cleanup
Chores: trigger build only when needed
Fixes #
```release-note
```
```docs
NONE
```
=> Chores: trigger build only when needed

Dockerfile, cloud-node-manager.Dockerfile, e2e.Dockerfile
/kind cleanup
replace docker hub registry with mcr repo
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: replace docker hub registry with mcr repo

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml
Remove GA feature gate HPAContainerMetrics
Fixes #
```release-note
NONE
```
```docs
```
=> Remove GA feature gate HPAContainerMetrics

Dockerfile, cloud-node-manager.Dockerfile, health-probe-proxy/Dockerfile
/kind cleanup
Chores: add sha signature to dockerfile
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: add sha signature to dockerfile

pkg/azclient/configloader/load.go, pkg/azclient/configloader/loader_file_test.go, pkg/azclient/configloader/loader_yaml.go, pkg/azclient/configloader/loader_yaml_test.go
/kind cleanup
track2 sdk: load config from string
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: load config from string

content/en/topics/azure-permissions.md
this change adds a few azure permissions which are required by linked actions. this is being proposed based on an audit done by red hat during a recent security review, please see
https://issues.redhat.com/browse/OCPBUGS-44126 for more information.
Fixes #
```release-note
Updated suggested Azure permissions documentation
```
```docs
```
=> update recommended ccm azure permissions

pkg/azclient/cache/go.mod
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: rename cache module in azclient

pkg/provider/azure.go
/kind cleanup
Chores: add ua for cloud provider
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: add ua for cloud provider

pkg/azclient/accountclient/custom.go, pkg/azclient/accountclient/custom_test.go, pkg/azclient/accountclient/interface.go, pkg/azclient/accountclient/testdata/Account.yaml
/kind cleanup
Track2 sdk:add update function for account client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk:add update function for account client

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_storageaccount_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmssflex.go, pkg/util/lockmap/lockmap.go, pkg/util/lockmap/lockmap_test.go
/kind cleanup
Chores: move lockmap to util package
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: move lockmap to util package

go.mod
/kind cleanup
chore: drop use of winreadlinkvolume godebug option on Windows node
refer to https://github.com/kubernetes/kubernetes/pull/129103 for more details
Fixes #
```release-note
none
```
```docs
none
```
=> chore: drop use of winreadlinkvolume godebug option on Windows node

pkg/azclient/publicipaddressclient/interface.go, pkg/azclient/publicipaddressclient/mock_publicipaddressclient/interface.go
/kind feature
Track2 sdk: add GetVirtualMachineScaleSetPublicIPAddress to pip client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add GetVirtualMachineScaleSetPublicIPAddress to pip client

pkg/provider/storage/azure_storageaccount.go, pkg/provider/storage/azure_storageaccount_test.go
/kind bug
Chores: init sub repo in storage account package
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: init sub repo in storage account package

pkg/azclient/fileshareclient/custom.go, pkg/azclient/fileshareclient/custom_test.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go, pkg/azclient/fileshareclient/testdata/FileShare.yaml
/kind feature
Track2 sdk: add list function to fileshareclient
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add list function to fileshareclient

pkg/provider/storage/azure_storageaccount.go
/kind feature
feat: add privateDNSZoneName option in AccountOptions
Fixes #
```release-note
none
```
```docs
none
```
=> feat: add privateDNSZoneName option in AccountOptions

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_vmss_cache.go
/kind cleanup
cleanup: updateCache function
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: updateCache function

pkg/azclient/fileshareclient/custom.go, pkg/azclient/fileshareclient/custom_test.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
/kind cleanup
Track2 sdk: add filter parameter in list function of fileshare client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add filter parameter in list function of fileshare client

pkg/azclient/fileshareclient/fileshareclient_test.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go, pkg/azclient/fileshareclient/zz_generated_client.go
/kind feature
Track2 sdk:add expand param in get function of fileshare client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk:add expand param in get function of fileshare client

.github/workflows/codeql-analysis.yml
/kind cleanup
Chores:ignore mock file in coverage test
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:ignore mock file in coverage test

content/en/blog/releases/v1.32.0.md
Update release notes for v1.32.0
Fixes #
```release-note
NONE
```
```docs
```
=> Update release notes for v1.32.0

pkg/azclient/virtualmachineclient/interface.go, pkg/azclient/virtualmachineclient/testdata/VirtualMachine.yaml, pkg/azclient/virtualmachineclient/virtualmachineclient_test.go, pkg/azclient/virtualmachineclient/zz_generated_client.go, pkg/azclient/virtualmachinescalesetclient/interface.go, pkg/azclient/virtualmachinescalesetclient/testdata/VirtualMachineScaleSet.yaml, pkg/azclient/virtualmachinescalesetclient/virtualmachinescalesetclient_test.go, pkg/azclient/virtualmachinescalesetclient/zz_generated_client.go, pkg/azclient/virtualmachinescalesetvmclient/custom_test.go, pkg/azclient/virtualmachinescalesetvmclient/interface.go, pkg/azclient/virtualmachinescalesetvmclient/testdata/VirtualMachineScaleSetVM.yaml, pkg/azclient/virtualmachinescalesetvmclient/zz_generated_client.go
/kind cleanup
track2 sdk: add etag support for compute client
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk: add etag support for compute client

vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/custom.go
/kind cleanup
Track2 sdk: remove unused code
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: remove unused code

.github/dependabot.yml
/kind testing
Chores: add release-1.28 release-1.29 to supported list.
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: add release-1.28 release-1.29 to supported list.

pkg/provider/azure.go
/kind bug
fix: AzureStack env var setting issue
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8002
Fixes #
```release-note
fix: AzureStack env var setting issue
```
```docs
fix: AzureStack env var setting issue
```
=> [release-1.30] fix: AzureStack env var setting issue

hack/test-ccm-e2e.sh
/kind testing
Chores: update test deps before run e2e test
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: update test deps before run e2e test

pkg/credentialprovider/azure_credentials.go, pkg/provider/azure.go
/kind bug
[release-1.31]bump azclient to 0.4.14
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.31]bump azclient to 0.4.14

pkg/credentialprovider/azure_credentials.go, pkg/provider/azure.go
[release-1.30]bump azclient to 0.4.14
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30]bump azclient to 0.4.14

Dockerfile, cloud-node-manager.Dockerfile, e2e.Dockerfile
/kind cleanup
bump golang to 1.23.6-bookworm
Fixes #
```release-note
NONE
```
```docs
```
=> bump golang to 1.23.6-bookworm

content/en/topics/pls-integration.md, content/en/topics/shared-ip.md
improve doc for PLS integration:
- Update customize health probe tips
- Update limitations
Fixes #
```release-note
NONE
```
```docs
```
=> doc: improve doc for PLS integration

content/en/blog/releases/v1.29.12.md
Update release notes for v1.29.12
Fixes #
```release-note
NONE
```
```docs
```
=> Update release notes for v1.29.12

content/en/blog/releases/v1.28.14.md
Update release notes for v1.28.14
Fixes #
```release-note
NONE
```
```docs
```
=> Update release notes for v1.28.14

LICENSES/vendor/github.com/samber/lo/LICENSE
Update vendor license for master
Fixes #
```release-note
NONE
```
```docs
```
=> Update vendor license for master

LICENSES/vendor/github.com/samber/lo/LICENSE
Update vendor license for release-1.32
Fixes #
```release-note
NONE
```
```docs
```
=> Update vendor license for release-1.32

pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind bug
cherry-pick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8255
Fixes #
```release-note
fix(credential-provider): check acr pattern to avoid spoofing
```
```docs
```
=> [release-1.29] fix(credential-provider): check acr pattern to avoid spoofing

pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind bug
cherr-pick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8255
Fixes #
```release-note
fix(credential-provider): check acr pattern to avoid spoofing
```
```docs
```
=> [release-1.28] fix(credential-provider): check acr pattern to avoid spoofing

.github/workflows/lint.yaml
Reverts kubernetes-sigs/cloud-provider-azure#8274
=> Fix golangci-lint errors: switch Go version to 1.23

cloudbuild.yaml
cherry-pick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8322
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30] bump golang in gcb-docker-gcloud to 1.23.4

content/en/blog/releases/v1.30.8.md, content/en/blog/releases/v1.31.2.md
generate the release doc by running the following commands
```bash
./hack/generate-release-note.sh v1.28.14 release-notes.md true
./hack/generate-release-note.sh v1.31.2 release-notes.md true
```
Fixes #
```release-note
NONE
```
```docs
```
=> docs: update release notes for v1.30.8 and v1.31.2

.github/workflows/lint.yaml
/kind testing
update lint config in release-1.28 branch
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28]bump golang-ci-lint

.github/workflows/lint.yaml, .golangci.yml, pkg/provider/azure_loadbalancer.go
/kind testing
Chores: fix linter config
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: fix linter config

.github/workflows/lint.yaml, .golangci.yml, pkg/provider/azure_loadbalancer.go
/kind testing
[release-1.29]fix linter config
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29]fix linter config

.github/workflows/lint.yaml, .golangci.yml, pkg/provider/azure_loadbalancer.go
/kind testing
[release-1.28]fix linter config
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28]fix linter config

LICENSES/vendor/github.com/Azure/msi-dataplane/LICENSE
/kind cleanup
Update vendor license for release-1.31
Fixes #
```release-note
NONE
```
```docs
```
=> Update vendor license for release-1.31

pkg/provider/azure.go
/kind bug
Fixes #
cherry-pick #8375
```release-note
NONE
```
```docs
```
=> [release-1.32] Set auxiliary token policy when auxiliary token provider enabled

Makefile, pkg/provider/azure.go, pkg/retry/azure_retry.go
/kind bug
Fixes #
cherry-pick #8375
```release-note
NONE
```
```docs
```
=> [release-1.31] Set auxiliary token policy when auxiliary token provider enabled

pkg/provider/azure.go
/kind feature
Fixes #
```release-note
NONE
```
```docs
```
=> Set auxiliary token policy when auxiliary token provider enabled

pkg/retry/azure_retry.go
/kind testing
[release-1.29]fix linter issue
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.29]fix linter issue

.github/workflows/release.yaml
/kind testing
Chores: commit release note to doc/release-note-vxxxx branch
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: commit release note to doc/release-note-vxxxx branch

.github/workflows/release.yaml
/kind testing
Chores:remove step in release action
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:remove step in release action

content/en/blog/releases/v1.32.2.md
Update release notes for v1.32.2
Fixes #
```release-note
NONE
```
```docs
```
=> Update release notes for v1.32.2

Makefile, hack/ensure-azcli.sh
pin az cli to fix acr cache create issue
Fixes #
```release-note
NONE
```
```docs
```
=> test: pin az cli to fix acr cache create issue

pkg/provider/azure.go
/kind bug
cherry-pick of #8504: fix incorrect cloud provider setting in sovereign cloud
Fixes #
```release-note
fix incorrect cloud provider setting in sovereign cloud
```
```docs
```
=> [release-1.32] fix: incorrect cloud provider setting in sovereign cloud

pkg/azclient/.golangci.yml, pkg/azclient/Makefile, pkg/azclient/accountclient/interface.go, pkg/azclient/accountclient/zz_generated_client.go, pkg/azclient/blobcontainerclient/interface.go, pkg/azclient/blobcontainerclient/zz_generated_client.go, pkg/azclient/blobservicepropertiesclient/interface.go, pkg/azclient/blobservicepropertiesclient/zz_generated_client.go, pkg/azclient/client-gen/generator/clientfactory.go, pkg/azclient/client-gen/generator/gentest_action.go, pkg/azclient/client-gen/generator/template.go, pkg/azclient/cloud.go, pkg/azclient/cloud_test.go, pkg/azclient/factory_gen.go, pkg/azclient/fileservicepropertiesclient/interface.go, pkg/azclient/fileservicepropertiesclient/zz_generated_client.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/zz_generated_client.go, pkg/azclient/ipgroupclient/interface.go, pkg/azclient/ipgroupclient/zz_generated_client.go, pkg/azclient/registryclient/interface.go, pkg/azclient/registryclient/zz_generated_client.go, pkg/azclient/utils/cloud.go, pkg/azclient/utils/cloud_test.go, pkg/azclient/utils/utils_suite_test.go
/kind feature
track2 sdk:add support for non-public cloud
Fixes #
```release-note
for non-public cloud, apiVersion will be pinned to a specific version
```
```docs
```
=> track2 sdk:add support for non-public cloud

pkg/azclient/cloud.go, pkg/azclient/cloud_test.go
/kind feature
Track2 sdk: add default cloud config
Fixes #
https://github.com/Azure/go-autorest/blob/main/autorest/azure/environments.go#L293-L311
```release-note
NONE
```
```docs
```
=> Track2 sdk: add default cloud config

pkg/provider/storage/azure_storageaccount.go
/kind bug
fix: account match algorithm when source account name is provided, this is used in volume clone and snapshot restore scenarios
<details>
```
I0306 12:52:31.840777       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0306 12:52:31.840801       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","parameters":{"csi.storage.k8s.io/pv/name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","csi.storage.k8s.io/pvc/name":"afspvc","csi.storage.k8s.io/pvc/namespace":"choudharypr-test-target","skuName":"Standard_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["mfsymlinks","actimeo=30","nosharesock"]}},"access_mode":{"mode":5}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"MC …
```
=> fix: account match algorithm when source account name is provided

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: Update image versions in readme and examples
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Update image versions in readme and examples

content/en/blog/releases/v1.29.13.md, content/en/blog/releases/v1.30.10.md, content/en/blog/releases/v1.31.4.md, content/en/blog/releases/v1.32.3.md
doc: Add release notes for v1.29.13, v1.30.10, v1.31.4 and v1.32.3
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Add release notes for v1.29.13, v1.30.10, v1.31.4 and v1.32.3

content/en/topics/tagging-resources.md
doc: Enrich doc for reserved tag keys
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Enrich doc for reserved tag keys

tests/e2e/network/ensureloadbalancer.go
Fixes #
```release-note
```
```docs
```
=> chore: Fix linting issues

cmd/cloud-controller-manager/app/controllermanager.go, pkg/trace/provider.go
/kind feature
To export all metrics in 1 endpoint.
Fixes #
```release-note
NONE
```
```docs
```
=> Merge OTEL metrics with legacy registerer

internal/testutil/fixture/fixture.go
/kind testing
cherry pick #8587 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.32] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)

cmd/cloud-controller-manager/app/controllermanager.go, pkg/trace/provider.go
/kind feature
cherry pick #8594 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30] Merge OTEL metrics with legacy registerer (#8594)

pkg/azclient/accountclient/custom.go, pkg/azclient/blobcontainerclient/custom.go, pkg/azclient/blobservicepropertiesclient/custom.go, pkg/azclient/fileservicepropertiesclient/custom.go, pkg/azclient/fileshareclient/custom.go
/cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> cleanup: add csi related track2 metrics

cmd/cloud-controller-manager/app/controllermanager.go, pkg/trace/provider.go
/kind feature
cherry pick #8594 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.31] Merge OTEL metrics with legacy registerer (#8594)

cmd/cloud-controller-manager/app/controllermanager.go, pkg/trace/provider.go
/kind feature
cherry pick #8594 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.32] Merge OTEL metrics with legacy registerer (#8594)

internal/testutil/fixture/fixture.go
/kind testing
cherry pick #8587 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.30] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)

pkg/provider/storage/azure_storageaccount.go
/kind cleanup
cleanup: add authProvider in AccountRepo struct
Fixes #
```release-note
none
```
```docs
```
=> cleanup: add authProvider in AccountRepo struct

.github/workflows/lint.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> Fix linter version

.github/workflows/lint-azclient.yaml
/kind testing
Track2 sdk: pin golangci-lint-action to v6
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: pin golangci-lint-action to v6

helm/OWNERS
/kind cleanup
This PR enables a specific list of OWNERS to maintain the cloud-provider-azure helm chart.
Fixes #
```release-note
NONE
```
```docs
```
=> add helm chart OWNERS

.github/workflows/labeler.yml
/kind feature
All tide/merge-method-squash label to all pull requests to ensure commits being squashed before merging.
Fixes #
```release-note
NONE
```
```docs
```
=> feat: All tide/merge-method-squash label to all pull requests

pkg/azclient/go.mod, pkg/azclient/go.sum, pkg/azclient/virtualmachinescalesetvmclient/custom.go, pkg/azclient/virtualmachinescalesetvmclient/interface.go, pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
/kind feature
chore: add VMSS AttachDetachDataDisks interface
Fixes #
```
cd pkg/azclient
make generate test
echo "fail if files changed"
git add . && git diff --quiet && git diff --cached --quiet
mockgen -package mock_virtualmachinescalesetvmclient -source virtualmachinescalesetvmclient/interface.go -typed -write_generate_directive -copyright_file ../../hack/boilerplate/boilerplate.generatego.txt > virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
```
```release-note
chore: add VMSS AttachDetachDataDisks interface
```
```docs
chore: add VMSS AttachDetachDataDisks interface
```
=> chore: add VMSS AttachDetachDataDisks interface

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go
/kind bug
fix: remove unnecessary get vmss call during disk attach
Fixes #
```release-note
fix: remove unnecessary get vmss call during disk attach
```
```docs
fix: remove unnecessary get vmss call during disk attach
```
=> fix: remove unnecessary get vmss call during disk attach

pkg/provider/azure_local_services.go
Add metrics service_local_update_backend_pool_xxx
/kind cleanup
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx
Fixes #
```release-note
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx.
```
```docs
```
=> chore: Add metrics for local service backend pool updater

Makefile
/kind testing
Chores: skip buildx setup if it is done in previous step
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: skip buildx setup if it is done in previous step

pkg/azclient/utils/poller.go
/kind cleanup
change poller frequency to 5s
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: change poller frequency to 5s

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go
/kind cleanup
chore: DeleteCacheForNode should be only called when updateCache is not called, this could also reduce get vmss call num
Fixes #
```release-note
none
```
```docs
none
```
=> chore: DeleteCacheForNode should be only called when updateCache is not called

pkg/provider/azure_local_services.go
Add metrics service_local_update_backend_pool_xxx
/kind cleanup
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx
Fixes #
```release-note
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx.
```
```docs
```
=> [release-1.31] chore: Add metrics for local service backend pool updater

pkg/provider/azure_local_services.go
Add metrics service_local_update_backend_pool_xxx
/kind cleanup
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx
Fixes #
```release-note
chore: Add metrics for local service backend pool updater
Add metrics service_local_update_backend_pool_xxx.
```
```docs
```
=> [release-1.30] chore: Add metrics for local service backend pool updater

.github/workflows/release.yaml
/kind testing
Chores: fetch all tags and commits in release action
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: fetch all tags and commits in release action

content/en/blog/releases/v1.29.14.md, content/en/blog/releases/v1.30.11.md, content/en/blog/releases/v1.31.5.md, content/en/blog/releases/v1.32.4.md
doc: Add release notes for v1.32.4, v1.31.5, v1.30.11 and v1.29.14
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Add release notes for v1.32.4, v1.31.5, v1.30.11 and v1.29.14

.github/workflows/release.yaml
/kind testing
Chore: install arm toolchain before build release artifacts
Fixes #
```release-note
NONE
```
```docs
```
=> Chore: install arm toolchain before build release artifacts

.github/workflows/release.yaml
/kind testing
Chore: install arm toolchains before build release artifacts
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.33]Chore: install arm toolchains before build release artifacts

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: Update readme and examples to use the latest images
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Update readme and examples to use the latest images

.github/dependabot.yml
/kind cleanup
chore: Dependabot do not bump go version
Fixes #
```release-note
NONE
```
```docs
```
=> chore: Dependabot do not bump go version

health-probe-proxy/go.mod
/kind cleanup
fix: CVE-2025-22871
Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/security/code-scanning/230
```release-note
NONE
```
```docs
```
=> fix: CVE-2025-22871

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml
doc: Bump the image versions in readme and examples
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Bump the image versions in readme and examples

.github/workflows/release.yaml
/kind cleanup
gh-release github action is broken on new version, so roll it back here
Fixes #
```release-note
NONE
```
```docs
```
=> chore: fix release pipeline

netlify.toml
fix: Bump hugo version to 0.147.8
Fixes #
```release-note
NONE
```
```docs
```
=> fix: Bump hugo version to 0.147.8

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go
/kind cleanup
cherry-pick #9208 
Fixes #
```release-note
Skip adding Internet service tag if IP ranges allow all
```
```docs
```
=> [release-1.30] Skip adding Internet service tag if IP ranges allow all

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go
/kind cleanup
cherry-pick #9208 
Fixes #
```release-note
Skip adding Internet service tag if IP ranges allow all
```
```docs
```
=> [release-1.33] Skip adding Internet service tag if IP ranges allow all

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go
/kind cleanup
cherry-pick #9208 
Fixes #
```release-note
Skip adding Internet service tag if IP ranges allow all
```
```docs
```
=> [release-1.32] Skip adding Internet service tag if IP ranges allow all

pkg/provider/azure_controller_vmss.go
/kind bug
Fixes #
```release-note
chore: fix typo in vmss controller
```
```docs
chore: fix typo in vmss controller
```
=> chore: fix typo in vmss controller

content/en/blog/releases/v1.30.14.md, content/en/blog/releases/v1.31.8.md, content/en/blog/releases/v1.32.7.md, content/en/blog/releases/v1.33.2.md
doc: Update release docs
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Update release docs

.github/workflows/cleanupcache.yaml, .github/workflows/lint-azclient.yaml, .github/workflows/lint.yaml, .github/workflows/release-azclient-trace.yml, .github/workflows/release-azclient.yml, .github/workflows/release-cache.yml, .github/workflows/release-configloader.yml, .github/workflows/release.yaml
/kind cleanup
Add explanatory comments for elevated permissions in workflows to clarify why specific write permissions are needed:
- contents: write for creating releases and pushing git tags
- checks: write for golangci-lint to create check runs
- actions: write for cache cleanup operations
These permissions follow the principle of least privilege with job-level restrictions rather than workflow-level write-all permissions.
Hope those changes would help scanning tools to shrink the security alerts.
Fixes #
```release-note
NONE
```
```docs
```
=> docs: document required permissions in GitHub Actions workflows

Dockerfile, cloud-node-manager.Dockerfile, health-probe-proxy/Dockerfile
/kind cleanup
chore: bump distroless base image for CVEs
Fixes #
```release-note
NONE
```
```docs
```
=> chore: bump distroless base image for CVEs

cmd/cloud-controller-manager/app/config/config.go, cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-controller-manager/app/options/options_test.go, examples/node-filtering-example.md
/kind feature
To allow Cloud Controller Manager (CCM) to selectively manage nodes using Kubernetes label selector expressions.
Fixes #
```feat: 
Support node filtering feature:
Added --node-filter-requirements flag to selectively manage nodes using Kubernetes label selectors.
Usage examples:
--node-filter-requirements="environment=production"
--node-filter-requirements="environment in (production,staging),!maintenance"
```
- [Usage]: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/examples/node-filtering-example.md
```release-note
New Feature: Node Filtering for Cloud Controller Manager
Added --node-filter-requirements flag to selectively manage nodes using Kubernetes label selectors.
Usage examples:
--node-filter-requirements="environment=production" …
```
=> Support node filtering feature

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/securitygroup/securitygroup.go, pkg/provider/securitygroup/securitygroup_test.go, pkg/provider/securitygroup/securityrule.go, pkg/provider/securitygroup/securityrule_test.go
/kind bug
Fixes #9328
Fixes #9355
```release-note
Clean backend pool node destination while reconciling security group
```
```docs
```
=> Clean backend pool node destination while reconciling security group

go.mod, go.sum, vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/local/server.go, vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go, vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/resolvers.go, vendor/modules.txt
/kind bug
fix: China cloud endpoints
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/9418
Fixes #
```release-note
fix: China cloud endpoints
```
```docs
fix: China cloud endpoints
```
=> [release-1.32] fix: China cloud endpoints

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/securitygroup/securitygroup.go, pkg/provider/securitygroup/securitygroup_test.go, pkg/provider/securitygroup/securityrule.go, pkg/provider/securitygroup/securityrule_test.go
/kind bug
cherry-pick #9417 
Fixes #
```release-note
Clean backend pool node destination while reconciling security group
```
```docs
```
=> [release-1.32] Clean backend pool node destination while reconciling security group

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/securitygroup/securitygroup.go, pkg/provider/securitygroup/securitygroup_test.go, pkg/provider/securitygroup/securityrule.go, pkg/provider/securitygroup/securityrule_test.go
/kind bug
cherry-pick #9417 
Fixes #
```release-note
Clean backend pool node destination while reconciling security group
```
```docs
```
=> [release-1.31] Clean backend pool node destination while reconciling security group
