kubernetes-sigs/cloud-provider-azure

Dockerfile
cloud-controller-manager/main.go
glide.yaml
scripts/pkg-config.sh
scripts/update-dependencies.sh

Change 'github.com/kubernetes' to 'k8s.io'.
/assign @feiskyer

Update package import path

---

README.md
docs/cloud-provider-config.md

Add cloud provider config doc

---

docs/e2e-tests.md

Line 74: kuberentes->kubernetes

Typo fix: kuberentes->kubernetes

---

tests/k8s-azure/k8s-azure

Typo fix: skiped->skipped

---

docs/cloud-controller-manager.md

Update doc for cloud-controller-manager

---

README.md
docs/development-loadbalancer.md

Import azure_loadbalancer.md and update annotation section.
Move loadbalancer doc from https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.0/pkg/cloudprovider/providers/azure/azure_loadbalancer.md
Fixes #11

Import loadbalancer document

---

Makefile
docs/e2e-tests.md
tests/k8s-azure/k8s-azure

1. Add test-check target, which will cover lint and some more test in future.
Will update 'pull-cloud-provider-azure-lint ' job to 'pull-cloud-provider-azure-check' then.
2. Update doc for e2e test.

Test refinement

---

docs/cloud-controller-manager.md

Typo fix: refere->refer

---

docs/azuredisk-issues.md
docs/azurefile-issues.md

add azuredisk-issues.md & azurefile-issues.md

---

SECURITY_CONTACTS

Closes: #19 
/sig azure
Signed-off-by: Stephen Augustus <foo@agst.us>

Add `SECURITY_CONTACTS`

---

docs/development-loadbalancer.md

Docs are for kubernetes/kubernetes@55569494d64dd93777ca42437055884d6a99c46d

Add docs for LB idle timeouts

---

code-of-conduct.md

Adding missing code-of-conduct.md as suggested in kubernetes-template-project.

adding code-of-conduct.md file

---

OWNERS
SECURITY_CONTACTS

* Remove Jaice
* Remove Cole
* Add Stephen as reviewer
Signed-off-by: Stephen Augustus <foo@agst.us>
/sig azure
/assign @khenidak @feiskyer

Update OWNERS / SECURITY_CONTACTS

---

tests/e2e/autoscaling/autoscaler.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_auth.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/ip_utils.go
tests/e2e/utils/ip_utils_test.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/pod_utils.go
tests/e2e/utils/service_utils.go
tests/e2e/utils/utils.go

Add tests for load balancer annotations
Add azure resource framework
Rename some of the functions

add azure internal and subnet service annotation test

---

docs/release-versioning.md

versionging->versioning
increse->increase

Fix small typos in release-versioning.md

---

docs/dependency-management.md

Fix some typo :
Line 7: preovide->provided
Line 47: thers->there

Fix some typos in doc dependency-management.md

---

docs/azuredisk-issues.md

/assign @feiskyer @karataliu 
cc @weherdh I put the azure disk & azure file issues here

update disk issues

---

README.md
docs/azuredisk-issues.md
docs/azurefile-issues.md

Update TOC for docs and fix various format issues.

Update TOC for docs

---

README.md
docs/using-cross-resource-group-nodes.md

Add docs for cross-RG nodes: https://github.com/kubernetes/features/issues/604
/assign @justaugustus

Add documentation for cross resource group nodes

---

docs/dependency-management.md

Signed-off-by: Rui Cao <ruicao@alauda.io>

Fix typo: dependecies -> dependencies

---

docs/issues-and-pull-requests-migration.md
tests/e2e/network/service_annotations.go

Fix typos: levae->levae, pulic->public

Fix typos: levae->levae, pulic->public

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support.md
.github/PULL_REQUEST_TEMPLATE.md

/assign @justaugustus 
```
none
```

add Issue and PR templates

---

README.md
docs/cloud-provider-config.md
tests/e2e/autoscaling/autoscaler.go

>
> /kind bug
> /kind design
> /kind flake
Add missing options into our documentation. Also added more docs about excludeMasterFromStandardLB from #83.
Fixes #83
```
NONE
```

Add missing options into documents

---

Makefile
tests/e2e/e2e_test.go

>
> /kind bug
> /kind design
> /kind flake
Part of #4 to run ccm specific e2e tests
Fixes # 
```
make TestAzureTest report dir configurable
```

make TestAzureTest report dir configurable

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Add timeout to ccm e2e test suite
Fixes #
```
Add timeout to ccm e2e test suite
```
cc @feiskyer

add timeout to ccm e2e

---

run-e2e-tests.sh

>
> /kind bug
> /kind design
> /kind flake
Adding this script so we can call `control.FinishRunning(exec.Command("./hack/run-e2e-tests.sh", testArgs...))` from test-infra to use `--test_args=` to pass in `--ginkgo.skip=` and `--ginkgo.focus`.
Fixes #
```
add run-e2e-tests script
```

add run-e2e-tests script

---

hack/run-e2e-tests.sh

>
> /kind bug
> /kind design
> /kind flake
- move run e2e script to hack and append arg
Fixes #
```
move run e2e script to hack
```

move run e2e script to hack

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```

 Add CCM_E2E_ARGS for customizing ccm test cases

---

tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux.json

>
> /kind bug
> /kind design
> /kind flake
- Update the test manifests (apimodels) used by aks-engine to create the test cluster
- Update the manifest to set custom image to ccm only as we are not building our own hyperkube image
Fixes #
```
Update test manifest to only set image for ccm
```

Update test manifest to only build for ccm

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Allows the user to override the IMAGE_TAG value in the Makefile. This is useful when building ccm in a CI environment.
Fixes #
```
Allow user to override the IMAGE_TAG var in the Makefile
```

fix: Allow IMAGE_TAG to be overridden

---

Makefile
glide.lock
glide.yaml
tests/k8s-azure/Dockerfile
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux.json
vendor/github.com/spf13/cobra/cobra.go
vendor/github.com/spf13/cobra/command.go
vendor/github.com/spf13/cobra/command_win.go

>
> /kind bug
> /kind design
> /kind flake
Update kubernetes version to 1.14.0. This is the last thing to do before alpha release.
Fixes #
```
NONE
```

Update kubernetes version to 1.14.0

---

docs/azure-loadbalancer.md

This improves the grammar in the documentation for Azure LoadBalancer
Fixes # None

Improve loadbalancer docs

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/service_utils.go

Add tests when updating service load balancer including:
1. assigning to specific IP when updating public service
2. updating internal IP when updating internal service
3. updating an internal service to a public service with assigned IP
4. no operation since no change in service when update
```
none
```

add ensure load balancer e2e test

---

.gitignore
Makefile
examples/aks-engine.json
hack/deploy-cluster.sh

>
> /kind bug
kind design
> /kind flake
This PR adds a new target to the makefile named deploy.
Fixes #4 
```
action-required: review
```

Updated Makefile with deploy target

---

hack/deploy-cluster.sh

>
> /kind bug
kind design
> /kind flake
Add plugin for Azure File and Disk CSI
Fixes #7 
Locally tested. Successful
```
```

Add deploy plugin for AzureFile and Azure Disk CSI

---

docs/e2e-tests.md

>
> /kind bug
> /kind design
kind documentation
> /kind flake
This PR updates the documentation
Part of #4 
More steps to be added for running tests suites
```
NONE
```

Updating e2e documentation-ongoing updation

---

hack/deploy-cluster.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fix KUBECONFIG setup in hack/deploy-cluster.sh.
Fixes #
```
NONE
```

Fix KUBECONFIG setup in hack/deploy-cluster.sh

---

docs/cloud-provider-config.md

Azure Stack requires using unique endpoints that are different from Azure Public Cloud.
Add documentation describing the available options and how to enable it.
Explains how to enable the Azure provider on Azure clouds other than the Public cloud, such as China, Germany, Azure Stack, etc...
Fixes #151
**Release Notes**:
```release-note
documentation for other Azure clouds (China, Germany, US Gov), incl. Azure Stack
```

Describe configuration required for Azure Stack

---

hack/deploy-cluster.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR cleans up the script for deploying aks-engine clusters.
N/A
**Release note:**
```
None
```

Cleanup deploy script

---

docs/e2e-tests-azure.md
tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/azure_auth.go

>
> /kind bug
> /kind design
> /kind flake
Add support of testing standard LB and fix e2e docs.
Fixes #
```
Add support of testing standard LB and fix e2e docs
```

Add support of testing standard LB and fix e2e docs

---

examples/az.json
hack/deploy-cluster.sh

>
> /kind bug
> /kind design
kind feature
> /kind flake
To add the option of availability zone to user while deploying cluster
Fixes #7 
Previous PR was made without being at par with the current master branch of kubernetes/cloud-provider-azure
```
none
```

Add availabiity zone feature to deploy-cluster.sh

---

docs/cloud-provider-config.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```

Config the minimal permissions for azure-cloud-provider-secret-getter

---

Makefile
examples/aks-engine.json
examples/az.json
go.mod
go.sum
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

>
> /kind bug
> /kind design
> /kind flake
/kind api-change
Update Kubernetes version to v1.15.0.
Fixes #
```
Update Kubernetes version to v1.15.0.
```
/assign @ritazh @andyzhangx

Update Kubernetes version to v1.15.0

---

docs/cloud-provider-config.md

Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
>
> /kind bug
> /kind design
> /kind flake
This PR just fixes typo in documentation.
```
```

docs/cloud-provider-config.md: fix typo

---

docs/cloud-controller-manager.md

>
> /kind bug
> /kind design
> /kind flake
Fix link of Azure cloud provider since it has been moved to staging.
Fixes #169 
```
NONE
```

Fix link of Azure cloud provider since it has been moved to staging

---

tests/e2e/utils/network_utils.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```

improve the performence of loadbalancer e2e test

---

docs/e2e-tests.md

Fixes #188. Add ssh configurations to docs/e2e-tests.md.
/kind bug
```
NONE
```

Fixes https://github.com/kubernetes/cloud-provider-azure/issues/188

---

tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind testing
Fixes #186 
```
None
```

Add e2e test for annotation idletimeout.

---

tests/k8s-azure/manifest/linux-vmss-multi-zones.json

Add config file for enabling multi-zone e2e test.

---

tests/e2e/network/service_annotations.go
tests/e2e/utils/network_utils.go

/kind testing
Fixes #187 
```
NONE
```

Add e2e test case for annotation "service.beta.kubernetes.io/azure-load-balancer-mixed-protocols".

---

docs/using-availability-zones.md

>
> /kind bug
> /kind design
**What this PR does / why we need it**: 
Fix link for Azure availability zones KEP.
Fixes #208
```
NONE
```

Fix link for Azure availability zones KEP

---

examples/aks-engine.json
examples/az.json
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss-serial.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

/kind bug
Since the default linux distribution of aks-engine might cause some troubles, we change it to the specific version.
Fixes #
```
None
```

Add distro setting to corresponding aks config files.

---

docs/azure-loadbalancer.md
docs/cloud-provider-config.md

Update documentations for enableTcpReset and identitySystem.
Refer https://github.com/kubernetes/kubernetes/pull/80624
Refer https://github.com/kubernetes/kubernetes/pull/80841
```
NONE
```

Update documentations for enableTcpReset and identitySystem

---

tests/e2e/network/standard_lb.go
tests/e2e/utils/pod_utils.go

/kind testing
Add test cases for slb.
Fixes #181 
```
None
```

Add test cases for slb.

---

examples/aks-engine.json
examples/az.json
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss-serial.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

Delete distro settings for it's the cause of a series of test failures.
```
None.
```

Delete distro settings.

---

docs/using-cross-resource-group-nodes.md

>
**What this PR does / why we need it**: Fix KEP link for cross resource group nodes
Fixes #
```
NONE
```

Fix KEP link for cross resource group nodes

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/resource_group_utils.go

/kind bug
Fix the bug: cannot delete test pip and resource group after test.
```
None.
```

Fix the bug: cannot delete test pip and resource group after test.

---

Dockerfile

/kind cleanup
Upgrade golang to 1.12.9 (contains many `CVE` fixes).
Fixes #
```
NONE
```

Upgrade golang to 1.12.9

---

tests/k8s-azure/manifest/e2e-slow.json

>
> /kind bug
> /kind design
> /kind flake
Enable ServiceLoadBalancerFinalizer for slow e2e test cases.
```
NONE.
```

Enable ServiceLoadBalancerFinalizer for slow e2e test cases.

---

tests/k8s-azure/manifest/e2e-slow.json

>
> /kind bug
> /kind design
> /kind flake
Enable ccm feature flag ServiceLoadBalancerFinalizer because some E2E test cases need it.
Fixes #
```
None.
```

Enable ccm feature flag ServiceLoadBalancerFinalizer.

---

tests/k8s-azure/manifest/e2e-slow.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss.json

>
> /kind bug
> /kind design
> /kind flake
Enlarge the vm sku for slow and slow-vmss tests.
Fixes #
```
None.
```

Enlarge the vm sku for slow and slow-vmss tests.

---

docs/dependency-management.md

>
> /kind bug
> /kind design
Update docs for Kubernetes go modules upgrade.
Fixes #
```
NONE
```

Update docs for Kubernetes go modules upgrade

---

docs/e2e-tests.md
hack/deploy-cluster.sh

>
> /kind bug
> /kind design
> /kind flake
Update hack/deploy-cluster.sh and corresponding doc.
Fixes #
```
None.
```

Update hack/deploy-cluster.sh and corresponding doc.

---

Dockerfile
Dockerfile.node

Rebase base image of cloud controller manager and cloud node manager to distroless.
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fixes #235 
```
None.
```

Rebase base image of cloud controller manager and cloud node manager to distroless.

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
Update examples of v0.3.0.
```
NONE
```

Update examples of v0.3.0

---

tests/e2e/utils/network_utils.go

>
> /kind bug
> /kind design
Use the subnetPrefix when determining the available private IP. The test shouldn't assume subnet's CIDR.
Fixes #
```
NONE
```

Use the subnetPrefix when determining the available private IP

---

docs/cloud-controller-manager.md

Fixes #244 
```
removed stale links from documentation
```

removed links that led to 404s and updated documentation

---

docs/dependency-management.md

fix:"pacakge" should be package

fix:"pacakge" should be package

---

docs/e2e-tests-azure.md

fix :junit should be JUnit

---

docs/cloud-provider-config.md

fix:Azure loadbalancer should be capital , such as Azure LoadBalancer

fix: loadbalancer should be capital

---

tests/e2e/network/node.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/utils.go
tests/e2e/utils/vmss_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind testing
Add test case to test zone label on VMSS nodes.
Fixes #
```
None.
```

Add test case to test zone label on nodes.

---

hack/log-dump/log-dump.sh

>
> /kind bug
> /kind design
> /kind flake
Currently, log-dump.sh also try to run `post-dump-log` on log files generated from the test cases ([example](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-cloud-provider-azure-slow-vmss/1188467762876387333/artifacts/_sig-storage_CSI_Volumes_Driver_csi-hostpath-v0_Testpattern_Dynamic_PV_block_volmode_volumeMode_should_fail_in_binding_dynamic_provisioned_PV_to_PVC_Slow_/)). This PR ensures that we only run `post-dump-log` on valid JSON-encoded log files. …

Check if the log file can be parsed by jq

---

tests/e2e/network/node.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_interface_utils.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/route_table_utils.go
tests/e2e/utils/utils.go
tests/e2e/utils/vm_utils.go
tests/e2e/utils/vmss_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind testing
Add test cases for node resources.
Fixes #179
```
None.
```

Add test cases for node resources.

---

cmd/cloud-controller-manager/app/apis/config/v1alpha1/zz_generated.conversion.go
cmd/cloud-controller-manager/app/config/config.go
cmd/cloud-controller-manager/app/controllermanager.go
cmd/cloud-controller-manager/app/core.go
cmd/cloud-controller-manager/app/options/options.go
cmd/cloud-controller-manager/controller-manager.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
tests/e2e/network/service_annotations.go
tests/k8s-azure/manifest/linux-vmss-multi-zones.json

>
> /kind bug
> /kind design
> /kind flake
- Fix gofmt error introduced by #256
- Unable to deploy a multi-zone cluster with linux-vmss-multi-zones.json because default `outboundRuleIdleTimeoutInMinutes` is not set correctly, causing an ARM error `LBOutboundRule has invalid Idle Timeout. The value must be between 4 and 120`. 
Opened a PR on aks-engine to fix the problem: https://github.com/Azure/aks-engine/pull/2269
Fixes #
/assign …

Fix gofmt error & add outboundRuleIdleTimeoutInMinutes field in multi-zone API model

---

hack/log-dump/log-dump.sh
tests/k8s-azure/manifest/linux-autoscaler.json

>
> /kind bug
> /kind design
> /kind flake
This PR added autoscaler addon types that Azure/aks-engine#2138 introduced.
Fixes #260
/assign @feiskyer
```
None.
```

Modify API model for autoscaler e2e test

---

Makefile
docs/azure-permissions.md
docs/e2e-tests.md
docs/release-versioning.md
docs/services/README.md
hack/verify-spelling.sh
tests/e2e/network/network_security_group.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
/area provider/azure
Enable spell checking and fix spelling issues.
Fixes #
```
NONE
```

Enable spell checking and fix spelling issues

---

README.md

Updates the version support matrix in README.md for the recent [v0.4.0 release](https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v0.4.0).
```
Update README for v0.4.0 alpha release
```

Update README for v0.4.0 alpha release

---

Makefile
go.mod
go.sum
hack/update-gofmt.sh
hack/verify-gofmt.sh
hack/verify-golint.sh
hack/verify-govet.sh
tests/e2e/autoscaling/autoscaler.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/container_registry_utils.go
tests/e2e/utils/network_interface_utils.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/resource_group_utils.go
tests/e2e/utils/service_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind testing
Add more verifications and fix verify failures: 
* Since gometalinter has been deprecated, it switches to golangci-lint.
* Added gofmt and govet verifications
* Fixed existing govet and gofmt failures
Fixes #
There is still a lint error:
```
pkg/nodemanager/nodemanager.go:337:6: func `ensureNodeExistsByProviderID` is unused (unused)
func ensureNodeExistsByProviderID(instances …
```

Add more verifications and fix verify failures

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Check if TAG exists before IMAGE_TAG is assigned.
Fixes #
```
None.
```

Check if TAG exists before IMAGE_TAG is assigned.

---

Makefile
hack/pkg-config.sh

…in ./hack/pkg-config.sh.
>
> /kind bug
> /kind design
> /kind flake
Add a config to check if git commands can run in `./hack/pkg-config.sh`.
Fixes #
```
None.
```

Add a config for `./hack/pkg-config.sh`.

---

README.md

Update README.md with correct image registry.
The current README.md points to `mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.4.0` which fails to be pulled
```
$ docker pull mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.4.0
Error response from daemon: manifest for mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.4.0 not found: manifest unknown: manifest unknown
```
From the releases section the right registry seems to be `mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager`.
```
$ docker pull mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v0.4.1
v0.4.1: Pulling from oss/kubernetes/azure-cloud-controller-manager
39fafc05754f: Already …
```

Update README.md with correct image registry

---

tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
tests/k8s-azure/manifest/e2e-slow.json
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss-serial.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add virtual kubelet manifest and update k8s version to 1.17.
Fixes #
```
None.
```

Add virtual kubelet manifest and update k8s version to 1.17.

---

tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json

>
> /kind bug
> /kind design
> /kind flake
The corresponding config in virtual node aks-engine manifest in incorrect. This PR fixes it.
Fixes #
```
None.
```
/kind bug

Fix the config of vnode manifest.

---

examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
examples/out-of-tree/kube-apiserver.yaml
examples/out-of-tree/kube-controller-manager.yaml
examples/out-of-tree/kube-scheduler.yaml

Update out-of-tree examples
Fixes #
```
NONE
```

Update out-of-tree examples

---

docs/e2e-tests.md

>
> /kind bug
> /kind design
> /kind flake
Change the way to run k8s e2e test because `hack/e2e.go` has been deprecated.
Fixes #
```
None.
```

Change go run hack/e2e.go to kubetest.

---

Makefile
tests/e2e/autoscaling/autoscaler.go
tests/e2e/utils/node_utils.go
tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
tests/k8s-azure/manifest/linux-autoscaler.json

>
> /kind bug
> /kind design
> /kind flake
This PR Increases test coverage for CA, aimed to be used by upstream test-infra and canary test pipeline.
Fixes #
/assign @feiskyer @aramase 
/cc @andyzhangx @nilo19 
```
None
```

Add a new test case on CA, StatefulSet and Azure Disks

---

docs/cloud-provider-config.md
docs/services/README.md

Helps readability of some documentation for Azure cloud provider by fixing grammar.
Made some readability improvements when reviewing a couple docs. Happy to help make incremental improvements over time.

grammatical fixes on cloud-provider-config.md and README.md

---

tests/e2e/autoscaling/autoscaler.go

>
> /kind bug
> /kind design
> /kind flake
Looks like https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-autoscaling does not have enough pods in the deployment to trigger a scale-up operation in the second test case. This PR rounds up the number of pods needed in the autoscaler test case to ensure that there is not enough resource at least one pod.
Fixes #
/assign @feiskyer 
```
None
```

Ensure that there are enough pods in a deployment to trigger a scale-up operation

---

docs/cloud-controller-manager.md

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Fix the version and CSI docs
Fixes #
```
NONE
```

Fix the version and CSI docs

---

docs/services/README.md

Refer https://github.com/kubernetes-sigs/cloud-provider-azure/issues/295. The annoation `service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"` doesn't work, hence remove it from our documentations.
Fixes #
```
NONE
```

Remove unsupported annotation from docs

---

go.sum
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
tests/e2e/network/service_annotations.go

>
> /kind bug
> /kind design
> /kind flake
- One of the services created in `Network security group can share a rule for multiple services` test case isn't cleaned up properly, which might be the reason why it is failing frequently in https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-vmss
- Added some logging to `Service with annotation can be accessed by domain name`, which flakes occasionally
- Changed `ginkgo.FDescribe()` to `ginkgo.Describe()` so developers can use …

Fix NSG test case & add logging to flaky svc test caes

---

examples/aks-engine.json
examples/az.json
hack/deploy-cluster.sh

/kind cleanup
Fix sample aks-engine cluster definition and deployment script which used in e2e test.
None.
None.
```
None.
```

Fix deploy cluster script

---

docs/cloud-provider-config.md
docs/services/README.md

>
> /kind bug
> /kind design
> /kind flake
Update docs for per-client rate-limiting configs and loadBalancerResourceGroup
Fixes #
```
NONE
```

Update docs for per-client rate-limiting configs and loadBalancerResourceGroup

---

tests/kubemark/README
tests/kubemark/build-kubemark.sh
tests/kubemark/extensions/config-kubemark-master/v1/config-kubemark-master.sh
tests/kubemark/extensions/config-kubemark-master/v1/supported-orchestrators.json
tests/kubemark/extensions/config-kubemark-master/v1/template-link.json
tests/kubemark/extensions/config-kubemark-master/v1/template.json
tests/kubemark/templates/kubemark-cluster.json

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Change jq query format.
Fixes #
```
None.
```

Add extension for building kubemark master cluster.

---

docs/cloud-provider-config.md

disableAvailabilitySetNodes is added by https://github.com/kubernetes/kubernetes/pull/87685. This PR adds its documentation.
Fixes #
```
NONE
```

Update docs for disableAvailabilitySetNodes

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
/kind feature
Enable Windows builds for azure-cloud-node-manager.
Fixes #
```
Enable Windows builds for azure-cloud-node-manager
```

Enable Windows builds for azure-cloud-node-manager

---

tests/kubemark/build-kubemark.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
The azure credential in CNCF prow isn't of json format. Change jq to grep.
Fixes #
```
```

Change the way of reading azure credential file.

---

OWNERS

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add @nilo19 to owners.
Fixes #
```
```

Add nilo19 to owners.

---

tests/kubemark/build-kubemark.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Read azure credentials from environment variables in azure kubemark test since directly reading them from azure credential files doesn't work.
Fixes #
```
None.
```

Read azure credentials from environment variables in azure kubemark test.

---

.dockerignore
Makefile
cloud-node-manager-windows.Dockerfile
cloud-node-manager.Dockerfile
cmd/cloud-node-manager/app/nodemanager.go
cmd/cloud-node-manager/app/options/options.go
examples/out-of-tree/cloud-node-manager.yaml
pkg/node/node.go

/kind feature
Add Windows support for cloud-node-manager as well as the examples for Windows daemonset.
Fixes #
```
Add Windows support for cloud-node-manager
```

Add Windows support for cloud-node-manager

---

tests/kubemark/build-kubemark.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fix calculating ready hollow nodes and all more logs.
Fixes #
```
None.
```

Fix calculating ready hollow nodes and all more logs.

---

tests/kubemark/build-kubemark.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #
```
None.
```

Fix self addding problem.

---

tests/kubemark/build-kubemark.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #
```
None.
```

Fix grep exit with an error code.

---

examples/out-of-tree/cloud-node-manager.yaml
hack/log-dump/log-dump-daemonset.yaml

/kind cleanup
Ref: kubernetes/kubernetes#89477
Fixes #
```
replace beta label beta.kubernetes.io/os to GA label for kubernetes
```
/assign @feiskyer

[Trival] replace beta label beta.kubernetes.io/os to GA label for kubernetes

---

tests/kubemark/extensions/config-kubemark-master/v1/template.json

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fix wrong init url.
Fixes #
```
None.
```

Fix wrong init url.

---

examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
examples/out-of-tree/kube-apiserver.yaml
examples/out-of-tree/kube-controller-manager.yaml
examples/out-of-tree/kube-scheduler.yaml

Update images for out-of-tree examples.
Fixes #
```
NONE
```

Update images for out-of-tree examples

---

docs/cloud-controller-manager.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Changes example to use a service account instead of admin kubeconfig
```
Use a service account for CCM
```

Use a service account for CCM

---

tests/kubemark/build-kubemark.sh

>
/kind bug
> /kind design
> /kind flake
The aks-engine of version v0.49.0 or later would lead our kubemark test to failure. This PR switch its version to v0.48.0 before the root cause is found.
Fixes #
```
NONE
```

Switch to a stable version of aks-engine.

---

tests/kubemark/build-kubemark.sh

>
/kind bug
> /kind design
> /kind flake
The latest version of azure cli would introduce a failure when deploying cluster with custom extension:
```
{'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'An item with the same key has already been added.'.", 'target': None, 'details': None, 'additionalInfo': None} 
```
Since the root cause is unknown, we roll back to an effective version of azure cli.
Fixes #
**Special …

Use old version of azure cli.

---

README.md

**What this PR does / why we need it**: Update version matrix
Fixes #
```
NONE
```

Update version matrix

---

docs/using-cross-resource-group-nodes.md

the node label `alpha.service-controller.kubernetes.io/exclude-balancer` which excludes a node from cloud load balancers (using Service Type=LoadBalancer) is deprecated in favor of `node.kubernetes.io/exclude-balancer`. Support for `alpha.service-controller.kubernetes.io/exclude-balancer` would be removed in v1.19.
Fixes #
```
NONE
```
/assign @nilo19

Update docs for cross resource group nodes

---

.dockerignore
Makefile
e2e.Dockerfile
tests/e2e/autoscaling/autoscaler.go
tests/e2e/job/clusterrolebinding.yaml
tests/e2e/job/run.sh
tests/e2e/job/test_in_cluster_job.yaml
tests/e2e/utils/utils.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Enable running ccm e2e test in a job.
Fixes #
```
NONE
```

Enable running ccm e2e test in a job

---

Makefile
tests/e2e/job/test_in_cluster_job.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Error parsing reference: "docker.pkg.github.com/Kubernetes-sigs/cloud-provider-azure/ccm-e2e-full:1.0.0" is not a valid repository/tag: invalid reference format: repository name must be lowercase
Fixes #
```
NONE
```

Fix image format

---

hack/log-dump/log-dump-daemonset.yaml
hack/log-dump/log-dump.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/kubernetes/test-infra/pull/18283#issuecomment-657340911. `fedora:latest` does not have `journalctl` binary available, causing the log-dumping error. `fedora:30` is the latest release with journalctl available.
/assign @feiskyer @andyzhangx 
```
None
```

fix: fix error from log-dumping script

---

tests/e2e/utils/utils.go

>
/kind bug
> /kind design
> /kind flake
Increase VMSS polling operation interval to prevent potential throtting issues.
Fixes #
```
NONE
```

Increase VMSS polling operation interval

---

docs/index.md

>
> /kind bug
> /kind design
> /kind flake
Add index page for building github pages. Expamle: https://nilo19.github.io/cloud-provider-azure/
Fixes #
```
NONE
```

Add index page for building github pages

---

docs/dependency-management.md
docs/e2e-tests.md
examples/aks-engine.json
hack/deploy-cluster.sh

>
> /kind bug
> /kind design
> /kind flake
Since the hyperkube is not supported in k8s upstream, the E2E test releated docs and scripts are needed to be updated.
Fixes #
```
NONE
```

Update E2E test related docs and script

---

.github/workflows/gh-pages.yaml

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fixes #
```
NONE
```

Ensure github actions only run on master branch

---

site/content/en/_index.html

>
> /kind bug
> /kind design
> /kind flake
Add two blocks in the index pages of the doc website, which makes the index page more good looking.
Fixes #
```
Add two blocks in the index pages of the doc website.
```

Prettify the index page of the doc web site

---

cloudbuild.yaml

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fix cloud build for image building: `TAG` should be used in cloudbuild.
This should fix the build https://testgrid.k8s.io/provider-azure-cloud-provider-azure#post-cloud-provider-azure-push-images.
Fixes #
```
NONE
```

Fix cloud build for image building

---

tests/k8s-azure/manifest/linux-vmss-serial.json

>
/kind bug
> /kind design
> /kind flake
Since aks-engine enable the check that the lb must be basic when enabling public IP address in agentpool since v0.53.0, we should set an env to prevent test failure in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/cloud-provider-azure-serial/1291895438504366081.
Fixes #
```
NONE
```

Set azure loadbanacer sku to basic when enable public IP address in agentpool

---

tests/k8s-azure/manifest/linux-vmss-serial.json

>
/kind bug
> /kind design
> /kind flake
typo due to the misleading aks-engine doc
Fixes #
```
NONE
```

Chang lb sku basic to Basic

---

tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
tests/k8s-azure/manifest/linux-vmss-basic-lb.json

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```
NONE
```

Add aks-engine deploy manifest for basic LB and cluster autoscaler multiple node pool

---

tests/e2e/network/network_security_group.go
tests/e2e/network/node.go
tests/e2e/network/service_annotations.go
tests/e2e/network/standard_lb.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Move service annotation tests to the `service_annotation.go` for clarity.
Fixes #
```
NONE
```

Move service annotation tests to the corresponding file

---

tests/kubemark/build-kubemark.sh

>
/kind bug
> /kind design
> /kind flake
Delete sudo command to prevent failure.
Fixes #
```
NONE
```

Delete sudo command to prevent failure

---

examples/out-of-tree/cloud-node-manager.yaml

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Enable cloud node controller to patch nodes/status in exapmle yaml file.
Fixes #
```
NONE
```

Enable cloud node controller to patch nodes/status in exapmle yaml file

---

tests/kubemark/build-kubemark.sh

>
/kind bug
> /kind design
> /kind flake
Switch from azure cli to aks-engine api to deploy clusters.
Fixes #
```
NONE
```

Switch from azure cli to aks-engine api to deploy clusters

---

tests/e2e/autoscaling/autoscaler.go

>
> /kind bug
> /kind design
> /kind flake
Reduce the total number of cores in scaling tests to prevent quota problems.
Fixes #
```
NONE
```

Reduce the total number of cores in scaling tests to prevent quota problems

---

site/content/en/blog/releases/v0.6.0.md

>
> /kind bug
> /kind design
> /kind flake
Add v0.6.0 release note.
Fixes #
```
Add v0.6.0 release note.
```

Add v0.6.0 release note.

---

site/config.toml

>
/kind bug
> /kind design
> /kind flake
Fix edit url in doc website.
Fixes #
```
NONE
```

Fix edit url in doc website.

---

site/content/en/install/azure-ccm.md

Reading the documentation some links in how to deploy the Azure Disk/File CSI Driver does not exist anymore, This PR update the manifest links.
Fixes #
```
NONE
```

docs: update documentation in how to deploy azure disk/file csi drivers

---

examples/out-of-tree/cloud-controller-manager.yaml

Add healthz/readyz probes in the example manifest
@feiskyer please let me know if this what you want, the issue was not too clear.
Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/271
```
add healthz/readyz probes in the example manifest and bump the image to the lastest available
```

add healthz/readyz probes in the example manifest and bump the image to the lastest available

---

tests/e2e/autoscaling/autoscaler.go

>
/kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```

Fix an error log

---

tests/e2e/network/node.go
tests/e2e/utils/utils.go
tests/e2e/utils/vmss_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fixes #
```
NONE
```

Add e2e log

---

cmd/cloud-controller-manager/app/controllermanager.go

>
/kind bug
> /kind design
> /kind flake
Fix readyz probe.
Fixes #
```
Fix readyz probe
```

Fix readyz probe

---

cmd/cloud-controller-manager/app/controllermanager.go

(cherry picked from commit a02c319502ce50d4c4b5225a9f869f5cf62cf3b7)
>
/kind bug
> /kind design
> /kind flake
Fix readyz probe.
Fixes #
```
Fix readyz probe
```

Cherry pick of #394 to release 0.5: fix readyz probe

---

cmd/cloud-controller-manager/app/controllermanager.go

(cherry picked from commit a02c319502ce50d4c4b5225a9f869f5cf62cf3b7)
>
/kind bug
> /kind design
> /kind flake
Fix readyz probe.
Fixes #
```
Fix readyz probe
```

Cherry pick of #394 to release 0.6: fix readyz probe

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/service_utils.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add e2e test cases for multiple services sharing one ip address
Fixes #
```
NONE
```

Add e2e test cases for multiple services sharing one ip address

---

site/content/en/install/configs.md

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Add docs on cache TTLs for various resources
Fixes #
```
NONE
```

Add docs on cache TTLs for various resources

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/node_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add e2e test cases for shared IP and node label
Fixes #
```
NONE
```

Add e2e test cases for shared IP and node label

---

site/content/en/topics/loadbalancer.md
site/content/en/topics/shared-ip.md

>
> /kind bug
> /kind design
> /kind flake
Add docs for shared IP and node exclusion.
Fixes #
```
NONE
```

Add docs for shared IP and node exclusion

---

tests/k8s-azure/manifest/linux-vmss-multi-zones.json

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```

Use vmas for masters

---

site/content/en/development/design-docs/_index.md
site/content/en/development/design-docs/multiple-slb.md

>
> /kind bug
> /kind design
> /kind flake
Add design doc for the feature "support multiple slbs in one cluster"
Fixes #
```
NONE
```

Add design doc for the feature "support multiple slbs in one cluster"

---

examples/azure.json
site/content/en/topics/custom-health-probe.md
site/content/en/topics/loadbalancer.md
site/content/en/topics/multiple-slb.md
site/content/en/topics/tagging-resources.md

>
> /kind bug
> /kind design
> /kind flake
Add docs for recent features:
1. custom health probe
2. multiple standard load balancer
3. custom tags
Fixes #419 
Fixes #418 
```
NONE
```

Add docs for recent features

---

site/content/en/topics/multiple-slb.md
site/content/en/topics/shared-ip.md
site/content/en/topics/tagging-resources.md

>
> /kind bug
> /kind design
> /kind flake
Specify the supported version in the docs of recent features.
Fixes #
```
NONE
```

Specify the supported version in the docs of recent features

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
tests/e2e/network/node.go
tests/e2e/network/service_annotations.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/network_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add e2e test case for the service annotation `service.beta.kubernetes.io/azure-pip-tags` and `service.beta.kubernetes.io/azure-pip-name`.
Fixes #415
```
NONE
```

Add e2e test case for the service annotation `service.beta.kubernetes.io/azure-pip-tags` and `service.beta.kubernetes.io/azure-pip-name`

---

tests/k8s-azure/manifest/kubernetes.json

>
> /kind bug
> /kind design
> /kind flake
add a test manifest
Fixes #
```
NONE
```

add a test manifest

---

site/content/en/topics/loadbalancer.md

>
> /kind bug
> /kind design
> /kind flake
kind documentation
Add docs for service annotation service.beta.kubernetes.io/azure-load-balancer-enable-high-availability-ports, which is required when applications require IP fragments.
Fixes #
```
NONE
```

Add docs for service annotation service.beta.kubernetes.io/azure-load-balancer-enable-high-availability-ports

---

tests/e2e/utils/utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind flake
increase the timeout in e2e test
Fixes #
```
NONE
```

increase the timeout in e2e test

---

go.mod
vendor/modules.txt

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Move the kubernetes to require in go.mod
Fixes #
```
NONE
```

Move the kubernetes to require in go.mod

---

pkg/azureclients/diskclient/mockdiskclient/interface.go

>
/kind bug
> /kind design
> /kind flake
Rectify ListByResourceGroup mock so that UTs work as expected
Fixes #
```
NONE
```

fix: Fix ListByResourceGroup in azure diskClient mock

---

tests/k8s-azure/manifest/kubernetes.json

>
> /kind bug
> /kind design
> /kind flake
Add feature gate `ExecProbeTimeout=true`, ref: https://github.com/kubernetes-sigs/windows-testing/pull/227.
Fixes #
```
NONE
```

add feature gate ExecProbeTimeout=true

---

site/content/en/topics/loadbalancer.md

>
> /kind bug
> /kind design
> /kind flake
add lb limits in docs
Fixes #
```
NONE
```

add lb limits in docs

---

tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
tests/k8s-azure/manifest/e2e-slow.json
tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-ipv6.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss-basic-lb.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss-serial.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

>
> /kind bug
> /kind design
> /kind flake
Update manifests for some failing e2e tests.
Fixes #
```
NONE
```

Update manifests for some failing e2e tests

---

tests/e2e/network/ensureloadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
/kind flake
Get node before tag it to prevent etag mismatch.
Fixes #
```
NONE
```

Get node before tag it

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_test.go
pkg/provider/azure_vmss.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Support change the LB selection mode annotation on the existing services.
Mirror: https://github.com/kubernetes/kubernetes/pull/96937.
Fixes: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/416
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/427
```
Support change the LB selection mode on the existing services
```

Support change the LB selection mode on the existing services

---

site/content/en/topics/loadbalancer.md

>
> /kind bug
> /kind design
> /kind flake
Refine the doc of the mode selection annotation.
Fixes #
```
NONE
```

Refine the doc of the mode selection annotation

---

tests/k8s-azure/manifest/linux-vmss-basic-lb.json

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add a node pool in basic lb test to cover more e2e cases
Fixes #
```
NONE
```

Add a node pool in basic lb test

---

hack/update-dependencies.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Explicitly set mod=mod in go list
Fixes #454
```
NONE
```

Explicitly set mod=mod in go list

---

tests/e2e/autoscaling/autoscaler.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/node_utils.go

>
> /kind bug
> /kind design
> /kind flake
Skip the exclude LB test on multi node pool cluster
Fixes #
```
NONE
```

Skip the exclude LB test on multi node pool cluster

---

README.md
site/content/en/blog/releases/v0.7.0.md

>
> /kind bug
> /kind design
> /kind flake
Release Cloud Provider Azure v0.7.0.
Fixes #
```
NONE
```

Release Cloud Provider Azure v0.7.0

---

site/content/en/topics/multiple-slb.md

>
> /kind bug
> /kind design
> /kind flake
Change the expression of the mode selection annotation in multiple SLB doc
Fixes #
```
NONE
```

Change the expression of the mode selection annotation in multiple SLB doc

---

pkg/provider/azure_storageaccount.go

/kind feature
feat: add CreateAccount option in EnsureStorageAccount
This PR:
- add CreateAccount option in EnsureStorageAccount
- if CreateAccount is false(by default), use a random matching account if user does not provide an account name(current behavior is always use first matching account)
Fixes #
```
none
```

feat: add CreateAccount option in EnsureStorageAccount

---

pkg/azureclients/armclient/azure_armclient.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
add logs in LB GET and PUT to gain insight into the requests
Fixes #463
```
add logs in ARM GET and PUT
```

chore: add logs in ARM GET and PUT

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/service_annotations.go

>
> /kind bug
> /kind design
> /kind flake
Skip the always failed test case caused by underlying SLB issue.
Related issue #485.
```
NONE
```

Skip the always failed test case caused by underlying SLB issue

---

pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
Support etag when putting network interface.
Fixes #425
```
Support etag when putting network interface.
```

feat: Support etag when putting network interface

---

pkg/provider/azure.go
pkg/provider/azure_instances.go
pkg/provider/azure_instances_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
Implement cloudprovider.InstancesV2 interface
Fixes #344
```
Implement cloudprovider.InstancesV2 interface
```

Implement cloudprovider.InstancesV2 interface

---

pkg/provider/azure_loadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Ignore the default load balancer ranges when adding the deny rule
Fixes #
```
Ignore the default load balancer ranges when adding the deny rule
```

fix: Ignore the default load balancer ranges when adding the deny rule

---

pkg/provider/azure_storageaccount.go

/kind feature
feat: skip account matching with special tags
This PR also select first matching account to make sure account matching is deterministic.
Fixes #
```
feat: skip account matching with special tags
```

feat: skip account matching with special tags

---

pkg/provider/azure_loadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
add error detail in a verbose log
Fixes #
```
add error detail in a verbose log
```

add error detail in a verbose log

---

pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
pkg/azureclients/storageaccountclient/interface.go
pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go
pkg/provider/azure_storageaccount.go

/kind feature
feat: add AddStorageAccountTags func
Fixes #
```
feat: add AddStorageAccountTags func
```

feat: add AddStorageAccountTags func

---

pkg/azureclients/armclient/azure_armclient.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
add log level in armclient
Fixes #
```
add log level in armclient
```

chore: add log level in armclient

---

pkg/provider/azure_storageaccount.go

/kind feature
feat: add RemoveStorageAccountTag func
Fixes #
```
feat: add RemoveStorageAccountTag func
```

feat: add RemoveStorageAccountTag func

---

site/content/en/development/design-docs/_index.md
site/content/en/development/design-docs/ipam.md

>
> /kind bug
> /kind design
> /kind flake
/kind design
Add design proposal of the out-of-tree node IPAM controller
Fixes #
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/462
```
NONE
```

doc: add design proposal of the out-of-tree node IPAM controller

---

pkg/azureclients/snapshotclient/interface.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #
Update snapshotclient API version for Azure Stack
```
none
```

fix: update snapshotclient api version for Azure Stack

---

pkg/azureclients/diskclient/interface.go
pkg/azureclients/snapshotclient/interface.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Lower snapshot and disk client API version for Azure Stack to make them compatible on build 2008.
Fixes #
```
none
```

fix: lower snapshot and disk client API version for Azure Stack

---

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json

/kind cleanup
- Adds dual-stack test manifests
Fixes #
```
NONE
```

test: add dual-stack test manifests

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/service_annotations.go

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Re-enable a set of tests that have been disabled, and validate whether they're working now.
Fixes #485
```
NONE
```

Enable ILB e2e tests

---

tests/e2e/network/network_security_group.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fixes #
```
add e2e test for annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`
```

e2e: add e2e test for annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`

---

site/content/en/blog/releases/v0.7.0.md

>
> /kind bug
> /kind design
> /kind flake
docs: fix v0.7.0 release date
Fixes #
```
NONE
```

docs: fix v0.7.0 release date

---

site/content/en/blog/releases/v0.7.1.md

>
> /kind bug
> /kind design
> /kind flake
Refer #515, prepare release notes for release v0.7.1.
Fixes #
```
NONE
```

Prepare release notes for release v0.7.1

---

tests/e2e/network/service_annotations.go

>
> /kind bug
> /kind design
> /kind flake
E2e test should wait for service deletion, hence `utils.DeleteService()` should be used in cleanup steps.
Fixes #
```
NONE
```

E2e test should wait for service deletion

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

>
> /kind bug
> /kind design
docs: update references to latest release v0.7.1.
Fixes #515
```
NONE
```

docs: update references to latest release v0.7.1

---

.golangci.yml
pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
pkg/azureclients/diskclient/azure_diskclient_test.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
pkg/azureclients/routetableclient/azure_routetableclient_test.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
pkg/azureclients/subnetclient/azure_subnetclient_test.go
pkg/azureclients/vmclient/azure_vmclient_test.go
pkg/azureclients/vmsizeclient/azure_vmsizeclient_test.go
pkg/azureclients/vmssclient/azure_vmssclient_test.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
pkg/cache/azure_cache_test.go
pkg/nodeipam/ipam/cidrset/cidr_set_test.go
pkg/provider/azure.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_managedDiskController_test.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_test.go
pkg/provider/azure_vmss_cache_test.go
tests/e2e/network/ensureloadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Fix code and enable goconst linter. Follow up from #518.
Fixes #
```
NONE
```

enable goconst linter

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v0.7.2.md
site/content/en/install/configs.md

>
> /kind bug
> /kind design
> /kind flake
* Update image references to v0.7.2
* Add docs for disableAzureStackCloud
Fixes #
```
NONE
```

Update image references to v0.7.2

---

pkg/provider/azure_storageaccount.go

/kind bug
fix: account name logging in azure file
```
azure_storageaccount.go:99] found skip-matching tag for account %!s(*string=0xc000cbd7b0), skip matching
```
Fixes #
```
fix: account name logging in azure file
```

fix: account name logging in azure file

---

pkg/azureclients/fileclient/azure_fileclient.go

/kind feature
chore: remove get file in CreateFileShare
it's not necessary to get file in CreateFileShare
Fixes #
```
chore: remove get file in CreateFileShare
```

chore: remove get file in CreateFileShare

---

site/content/en/topics/assumptions.md

>
> /kind bug
> /kind design
> /kind flake
Add assumption docs for provisioning tools
Fixes #507
```
NONE
```

Add assumption docs for provisioning tools

---

.golangci.yml
cmd/cloud-controller-manager/app/options/options.go
cmd/cloud-controller-manager/app/testing/testserver.go
cmd/cloud-node-manager/app/options/options.go
pkg/nodeipam/ipam/cloud_cidr_allocator.go
pkg/nodeipam/ipam/range_allocator.go
pkg/nodeipam/node_ipam_controller_test.go
pkg/provider/azure_config.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_storageaccount.go
pkg/provider/azure_test.go
pkg/retry/azure_retry.go
pkg/util/controller/testutil/test_utils.go
tests/e2e/autoscaling/autoscaler.go
tests/e2e/network/network_security_group.go
tests/e2e/network/node.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_auth.go
tests/e2e/utils/container_registry_utils.go
tests/e2e/utils/network_interface_utils.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/route_table_utils.go
tests/e2e/utils/vm_utils.go
tests/e2e/utils/vmss_utils.go

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Fix code and enable gosec linter. Follow up from #518.
Fixes #
```
NONE
```

enable gosec linter

---

tests/k8s-azure/manifest/kubernetes.json

>
> /kind bug
> /kind design
> /kind flake
The PR tests are failing due to a required flag on the apiserver: https://github.com/kubernetes/kubernetes/issues/99470#issuecomment-792904345
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-aks-engine-azure/1368758016026873856
Fixes https://github.com/kubernetes/kubernetes/issues/99470#issuecomment-792904345
```
NONE
```

add service account issuer flag

---

pkg/azureclients/fileclient/azure_fileclient.go

/kind feature
add get/set azure file ServiceProperties client
Fixes #
```
add get/set azure file ServiceProperties client
```
/hold

add get/set azure file ServiceProperties client

---

pkg/azureclients/fileclient/azure_fileclient.go
pkg/azureclients/fileclient/interface.go
pkg/azureclients/fileclient/mockfileclient/interface.go

/kind feature
feat: refine ServiceProperties interface
Fixes #
```
feat: refine ServiceProperties interface
```

feat: refine ServiceProperties interface

---

pkg/provider/azure_storageaccount.go

/kind feature
feat: add disable RetentionPolicy parameter
Fixes #
```
feat: add disable RetentionPolicy parameter
```

feat: add disable RetentionPolicy parameter

---

tests/k8s-azure/manifest/kubernetes.json

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
>
> /kind bug
> /kind design
> /kind flake
Removing ExecProbeTimeout kubelet feature gate so we can test changes introduced in https://github.com/kubernetes/kubernetes/pull/100028.
/assign @feiskyer 
/cc @jackfrancis 
Fixes #
```
```

fix: remove ExecProbeTimeout kubelet feature gate

---

pkg/consts/consts.go
pkg/nodeipam/ipam/cloud_cidr_allocator_test.go
pkg/provider/azure_backoff.go
pkg/provider/azure_backoff_test.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: move consts in azure_vmss.go to consts.go
Fixes #
```
chore: move consts in azure_vmss.go to consts.go
```

chore: move consts in azure_vmss.go to consts.go

---

tests/e2e/network/standard_lb.go

>
> /kind bug
> /kind design
> /kind flake
fix flaky test
Fixes #
```
fix flaky test
```

fix flaky test

---

tests/e2e/network/standard_lb.go

>
> /kind bug
> /kind design
> /kind flake
/kind flake
fix: add logs for flaky tests
Fixes #
```
fix: add logs for flaky tests
```

fix: add logs for flaky tests

---

pkg/consts/consts.go
pkg/provider/azure.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_routes.go
pkg/provider/azure_utils.go
pkg/provider/azure_utils_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
| Tags | SystemTags | existing tags on resources | new tags on resources |
| ----- | ------------ | ----- | ----- |
| "a=b,c=d" | "" | {} | {"a": "b", "c": "d"} |
| "a=b,c=d" | "" | {"a": "x", "c": "y"} | {"a": "b", "c": "d"} |
| "a=b,c=d" | "" | {"e": "f"} | {"a": "b", "c": "d", "e": "f"} /* won't delete `e` because the SystemTags is empty */ |
| "c=d" | "a" | {"a": "b"} | {"a": "b", "c": "d"} /* won't delete `a` because it's in the SystemTags */ |
| …

feat: support system tag

---

pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmasclient/azure_vmasclient_test.go
pkg/azureclients/vmasclient/doc.go
pkg/azureclients/vmasclient/interface.go
pkg/azureclients/vmasclient/mockvmasclient/doc.go
pkg/azureclients/vmasclient/mockvmasclient/interface.go
pkg/consts/consts.go
pkg/provider/azure.go
pkg/provider/azure_fakes.go
pkg/provider/azure_instances_test.go
pkg/provider/azure_ratelimit.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_cache.go
pkg/provider/azure_vmss_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
feat: implement cloud allocator for vmas. This would be useful after integrating with aks-engine because the availability set doesn't support manual scale.
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/462
```
feat: implement cloud allocator for vmas
```

feat: implement cloud allocator for vmas

---

site/content/en/install/configs.md
site/content/en/topics/tagging-resources.md

>
> /kind bug
> /kind design
> /kind flake
chore: enrich docs for tags
Fixes #
```
chore: enrich docs for tags
```

chore: enrich docs for tags

---

.golangci.yml
pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_vmss.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_routes.go
pkg/retry/azure_retry_test.go
tests/e2e/autoscaling/autoscaler.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
**What this PR does / why we need it**: Fixes code and enabled unconvert linter.
Fixes #
```
NONE
```

enable unconvert linter

---

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
tests/k8s-azure/manifest/linux-ipv6.json

/kind cleanup
To fix the following test case
```
Kubernetes e2e suite.[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
```
Fix has been merged in aks-engine and will be available in v0.62.0. We can then remove this. 
Fixes #
```
NONE
```

chore: add issuer url in apiserver config for dual-stack and ipv6

---

pkg/provider/azure_loadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: add verbose logs for load balancer rules/probes.
Fixes #563
```
NONE
```

chore: add verbose logs for load balancer rules/probes

---

pkg/azureclients/azure_client_config.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/diskclient/interface.go
pkg/provider/azure.go
pkg/provider/azure_controller_common.go
pkg/provider/azure_fakes.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_managedDiskController_test.go

/kind feature
This PR allows cloud provider to deploy managed disks to the extended location.
```
Add extended location support for managed disks.
```

Use extended location for managed disks

---

pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/diskclient/interface.go
pkg/azureclients/snapshotclient/interface.go
pkg/azureclients/vmasclient/interface.go
pkg/azureclients/vmclient/interface.go
pkg/azureclients/vmsizeclient/interface.go
pkg/azureclients/vmssclient/interface.go
pkg/azureclients/vmssvmclient/interface.go
pkg/azureclients/zoneclient/azure_zoneclient.go
pkg/azureclients/zoneclient/interface.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Update compute API version to 2020-12-01.
Fixes #
```
Update Azure compute API version to 2020-12-01
```

Update compute API version to 2020-12-01

---

cmd/cloud-node-manager/app/config/config.go
cmd/cloud-node-manager/app/nodemanager.go
cmd/cloud-node-manager/app/options/options.go
pkg/node/BUILD.bazel
pkg/node/nodearm.go
pkg/node/nodeproviderfactory.go

>
/kind feature
Adds ARM node provider for custom clouds where IMDS is not available. Primary use case for this change is to support Azure Stack Hub.
Fixes #
Adding ARM node provider required for Azure Stack clouds where IMDS compute is not yet available.
```
feat: add ARM node provider 
```

feat: add ARM node provider

---

hack/log-dump/log-dump.sh

/kind flake
The CSI Drivers logs on master is missing. Need to add them for debugging.
Fixes #
```
NONE
```

chore: dump CSI Drivers logs on master

---

pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_controller_standard.go
pkg/provider/azure_controller_standard_test.go
pkg/provider/azure_controller_vmss.go
pkg/provider/azure_controller_vmss_test.go
pkg/provider/azure_mock_vmsets.go
pkg/provider/azure_vmsets.go

/kind feature
feat: add update vm interface
Fixes #
/hold
```
feat: add update vm interface
```

feat: add update vm interface

---

pkg/provider/azure_backoff.go
pkg/provider/azure_backoff_test.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_mock_vmsets.go
pkg/provider/azure_standard.go
pkg/provider/azure_test.go
pkg/provider/azure_vmsets.go
pkg/provider/azure_vmss.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/pod_utils.go
tests/e2e/utils/service_utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
There were potential issues when enabling share-slb mode if there are both external and internal load balancers in the cluster. This PR fix that.
Fixes #
```
fix: support sharing the primary slb when there are both external and internal load balancers in the cluster
```

fix: support sharing the primary slb when there are both external and internal load balancers in the cluster

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v0.7.3.md

>
> /kind bug
> /kind design
> /kind flake
Add release note for v0.7.3 and update image references.
Fixes #
```
doc: release v0.7.3
```

doc: release v0.7.3

---

pkg/provider/azure_controller_common.go

/kind bug
fix: potential race condition in detach disk
Original detach disk logic hols `diskMap` data too long time and it would have potential race condition in such case. This PR only tries one(holding a lock) if it's a triable error, and unlock after retry. If there is still failure, k8s volume controller would retry in an outer loop.
Fixes #
/hold
```
fix: potential race condition in detach disk
```

fix: potential race condition in detach disk

---

examples/out-of-tree/cloud-node-manager.yaml
site/content/en/development/custom-images.md
site/content/en/install/azure-ccm.md

>
> /kind bug
> /kind design
> /kind flake
chore: update and cleanup docs.
Fixes #
```
NONE
```

chore: update and cleanup docs

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v0.7.3.md
site/content/en/blog/releases/v0.7.4.md

>
> /kind bug
> /kind design
> /kind flake
doc: release v0.7.4
Fixes #
```
doc: release v0.7.4
```

doc: release v0.7.4

---

pkg/provider/azure.go

/kind bug
Edge zone managed disk bug fix. Need to cherry pick this fix for 1.20
There was type conversion error when deploying managed disk to an edge zone.
Fixes #
```
Bug fix for deploying managed disks to edge zones.
```

Edge zone managed disk bug fix.

---

pkg/provider/azure_loadbalancer.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: not tagging static public IP
Fixes #
```
fix: not tagging static public IP
```

fix: not tagging static public IP

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v1.0.0.md

>
> /kind bug
> /kind design
> /kind flake
doc: release v1.0.0
Fixes #
```
doc: release v1.0.0
```

doc: release v1.0.0

---

site/content/en/install/configs.md

>
> /kind bug
> /kind design
> /kind flake
docs: add docs for ccm dynamic reloading
Fixes #
```
docs: add docs for ccm dynamic reloading
```

docs: add docs for ccm dynamic reloading

---

pkg/provider/azure_controller_common.go

/kind bug
fix: dangling volume issue
if disk is already attached to current node, should invalidate cache and return error directly
```
I0508 12:32:45.134778       1 azure_controller_common.go:180] found dangling volume /subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Microsoft.Compute/disks/pvc-4521fb02-44f5-46ed-baef-6473fd6fbf58 attached to node aks-agentpool-15002531-vmss00000x
E0508 12:32:45.134801       1 controllerserver.go:463] Attach volume "/subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Microsoft.Compute/disks/pvc-4521fb02-44f5-46ed-baef-6473fd6fbf58" to instance "aks-agentpool-15002531-vmss00000x" failed with disk(/subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Micro …
```

fix: dangling volume issue

---

pkg/provider/azure_storage_test.go
pkg/provider/azure_storageaccount.go

/kind feature
feat: add NFSv3 account creation support
Fixes #
```
feat: add NFSv3 account creation support
```

feat: add NFSv3 account creation support

---

pkg/provider/azure_controller_common.go

/kind cleanup
chore: only get vmset when it's needed
get vmset is generating a few useless logs, this PR may help reduce logs.
Fixes #
```
none
```
/hold

chore: only get vmset when it's needed

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
site/content/en/topics/loadbalancer.md

cherry-pick of #664 to 1.0 release: add support for SCTP services
```release-note
feat: add support for SCTP services
```

cherry-pick of #664 to 1.0 release

---

site/content/en/topics/loadbalancer.md

chore: update docs for service tags NSG.
Fixes #
```
chore: update docs for service tags NSG
```

chore: update docs for service tags NSG

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
site/content/en/topics/loadbalancer.md

>
> /kind bug
> /kind design
> /kind flake
/kind feature
This PR adds support for SCTP services. Because the public SLB only supports TCP and UDP protocols, the SCTP services would only be supported in internal SLB. Documents have also been added.
Fixes #
```
feat: add support for SCTP services
```

cherry-pick of #645 to release-1.0

---

tests/k8s-azure/manifest/windows-dual-stack.json

/kind cleanup
- Adds dual-stack windows test manifest
Fixes #
```
NONE
```

test: add windows dual-stack manifest

---

pkg/metrics/azure_metrics.go

/kind cleanup
chore: add more buckets for operation metrics
Fixes #
```
chore: add more buckets for operation metrics
```

chore: add more buckets for operation metrics

---

pkg/metrics/azure_metrics.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Cherry pick https://github.com/kubernetes-sigs/cloud-provider-azure/pull/656 to release-1.0.
Fixes #
```
add more buckets for operation metrics
```

Cherry pick #656 to release-1.0

---

tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json
tests/k8s-azure/manifest/e2e-slow.json
tests/k8s-azure/manifest/kubernetes.json
tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json
tests/k8s-azure/manifest/linux-autoscaler.json
tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
tests/k8s-azure/manifest/linux-ipv6.json
tests/k8s-azure/manifest/linux-kcm.json
tests/k8s-azure/manifest/linux-vmss-basic-lb.json
tests/k8s-azure/manifest/linux-vmss-multi-zones.json
tests/k8s-azure/manifest/linux-vmss-serial.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/windows-dual-stack.json

Ensure all CSI controllers are running to unblock the tests.
Fixes #
```
NONE
```

chore: update the master count in testing

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v1.0.1.md

>
> /kind bug
> /kind design
> /kind flake
doc: release v1.0.1
Fixes #
```
doc: release v1.0.1
```

doc: release v1.0.1

---

.github/workflows/gh-pages.yaml
.github/workflows/test-docs.yaml
site/content/en/blog/releases/v1.0.1.md
site/package-lock.json

>
> /kind bug
> /kind design
> /kind flake
chore: fix the format for v1.0.1 release notes
Fixes #
```
NONE
```

chore: fix the format for v1.0.1 release notes

---

pkg/provider/azure_storageaccount.go

/kind feature
chore: upgrade TLS1.0 to TLS1.2 in account creation
Fixes #
```
chore: upgrade TLS1.0 to TLS1.2 in account creation
```

chore: upgrade TLS1.0 to TLS1.2 in account creation

---

pkg/provider/azure_storageaccount.go

chore: increase log level for creating private endpoint in account
Fixes #
```
none
```

chore: increase log level for creating private endpoint in account

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: only put pip if it is necessary
Fixes #
```
chore: only put pip if it is necessary
```

chore: only put pip if it is necessary

---

pkg/consts/consts.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_utils.go
pkg/provider/azure_utils_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
feat: add support for additional public IPs via service annotations. This is required when using Azure cross-region LoadBalancer together with regional AKS LoadBalancer as the iptables rules would also need to be configured on each nodes besides the regional VIP.
Fixes #
```
feat: add support for additional public IPs via service annotation …
```

feat: add support for additional public IPs via service annotations

---

pkg/consts/consts.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_utils.go
pkg/provider/azure_utils_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
cherry-pick of #691: add support for additional public IPs via service annotations.
Fixes #
```
feat: add support for additional public IPs via service annotations
```

cherry-pick of #691: add support for additional public IPs via service annotations

---

README.md
site/content/en/blog/releases/v0.7.5.md
site/content/en/blog/releases/v1.0.2.md
site/content/en/topics/loadbalancer.md

>
> /kind bug
> /kind design
chore: update release notes for v1.0.2 and v0.7.5.
Fixes #
```
NONE
```

chore: update release notes for v1.0.2 and v0.7.5

---

.golangci.yml
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_managedDiskController_test.go

/kind feature
feat: support networkAccessPolicy
Fixes #
/hold
```
feat: support networkAccessPolicy
```

feat: support networkAccessPolicy

---

pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: enrich unit test for serviceOwnsFrontendIP
Fixes #
```
chore: enrich unit test for serviceOwnsFrontendIP
```

chore: enrich unit test for serviceOwnsFrontendIP

---

pkg/provider/azure_loadbalancer.go

Signed-off-by: GitHub <noreply@github.com>
>
> /kind bug
> /kind design
> /kind flake
cherry-pick of #703 to 1.0: Provide IPv6 support for internal load balancer
Fixes #
```
Feat: Provide IPv6 support for internal load balancer
```

cherry-pick of #703 to 0.7: Provide IPv6 support for internal load balancer

---

README.md
site/content/en/blog/releases/v0.7.6.md
site/content/en/blog/releases/v1.0.3.md

chore: add release notes for v1.0.3 and v0.7.6.
Fixes #
```
NONE
```

chore: add release notes for v1.0.3 and v0.7.6

---

pkg/provider/azure_storageaccount.go
pkg/provider/azure_storageaccount_test.go

/kind bug
This PR fixed two issues related to private endpoint:
- fixed PrivateEndpoint matching in storage account search
- fixed private dns zone creation error if it already exists, related error msg is like following:
```
E0720 08:55:58.712928       1 utils.go:123] GRPC error: rpc error: code = Internal desc = failed to ensure storage account: Failed to create private DNS zone(privatelink.file.core.windows.net) in resourceGroup(mc_andy-aks1205_andy-aks1205_eastus2), error: Code="PreconditionFailed" Message="The Zone privatelink.file.core.windows.net exists already and hence cannot be created again."
```
Fixes #
/hold
```
fixed …
```

fix: PrivateEndpoint matching in storage account search

---

pkg/provider/azure_storageaccount.go
pkg/provider/azure_storageaccount_test.go

/kind bug
fix: respect VnetResourceGroup in private link creation
Fixes #
/hold
```
fix: respect VnetResourceGroup in private link creation
```

fix: respect VnetResourceGroup in private link creation

---

site/content/en/install/azure-ccm.md

>
> /kind bug
> /kind design
> /kind flake
docs: fix broken links for azuredisk/azurefile CSI driver deployments.
Fixes #717 
```
NONE
```

docs: fix broken links

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmclient/azure_vmclient_test.go
pkg/azureclients/vmclient/interface.go
pkg/azureclients/vmclient/mockvmclient/interface.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
pkg/azureclients/vmssvmclient/interface.go
pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
pkg/provider/azure.go
pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_controller_standard.go
pkg/provider/azure_controller_standard_test.go
pkg/provider/azure_controller_vmss.go
pkg/provider/azure_controller_vmss_test.go
pkg/provider/azure_mock_vmsets_test.go
pkg/provider/azure_ratelimit.go
pkg/provider/azure_ratelimit_test.go
pkg/provider/azure_vmsets.go

/kind feature
feat: support async attach/detach disk
This PR splits the original `AttachDisk` functions to two parts: `AttachDisk` would use `UpdateAsync` and return immediately after server accepted, and then release lock, wait for former function running complete, same logic for `DetachDisk`
This PR also add a rate limiter(read from default fields: `cloudProviderRateLimitWriteQPS`, `cloudProviderRateLimitWriteBucket`) for disk attach/detach operation, if it exceeds rate limit, will switch to batch operation to prevent throttling. 
Fixes #
```
feat: support async attach/detach disk
```

feat: support async attach/detach disk

---

.github/dependabot.yml

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: add configuration for dependabot, so that dependencies would be updated automatically for master branch.
Fixes #
```
NONE
```

chore: add configuration for dependabot

---

pkg/provider/azure.go
pkg/provider/azure_zones.go

/kind bug
Disabling zones check and other zone related bit on azure stack cloud due to it is not supported on this platform.
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-2102 
Fixes #715
```
Zones logic on Azure Stack Cloud platform was disabled because it does not supported on this platform.
```

fix: Disable zones on azure stack cloud

---

.github/dependabot.yml

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: enable vendor for dependabot.
Fixes #
```
NONE
```

chore: enable vendor for dependabot

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: ensure NSG rules are handled regardless of case. This is because any properties in NSG rules (e.g. protocol) may be changed to a different case by external clients (e.g. Azure Portal or CLI).
Fixes #740
```
fix: ensure NSG rules are handled regardless of case
```

fix: ensure NSG rules are handled regardless of case

---

Dockerfile
Makefile
cloud-node-manager-windows.Dockerfile
cloud-node-manager.Dockerfile
cloudbuild.yaml
hack/pkg-config.sh
pkg/provider/azure_instances.go
pkg/provider/azure_instances_test.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_mock_vmsets.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_test.go
pkg/provider/azure_vmsets.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug 
cherry-pick a set of bug fixes to release-1.0:
- #741
- #745
- #743
Fixes #
```
- fix: ensure NSG rules are handled regardless of case
- fix: enable git command by default
- fix: ensure VM with provisioningState=Creating and powerState=Stopped is treated as Creating instead of Stopped
```

release-1.0: cherry-pick of #741 #743 #745

---

Dockerfile
Makefile
cloud-node-manager-windows.Dockerfile
cloud-node-manager.Dockerfile
cloudbuild.yaml
hack/pkg-config.sh
pkg/provider/azure_instances.go
pkg/provider/azure_instances_test.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_mock_vmsets.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_test.go
pkg/provider/azure_vmsets.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug 
cherry-pick a set of bug fixes to release-0.7:
- #741
- #745
- #743
Fixes #
```
- fix: ensure NSG rules are handled regardless of case
- fix: enable git command by default
- fix: ensure VM with provisioningState=Creating and powerState=Stopped is treated as Creating instead of Stopped
```

release-0.7: cherry-pick of #741 #743 #745

---

pkg/provider/azure_instances.go
pkg/provider/azure_instances_test.go
pkg/provider/azure_mock_vmsets_test.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_vmsets.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: ensure VM with provisioningState=Creating and powerState=Stopped  is treated as Creating instead of Stopped
Fixes #742
```
fix: ensure VM with provisioningState=Creating and powerState=Stopped  is treated as Creating instead of Stopped
```

fix: ensure VM with provisioningState=Creating and powerState=Stopped  is treated as Creating instead of Stopped

---

Dockerfile
Makefile
cloud-node-manager.Dockerfile
cloudbuild.yaml
hack/pkg-config.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: enable git command by default so that images could get the correct version from git.
Fixes #744
```
fix: enable git command by default so that images could get the correct version from git
```

fix: enable git command by default

---

cloudbuild.yaml
hack/pkg-config.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug 
- cherry pick of #749
Fixes #
```
fix: ensure major and minor versions are set correctly
```

release-1.0: cherry-pick of #749

---

cloudbuild.yaml
hack/pkg-config.sh

>
> /kind bug
> /kind design
> /kind flake
/kind bug
- cherry pick of #749
Fixes #
```
fix: ensure major and minor versions are set correctly
```

release-0.7: cherry-pick of #749

---

README.md
site/content/en/blog/releases/v0.7.7.md
site/content/en/blog/releases/v1.0.4.md
site/content/en/blog/releases/v1.1.0.md

>
> /kind bug
> /kind design
> /kind flake
docs: add release notes for v1.1.0, v1.0.4 and v0.7.7
Fixes #
```
NONE
```

docs: add release notes for v1.1.0, v1.0.4 and v0.7.7

---

pkg/provider/azure.go
pkg/provider/azure_config.go
pkg/provider/azure_config_test.go
pkg/provider/azure_ratelimit_test.go
pkg/provider/azure_test.go

/kind cleanup
chore: expose some public functions
Fixes #
```
chore: expose some public functions
```

chore: expose some public functions

---

pkg/azureclients/armclient/azure_armclient.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: use correct gitVersion in userAgent
Fixes #
```
fix: use correct gitVersion in userAgent
```

cherry-pick of #764: use correct gitVersion in userAgent

---

pkg/azureclients/fileclient/azure_fileclient.go

/kind feature
Add AzureFile API metrics so that we can scrape them in prometheus.
Fixes #
```
Add AzureFile API metrics
```

feat: Add AzureFile API metrics

---

pkg/azureclients/fileclient/azure_fileclient.go

/kind feature
feat: add AccessTier in file share creation interface
Fixes #
```
feat: add AccessTier in file share creation interface
```

feat: add AccessTier in file share creation interface

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
examples/out-of-tree/kube-apiserver.yaml
examples/out-of-tree/kube-controller-manager.yaml
examples/out-of-tree/kube-scheduler.yaml
site/content/en/blog/releases/v0.7.8.md
site/content/en/blog/releases/v1.0.5.md
site/content/en/blog/releases/v1.1.1.md

chore: add release notes for v1.1.1, v1.0.5 and v0.7.8
Fixes #
```
NONE
```

chore: add release notes for v1.1.1, v1.0.5 and v0.7.8

---

pkg/consts/consts.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_storageaccount.go

/kind feature
chore: rename tag key for CSI drivers
Fixes #
```release-note
chore: rename tag key for CSI drivers
```
```docs
chore: rename tag key for CSI drivers
```

chore: rename tag key for CSI drivers

---

pkg/provider/azure_standard.go

doc: add one comment for node labeling rules, this could eliminate confusion in https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1013
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1013
```release-note
none
```
```docs
none
```

doc: add one comment for node labeling rules

---

pkg/azureclients/privatednsclient/azure_privatednsclient.go
pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
pkg/azureclients/privateendpointclient/azure_privateendpointclient.go

/kind bug
fix: create private endpoint failure on Government cloud
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/826
```release-note
fix: create private endpoint failure on Government cloud
```
```docs
fix: create private endpoint failure on Government cloud
```

fix: create private endpoint failure on Government cloud

---

pkg/provider/azure_routes.go
pkg/provider/azure_routes_test.go

(cherry picked from commit 4edce73a852a0c695bbacd445c925d75f772ee88)
/kind bug
fix: remove outdated ipv4 route when the corresponding node is deleted
Fixes #875
```release-note
fix: remove outdated ipv4 route when the corresponding node is deleted
```
```docs
```

fix: remove outdated ipv4 route when the corresponding node is deleted

---

pkg/provider/azure.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_routes.go
pkg/provider/azure_utils.go
site/content/en/install/configs.md
site/content/en/topics/tagging-resources.md
tests/e2e/network/service_annotations.go

/kind feature
Cherry pick from #892: feat: support json sytle tags
Fixes #
```release-note
feat: support json style tags
```
```docs
```

feat: support json style tags

---

tests/k8s-azure/manifest/linux-vmss-basic-lb.json
tests/k8s-azure/manifest/linux-vmss.json
tests/k8s-azure/manifest/linux.json

/kind cleanup
chore: enable mixed protocol service feature gates in e2e templates
Fixes #
```release-note
chore: enable mixed protocol service feature gates in e2e templates
```
```docs
```

chore: enable mixed protocol service feature gates in e2e templates

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/standard_lb.go

/kind cleanup
chore: add mixed protocol service e2e test
Fixes #873 
```release-note
chore: add mixed protocol service e2e test
```
```docs
```

chore: add mixed protocol service e2e test

---

pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_controller_standard.go
pkg/provider/azure_controller_standard_test.go
pkg/provider/azure_controller_vmss.go
pkg/provider/azure_controller_vmss_test.go

/kind cleanup
cleanup: remove blob disk operations, blob disk is not supported any more
continue with PR#909
Fixes #
```release-note
none
```
```docs
none
```

cleanup: remove blob disk operations

---

pkg/azureclients/armclient/azure_armclient.go
pkg/provider/azure_backoff.go

/kind cleanup
Add some warning logs for ARM request body on failures, which would help for troubleshooting on failures.
Fixes #
```release-note
NONE
```
```docs
```

chore: add warning logs for ARM request body on failures

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/azure_client_config.go
pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/azureclients/deploymentclient/azure_deploymentclient.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/routeclient/azure_routeclient.go
pkg/azureclients/routetableclient/azure_routetableclient.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/subnetclient/azure_subnetclient.go
pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmsizeclient/azure_vmsizeclient.go
pkg/azureclients/vmssclient/azure_vmssclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/zoneclient/azure_zoneclient.go

/kind feature
adds a rest client config for configuring polling and retries on ARM clients. Consumers creating AZ clients can specify different configurations.
Fixes #
```release-note
N/A
```
```docs
```

add a rest client config for configuring polling and retries on ARM clients

---

Dockerfile
Makefile

Support building `cloud-controller-manager` for `arm` / `arm64` / etc platforms.
Fixes #
```release-note
NONE
```
```docs
```

build: support building ccm for multi-platform

---

cloud-node-manager.Dockerfile

refer #921 
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick from #921 to release-1.0 (build: cross-compile under linux/amd64 platform)

---

Makefile

#926 had built ccm for multi-platforms, and this PR try to build/push ccm for `arm64/arm/amd64` by default.
Fixes #
```release-note
NONE
```
```docs
```

build: build and push ccm images for all platforms by default

---

cloud-node-manager.Dockerfile

refer #921 
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick from #921 to release-1.1 (build: cross-compile under linux/amd64 platform)

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v1.23.0.md

doc: release v1.23.0
Fixes #
```release-note
NONE
```
```docs
```

doc: release v1.23.0

---

pkg/provider/azure_backoff.go

/kind bug
Fixes #924 in release-1.1
The fix has been included in master and release-1.23 by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/918 and is needed to be cherry-picked to release-1.1, release-1.0 and release-0.7.
```release-note
NONE
```
```docs
```

fix: always include the primary load balancer when listing managed load balancers

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
pkg/azureclients/vmssvmclient/interface.go
pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go
pkg/provider/azure.go
pkg/provider/azure_vmss.go
pkg/provider/azure_vmss_test.go

/kind feature
Introduce a configuration option `putVMSSVMBatchSize`. If set, the sync requests will be sent concurrently in batches when putting vmss vms.
Fixes #
```release-note
Introduce a configuration option `putVMSSVMBatchSize`. If set, the sync requests will be sent concurrently in batches when putting vmss vms.
```
```docs
```

feat: support sending sync requests concurrently in batches when putting vmss vm

---

site/content/en/topics/loadbalancer.md

Signed-off-by: Shangxiang Fan <shafan@microsoft.com>
related: #948 
```release-note
None
```
```docs
```

feat: add docs for probeinterval and numofprobe

---

cloud-node-manager.Dockerfile

refer #921
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick from #921 to release-0.7 (build: cross-compile under linux/amd64 platform)

---

site/package-lock.json
site/package.json

/kind bug
test-docs fails recently for missing package autoprefixer@10.4.1, a breaking change. This PR updates the packages according to   suggestion from the building log,
https://github.com/kubernetes-sigs/cloud-provider-azure/runs/4735515422?check_suite_focus=true
Fixes #
```release-note
NONE
```
```docs
```

fix: install breaking change autoprefixer@10.4.1

---

Dockerfile

/kind bug
argument `ARCH` doesn't pass through to build binary.
Fixes #
```release-note
NONE
```
```docs
```

build: fix building multi-arch ccm image

---

Dockerfile
Makefile

refer #926 #936 #978
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick #926 #936 #978 to release-1.0

---

Dockerfile
Makefile

refer #926 #936 #978
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick #926 #936 #978 to release-0.7

---

Dockerfile
Makefile
site/package-lock.json
site/package.json

refer #926 #936 #978
Fixes #
```release-note
NONE
```
```docs
```

cherry-pick #926 #936 #978 to release-1.1

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml
site/content/en/blog/releases/v0.7.11.md
site/content/en/blog/releases/v1.0.8.md
site/content/en/blog/releases/v1.1.4.md
site/content/en/blog/releases/v1.23.1.md

doc: release v1.23.1, v1.1.4, v1.0.8 and v0.7.11
Fixes #
```release-note
NONE
```
```docs
```

doc: release v1.23.1, v1.1.4, v1.0.8 and v0.7.11

---

site/content/en/blog/releases/v0.7.11.md
site/content/en/blog/releases/v1.0.8.md
site/content/en/blog/releases/v1.1.4.md

doc: update contents for release doc v0.7.11, v1.0.8 and v1.1.4
Fixes #
```release-note
NONE
```
```docs
```

doc: update contents for release doc v0.7.11, v1.0.8 and v1.1.4

---

Dockerfile
Makefile
cloud-node-manager.Dockerfile
hack/boilerplate/boilerplate.Dockerfile.txt

Fixes #
```release-note
Upgrade docker/dockerfile image
```
```docs
```

Upgrade docker/dockerfile image

---

cmd/cloud-node-manager/app/options/options.go
pkg/nodemanager/nodemanager.go
pkg/nodemanager/nodemanager_test.go

/kind cleanup
cherry-pick of #986: reduce node LIST APIs in cloud-node-manager
Fixes #
```release-note
chore: reduce node LIST APIs in cloud-node-manager
```
```docs
```

cherry-pick of #986 to release-1.1: reduce node LIST APIs in cloud-node-manager

---

cmd/cloud-node-manager/app/options/options.go
pkg/nodemanager/nodemanager.go
pkg/nodemanager/nodemanager_test.go
pkg/provider/azure.go
site/package-lock.json
site/package.json

/kind cleanup
cherry-pick of #986: reduce node LIST APIs in cloud-node-manager
Fixes #
```release-note
chore: reduce node LIST APIs in cloud-node-manager
```
```docs
```

cherry-pick of #986 to release-1.23: reduce node LIST APIs in cloud-node-manager

---

cmd/cloud-node-manager/app/options/options.go
pkg/nodemanager/nodemanager.go
pkg/nodemanager/nodemanager_test.go

/kind cleanup
cherry-pick of #986: reduce node LIST APIs in cloud-node-manager
Fixes #
```release-note
chore: reduce node LIST APIs in cloud-node-manager
```
```docs
```

cherry-pick of #986 to release-1.0: reduce node LIST APIs in cloud-node-manager

---

Makefile
README.md
cloud-node-manager-windows.Dockerfile
cloudbuild.yaml
site/content/en/development/custom-images.md
site/content/en/development/e2e/e2e-tests.md
site/content/en/development/future.md
site/content/en/development/image-building.md

chore: Polish node manager image building
Fixes #
```release-note
None
```
```docs
```

cherry-pick of #974 to release-1.1: chore: Polish node manager image building

---

Makefile
README.md
cloud-node-manager-windows.Dockerfile
cloudbuild.yaml
site/content/en/development/custom-images.md
site/content/en/development/e2e/e2e-tests.md
site/content/en/development/future.md
site/content/en/development/image-building.md

/kind cleanup
`docker login` is introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/974, but as https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1962 is merged which do `docker login` before we push image through `docker buildx` as an overall temporary fix, we should delete the unused code here.
Fixes #
```release-note
None
```
```docs
```

cherry-pick of #974 to release-0.7: chore: Polish node manager image building

---

Makefile
README.md
cloud-node-manager-windows.Dockerfile
cloudbuild.yaml
site/content/en/development/custom-images.md
site/content/en/development/e2e/e2e-tests.md
site/content/en/development/future.md
site/content/en/development/image-building.md

chore: Polish node manager image building
Fixes #
```release-note
None
```
```docs
```

cherry-pick of #974 to release-1.0: chore: Polish node manager image building

---

hack/deploy-cluster-capz.sh
tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json

/kind cleanup
chore: add more customizations to the capz cloud config template
Fixes #
```release-note
NONE
```
```docs
```

chore: add more customizations to the capz cloud config template

---

tests/k8s-azure/manifest/linux-vmss-multi-zones.json

Fixes #
```release-note
Enable TopologyAwareHints for linux-vmss-multi-zone template
```
```docs
```

linux-vmss-multi-zone template: enable TopologyAwareHints

---

hack/deploy-cluster-capz.sh
site/content/en/development/deploy-cluster.md
tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml

/kind cleanup
chore: add ssh public key customization for capz cluster deployment
Fixes #
```release-note
NONE
```
```docs
```

chore: add ssh public key customization for capz cluster deployment

---

OWNERS

Request to join  maintainer team of cloud-provider-azure
```release-note
NONE
```
```docs
```

chores:  MartinForReal join maintainer team of cloud-provider-azure

---

.github/workflows/release.yaml

Fixed #878 #879 
HOW-TO:
```
git checkout release-1.23
git tag v1.23.2  # create a new release tag
git push upstream v1.23.2  # push tag to upstream
```
example:
- action: https://github.com/luncj/cloud-provider-azure/actions/runs/1712322173
- release: https://github.com/luncj/cloud-provider-azure/releases/tag/v1.23.2
```release-note
NONE
```
```docs
```

build: add Github action workflow for publishing release

---

.github/workflows/release.yaml

see #1014 
example release: https://github.com/luncj/cloud-provider-azure/releases
example action: https://github.com/luncj/cloud-provider-azure/actions/workflows/release.yaml
```release-note
NONE
```
```docs
```

[cherry pick #1014 for 1.1] build: add Github action workflow for publishing release

---

.github/workflows/release.yaml

see #1014 
example release: https://github.com/luncj/cloud-provider-azure/releases
example action: https://github.com/luncj/cloud-provider-azure/actions/workflows/release.yaml
```release-note
NONE
```
```docs
```

[cherry pick #1014 for 1.0] build: add Github action workflow for publishing release

---

.github/workflows/release.yaml

`release-*-*` branch may not exist, use the `master` branch for scraping instead.
related #1014 
```release-note
NONE
```
```docs
```

build(release): fix the branch to scrape while originating from master

---

.github/workflows/release.yaml

related #1019
```release-note
NONE
```
```docs
```

[cherry pick #1019 for 1.0] build(release): fix the branch to scrape while originating from master

---

.github/workflows/release.yaml

see #1014 
example release: https://github.com/luncj/cloud-provider-azure/releases
example action: https://github.com/luncj/cloud-provider-azure/actions/workflows/release.yaml
```release-note
NONE
```
```docs
```

[cherry pick #1014 for 0.7] build: add Github action workflow for publishing release

---

.github/workflows/release.yaml

related #1019
```release-note
NONE
```
```docs
```

[cherry pick #1019 for 1.1] build(release): fix the branch to scrape while originating from master

---

.github/workflows/release.yaml

related #1019
```release-note
NONE
```
```docs
```

[cherry pick #1019 for 0.7] build(release): fix the branch to scrape while originating from master #1021

---

.github/workflows/release.yaml

see #1014 #1019 
example release: https://github.com/luncj/cloud-provider-azure/releases
example action: https://github.com/luncj/cloud-provider-azure/actions/workflows/release.yaml
```release-note
NONE
```
```docs
```

[cherry pick #1014 / #1019 for 1.23] build: add Github action workflow for publishing release

---

Makefile
README.md
cloud-node-manager-windows.Dockerfile
cloudbuild.yaml
site/content/en/development/custom-images.md
site/content/en/development/e2e/e2e-tests.md
site/content/en/development/future.md
site/content/en/development/image-building.md

related #974
```release-note
NONE
```
```docs
```

[cherry-pick #974 to 1.23] Polish node manager image building

---

.github/dependabot.yml

/kind cleanup
add release-* to monitored branches of Dependabot
```release-note
NONE
```
```docs
```

Chores: add release-* to monitored branches of Dependabot

---

.github/workflows/codeql-analysis.yml
pkg/azureclients/armclient/azure_armclient.go
pkg/retry/azure_retry.go

/kind cleanup
repo config changes:
add github actions to scan code commits before pr is merged.
Fixes #
```release-note
NONE
```
```docs
```

chore: Add actions to scan code

---

Makefile

/kind cleanup
`docker login` is introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/974, but as https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1962 is merged which do `docker login` before we push image through `docker buildx` as an overall temporary fix, we should delete the unused code here.
Fixes #
```release-note
None
```
```docs
```

remove docker login

---

.github/workflows/release.yaml
Makefile

build `acr-credential-provider` binaries when publishing release.
action: https://github.com/luncj/cloud-provider-azure/actions/runs/1744210089
release: https://github.com/luncj/cloud-provider-azure/releases/tag/v1.23.3
Fixes #
```release-note
NONE
```
```docs
```

build: build binaries for acr-credential-provider when release

---

.github/dependabot.yml

/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```

chores: ignore update in build images

---

.github/workflows/release.yaml

fix generating release note. before this PR, the `branch to scrape` is always equal to `master`.
Fixes #
```release-note
NONE
```
```docs
```

build: fix generating release note

---

pkg/azureclients/interfaceclient/interface.go
pkg/azureclients/loadbalancerclient/interface.go
pkg/azureclients/publicipclient/interface.go
pkg/azureclients/routeclient/interface.go
pkg/azureclients/routetableclient/interface.go
pkg/azureclients/securitygroupclient/interface.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_test.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
tests/e2e/network/node.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_interface_utils.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/route_table_utils.go
tests/e2e/utils/service_utils.go

/kind bug
Cherry pick of #1070 to release-1.23:
fix: use zones in the pre-existing frontend IP configurations for internal LBs
chore: bump network api version from 2020-08-01 to 2021-02-01
Fixes #
```release-note
fix: use zones in the pre-existing frontend IP configurations for internal LBs
```
```docs
```

[release-1.23] Cherry pick of #1070 to release-1.23

---

pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_controller_standard.go
pkg/provider/azure_controller_standard_test.go
pkg/provider/azure_controller_vmss.go
pkg/provider/azure_controller_vmss_test.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_managedDiskController_test.go
pkg/provider/azure_mock_vmsets.go
pkg/provider/azure_storageaccount.go
pkg/provider/azure_vmsets.go

/kind bug
/kind cleanup
fix: azure file location specification issue related to https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/906
This PR also add context for Azure disk APIs
Fixes #
```release-note
fix: azure file location specification issue
```
```docs
fix: azure file location specification issue
```

fix: azure file location specification issue

---

site/content/en/blog/releases/v0.7.12.md
site/content/en/blog/releases/v0.7.13.md
site/content/en/blog/releases/v1.0.10.md
site/content/en/blog/releases/v1.0.9.md
site/content/en/blog/releases/v1.1.5.md
site/content/en/blog/releases/v1.1.6.md
site/content/en/blog/releases/v1.23.2.md
site/content/en/blog/releases/v1.23.3.md

Fixes #
```release-note
NONE
```
```docs
```

doc: add release doc for multiple versions

---

.github/workflows/release.yaml

fix bugs:
1. when pushing tags simultaneously, the PR only contains notes of the last successful job. (fix: specify different branches for different tags)
2. and the PR should be based on the `master` branch
Fixes #
```release-note
NONE
```
```docs
```

build: create release-note PR based on `master` branch

---

.github/workflows/release.yaml

Fixes #
```release-note
NONE
```
```docs
```

fix(build): fix branch for release-0.7

---

.github/workflows/release.yaml

Fixes #
```release-note
NONE
```
```docs
```

fix(build): fix branch for release-1.0

---

.github/workflows/release.yaml

Fixes #
```release-note
NONE
```
```docs
```

fix(build): fix branch for release-1.23

---

.github/workflows/release.yaml

Fixes #
```release-note
NONE
```
```docs
```

fix(build): fix branch for release-1.1

---

cmd/cloud-controller-manager/app/controllermanager.go
cmd/cloud-controller-manager/app/testing/testserver.go
cmd/cloud-node-manager/app/nodemanager.go
vendor/k8s.io/controller-manager/controller/interfaces.go
vendor/modules.txt

fixes #1071
Fixes #
```release-note
feat: Support controller health check in ccm
```
```docs
```

feat: Support controller health check in ccm

---

pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/diskclient/azure_diskclient_test.go
pkg/azureclients/diskclient/interface.go
pkg/azureclients/diskclient/mockdiskclient/interface.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
pkg/azureclients/snapshotclient/interface.go
pkg/azureclients/snapshotclient/mocksnapshotclient/interface.go
pkg/provider/azure_controller_common.go
pkg/provider/azure_controller_common_test.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_managedDiskController_test.go
pkg/provider/azure_test.go

/kind feature
chore: add subsID parameter in snapshot and disk client
Fixes #
```release-note
chore: add subsID parameter in snapshot and disk client
```
```docs
chore: add subsID parameter in snapshot and disk client
```

chore: add subsID parameter in snapshot and disk client

---

site/content/en/topics/loadbalancer.md

add docs for health probe customization for svc port
Fixes #949 #948
```release-note
NONE
```
```docs
```

Docs: add docs for health probe customization for svc port

---

pkg/provider/doc.go

/kind bug
adds missing ["] in pkg/provider/doc.go file.
Fixes #
adds missing ["] in pkg/provider/doc.go file.
```release-note
NONE
```
```docs
```

Add missing ["] in pkg/provider/doc.go file.

---

site/content/en/development/deploy-cluster.md
tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml

/kind bug
* Set `cloud-provider` field for worker nodes as `external` so that worker nodes can also get cloud taints and be initialized.
* Remove the `cloud-provider` arg for apiserver setting according to https://kubernetes-sigs.github.io/cloud-provider-azure/install/azure-ccm/#kube-apiserver
* Increase log level to 4 for node manager for debugging
* Minor fix for capz doc
```release-note
NONE
```
```docs
```

capz deploy-cluster script and doc minor fixes

---

.github/workflows/release.yaml

Fixes #1192 
run: 
- https://github.com/lodrem/cloud-provider-azure/releases/tag/v1.23.4
- https://github.com/lodrem/cloud-provider-azure/pull/29
```release-note
NONE
```
```docs
```

build: remove site-header from release-note

---

pkg/azureclients/fileclient/azure_fileclient.go

/kind feature
feat: add more options in file client
Fixes #
```release-note
feat: add more options in file client
```
```docs
feat: add more options in file client
```

feat: add more options in file client

---

pkg/provider/azure_loadbalancer_backendpool.go
pkg/provider/azure_loadbalancer_backendpool_test.go

/kind bug
#1034 tried to avoid mixed type LB backend pool error by deleting and re-creating the LB backend pool. However, this may introduce potential issues and extra api calls. This PR removes all the calls of delete LB backend pool and decouples all VMs from the backend pool before changing its type.
Fixes #
```release-note
fix: do not delete backend pool when reconciling lb backend pools
```
```docs
```

fix: do not delete backend pool when reconciling lb backend pools

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

doc: update readme for new releases
Fixes #
```release-note
NONE
```
```docs
```

doc: update readme for new releases

---

.github/workflows/release.yaml

cherry-pick #1198 for `release-1.0`
```release-note
NONE
```
```docs
```

[cherry-pick for release-1.0] build: fix release note

---

.github/workflows/release.yaml

cherry-pick #1198 for `release-0.7`
```release-note
NONE
```
```docs
```

[cherry-pick for release-0.7] build: fix release note

---

.github/workflows/release.yaml

cherry-pick #1198 for `release-1.23`
```release-note
NONE
```
```docs
```

[cherry-pick for release-1.23] build: fix release note

---

.github/workflows/release.yaml

cherry-pick #1198 for `release-1.1`
```release-note
NONE
```
```docs
```

[cherry-pick for release-1.1] build: fix release note

---

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json
tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json

…
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
/kind bug
Sets `LegacyServiceAccountTokenNoAutoGeneration=false` for controller-manager feature gates as a mitigation to preserve previous SA token generation behaviors for aks-engine.
https://github.com/kubernetes/enhancements/pull/2800/files introduced this feature gate and set true-by-default.
Fixes #
```release-note
NONE
```
```docs
```

Set LegacyServiceAccountTokenNoAutoGeneration to false for master/1.24 aks-engine configs

---

.github/dependabot.yml

/kind cleanup
Automatically run test for dependabot jobs
Fixes #
```release-note
NONE
```
```docs
```

Add ok to test label

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/service_utils.go

Fixes #
```release-note
NONE
```
```docs
```

[e2e] Refactor: Service and Node deletion

---

Makefile
cloudbuild.yaml

/kind bug
For cloud build, docker buildx doesn't work in Makefile:
"buildx is not a docker command"
Instead, we should use: /root/.docker/cli-plugins/docker-buildx
Fixes #
```release-note
NONE
```
```docs
```

[Cloud build] Fix docker buildx

---

site/content/en/topics/loadbalancer.md

remove stale docs for the features which we no longer support: TCP reset and health-protocol 
Fixes #
```release-note
NONE
```
```docs
```

Remove stale docs: tcp reset and health protocol

---

OWNERS

Fixes #
```release-note
NONE
```
```docs
```

chores: lzhecheng joins maintainer team of cloud-provider-azure

---

pkg/metrics/azure_metrics.go

/kind cleanup
chore: increase log level for ARM requests.
Fixes #
```release-note
NONE
```
```docs
```

chore: increase log level for ARM requests

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

/kind bug
1. If the vmSet is changed from non-primary to the primary vmSet, we need to make sure the dedicated LB is deleted.
2. In some cases, the private IP of an internal service may change when switching from one LB to another. We need to re-use the previous private IP.
Fixes #
Bug 2 cannot be reproduced, I have just hit it once.
```release-note
fix: remove agent pool LB if that vmSet is changed to primary vmSet
fix: reuse previous private IP address when changing load balancers
```
```docs
```

Fix bugs related to multiple slbs

---

site/content/en/install/azure-ccm.md

This PR fixes a link to a 404 in the official Kubernetes docs for `kube-controller-manager`.
Fixes #
```release-note
NONE
```
```docs
```

docs: fix broken link to kube-controller-manager reference

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

/kind bug
fix: update load balancer rule when probe changes
Fixes #
```release-note
fix: update load balancer rule when probe changes
```
```docs
```

fix: update load balancer rule when probe changes

---

Makefile
cloudbuild.yaml

* push-ccm-image no need to build again
* Larger timeout for cloud build
Fixes #
```release-note
NONE
```
```docs
```

fix Makefile for release-staging

---

.github/workflows/release.yaml

Fixes #
```release-note
NONE
```
```docs
```

Doc: List all of pr changes without any filter in release note

---

Makefile

gcb-docker-gcloud image doesn't have jq but it is needed for node
manager images build
/kind bug
gcb-docker-gcloud image doesn't have jq but it is needed for node
manager images build
Fixes #
```release-note
NONE
```
```docs
```

Install jq for cloud build in Makefile

---

tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml

Fix ccm deployment in vmss-multi-nodepool
* incorrect apiVersion
* incorrect indent for template
/kind bug
Fix ccm deployment in vmss-multi-nodepool
* incorrect apiVersion
* incorrect indent for template
Fixes #
```release-note
NONE
```
```docs
```

Fix ccm deployment in vmss-multi-nodepool

---

site/content/en/development/design-docs/pls-integration.md

Initial design document for Azure PLS integration for loadBalancer typed services.
Fixes #
```release-note
NONE
```
```docs
```

Add pls integration design doc

---

site/content/en/development/design-docs/pls-integration.md

Fixes #
```release-note
NONE
```
```docs
```

Minor doc link fix

---

tests/e2e/network/service_annotations.go
tests/e2e/utils/service_utils.go

/kind testing
We need to add e2e test case to cover the scenario in which a service with multiple ports is applied. 
Fixes #1318
```release-note
NONE
```
```docs
```

Tests: e2e add multiport service test

---

site/content/en/development/design-docs/pls-integration.md

Fixes #
```release-note
NONE
```
```docs
```

Refine doc

---

pkg/azureclients/armclient/azure_armclient_test.go

Use table driven UT
Refactor azure_armclient tests. Use table driven UT.
Fixes #
```release-note
NONE
```
```docs
```

Refactor azure_armclient tests

---

pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go
pkg/azureclients/privatelinkserviceclient/interface.go
pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go

/kind feature
Add List() to Azure privatelinkservice client interface
Fixes #
```release-note
NONE
```
```docs
```

Add List() to pls client interface

---

pkg/azureclients/armclient/azure_armclient_test.go

Use table driven UT
Fixes #
```release-note
NONE
```
```docs
```

[cherrypick][release-1.0] Refactor azure_armclient tests

---

pkg/azureclients/armclient/azure_armclient_test.go

Use table driven UT
Fixes #
```release-note
NONE
```
```docs
```

[cherrypick][release-1.1] Refactor azure_armclient tests

---

pkg/azureclients/armclient/azure_armclient_test.go

Use table driven UT
Fixes #
```release-note
NONE
```
```docs
```

[cherrypick][release-0.7] Refactor azure_armclient tests

---

helm/cloud-provider-azure/README.md

* update installation and configuration parts
* add uninstallation part
* update installation and configuration parts
* add uninstallation part
Users may copy the example command to install the chart but the original one is actually for old K8s. If so, with latest K8s, users will find that with kcm (new) and ccm (old), node-ipam-controller is not there.
So it is better to provider 2 commands for users.
Fixes #
```release-note
NONE
```
```docs
```

[helm] Update helm doc

---

Makefile
hack/verify-helm-repo.sh
helm/cloud-provider-azure/README.md

* ignore README.md when verifying helm repo
* support make update-helm
* ignore README.md when verifying helm repo
* support make update-helm
Fixes #
```release-note
NONE
```
```docs
```

[helm] Update helm repo

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go

backport #1084 #1235
/kind feature
backport #1084
Fixes #
```release-note
NONE
```
```docs
```

[release-1.0]backport #1084 #1235

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go
pkg/provider/azure_test.go

/kind feature
Manual cherry pick PR #1500 into release-0.7 branch.
Reduce listPIP calls.
Fixes #
```release-note
NONE
```
```docs
```

Reduce listPIP calls

---

tests/e2e/autoscaling/autoscaler.go
tests/e2e/e2e_test.go
tests/e2e/network/node.go
tests/e2e/node/vmss.go
tests/e2e/utils/log.go
tests/e2e/utils/vmss_utils.go

Fixes #1514 
```release-note
NONE
```

test: add e2e test for deletion of VMSS instance

---

.github/dependabot.yml

/kind testing
Add label for dependabot jobs
Fixes #
```release-note
NONE
```
```docs
```

chores: Add kind label for dependency update pr

---

.github/dependabot.yml

/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```

chores:Retire release-0.7 and disable dependabot

---

tests/e2e/utils/service_utils.go

/kind bug
fix: fix a nil pointer issue in e2e
Fixes #
```release-note
NONE
```
```docs
```

fix: fix a nil pointer issue in e2e

---

pkg/provider/azure_routes.go

/kind cleanup
chore: add a log for deleting routes that doesn't exist
Fixes #
```release-note
chore: add a log for deleting routes that doesn't exist
```
```docs
```

chore: add a log for deleting routes that doesn't exist

---

.github/workflows/release.yaml
Makefile

/kind feature
pick #1053 to release-1.23
generated sample: https://github.com/lodrem/cloud-provider-azure/releases/tag/v1.23.5
Fixes #
```release-note
NONE
```
```docs
```

[pick #1053 to release-1.23] build: build binaries for acr-credential-provider when release

---

site/content/en/development/design-docs/pls-integration.md

Update design doc to follow the implementation.
Fixes #
```release-note
NONE
```
```docs
```

Update design doc for pls integration

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

/kind bug
fix: update probe when protocol or request path change, so that the updated probe annotations would trigger Azure LoadBalancer updates.
Fixes #
```release-note
fix: update probe when protocol or request path change
```
```docs
```

fix: update probe when protocol or request path change

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

/kind bug
fix-0.7: update probe when protocol or request path change
Fixes #
```release-note
fix-0.7: update probe when protocol or request path change
```
```docs
```

fix-0.7: update probe when protocol or request path change

---

README.md

Makes some small changes to improve the landing page document.
N/A
```release-note
NONE
```

docs: language fixes to README.md

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/azureclients/deploymentclient/azure_deploymentclient.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmssclient/azure_vmssclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/zoneclient/azure_zoneclient.go

Add a new function GetResourceListID() and use other armclient ones if possible.
/kind cleanup
Add a new function GetResourceListID() and use other armclient ones if possible.
Fixes #
```release-note
NONE
```
```docs
```

Refactor: Use armclient functions

---

hack/verify-helm-repo.sh

/kind cleanup
To get LATEST_CHART, "ls -t" won't work for CI because tgz files will have same modification time. Instead, use "sort -rV"
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/968/pull-cloud-provider-azure-check/1522112615810076672
```
ls hack/../helm/repo/cloud-provider-azure-1.23.10.tgz hack/../helm/repo/cloud-provider-azure-1.23.11.tgz hack/../helm/repo/cloud-provider-azure-1.23.8.tgz -al
-rw-r--r-- 1 root root 7243 May  5 07:15 hack/../helm/repo/cloud-provider-azure-1.23.10.tgz
-rw-r--r-- 1 root root 7242 May  5 07:15 hack/../helm/repo/cloud-provider-azure-1.23.11.tgz
-rw-r--r-- 1 root root 7154 May  5 07:15 hack/../helm/repo/cloud-provider-azure-1.23.8.tgz
```
Fixes # …

Fix verify helm script

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

Fixes #
```release-note
NONE
```
```docs
```

chore: update readme and examples

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/privatednsclient/azure_privatednsclient.go
pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
pkg/azureclients/privatednsclient/interface.go
pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
pkg/azureclients/privatednszonegroupclient/interface.go
pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
pkg/provider/azure_storageaccount.go
pkg/provider/azure_storageaccount_test.go

* Use arm client
* Add UT
/kind cleanup
Refactor private dns zone and zone group clients
* Use arm client
* Add UT
related: #1493
Fixes #
```release-note
NONE
```
```docs
```

Refactor private dns zone and zone group clients

---

site/content/en/blog/releases/v1.24.0.md

Update release notes for v1.24.0 with an action required part.
Fixes #
```release-note
NONE
```
```docs
```

Update release notes for v1.24.0

---

helm/cloud-provider-azure/README.md

This PR adds more detail to the helm chart maintenance documentation, especially how to manage chart version updates.
Fixes #
```release-note
NONE
```
```docs
```

helm: update docs to clarify chart maintenance requirements

---

pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/azureclients/deploymentclient/azure_deploymentclient.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/routeclient/azure_routeclient.go
pkg/azureclients/routetableclient/azure_routetableclient.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/subnetclient/azure_subnetclient.go
pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmssclient/azure_vmssclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/zoneclient/azure_zoneclient.go

/kind cleanup
Refactor: Use variables for providers and types
Fixes #
```release-note
NONE
```
```docs
```

Refactor: Use variables for providers and types

---

pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/provider/azure.go
pkg/provider/azure_ratelimit.go
site/content/en/install/configs.md

/kind feature
Add missing rate limit configs for some clients
- ContainerServiceRateLimit
- DeploymentRateLimit
- PrivateDNSRateLimit
- PrivateDNSZoneGroupRateLimit
- PrivateEndpointRateLimit
- PrivateLinkServiceRateLimit
- VirtualNetworkRateLimit
Fixes #
```release-note
Add missing rate limit configs for some clients
- ContainerServiceRateLimit
- DeploymentRateLimit
- PrivateDNSRateLimit
- PrivateDNSZoneGroupRateLimit
- PrivateEndpointRateLimit
- PrivateLinkServiceRateLimit
- VirtualNetworkRateLimit
```
```docs
```

Add missing rate limit configs for some clients

---

tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind cleanup
Add e2e tests for private link service integration
Fixes #
related: #872 #1484
```release-note
NONE
```
```docs
```

test: Add e2e tests for private link service integration

---

tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind cleanup
Cherry pick private link service e2e tests to release-1.24
Fixes #
related https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1692
```release-note
NONE
```
```docs
```

[release-1.24]test: Add e2e tests for pls

---

tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind cleanup
Cherry pick private link service e2e tests to release-1.0
Fixes #
related #1692 
```release-note
NONE
```
```docs
```

[release-1.0]test: Add e2e tests for pls

---

tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind cleanup
Cherry pick private link service e2e tests to release-1.23
Fixes #
related https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1692
```release-note
NONE
```
```docs
```

[release-1.23]test: Add e2e tests for pls

---

tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/utils/azure_test_client.go
tests/e2e/utils/network_utils.go

/kind cleanup
Cherry pick private link service e2e tests to release-1.1
Fixes #
related #1692 
```release-note
NONE
```
```docs
```

[release-1.1]test: Add e2e tests for pls

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go
pkg/azureclients/deploymentclient/azure_deploymentclient.go
pkg/azureclients/deploymentclient/azure_deploymentclient_test.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
pkg/azureclients/routeclient/azure_routeclient.go
pkg/azureclients/routeclient/azure_routeclient_test.go
pkg/azureclients/routetableclient/azure_routetableclient.go
pkg/azureclients/routetableclient/azure_routetableclient_test.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient_test.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/subnetclient/azure_subnetclient.go
pkg/azureclients/subnetclient/azure_subnetclient_test.go
pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmclient/azure_vmclient_test.go
pkg/azureclients/vmssclient/azure_vmssclient.go
pkg/azureclients/vmssclient/azure_vmssclient_test.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/zoneclient/azure_zoneclient.go

/kind cleanup
cherrypick https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1612 https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1550 https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1613
Fixes #
```release-note
NONE
```
```docs
```

Cherry-pick armclients 1.0

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/utils/pod_utils.go
tests/e2e/utils/service_utils.go

/kind cleanup
Add 2 LB tests:
* internal -> public
* public -> internal with specific IP
This change is to replace an upstream k/k test because there's a bug
there now.
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Add LB tests about switching between public and internal ones

---

tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml

/kind cleanup
[CI] Add vmss template for CAPZ
related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/919
Fixes #
```release-note
NONE
```
```docs
```

[CI] Add vmss template for CAPZ

---

tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml

/kind cleanup
Add multiple zone vmss template
Fixes #
```release-note
NONE
```
```docs
```

Add multiple zone vmss template

---

hack/deploy-cluster.sh

/kind cleanup
Fix some typo found during local test.
Fixes #
```release-note
NONE
```
```docs
```

chore: fix aks engine deploy script

---

examples/aks-engine.json
tests/k8s-azure/manifest/linux-vmss.json

Use containerd as container runtime to enable aks-engine e2e test for 1.24 branch.
Fixes #
```release-note
NONE
```
```docs
aks-engine reference: https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md
```

chore: Use containerd for aks-engine e2e test deployment

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/containerserviceclient/azure_containerserviceclient.go
pkg/azureclients/deploymentclient/azure_deploymentclient.go
pkg/azureclients/diskclient/azure_diskclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go
pkg/azureclients/privatednsclient/azure_privatednsclient.go
pkg/azureclients/privatednsclient/azure_privatednsclient_test.go
pkg/azureclients/privatednsclient/interface.go
pkg/azureclients/privatednsclient/mockprivatednsclient/interface.go
pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient.go
pkg/azureclients/privatednszonegroupclient/azure_privatednszonegroupclient_test.go
pkg/azureclients/privatednszonegroupclient/interface.go
pkg/azureclients/privatednszonegroupclient/mockprivatednszonegroupclient/interface.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/routeclient/azure_routeclient.go
pkg/azureclients/routetableclient/azure_routetableclient.go
pkg/azureclients/securitygroupclient/azure_securitygroupclient.go
pkg/azureclients/snapshotclient/azure_snapshotclient.go
pkg/azureclients/storageaccountclient/azure_storageaccountclient.go
pkg/azureclients/subnetclient/azure_subnetclient.go
pkg/azureclients/vmasclient/azure_vmasclient.go
pkg/azureclients/vmclient/azure_vmclient.go
pkg/azureclients/vmssclient/azure_vmssclient.go
pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
pkg/azureclients/zoneclient/azure_zoneclient.go
pkg/provider/azure_storageaccount.go
pkg/provider/azure_storageaccount_test.go

/kind cleanup
Cherrypick #1613 #1556
Fixes #
```release-note
NONE
```
```docs
```

Cherrypick armclients 1.24

---

OWNERS

Fixes #
```release-note
NONE
```
```docs
```

Add jwtty to owners list

---

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml

/kind cleanup
Support ci-version templates for CAPZ jobs
Then KUBERNETES_VERSION can be set as "latest-xx" for vmss clusters.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2325#discussion_r880735733
Fixes #
```release-note
NONE
```
```docs
```

Support ci-version templates for CAPZ jobs

---

site/content/en/topics/pls-integration.md

Add PLS document to "Topics" section and refine some details. I'll delete the old one under "Design doc" section once the AKS official doc removes the reference.
Fixes #
```release-note
NONE
```
```docs
```

chore: Move pls doc to topics

---

site/content/en/topics/pls-integration.md

Fix link reference in pls doc.
Fixes #
```release-note
NONE
```
```docs
```

chore: Fix doc reference

---

tests/e2e/network/standard_lb.go

Skip master VM for test: should add all nodes in different agent pools
to backends
/kind cleanup
Skip master VM for test: should add all nodes in different agent pools
to backends
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Skip if master VM

---

.github/workflows/gh-pages.yaml
.gitignore
netlify.toml
site/config.toml

add netlify config as requested by admin
Fixes #
```release-note
NONE
```
```docs
```

Add netlify config for cloud provider azure

---

README.md

Update README to reflect the latest ccm/cnm versions.
Fixes #
```release-note
NONE
```
```docs
```

chore: Update ccm/cnm versions in README

---

tests/e2e/network/service_annotations.go
tests/e2e/utils/network_utils.go

/kind cleanup
[e2e] Fix PIP prefix e2e
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Fix PIP prefix e2e

---

tests/e2e/network/service_annotations.go

/kind cleanup
[e2e] Clean up pip after test for azure-pip-name
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Clean up pip after test for azure-pip-name

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
[release-1.1] Cherrypick 1826 1827 1844 1608 1861
Fixes #
```release-note
NONE
```
```docs
```

[release-1.1] Cherrypick 1826 1827 1844 1608 1861

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
[release-1.0] Cherrypick 1826 1827 1844 1608 1861
Fixes #
```release-note
NONE
```
```docs
```

[release-1.0] Cherrypick 1826 1827 1844 1608 1861

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
[release-1.24] Cherrypick 1826 1827 1844 1608 1861
Fixes #
```release-note
NONE
```
```docs
```

[release-1.24] Cherrypick 1826 1827 1844 1608 1861

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/armclient/interface.go
pkg/azureclients/armclient/mockarmclient/interface.go
pkg/azureclients/interfaceclient/azure_interfaceclient.go
pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
pkg/azureclients/publicipclient/azure_publicipclient.go
pkg/azureclients/publicipclient/azure_publicipclient_test.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
[release-1.23] Cherrypick 1826 1827 1844 1608 1861
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] Cherrypick 1826 1827 1844 1608 1861

---

tests/e2e/network/service_annotations.go

/kind cleanup
[e2e] Dump Pod describe info
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Dump Pod describe info

---

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml

This PR updates the referenced Windows image in capz test templates to "latest".
FYI, this custom test template should always track changes in this template in the capz repository:
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-machine-pool-ci-version.yaml
Fixes #
```release-note
NONE
```
```docs
```

capz: use latest windows image in test templates

---

tests/e2e/network/node.go
tests/e2e/network/standard_lb.go
tests/e2e/utils/network_interface_utils.go
tests/e2e/utils/route_table_utils.go
tests/e2e/utils/utils.go
tests/e2e/utils/vm_utils.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
[e2e] ListXX can return empty list instead of error
Fixes #
```release-note
NONE
```
```docs
```

[e2e] ListXX can return empty list instead of error

---

pkg/retry/azure_error.go
pkg/retry/azure_retry.go

/kind cleanup
split error parsing logic in order to work with retry implementation in autorest
Fixes #
```release-note
NONE
```
```docs
```

Refactor: refactor retry package and split validator and error parser

---

pkg/azureclients/armclient/azure_armclient.go
pkg/azureclients/armclient/azure_armclient_test.go

For replication latency, it is possible contentLength is 0 and http
status code is 200
/kind bug
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
Fixes #
```release-note
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
```
```docs
```

[release-1.1] Improve the error handling for ARM APIs

---

pkg/provider/azure_vmss_cache.go
pkg/provider/azure_vmss_cache_test.go

/kind bug
cherry-pick "invalidate vmssVMCache when rg is not found" PR into release-1.0.
Fixes #
related: #1954 
```release-note
NONE
```
```docs
```

[release-1.0]fix: invalidate vmssVMCache when rg is not found

---

pkg/provider/azure_vmss_cache.go
pkg/provider/azure_vmss_cache_test.go

/kind bug
cherry-pick "invalidate vmssVMCache when rg is not found" PR into release-1.23.
Fixes #
related: #1954 
```release-note
NONE
```
```docs
```

[release-1.23]fix: invalidate vmssVMCache when rg is not found

---

.pipelines/azure-pipeline.yml

/kind testing
Add a testing Azure Pipeline
Fixes #
```release-note
NONE
```
```docs
```

Add a testing Azure Pipeline

---

site/content/en/topics/cross-resource-group-nodes.md

docs: update document for cross resource group nodes and fix the node label for `node.kubernetes.io/exclude-from-external-load-balancers`.
Fixes #
```release-note
NONE
```
```docs
```

docs: update document for cross resource group nodes

---

pkg/consts/consts.go
pkg/consts/helpers.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_backendpool.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_mock_loadbalancer_backendpool.go
pkg/provider/azure_test.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go

/kind feature
Cherry pick of #1729: Add servie annotation to disable lb floating ip
Fixes #1659
```release-note
A new service annotation `service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip` has been added to disable floating IPs in load balancer rule. 
If annotation is omitted or if the annotation is set to be "false", then floating IP will be enabled.
If the annotation is set to be "true", then floating IP will be disabled.
```
```docs
```

[release-1.24] Add servie annotation to disable lb floating ip

---

go.mod
go.sum
pkg/consts/consts.go
pkg/consts/helpers.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_backendpool.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_mock_loadbalancer_backendpool.go
pkg/provider/azure_test.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
vendor/k8s.io/utils/clock/clock.go
vendor/k8s.io/utils/clock/testing/fake_clock.go
vendor/k8s.io/utils/pointer/pointer.go
vendor/k8s.io/utils/strings/slices/slices.go
vendor/modules.txt

/kind feature
Cherry pick of #1729: Add servie annotation to disable lb floating ip
Fixes #1659
```release-note
A new service annotation `service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip` has been added to disable floating IPs in load balancer rule. 
If annotation is omitted or if the annotation is set to be "false", then floating IP will be enabled.
If the annotation is set to be "true", then floating IP will be disabled.
```
```docs
```

[release-1.23] Add servie annotation to disable lb floating ip

---

site/content/en/topics/loadbalancer.md

Fixes #1982 
```release-note
NONE
```
```
```

doc: update load balancer doc

---

tests/e2e/network/service_annotations.go

Check lb type before pip-prefix-id test
Fixes #
```release-note
NONE
```
```docs
```

Check lb type before pip-prefix-id test

---

site/content/en/topics/azure-permissions.md

docs: update cloud provider permissions for LoadBalancer backendAddressPools and PLS.
Fixes #1999
```release-note
NONE
```
```docs
```

docs: update cloud provider permissions

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

doc: bump image versions in readme and exapmels
Fixes #
```release-note
NONE
```
```docs
```

doc: bump image versions in readme and exapmels

---

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml

/kind cleanup
adjust customized CAPZ templates to solve multiple control-plane issue and more
Fixes #1921 
```release-note
NONE
```
```docs
```

Update: adjust customized CAPZ templates to solve multiple control-plane issue and more

---

pkg/provider/azure_loadbalancer_test.go

/kind cleanup
Strictly check the number of LB `CreateOrUpdate` calls during UT.
Fixes #
related #1990 
```release-note
NONE
```
```docs
```

chore: Strictly check LB CreateOrUpdate times during UT

---

tests/e2e/auth/cred.go

/kind cleanup
"should be able to pull private images from acr without docker secrets set explicitly" test will fail in Windows because linux testing environment always pull linux images which can't be pulled successfully in Windows.
Other tests can successfully run in Windows.
Fixes #
```release-note
NONE
```
```docs
```

update e2e-test to support windows

---

.pipelines/docker-login.yml
.pipelines/run-autoscaling-e2e.yml
.pipelines/run-autoscaling-multipool-e2e.yml
.pipelines/run-basic-lb-e2e.yml

/kind testing
Fix azure pipeline variables
Fixes #
```release-note
NONE
```
```docs
```

Fix azure pipeline variables

---

pkg/provider/azure_loadbalancer.go

/kind bug
Use correct subnet name in reconcileFrontendIPConfigs()
Fixes #
```release-note
Use correct subnet name in reconcileFrontendIPConfigs()
```
```docs
```
fixes: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2075

Use correct subnet name in reconcileFrontendIPConfigs()

---

pkg/provider/azure_privatelinkservice.go
pkg/provider/azure_privatelinkservice_test.go

/kind feature
Allow external service with floating ip disabled to create PLS.
Fixes #
related #2073 
```release-note
Allow external service with floating ip disabled to create PLS.
```
```docs
```

[release-1.23] Allow external service with floating ip disabled to use PLS

---

site/content/en/topics/pls-integration.md

docs: update limitations of PLS caused by upstream kubernetes.
Fixes #
```release-note
NONE
```
```docs
```

docs: update limitations of PLS

---

Makefile

/kind cleanup
The old os-version in windows manifest-image can't be recognized. Os-version must be the official version like "10.0.17763.3165", not "1809". 
Fixes #
```release-note
NONE
```
```docs
```

fix: update osversion in Makefile manifest-node-manager-image-window

---

pkg/provider/azure_privatelinkservice.go
pkg/provider/azure_privatelinkservice_test.go

/kind feature
Allow external service with floating ip disabled to create PLS.
Fixes #
related #2073 
```release-note
Allow external service with floating ip disabled to create PLS.
```
```docs
```

[release-1.1] Allow external service with floating ip disabled to use PLS

---

.golangci.yml
cmd/cloud-controller-manager/app/core.go
cmd/cloud-controller-manager/app/testing/testserver.go
hack/verify-golint.sh
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/node/node.go
pkg/node/nodearm.go
pkg/nodeipam/ipam/doc.go
pkg/nodemanager/nodemanager.go
pkg/provider/azure_instances.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_routes.go
pkg/provider/azure_standard.go
pkg/provider/azure_test.go
pkg/provider/azure_vmss.go
pkg/provider/azure_wrap.go
tests/e2e/utils/node_utils.go

/kind testing
Less mem usage for golangci-lint by less concurrency
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] Less mem usage for golangci-lint by less concurrency

---

.pipelines/run-autoscaling-e2e.yml
.pipelines/run-autoscaling-multipool-e2e.yml
.pipelines/run-basic-lb-e2e.yml
.pipelines/scripts/run-e2e.sh
.pipelines/templates/autoscaling-multipool.json
.pipelines/templates/autoscaling.json
hack/test-ccm-e2e.sh

/kind cleanup
1. Fix CLUSTER_TYPE of basic-lb
2. If CLUSTER_TYPE contains "autoscaling", only autoscaler e2e tests are needed.
3. For "autoscaling-multipool", balance-similar-node-groups=true to be better tested.
4. set KUBECONFIG to realpath unless "make test-ccm-e2e" cannot find the KUBECONFIG.
Fixes #
```release-note
NONE
```
```docs
```

Fix aks pipeline to test e2e

---

.golangci.yml
cmd/cloud-controller-manager/app/core.go
cmd/cloud-controller-manager/app/testing/testserver.go
hack/verify-golint.sh
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/node/node.go
pkg/node/nodearm.go
pkg/nodeipam/ipam/doc.go
pkg/nodemanager/nodemanager.go
pkg/provider/azure_blobDiskController.go
pkg/provider/azure_instances.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_routes.go
pkg/provider/azure_standard.go
pkg/provider/azure_test.go
pkg/provider/azure_vmss.go
pkg/provider/azure_wrap.go
tests/e2e/utils/node_utils.go

/kind testing
Less mem usage for golangci-lint by less concurrency
Fixes #
```release-note
NONE
```
```docs
```

[release-1.0] Less mem usage for golangci-lint by less concurrency

---

.pipelines/daily-gc.yml
.pipelines/run-autoscaling-e2e.yml
.pipelines/run-autoscaling-multipool-e2e.yml

/kind bug
fix aks pipeline gc job typo and job scheduling typo
Fixes #
```release-note
NONE
```
```docs
```

fix aks pipeline gc job typo and job scheduling typo

---

.golangci.yml
cmd/cloud-controller-manager/app/core.go
cmd/cloud-controller-manager/app/testing/testserver.go
hack/verify-golint.sh
pkg/azureclients/armclient/azure_armclient_test.go
pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go
pkg/node/node.go
pkg/node/nodearm.go
pkg/nodeipam/ipam/doc.go
pkg/nodemanager/nodemanager.go
pkg/provider/azure_blobDiskController.go
pkg/provider/azure_instances.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_managedDiskController.go
pkg/provider/azure_routes.go
pkg/provider/azure_standard.go
pkg/provider/azure_test.go
pkg/provider/azure_vmss.go
pkg/provider/azure_wrap.go
tests/e2e/utils/node_utils.go

/kind testing
Less mem usage for golangci-lint by less concurrency
Fixes #
```release-note
NONE
```
```docs
```

[release-1.1] Less mem usage for golangci-lint by less concurrency

---

.pipelines/README.md
.pipelines/daily-gc.yml
.pipelines/run-autoscaling-e2e.yml
.pipelines/run-autoscaling-multipool-e2e.yml
.pipelines/run-basic-lb-e2e.yml
.pipelines/run-e2e.yml
.pipelines/scripts/run-e2e.sh
.pipelines/var-e2e.yml

/kind cleanup
1. Modify aks pipeline to separate k8s version env var 
2. Make code more concise by reusing template run-e2e.yml.
3. Add "always: true" to daily_gc because we want the job to run every day even without code changes.
4. Make autoscaling tests run autoscaler and normal e2e tests.
Fixes #
```release-note
NONE
```
```docs
```

Modify aks pipeline to separate k8s version env var and make code more concise

---

Makefile
hack/test-ccm-e2e.sh
tests/e2e/autoscaling/autoscaler.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/node.go
tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/network/standard_lb.go
tests/e2e/node/vmss.go
tests/e2e/utils/azure_auth.go
tests/e2e/utils/node_utils.go
tests/e2e/utils/service_utils.go
tests/e2e/utils/vmss_utils.go

/kind cleanup
Fix e2e tests to support aks cluster, including basic-lb, autoscaling, autoscaling-multipool
Fixes #1929
```release-note
NONE
```
```docs
```

Fix e2e tests to support aks cluster

---

tests/e2e/utils/network_utils.go

/kind testing
Retry when getting security group list
Fixes #
```release-note
NONE
```
```docs
```

[e2e] Retry when getting security group list

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go

/kind bug
Fix one comparison bug during reconciling public ip. Avoid unnecessary pip update.
Also fix wrong UTs.
Fixes #
related: #1990 
```release-note
NONE
```
```docs
```

fix: public ip version check

---

pkg/provider/azure_loadbalancer_test.go

/kind bug
Cherry pick fixing public ip version check
Fixes #
related #2141 
```release-note
NONE
```
```docs
```

[release-1.0] fix: pip UT issue

---

pkg/azureclients/blobclient/azure_blobclient.go
pkg/azureclients/blobclient/azure_blobclient_test.go
pkg/azureclients/blobclient/interface.go
pkg/azureclients/blobclient/mockblobclient/interface.go

/kind feature
feat: change blobclient from management api to rest api
Fixes #
```release-note
feat: change blobclient from management api to rest api
```
```docs
feat: change blobclient from management api to rest api
```

feat: change blobclient from management api to rest api

---

.pipelines/scripts/run-e2e.sh
hack/test-ccm-e2e.sh

/kind cleanup
Aks ccm tests for basic-lb are not very stable. Using flake-attempts to rerun the failing tests can add up stability.
(Passing tests will not rerun)
Fixes #
```release-note
NONE
```
```docs
```

add flake attempts in aks pipeline tests

---

tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/private_link_service.go
tests/e2e/utils/network_utils.go

/kind testing
Add e2e tests to verify resources are not updated when service is reconciled without any significant changes.
Fixes #1990 
```release-note
NONE
```
```docs
```

test: Add e2e tests to avoid redundant reconciliation

---

pkg/provider/azure_storageaccount.go

Fixes #
```release-note
```
```docs
```

Introduce AllowSharedKeyAccess to the StorageAccount creation options

---

.pipelines/run-e2e.yml
.pipelines/scripts/collect-log.sh
.pipelines/scripts/run-e2e.sh

/kind cleanup
add log artifacts in ado for aks pipeline
Fixes #
```release-note
NONE
```
```docs
```

add log artifacts in aks pipeline

---

pkg/provider/azure_vmssflex.go
pkg/provider/azure_vmssflex_test.go

/kind feature
This PR is the first part of FlexScaleSet implementation of VMSet
Refer to #639 
```release-note
NONE
```
```docs
```

VMSS Flex Support: FlexScaleSet implementation of VMSet: part 1

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_vmss.go

/kind bug
Skip "instance not found" error for LB backend address pools
related: https://github.com/kubernetes/kubernetes/issues/111331
Fixes #
```release-note
Skip "instance not found" error for LB backend address pools
```
```docs
```

Skip "instance not found" error for LB backend address pools

---

pkg/provider/azure_vmssflex.go
pkg/provider/azure_vmssflex_cache.go
pkg/provider/azure_vmssflex_cache_test.go
pkg/provider/azure_vmssflex_test.go

/kind feature
This PR is the third part of FlexScaleSet implementation of VMSet
Refer To #639 
```release-note
NONE
```
```docs
```

VMSS Flex Support: VMSet implementation part 3 for VM modelview  related functions

---

pkg/provider/azure_vmssflex.go
pkg/provider/azure_vmssflex_cache_test.go
pkg/provider/azure_vmssflex_test.go

/kind feature
This PR is the part 5 of FlexScaleSet implementation of VMSet, mainly for network related functions
Refer to #639 
```release-note
NONE
```
```docs
```

VMSS Flex Support: part 5 of FlexScaleSet Implementation of VMSet interface mainly for network related functions

---

README.md

/kind cleanup
chore: update version matrix
Fixes #
```release-note
NONE
```
```docs
```

chore: update version matrix

---

site/content/en/install/azure-ccm.md

When reading the documentation I wasn't sure if the helm chart is the way to go for installing the CCM. This change adds a reference to the helm chart.
```release-note
NONE
```

link helm chart in deploy instructions

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_test.go

/kind bug
cherry pick PR #2230 
Fixes #
```release-note
Fix nsg reconciliation failure for floating-ip-disabled services in dual-stack clusters.
```
```docs
```

[release-1.0] fix: NSG destination IP version same as LB IP for floating ip disabled services

---

pkg/azureclients/fileclient/azure_fileclient.go
pkg/azureclients/fileclient/interface.go
pkg/azureclients/fileclient/mockfileclient/interface.go
pkg/provider/azure_file.go
pkg/provider/azure_storage.go
pkg/provider/azure_storage_test.go
pkg/provider/azure_storageaccount.go

/kind feature
Refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1077, we need to support operating azure file across subscription.
Fixes #
```release-note
```
```docs
```

support cross subscrition for azurefile csi driver

---

pkg/provider/azure_loadbalancer.go
pkg/provider/azure_loadbalancer_test.go
pkg/provider/azure_test.go

/kind bug
cherry pick PR #2230 
Fixes #
```release-note
Fix nsg reconciliation failure for floating-ip-disabled services in dual-stack clusters.
```
```docs
```

[release-1.1] fix: NSG destination IP version same as LB IP for floating ip disabled services

---

hack/deploy-cluster-capz.sh
site/content/en/development/deploy-cluster.md
site/content/en/development/e2e/e2e-tests-azure.md
site/content/en/development/e2e/e2e-tests.md
site/content/en/example/in-tree.md
site/content/en/example/out-of-tree.md
site/content/en/install/azure-ccm.md
site/content/en/install/configs.md
site/content/en/topics/ipam.md
tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml

Update doc to replace aks-engine with capz
Fixes #1927
```release-note
Update doc to replace aks-engine with capz
```
```docs
```

Update doc to replace aks-engine with capz

---

tests/e2e/network/service_annotations.go

When ExternalTrafficPolicy is updated
/kind testing
Improve flaky e2e test: "When ExternalTrafficPolicy is updated"
Fixes #
```release-note
NONE
```
```docs
```

Improve flaky e2e test

---

pkg/auth/azure_auth.go
pkg/auth/azure_auth_test.go
pkg/provider/azure.go
pkg/provider/azure_loadbalancer.go
pkg/provider/azure_routes.go
pkg/provider/azure_standard.go
pkg/provider/azure_standard_test.go

/kind feature
feat: add support for network resource in a different subscription when using MSI
Fixes #
```release-note
feat: add support for network resource in a different subscription when using MSI
```
```docs
```

feat: add support for network resource in a different subscription when using MSI

---

.github/workflows/release.yaml

/kind cleanup
Upload kubetest2-aks with correct path for releases
Fixes #
```release-note
NONE
```
```docs
```

Upload kubetest2-aks with correct path for releases

---

.github/dependabot.yml

/kind cleanup
[dependabot] Add 1.25 and remove 1.0
Fixes #
```release-note
NONE
```
```docs
```

[dependabot] Add 1.25 and remove 1.0

---

tests/e2e/auth/cred.go
tests/e2e/network/ensureloadbalancer.go
tests/e2e/network/network_security_group.go
tests/e2e/network/node.go
tests/e2e/network/private_link_service.go
tests/e2e/network/service_annotations.go
tests/e2e/network/standard_lb.go
tests/e2e/node/vmss.go
tests/e2e/utils/consts.go
tests/e2e/utils/kubectl.go
tests/e2e/utils/network_utils.go
tests/e2e/utils/pod_utils.go
tests/e2e/utils/service_utils.go
tests/e2e/utils/utils.go

/kind testing
[release-1.0] cherrypick 1846, 1996
Fixes #
```release-note
NONE
```
```docs
```

[release-1.0] cherrypick 1846, 1996

---

.github/workflows/release.yaml

/kind cleanup
[release-1.23] Fix release kubetest2-aks
* use go 1.18
* fix binary path
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] Fix release kubetest2-aks

---

README.md
examples/out-of-tree/cloud-controller-manager.yaml
examples/out-of-tree/cloud-node-manager.yaml

Update readme for release 1.25
Fixes #
```release-note
NONE
```
```docs
```

Update readme for release 1.25

---

.pipelines/scripts/run-e2e.sh
tests/e2e/autoscaling/autoscaler.go

/kind bug
Autoscaling-multipool tests need specify sub when updating the autoscaler profile.
Fixes #
```release-note
NONE
```
```docs
```

fix: autoscaling-multipool tests need specify sub

---

.pipelines/README.md
.pipelines/scripts/run-e2e.sh
tests/e2e/autoscaling/autoscaler.go

/kind cleanup
switch all ado tests location to eastus
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] fix: switch all ado tests location to eastus

---

.pipelines/scripts/run-e2e.sh
tests/e2e/autoscaling/autoscaler.go

/kind cleanup
switch all ado tests location to eastus
Fixes #
```release-note
NONE
```
```docs
```

[release-1.1] fix: switch all ado tests location to eastus

---

.pipelines/README.md
.pipelines/scripts/run-e2e.sh
tests/e2e/autoscaling/autoscaler.go

/kind cleanup
switch all ado tests location to eastus
Fixes #
```release-note
NONE
```
```docs
```

[release-1.24] fix: switch all ado tests location to eastus

---

.github/workflows/trivy.yaml
go.mod
go.sum
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/modules.txt

/kind testing
Add trivy Github Action
Fixes #
```release-note
NONE
```
```docs
```

Add trivy Github Action

---

.pipelines/README.md
.pipelines/scripts/run-e2e.sh
tests/e2e/autoscaling/autoscaler.go

/kind cleanup
switch all ado tests location to eastus
Fixes #
```release-note
NONE
```
```docs
```

[release-1.25] fix: switch all ado tests location to eastus

---

.github/workflows/trivy.yaml
.trivyignore
go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/modules.txt

/kind testing
Add trivy Github Action
Fixes #
```release-note
NONE
```
```docs
```

[release-1.1] Add trivy Github Action

---

.github/workflows/trivy.yaml
.trivyignore
go.mod
go.sum
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/modules.txt

/kind testing
Add trivy Github Action
Fixes #
```release-note
NONE
```
```docs
```

[release-1.24] Add trivy Github Action

---

.github/workflows/trivy.yaml
.trivyignore
go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/modules.txt

/kind testing
Add trivy Github Action
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] Add trivy Github Action

---

go.mod
go.sum
vendor/github.com/emicklei/go-restful/.gitignore
vendor/github.com/emicklei/go-restful/.travis.yml
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/Makefile
vendor/github.com/emicklei/go-restful/README.md
vendor/github.com/emicklei/go-restful/container.go
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/curly.go
vendor/github.com/emicklei/go-restful/custom_verb.go
vendor/github.com/emicklei/go-restful/jsr311.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/path_processor.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_builder.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/service_error.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

/kind cleanup
Refer https://avd.aquasec.com/nvd/2022/cve-2022-1996/, update go-restful version.
Fixes #
```release-note
chore: update go-restful for CVE-2022-1996
```
```docs
```

[release-1.23] chore: update go-restful version

---

go.mod
go.sum
vendor/github.com/emicklei/go-restful/.gitignore
vendor/github.com/emicklei/go-restful/.travis.yml
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/Makefile
vendor/github.com/emicklei/go-restful/README.md
vendor/github.com/emicklei/go-restful/container.go
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/curly.go
vendor/github.com/emicklei/go-restful/custom_verb.go
vendor/github.com/emicklei/go-restful/jsr311.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/path_processor.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_builder.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/service_error.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

/kind cleanup
Refer https://avd.aquasec.com/nvd/2022/cve-2022-1996/, update go-restful version.
Fixes #
```release-note
chore: update go-restful for CVE-2022-1996
```
```docs
```

[release-1.1] chore: update go-restful version

---

.github/workflows/trivy.yaml
.trivyignore

/kind testing
[release-1.23] Trivy should run for all
Fixes #
```release-note
NONE
```
```docs
```

[release-1.23] Trivy should run for all

---

.github/workflows/trivy.yaml
.trivyignore

/kind testing
[release-1.1] Trivy should run for all
Fixes #
```release-note
NONE
```
```docs
```

[release-1.1] Trivy should run for all

---

.github/workflows/trivy.yaml
.trivyignore

/kind testing
[release-1.24] Trivy should run for all
Fixes #
```release-note
NONE
```
```docs
```

[release-1.24] Trivy should run for all

---

.github/dependabot.yml

/kind testing
Fixes #
```release-note
NONE
```
```docs
```

Auto-approve dependency update

---

pkg/azureclients/armclient/util.go

/kind cleanup
chore: add debug logs for http response ContentLength, StatusCode and responseBody length.
Those debug logs would be useful when there are something wrong happened in the Azure ARM GET/LIST APIs.
Fixes #
```release-note
NONE
```
```docs
```

chore: add debug logs for http response ContentLength, StatusCode and responseBody length
