kubernetes-sigs/cloud-provider-azure

README.md, docs/using-availability-zones.md
Add docs for AZ: https://github.com/kubernetes/features/issues/586.
/assign @justaugustus
=> Add documentation for Azure availability zones

tests/k8s-azure/k8s-azure
Fixes #53 
Will first try verify against a failure deployment, do not view/merge before WIP flag removed.
=> Add timestamp in testing resource group name

README.md
Fix that Azure is spelled with uppercase A.
=> Change azure to Azure in README.md

tests/k8s-azure/skip.txt
Sig azure page on test grid is on now (https://testgrid.k8s.io/sig-azure-master), but some features added in v1.13 are failing now.
Since acs-engine doesn't support 1.13 yet, let's add those tests into skip list now.
=> Add more skip tests

Makefile, scripts/build-hyperkube.sh
Refer #75
> Junit output should be stored in the directory specified by the $ARTIFACTS environment variable and in files with names that match the regexp: junit.*\.xml
=> Put results into $ARTIFACTS and reduce hyperkube build logs

Makefile
This is required because artifacts path is different from workspace path: `/log/artifacts` vs `/workspace`.
=> Setup artifacts volume for runner

docs/cloud-provider-config.md
Correct an error in the documentation stating that you cannot add multiple scale sets to a load balancer. You can in fact do this as long as you are using the Load Balancer Standard SKU.
```release-note
NONE
```
=> Update documentation on multiple scale set support

Makefile, docs/azuredisk-issues.md, docs/azurefile-issues.md, docs/cloud-controller-manager.md, docs/cloud-provider-config.md, docs/component-versioning.md, docs/e2e-tests.md, tests/k8s-azure/Dockerfile, tests/k8s-azure/k8s-azure, tests/k8s-azure/manifest/linux-kcm.json, tests/k8s-azure/manifest/linux.json
- Update e2e test to use aks-engine release v0.31.0 with https://github.com/Azure/aks-engine/pull/492 to fix broken prow job: https://testgrid.k8s.io/sig-azure-master#azure-master-conformance
- Update the apimodel manifest to v1.14 so that aks-engine can remove deprecated flag
- Update docs where applicable
NOTE: The long term fix to point aks-engine release to a url from storage blob, instead of updating releases, will be in a followup PR after the prow job issue has been fixed.
cc @feiskyer @PatrickLang 
**Notes**:
```release-note
Update tests and docs to use aks-engine v0.31.0 to fix e2e tests
```
=> Update tests and docs to use aks-engine

Makefile, docs/e2e-tests.md, tests/k8s-azure/Dockerfile, tests/k8s-azure/k8s-azure, tests/k8s-azure/manifest/linux-kcm.json
Incorporate aks-engine update: https://github.com/Azure/aks-engine/pull/523
**Notes**:
```release-note
Update tests and docs to use aks-engine v0.31.1 to support private ACR to fix e2e tests
```
=> Bump aks-engine to v0.31.1 to support private ACR

tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_utils.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The prefix from DNS is not always same with resource group name. We need
to get it from providerID.
Fixes #
```
NONE
```
=> Fix resource group name for the cluster

tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
>
> /kind bug
> /kind design
> /kind flake
The current e2e tests are pretty flaky, set the timeouts to large values for reducing the failing tests.
Fixes #
```
NONE
```
=> Set timeout to a larger value

tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/pod_utils.go
Autoscaler e2e test exceeds time or returns 'Unexpected EOF' error
```
none
```
=> Make autoscaler e2e test more stable

tests/k8s-azure/manifest/linux-autoscaler.json, tests/k8s-azure/manifest/linux-kcm.json, tests/k8s-azure/manifest/linux.json
>
> /kind bug
> /kind design
> /kind flake
Enable feature gate CSIInlineVolume for kube-controller-manager. 
Fixes #130 
The other two feature flags are already enabled in aks-engine, we should preserve them too.
```
NONE
```
=> Enable feature gate CSIInlineVolume for kube-controller-manager

docs/azure-loadbalancer.md, docs/cloud-provider-config.md
>
> /kind bug
> /kind design
> /kind flake
Update documents for new options and add versions information for service annotations.
Fixes #138 #137 #122
```
NONE
```
=> Update documents for new options

docs/e2e-tests.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
NONE
```
=> Added several missing steps in docs/e2e-tests.md

tests/e2e/utils/service_utils.go, tests/k8s-azure/manifest/linux-vmss-serial.json
Add config manifest for serial e2e test.
```
None
```
=> Add config manifest for serial e2e test.

tests/e2e/network/ensureloadbalancer.go
Add some log info to gain insight into some failure cases.
/sig testing
```
None
```
=> Add some log info to gain insight into some failure cases.

tests/e2e/network/network_security_group.go
Add case for testing service annotation `ServiceAnnotationAllowedServiceTag`
Fixes #185 
```
None
```
/sig testing
=> Add case for testing service annotation `ServiceAnnotationAllowedServiceTag`

tests/e2e/network/cross_rg_nodes.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/functions.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/resource_group_utils.go
Enable e2e test for cross groups nodes.
Fixes #177 
```
None
```
=> Enable e2e test for cross groups nodes.

tests/e2e/network/cross_rg_nodes.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/network_interface_utils.go
Add test cases for standard load balancer.
Partly fixes issue https://github.com/kubernetes/cloud-provider-azure/issues/181
```
None
```
=> Add test cases for standard load balancer.

docs/cloud-provider-config.md
Add docs for two cloud configurations.
```
None
```
=> Add docs for two cloud configurations.

docs/azure-loadbalancer.md
Add corresponding information for newly added service annotation `service.beta.kubernetes.io/azure-load-balancer-pip-name` in doc.
```
None.
```
=> Add corresponding information for newly added annotation in doc.

cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-controller-manager/app/options/options_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Limit --concurrent-service-syncs to 1 to avoid parallel operations on Azure Load Balancer client.
Fixes #249
Related issue: https://github.com/kubernetes/kubernetes/issues/84052
```
Limit --concurrent-service-syncs to 1 to avoid parallel operations on Azure Load Balancer client.
```
=> Limit --concurrent-service-syncs to 1

hack/log-dump/log-dump.sh
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Convert json-based logs to slightly more human-readable logs.
Convert logs from
```json
{"log":"I1023 16:42:02.680863       1 flags.go:33] FLAG: --add-dir-header=\"false\"\n","stream":"stderr","time":"2019-10-23T16:42:02.681030225Z"}
{"log":"I1023 16:42:02.681103       1 flags.go:33] FLAG: --address=\"0.0.0.0\"\n","stream":"stderr","time":"2019-10-23T16:42:02.682702607Z"}
{"log":"I1023 16:42:02.681115       1 flags.go:33] FLAG: …
```
=> Convert json-based logs to slightly more human-readable logs

Makefile, cloudbuild.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Add makefile rules to push images to gcr staging repo.
Fixes #https://github.com/kubernetes-sigs/cloud-provider-azure/issues/233
```
Add makefile rules to push images to gcr staging repo.
```
=> Add makefile rules to push images to gcr staging repo.

Makefile
>
> /kind bug
> /kind design
> /kind flake
Add build-images and push-images targets, which is required for test job `post-provider-azure-push-images`.
Refer the build logs [here](https://storage.googleapis.com/kubernetes-jenkins/logs/post-provider-azure-push-images/1210164482425229312/artifacts/build.log):
```sh
IMAGE_REGISTRY=gcr.io/k8s-staging-provider-azure make build-images push-images
make[1]: Entering directory '/workspace'
fatal: not a git repository (or any parent up to mount point …
```
=> Add build-images and push-images targets

tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go
>
> /kind bug
> /kind design
> /kind flake
The job fails sometimes because the test case assumes a scale-down operation from 3 nodes to 2 nodes. However, kube-system pods are occasionally all scheduled to one worker nodes, causing 2 out of the 3 nodes to be eligible for removal. E.g.
```
cluster.go:107] Fast evaluation: node k8s-agentpool1-12501402-vmss000000 cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: …
```
=> Fixes flakiness in cloud-provider-azure-autoscaling job

tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go
>
> /kind bug
> /kind design
> /kind flake
In `GetAvailableNodeCapacity()`, we should check whether a pod is in a schedulable node instead of master node. It looks like the function could include some pods that are from nodes that are in the process of being eliminated by a previous test case, causing it to return a higher-than-expected number and scale-up is not being triggered in the next test case. This only happens when `should scale up or down if deployment replicas leave nodes busy or idle` scaled down …
=> test: fix flaky autoscaler e2e test

docs/cloud-provider-config.md
Add document of "use network resources in different AAD Tenant and Subscription" feature. 
None.
None.
```
Add document of "use network resources in different AAD Tenant and Subscription" feature. 
```
=> Add document of "use network resources in different AAD Tenant and Subscription" feature.

tests/e2e/network/network_security_group.go
>
> /kind bug
> /kind design
> /kind flake
Fixes the following error:
```
2020-02-29T02:31:03.2173802Z Network security group
2020-02-29T02:31:03.2175059Z [90m/home/azureuser/agent_5/_work/28/s/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/network_security_group.go:39[0m
2020-02-29T02:31:03.2175815Z   can share a rule for multiple services
2020-02-29T02:31:03.2177370Z   [90m/home/azureuser/agent_5/_work/28/s/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/network_security_group.go:137 …
```
=> test: prevent nil pointer dereference in nsg test case

WORKSPACE, go.sum, vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-07-01/compute/virtualmachinesizes.go, vendor/golang.org/x/crypto/ed25519/BUILD.bazel
/kind bug
Currently `make bazel-build` fails with:
```
$ make bazel-build
bazel build //cmd/cloud-controller-manager
ERROR: /Users/me/go/src/sigs.k8s.io/cloud-provider-azure/vendor/golang.org/x/crypto/ed25519/BUILD.bazel:3:1: no such package 'vendor/crypto/ed25519': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
- /Users/me/go/src/sigs.k8s.io/cloud-provider-azure/vendor/crypto/ed25519 and referenced by '//vendor/golang.org/x/crypto/ed25519:go_default_library'
ERROR: Analysis of target '//cmd/cloud-controller-manager:cloud-controller-manager' failed; build aborted: no such package 'vendor/crypto/ed25519': BUILD file not found in any of the following …
```
=> Fix 'make bazel-build'

docs/cloud-provider-config.md
Adds doc for current default rate limit config used for AKS and AKS-Engine clusters. This gives users a base to use when they bootstrap clusters with azure provider outside of AKS or AKS-Engine.
Fixes #
```
NONE
```
/cc @craiglpeters
=> docs: add current default rate limit config

hack/log-dump/log-dump.sh, tests/e2e/e2e_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes test regression (https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-autoscaling) introduced by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/345.
```
None
```
=> fix: fix autoscaling job

tests/e2e/autoscaling/autoscaler.go, tests/e2e/network/node.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/pod_utils.go, tests/e2e/utils/utils.go, tests/e2e/utils/vmss_utils.go, tests/k8s-azure/manifest/linux.json
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add several E2E cases for cluster autoscaler, which includes:
- scale multiple node groups together with `--balance-node-groups=true`
- scale single node group slowly
- scale multiple node groups quickly
- scale Spot VMSS
- scale node groups with GPU consumptions
Fixes #
```
NONE
```
=> Increase the e2e test coverage for cluster autoscaler

tests/k8s-azure/manifest/linux-autoscaler.json
>
/kind bug
> /kind design
> /kind flake
Increase agentpool max size to prevent [autoscaling e2e job](https://k8s-testgrid.appspot.com/provider-azure-cloud-provider-azure#cloud-provider-azure-autoscaling) from failing. 
Fixes #
```
NONE
```
=> Increase agentpool max size

tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
>
/kind bug
> /kind design
> /kind flake
In basic LB e2e tests, newly created subnets may not be deleted correctly for some reason, this pr ensures the subnet is deleted after moving forward. Also refactoring some test cases.
Fixes #
```
NONE
```
=> Ensure subnet is deleted

tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/pod_utils.go
>
/kind bug
> /kind design
> /kind flake
Ensure the pods are ready before creating new pods. Fix test failure https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-autoscaling-multipool.
Fixes #
```
NONE
```
=> Ensure the pods are ready before creating new pods

cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-node-manager/app/options/options.go
>
/kind bug
> /kind design
> /kind flake
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly.
Fixes #
```
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly
```
=> Ignore in-cluster config when --master or --kubeconfig is set explicitly

cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-node-manager/app/options/options.go
(cherry picked from commit 4bcb6fd846d31b19dcb73faace39b8502be57e8d)
>
/kind bug
> /kind design
> /kind flake
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly.
Fixes #
```
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly
```
=> Cherry pick of #397 to release 0.5: Ignore in-cluster config when --master or --kubeconfig is set explicitly

cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-node-manager/app/options/options.go
>
/kind bug
> /kind design
> /kind flake
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly.
Fixes #
```
Ignore in-cluster config when `--master` or `--kubeconfig` is set explicitly
```
=> Cherry pick of #397 to release 0.6: Ignore in-cluster config when --master or --kubeconfig is set explicitly

site/content/en/install/configs.md
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
cleanup: remove the duplicated options loadBalancerResourceGroup and loadBalancerName.
Fixes #
```
NONE
```
=> cleanup: remove the duplicated options loadBalancerResourceGroup and loadBalancerName

tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json, tests/k8s-azure/manifest/linux-autoscaler.json, tests/k8s-azure/manifest/linux-vmss-basic-lb.json, tests/k8s-azure/manifest/linux-vmss.json, tests/k8s-azure/manifest/linux.json
>
> /kind bug
> /kind design
> /kind flake
The aks-engine turns on managed identity by default, but the managed identity only affects the current resource group. Ref: https://github.com/Azure/aks-engine/blob/master/pkg/engine/roleassignments.go#L35. We need to disable it in the test jobs including cases where multiple resource groups are needed.
Fixes #
```
NONE
```
=> disable managed identity in azure e2e tests

hack/test-unit.sh, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
When the mode selection annotation is set to auto mode, the VMSS name would be nil because of the wrong return parameter in `scaleSet.GetVMSetNames`. This PR fixes it.
Fixes #
```
Fix nil VMSS name when setting service to auto mode
```
=> Fix nil VMSS name when setting service to auto mode

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The current `nicIDRE` is too restrictive to allow manual installations. We modify it to use the `network.Interface.VirtualMachines.ID` to determine the corresponding VM.
Fixes https://github.com/kubernetes/kubernetes/issues/97352
Fixes https://github.com/kubernetes/kubernetes/issues/97375
```
Use network.Interface.VirtualMachine.ID to get the VM
```
=> Use network.Interface.VirtualMachine.ID to get the VM

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_standard.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Skip standalone VM when reconciling LoadBalancer as there is no availabilitySet for those VMs.
Fixes #
```
Skip standalone VM when reconciling LoadBalancer
```
=> Skip standalone VM when reconciling LoadBalancer

pkg/azureclients/diskclient/interface.go, pkg/provider/azure_managedDiskController.go
/kind feature
Add LogicalSectorSize as a parameter so that azuredisk-csi can utilize it to set the logicalSectorSize for ultraSSD
related to : https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/559
Fixes #
```
none
```
=> feat: Add LogicalSectorSize support for UltraSSD

pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Cleanup subnet in frontend IP configs to prevent huge subnet request bodies in some scenarios.
Fixes #
```
Cleanup subnet in frontend IP configs to prevent huge subnet request bodies in some scenarios.
```
=> Cleanup subnet in frontend IP configs

pkg/azureclients/interfaceclient/azure_interfaceclient.go, pkg/azureclients/interfaceclient/azure_interfaceclient_test.go, pkg/azureclients/interfaceclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Interface client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: interface client changes for Azure Stack Hub support

pkg/provider/azure_vmss.go
>
/kind bug
> /kind design
> /kind flake
The error that shows up in the logs when vmss fails to update is not the error from the PUT, but rather the error from the previous `ss.getVMSS(vmssName, azcache.CacheReadTypeDefault)`. This is _very_ misleading.
```
Output the actual error when VMSS PUT fails rather than the error from the previous GET
```
=> output rerr to log rather than previous err from GET

pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/azure_vmssclient_test.go, pkg/azureclients/vmssclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
VMSS client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: vmss client changes for Azure Stack Hub support

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/azureclients/vmssvmclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
VMSS VM client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: vmss vm client changes for Azure Stack Hub support

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
VM client changes for Azure Stack Hub support.
Fixes #
```
feat: vm client changes for Azure Stack Hub support
```
=> feat: vm client changes for Azure Stack Hub support

pkg/azureclients/diskclient/azure_diskclient.go, pkg/azureclients/diskclient/azure_diskclient_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Disk client test changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: disk client changes for Azure Stack Hub support

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Aggregate errors when putting vmss, so the failure of the previous update would not interrupt the next ones.
Fixes #481
```
aggregate errors when putting vmss
```
=> Aggregate errors when putting vmss

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Add service annotation `ServiceAnnotationDenyAllExpectSourceRanges`.
Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/374
1. This annotation only works when the `service.Spec.LoadBalancerSourceRanges` is set.
2. It creates a security rule with the name `a<service-uid>-<service-protocol>-<port>-deny_all`, which denies all traffic to the service.
3. The priority of …
=> feat: Add service annotation `ServiceAnnotationDenyAllExpectSourceRanges`

pkg/azureclients/vmsizeclient/azure_vmsizeclient.go, pkg/azureclients/vmsizeclient/azure_vmsizeclient_test.go, pkg/azureclients/vmsizeclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
VM size client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: vm size client changes for Azure Stack Hub support

pkg/azureclients/subnetclient/azure_subnetclient.go, pkg/azureclients/subnetclient/azure_subnetclient_test.go, pkg/azureclients/subnetclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Subnet client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: subnet client changes for Azure Stack Hub support

site/content/en/topics/loadbalancer.md
>
> /kind bug
> /kind design
> /kind flake
Add doc for the service annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`
Fixes #
```
NONE
```
=> doc: add doc for the service annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`

pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go, pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go, pkg/azureclients/loadbalancerclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Load balancer client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: load balancerclient changes for Azure Stack Hub support

pkg/azureclients/storageaccountclient/azure_storageaccountclient.go, pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Storage account client test changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: storage account client test changes for Azure Stack Hub support

pkg/azureclients/securitygroupclient/azure_securitygroupclient.go, pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go, pkg/azureclients/securitygroupclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Security group client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: security group client changes for Azure Stack Hub support

pkg/azureclients/routeclient/azure_routeclient.go, pkg/azureclients/routeclient/azure_routeclient_test.go, pkg/azureclients/routeclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Route client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: route client changes for Azure Stack Hub support

pkg/azureclients/routetableclient/azure_routetableclient.go, pkg/azureclients/routetableclient/azure_routetableclient_test.go, pkg/azureclients/routetableclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Route table client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: route table client changes for Azure Stack Hub support

pkg/azureclients/snapshotclient/azure_snapshotclient.go, pkg/azureclients/snapshotclient/azure_snapshotclient_test.go, pkg/azureclients/snapshotclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Snapshot client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: snapshot client changes for Azure Stack Hub support

pkg/azureclients/publicipclient/azure_publicipclient.go, pkg/azureclients/publicipclient/azure_publicipclient_test.go, pkg/azureclients/publicipclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Public IP client changes for Azure Stack Hub support.
Fixes #
```
none
```
=> feat: public ip client changes for Azure Stack Hub support

hack/deploy-cluster.sh
/kind bug
`make deploy` fails and you can't deploy the test cluster.
Makes two fixes to deploy-cluster.sh. First is just a syntax error. The second is using the install scripts for Disk and File plugins that is recommended by the plugin owners. 
```
Fixes to deploy-cluster.sh
```
=> Deploy cluster script fix

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind feature
Adds extended location to the cloud config. 
If extended location is provided and a service is created, the corresponding slb and public ip are deployed with extended location.
```
Adds extended location to the cloud config. 
If extended location is provided and a service is created, the corresponding slb and public ip are deployed with extended location.
```
=> Made load balancer and public ip extended location aware.

pkg/azureclients/azure_client_config.go, pkg/azureclients/diskclient/azure_diskclient.go, pkg/azureclients/interfaceclient/azure_interfaceclient.go, pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go, pkg/azureclients/publicipclient/azure_publicipclient.go, pkg/azureclients/routeclient/azure_routeclient.go, pkg/azureclients/routetableclient/azure_routetableclient.go, pkg/azureclients/securitygroupclient/azure_securitygroupclient.go, pkg/azureclients/snapshotclient/azure_snapshotclient.go, pkg/azureclients/storageaccountclient/azure_storageaccountclient.go, pkg/azureclients/subnetclient/azure_subnetclient.go, pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmsizeclient/azure_vmsizeclient.go, pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/provider/azure.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
When using AzureStackCloud config on the public cloud to customize ARM endpoints, the API versions for AzureStackCloud would be too old for public Cloud environment. Hence, this PR adds another new cloud config option `DisableAzureStackCloud` to allow disable AzureStackCloud API versions.
Refer https://github.com/Azure/AKS/issues/2148#issuecomment-786972895.
The issue only happens on …
=> Allow disabling AzureStackCloud API versions when using AzureStackCloud config on public cloud

.golangci.yml, pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
**What this PR does / why we need it**: Fix code and enable gocyclo linter. Follow up from #518.
```
pkg/provider/azure_loadbalancer.go:1231:1: cyclomatic complexity 76 of func `(*Cloud).reconcileLoadBalancer` is high (> 30) (gocyclo)
func (az *Cloud) reconcileLoadBalancer(clusterName string, service *v1.Service, nodes []*v1.Node, wantLb bool) (*network.LoadBalancer, error) {
^
pkg/provider/azure_loadbalancer.go:1857:1: cyclomatic complexity 56 of func …
```
=> enable gocyclo linter

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
When highAvailabilityPorts enabled, the LoadBalancer port is always using 0, hence only one rule should be configured.
Fixes #521 
```
Ensure only LoadBalancer rule is created when HA mode is enabled
```
=> Ensure only LoadBalancer rule is created when HA mode is enabled

cmd/cloud-node-manager/app/config/config.go, cmd/cloud-node-manager/app/nodemanager.go, cmd/cloud-node-manager/app/options/options.go, pkg/nodemanager/nodemanager.go, pkg/provider/azure.go, pkg/provider/azure_routes.go
>
/kind bug
> /kind design
> /kind flake
When using kubenet network plugin together with cluster-autoscaler, new Pods scheduled to newly created node would get DNS resolution failure.
After talking with Azure Networking team, we confirmed this is because the route updates haven't take effect yet when the async updating returns success.
Since there's no API exposed to check whether routes take effect or not, this PR adds a delay after route updating requests (defautl is 30s). It also adds a new configuration …
=> Route updates wait a while for new routes to take effect

pkg/provider/azure.go, pkg/provider/azure_instance_metadata.go, pkg/provider/azure_instances_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
When VM or VMSS is bounded with "standard" LoadBalancer, the instance's public IP address would not be part of http://169.254.169.254/metadata/instance. Hence, kubectl get nodes would not show public IP address when using "standard" LoadBalancer.
This PR fixes the issue by fetching public IP from IMDS loadbalancer endpoint `http://169.254.169.254/metadata/loadbalancer `.
Fixes #535 …
=> Fix node public IP fetching from instance metadata service

Makefile, pkg/provider/azure.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
**What this PR does / why we need it**:  This fixes a bug affecting clusters with virtual machines when vmType is set to "vmss". What happens is the control manager comes online and queries for azure machines power status. Since the machines are not available yet they are not in the cache. When the request comes in for the load balancer the cache is queried and reports that the node does not exist as a VMAS and attempts to run the VMSS code hence the following error message: `failed: not a vmss …
=> Fix availability set cache in vmss cache

pkg/provider/azure_vmss.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
**What this PR does / why we need it**: This fixes an issue with UpdateLoadBalancer where if a new VMAS node joins a cluster in "vmss" vmType, UpdateLoadBalancer fails with "not a vmss instance". Instead, getting the nodeName via VMAS which allows the reconcile LB to proceed and the node does get added successfully.
To repro: add expose a service type load balancer, then add a node of type VM and watch UpdateLoadBalancer fail.
Fixes #
**Special notes for your …
=> Fix: ignore not a VMSS error for VMAS nodes in reconcileBackendPools

tests/e2e/network/standard_lb.go
>
> /kind bug
> /kind design
> /kind flake
fix: convert backend pool id to lower case before using it
Fixes #
```
fix: convert backend pool id to lower case before using it
```
=> fix: convert backend pool id to lower case before using it

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind bug
fix: check disk state before attach disk
Should check both diskState and ManagedBy field before attach disk
Fixes #
```
fix: check disk state before attach disk
```
/hold
=> fix: check disk state before attach disk

pkg/provider/azure_routes.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fix: avoid panic when RouteTablePropertiesFormat is nil.
Fixes #550 
```
Fix: avoid panic when RouteTablePropertiesFormat is nil
```
=> Fix: avoid panic when RouteTablePropertiesFormat is nil

tests/k8s-azure/manifest/kubernetes.json, tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
Signed-off-by: Ernest Wong <chuwon@microsoft.com>
>
> /kind bug
> /kind design
> /kind flake
With https://github.com/Azure/aks-engine/pull/4262, it should have the correct default value for the `--service-account-issuer` flag.
/kind failing-testing
/assign @feiskyer 
Fixes #
```
```
=> api-model: remove --service-account-issuer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The user-created services could be deleted accidentally because we delete the pip by checking if the service tags on it are empty. This fix solves the issue by not tagging the user-created pips.
Fixes #573
```
fix: not delete existing pip when service is deleted
```
=> fix: not delete existing pip when service is deleted

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json, tests/k8s-azure/manifest/linux-ipv6.json
Using `ubuntu` distro doesn't honor `runUnattendedUpgradesOnBootstrap: false` and the nodes get rebooted. This causes the API server reachability tests to fail for dual-stack. Switching to use `aks-ubuntu-16.04` instead.
Fixes #
```
NONE
```
=> chore: use aks-ubuntu-16.04 distro for dual-stack and ipv6

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
This PR enables multiple vmSets sharing the primary SLB. To do this, we need to:
1. turn on the multiple slbs mode;
2. store the vmSet names that share the primary SLB to a new cloud config `nodePoolsWithoutDedicatedSLB ` (comma separated).
Note that when switching from dedicated slb to shared slb, the service frontend IP configs would be moved to the primary slb as well, even if there is a mode annotation that selects the original non-primary vmSet. …
=> feat: support sharing the primary slb with multiple vmSets

pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Because VMSS network interface handling has some delay on creation time. when cloud provider gets the VMSS instances list, the instances in creating state may still have their network profile nil and hence cause issues in cloud provider. The issue could only be resolved after the cache TTL expires (default TTL is 10m).
This PR fixes this issue by not caching such VMSS instances whose network profile is nil.
Fixes #582 …
=> Avoid caching the VMSS instances whose network profile is nil

pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Ensure service deleted when the Azure resource group has been deleted.
Cherry-picking upstream fix https://github.com/kubernetes/kubernetes/pull/100944.
```
Ensure service deleted when the Azure resource group has been deleted
```
=> Ensure service deleted when the Azure resource group has been deleted

tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json, tests/k8s-azure/manifest/linux-autoscaler.json
>
> /kind bug
> /kind design
> /kind flake
Disable blobfuse-flexvolume addon in tests.
Related to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/581. Let's check whether this could help.
```
NONE
```
=> Disable blobfuse-flexvolume addon in tests

pkg/node/node.go, pkg/node/nodearm.go, pkg/nodemanager/mock/mock_node_provider.go, pkg/nodemanager/nodemanager.go
>
/kind bug
> /kind design
> /kind flake
PR fixes an issue on cloud node manager initialization of Windows nodes through ARM. Host name of the node manager Windows container is not equal to the node name, thus zone initialization cannot use the OS host name thus requires passing the node name as a parameter.
Fixes #
```
fix: arm node provider Windows initialization
```
=> fix: arm node provider Windows initialization

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #596
```
fix: call the counterpart function of availabilitySet when the instance is not a vmss vm
```
=> fix: call the counterpart function of availabilitySet when the instance is not a vmss vm

pkg/azureclients/containerserviceclient/azure_containerserviceclient.go, pkg/azureclients/deploymentclient/azure_deploymentclient.go, pkg/azureclients/diskclient/azure_diskclient.go, pkg/azureclients/interfaceclient/azure_interfaceclient.go, pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go, pkg/azureclients/publicipclient/azure_publicipclient.go, pkg/azureclients/routeclient/azure_routeclient.go, pkg/azureclients/routetableclient/azure_routetableclient.go, pkg/azureclients/securitygroupclient/azure_securitygroupclient.go, pkg/azureclients/snapshotclient/azure_snapshotclient.go, pkg/azureclients/storageaccountclient/azure_storageaccountclient.go, pkg/azureclients/subnetclient/azure_subnetclient.go, pkg/azureclients/vmasclient/azure_vmasclient.go, pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmsizeclient/azure_vmsizeclient.go, pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: only logs rate limiting configurations when rate limit is enabled.
Close #605 
```
chore: only logs rate limiting configurations when rate limit is enabled
```
=> chore: only logs rate limiting configurations when rate limit is enabled

pkg/provider/azure_storageaccount.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes : https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/436
```
feat: Enable creation of storage accounts that support large file shares
```
=> feat: Enable creation of storage accounts that support large file shares

pkg/provider/azure.go
/kind bug
Without this fix, managed disk provisioning in edge zone fails.
Fixes #
```
Bug fix for edge zone managed disk provisioning.
```
=> Edge zone managed disk bug fix.

hack/deploy-cluster.sh, site/content/en/development/e2e/e2e-tests-azure.md, site/content/en/development/e2e/e2e-tests.md, tests/e2e/job/test_in_cluster_job.yaml, tests/e2e/utils/azure_auth.go, tests/kubemark/build-kubemark.sh
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Following up on kubernetes-sigs/azurefile-csi-driver#459.
cloud-provider-azure e2e uses different environment variable names than everything else (https://github.com/kubernetes-sigs/cloud-provider-azure/blob/83ec139e2224561e12e896c483b31cb08ad351a2/site/content/en/development/e2e/e2e-tests-azure.md). Updating kubetest to set the same environment variables for consistency. The new names are also slightly better syntactically IMO.
/hold until …
=> Rename E2E environment variables for consistency across projects

pkg/consts/consts.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, tests/e2e/e2e_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Made some changes to get the CCM test suite to pass with a CAPZ built clusters. Tested using the `pull-cloud-provider-azure-e2e-ccm-capz` job.
Fixes #
```
NONE
```
=> Fix e2e tests to work with CAPZ

cmd/cloud-controller-manager/app/config/config.go, cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/app/dynamic/watch_secret.go, cmd/cloud-controller-manager/app/options/dynamic.go, cmd/cloud-controller-manager/app/options/options.go, cmd/cloud-controller-manager/app/options/options_test.go, cmd/cloud-controller-manager/app/testing/testserver.go, pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_config.go, pkg/provider/azure_config_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
This PR enables reloading ccm from secret dynamically.
There are two ways to build a ccm: statically build from cloud-config file or dynamically build from secret.
To use the cloud-config file, set `--enable-dynamic-reloading=false` and `--cloud-config` to an non-empty value. To use the secret, set `--enable-dynamic-reloading=true`, `--cloud-config-secret-name`, `--cloud-config-secret-namespace` and `--cloud-config-key`. In this way, the ccm would be …
=> feat: support reloading cloud controller manager from secret dynamically

pkg/provider/azure_standard.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: avoid nil-pointer panic when checking the frontend IP configuration. This is needed when the fip config is not bound to an public IP.
Fixes #
```
fix: avoid nil-pointer panic when checking the frontend IP configuration
```
=> fix: avoid nil-pointer panic when checking the frontend IP configuration

pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go, pkg/azureclients/loadbalancerclient/azure_loadbalancerclient_test.go, pkg/azureclients/loadbalancerclient/interface.go, pkg/azureclients/loadbalancerclient/mockloadbalancerclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
Add CreateOrUpdateBackendPools() interface for LoadBalancer client.
Fixes #619
```
Add CreateOrUpdateBackendPools() interface for LoadBalancer client
```
=> Add CreateOrUpdateBackendPools() interface for LoadBalancer client

pkg/provider/azure_controller_common.go
/kind bug
fix: reduce crp throttling in attach disk scenario
original `CacheReadTypeForceRefresh` is not necessary since once attach/detach completed, cache is already cleaned, this operation could clean cache for every disk attach, finally cause crp throttling, e.g.
```
I0508 05:26:08.763336       1 utils.go:95] GRPC call: /csi.v1.Controller/ControllerPublishVolume
I0508 05:26:08.763360       1 utils.go:96] GRPC request: {"node_id":"aks-agentpool-15002531-vmss000000","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"skuname":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1620324123891-8081-disk.csi.azure.com"},"volume_id":"/subscriptions/xxx/res …
```
=> fix: reduce crp throttling in attach disk scenario

pkg/provider/azure_managedDiskController.go
/kind bug
fix: delete non existing disk issue
- delete non existing disk should return success
- if `GetDisk` is throttled, should  wait 3s for disk creation complete(3s is the common time cost of creating a disk)
Fixes #
```
I0510 01:40:12.833561       1 utils.go:95] GRPC call: /csi.v1.Controller/DeleteVolume
I0510 01:40:12.833580       1 utils.go:96] GRPC request: {"volume_id":"/subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Microsoft.Compute/disks/pvc-66e17d3e-efc2-4758-9582-1b0728dfe3c1"}
I0510 01:40:12.833646       1 controllerserver.go:376] deleting azure disk(/subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Microsoft …
```
=> fix: delete non existing disk issue

pkg/provider/azure_managedDiskController.go
/kind bug
fix: no sleep when GetDisk is throttled
it's not necessary to sleep 3s when GetDisk is throttled since `DisksClient.CreateOrUpdate` already returned, which means disk is actually created.
Fixes #
```
fix: no sleep when GetDisk is throttled
```
=> fix: no sleep when GetDisk is throttled

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go
/kind cleanup
> // TODO(feiskyer): disable-tcp-reset annotations has been depracated since v1.18, it would removed on v1.20.
kubernetes/kubernetes#101898
Fixes #
/hold 
need k/k merged first
```
NONE
```
=> Remove azure disable-tcp-reset annotations

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
Since the VMSS and instances are cached in memory (default TTL is 10 min), if there're some changes on the VMSS capacity (e.g. by autoscaler), then the capacity value would be outdated in memory. However, cloud provider sets vmss.Sku when updating network profile, which may cause unexpected capacity change on VMSS.
This PR fixes the issue by not setting vmss.Sku when updating VMSS/instances data model.
Fixes #
```
Do not set cached Sku when updating VMSS and VMSS instances
```
=> Do not set cached Sku when updating VMSS and VMSS instances

site/content/en/topics/tagging-resources.md, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: add e2e test for byo public IP
Fixes #618
```
chore: add e2e test for byo public IP
```
=> chore: add e2e test for byo public IP

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json, tests/k8s-azure/manifest/linux-ipv6.json
aks-engine sets the `--service-account-issuer` flag by default for 1.20+ (as it's mandatory). For 1.19 this isn't required and setting just the `--service-account-issuer` flag without the `--service-account-signing-key-file` for older k8s versions results in an error. Removing the explicit `--service-account-issuer` key from the api model to fallback on aks-engine defaulting.
```bash
Error: --service-account-signing-key-file, --service-account-issuer, and --api-audiences should be specified together
```
Fixes dual-stack …
=> fix: remove --service-account-issuer from api model

pkg/provider/azure_standard.go
>
> /kind bug
> /kind design
Fixes #648
```
fix: serviceOwnsFrontendIP shouldn't report error when the public IP doesn't match
```
=> serviceOwnsFrontendIP shouldn't report error when the public IP doesn't match

cmd/cloud-controller-manager/app/controllermanager.go, pkg/node/node.go, pkg/node/nodearm.go, pkg/provider/azure.go, pkg/provider/azure_config.go, pkg/provider/azure_config_test.go, pkg/provider/azure_test.go, pkg/provider/azure_zones.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
1. Log detailed error messages in `syncRegionZonesMap`;
2. Wait for the initial run of `syncRegionZonesMap` to be successful.
3. Disable the zone sync operation in cnm, only enable it in ccm.
Fixes #640
```
fix: wait for the success of the initial run of syncRegionZonesMap
```
=> fix: wait for the success of the initial run of syncRegionZonesMap

cmd/cloud-controller-manager/app/controllermanager.go, pkg/node/node.go, pkg/node/nodearm.go, pkg/provider/azure.go, pkg/provider/azure_config.go, pkg/provider/azure_config_test.go, pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_test.go, pkg/provider/azure_zones.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
cherry-pick #646 and #661 to release-1.0.
Fixes #
```
wait for the success of the initial run of syncRegionZonesMap and ensure outdated routes are cleanup when dualstack is enabled
```
=> cherry-pick #646 and #661 to release-1.0

cmd/cloud-controller-manager/app/options/dynamic.go, cmd/cloud-controller-manager/app/options/options_test.go, pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_config_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: set default config secret name and namespace
Fixes #
```
chore: set default config secret name and namespace
```
=> chore: set default config secret name and namespace

pkg/auth/azure_auth.go, pkg/auth/azure_auth_test.go, pkg/provider/azure.go
/kind cleanup
chore: add resource param into GetServicePrincipalToken
CSI driver needs to change `resource` parameter as keyvault endpoint to read from keyvault, make `GetServicePrincipalToken` more generic.
Fixes #
related to https://github.com/kubernetes-sigs/blob-csi-driver/pull/460
```
none
```
=> chore: add resource param into GetServicePrincipalToken

site/content/en/install/configs.md
Add `securityGroupResourceGroup` cloud config value in the documentation.
```
docs: add 'securityGroupResourceGroup' cloud-config value
```
=> docs: add securityGroupResourceGroup cloud config value

pkg/provider/azure.go
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
chore: only reconciling routes in cloud controller manager
Fixes #654
```
chore: only reconciling routes in cloud controller manager
```
=> chore: only reconciling routes in cloud controller manager

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: make tags case-insensitive for both keys and values
Fixes #658
```
fix: make tags case-insensitive for both keys and values
```
=> fix: make tags case-insensitive for both keys and values

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: make tags case-insensitive for both keys and values.
Fixes #
```
fix: make tags case-insensitive for both keys and values
```
=> cherry-pick of #669: make tags case-insensitive for both keys and values

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind bug
fix: remove GetDisk operation in AttachDisk
This is actually one GetDisk operation in CSI driver AttachDisk interface, this PR removes GetDisk operation to reduce potential GetDisk throttling issue in large amount of disk attachment scenario.
And also retry immediately in DetachDisk is actually not necessary since CSI driver would retry if Detach failed in an outer looper, this could make things worse when there is throttling issue.
Fixes #
```
fix: remove GetDisk operation in AttachDisk
```
=> fix: remove GetDisk operation in AttachDisk

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The availabilitySet ID of the VM would be an empty string when using standalone VMs. `getAvailabilitySetNameByID ` should also return empty string in this scenario.
Fixes https://github.com/kubernetes/kubernetes/issues/103085
```
fix: return empty VMAS name if using standalone VM
```
=> fix: return empty VMAS name if using standalone VM

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
>
> /kind bug
> /kind design
> /kind flake
Not proactively set the default probe path for non HTTP or HTTPS probes.
Fixes https://github.com/kubernetes/kubernetes/issues/102803
```
fix: leave the probe path empty for TCP probes
```
=> fix: leave the probe path empty for TCP probes

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
(cherry picked from commit d37fa6c750e255e0dc0570119ed5e8376f8bd5fb)
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Cherry pick of #680: fix: leave the probe path empty for TCP probes
Fixes #
```
Cherry pick of #680: fix: leave the probe path empty for TCP probes
```
=> Cherry pick of #680: fix: leave the probe path empty for TCP probes

pkg/provider/azure_fakes.go
/kind cleanup
>
> /kind bug
> /kind design
> /kind flake
This PR changes the `GetTestCloud` function to call `initDiskControllers` instead of (incompletely) initializing the disk controllers directly. This way, the disk controller methods like `AttachDisk` and `DetachDisk` can be used in unit tests and mocked.
```
`GetTestCloud` properly initializes the disk controller fields enabling them to be used in unit tests and …
```
=> chore: Call initDiskControllers() in GetTestCloud()

pkg/provider/azure_controller_common_test.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_instances_test.go
/kind bug
fix: detach disk panic on Azure Stack
e2e tests already passes on https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/909
Fixes #684
```
fix: detach disk panic on Azure Stack
```
=> fix: detach disk panic on Azure Stack

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
cherry-pick of #691: add support for additional public IPs via service annotations
Fixes #
```
feat: add support for additional public IPs via service annotations
```
=> cherry-pick of #691: add support for additional public IPs via service annotations

pkg/azureclients/publicipclient/azure_publicipclient.go, pkg/azureclients/publicipclient/azure_publicipclient_test.go, pkg/azureclients/publicipclient/interface.go, pkg/azureclients/publicipclient/mockpublicipclient/interface.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
feat: add ListAll interface for PublicIP client. It would be used to list all the public IPs in the subscription.
Fixes #
```
feat: add ListAll interface for PublicIP client
```
=> feat: add ListAll interface for PublicIP client

Makefile
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Add make help support. Here is a sample help message:
```
$  make help
Usage:
make <target>
General
help             Display this help.
Binaries
all              Build binaries for the project.
azure-cloud-node-manager  Build node-manager binary for Linux.
azure-cloud-node-manager.exe  Build node-manager binary for Windows.
azure-cloud-controller-manager  Build binary for controller-manager.
Images
docker-pull-prerequisites  Pull prerequisite images. …
```
=> chore: add make help

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Public IP creation for edge zones started failing recently because NRP doesn't allow `Availability Zones` to be provided as part of create request if it contains `extendedLocation`. This PR fixes that.
Fixes #
```
Not send availability zones as part of create for edge zones
```
=> Not send availability zones as part of create for edge zones.

pkg/provider/azure_loadbalancer.go
Signed-off-by: GitHub <noreply@github.com>
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #697
I'm happy to help further but I'm new to Go. I have tried to check the SDK version but from what I've heard it should be fine.
```
Feat: Provide IPv6 support for internal load balancer
```
=> feat: Provide IPv6 support for internal load balancer

pkg/provider/azure_loadbalancer.go
Signed-off-by: GitHub <noreply@github.com>
>
> /kind bug
> /kind design
> /kind flake
cherry-pick of #703 to 1.0: Provide IPv6 support for internal load balancer
Fixes #
```
Feat: Provide IPv6 support for internal load balancer
```
=> cherry-pick of #703 to 1.0: Provide IPv6 support for internal load balancer

pkg/retry/azure_retry.go, pkg/retry/azure_retry_test.go
>
/kind bug
> /kind design
> /kind flake
The sender decorator builds a local `Error` type that embeds the RawError returned from the Azure service. However, in the client's `sendRequest` method it wraps this error again under the `Error` type.
```
retry.GetError(response, err)
```
This would return a double-wrapped error the consumers:
```
Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: …
```
=> fix: avoid wrapping RawError twice

cmd/cloud-controller-manager/app/core.go, cmd/cloud-controller-manager/app/core_test.go, site/content/en/topics/ipam.md
>
> /kind bug
> /kind design
> /kind flake
/kind bug
The NodeCIDRMaskSize is set to 24 by default. This is bad when enabling dualstack and ipv4/ipv6 masks are not set explicitly. In this case the ipv4 and ipv6 masks will be set to 24, which may out of the range of the cluster cidr, especially for ipv6 cluster cidr whose default mask size is 64.
Fixes #
```
fix: ignore the NodeCIDRMaskSize in dualstack clusters
```
=> fix: ignore the NodeCIDRMaskSize in dualstack clusters

pkg/provider/azure_fakes.go
/kind cleanup
>
> /kind bug
> /kind design
> /kind flake
`GetTestCloud` now initializes the `SnapshotsClient` field to a mock implementation to facilitate unit test development for consuming projects.
```
`GetTestCloud` now initializes the `SnapshotsClient` field to a mock implementation to facilitate unit test development for consuming projects.
```
=> chore: Add mock SnapshotsClient to facilitate unit test development.

pkg/azureclients/containerserviceclient/azure_containerserviceclient.go, pkg/azureclients/deploymentclient/azure_deploymentclient.go, pkg/azureclients/diskclient/azure_diskclient.go, pkg/azureclients/interfaceclient/azure_interfaceclient.go, pkg/azureclients/loadbalancerclient/azure_loadbalancerclient.go, pkg/azureclients/publicipclient/azure_publicipclient.go, pkg/azureclients/routeclient/azure_routeclient.go, pkg/azureclients/routetableclient/azure_routetableclient.go, pkg/azureclients/securitygroupclient/azure_securitygroupclient.go, pkg/azureclients/snapshotclient/azure_snapshotclient.go, pkg/azureclients/storageaccountclient/azure_storageaccountclient.go, pkg/azureclients/subnetclient/azure_subnetclient.go, pkg/azureclients/vmasclient/azure_vmasclient.go, pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmsizeclient/azure_vmsizeclient.go, pkg/azureclients/vmssclient/azure_vmssclient.go, pkg/azureclients/vmssclient/azure_vmssclient_test.go, pkg/azureclients/vmssclient/interface.go, pkg/azureclients/vmssclient/mockvmssclient/interface.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/metrics/azure_metrics.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/retry/azure_error.go, pkg/retry/azure_error_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
This adds a more detailed "Code" label to the azure API errors metrics which is useful to classify the reason behind failed calls. For example, Quota, SubnetExhaustion, etc.
This can help unlock certain auto-healing scenarios.
The PR also changes some existing parsing of an LB error to be more robust and build on the same pattern using `autorest.ServiceError` instead of duplicating the fields.
Fixes #
**Special notes for your …
=> Add a "code" dimension to the Azure API error metric

pkg/provider/azure.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Allows UserAgent to be passed through cloud provider configuration, which will allow for customer attribution
Fixes #
```
UserAgents can now be passed as part of the cloud provider config
```
=> Feat: Allow Useragent to be passed to client via config

cloudbuild.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
fix: increase cloud build timeout. 
Refer build failure logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-provider-azure-push-images/1427488367246839808
Fixes #
```
NONE
```
=> fix: increase cloud build timeout

pkg/consts/consts.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go, pkg/retry/azure_error.go, pkg/retry/azure_error_test.go
/kind bug
fix: ignore GetDisk throttling in DeleteDisk
Fixes #
```
1 controllerserver.go:378] delete azure disk(/subscriptions/xxx/resourceGroups/aks55h93-nodegroup/providers/Microsoft.Compute/disks/pvc-ecfefbb9-102c-4f40-944f-d5d4b6183568) returned with Retriable: true, RetryAfter: 0s, HTTPStatusCode: 0, RawError: azure cloud provider rate limited(read) for operation "GetDisk"
1 utils.go:100] GRPC error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: 0, RawError: azure cloud provider rate limited(read) for operation "GetDisk"
```
```
fix: ignore GetDisk throttling in DeleteDisk
```
=> fix: ignore GetDisk throttling in DeleteDisk

examples/aks-engine.json, tests/k8s-azure/manifest/autoscaler-virtual-kubelet.json, tests/k8s-azure/manifest/e2e-slow.json, tests/k8s-azure/manifest/linux-autoscaler-multi-nodepool.json, tests/k8s-azure/manifest/linux-autoscaler.json, tests/k8s-azure/manifest/linux-kcm.json, tests/k8s-azure/manifest/linux-vmss-basic-lb.json, tests/k8s-azure/manifest/linux-vmss-multi-zones.json, tests/k8s-azure/manifest/linux-vmss-serial.json, tests/k8s-azure/manifest/linux-vmss.json, tests/k8s-azure/manifest/linux.json, tests/kubemark/templates/external-cluster.json, tests/kubemark/templates/kubemark-cluster.json
Signed-off-by: Ernest Wong <chuwon@microsoft.com>
>
> /kind bug
> /kind design
> /kind flake
- Bump orchestrator release to 1.19 since 1.18 has reach end-of-life
- Remove all feature gates that are enabled by default (CSIInlineVolume, LocalStorageCapacityIsolation, ServiceNodeExclusion)
Fixes #
```
NONE
```
=> chore: bump orchestrator release to 1.19 and remove enabled feature gates

pkg/azureclients/armclient/azure_armclient.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: use correct gitVersion in userAgent. `sigs.k8s.io/cloud-provider-azure/pkg/version` should be used to get correct version.
The userAgent would be changed from `Go/go1.16.6 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v0.0.0-master+$Format:%H$` to `Go/go1.16.6 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v1.1.0` for release tag and `Go/go1.16.6 (amd64-linux) go-autorest/v14.2.1; …
=> fix: use correct gitVersion in userAgent

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind bug
fix: set back node level lock in disk detach
attach disk would depend on detach disk in pod failover between different nodes, original async disk detach would make some disk detach completion too soon, that would lead to more disk attach time cost and some internal error msg. This PR set back node level lock **only** in disk detach.
This PR also add `ctx context.Context` parameter in `AttachDisk` & `DetachDisk`
Fixes #
```console
v1.7.0 with sync detach
Events:
Type     Reason                  Age                From                     Message
----     ------                  ----               ----                     -------
Normal …
```
=> fix: set back node level lock in disk detach

pkg/provider/azure_blobDiskController.go, pkg/provider/azure_blobDiskController_test.go, pkg/provider/azure_storage.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: add AllowBlobPublicAccess setting in storage account creation
This PR also add `ctx context.Context` parameter in some functions.
Fixes #
```release-note
feat: add AllowBlobPublicAccess setting in storage account creation
```
```docs
feat: add AllowBlobPublicAccess setting in storage account creation
```
=> feat: add AllowBlobPublicAccess setting in storage account creation

pkg/provider/azure_blobDiskController.go, pkg/provider/azure_blobDiskController_test.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: support creating account if not exists when account name is provided
if `accountName` is provided, and `accountOptions.CreateAccount` is set as `true`(by default `false`), this PR would create account if not exists
Fixes #
/hold
```release-note
feat: support creating account if not exists when account name is provided
```
```docs
feat: support creating account if not exists when account name is provided
```
=> feat: support creating account if not exists when account name is provided

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix: ignore the case when comparing azure tags in service annotation
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/658
```release-note
fix: ignore the case when comparing azure tags in service annotation
```
```docs
```
=> fix: ignore the case when comparing azure tags in service annotation

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_vmss.go, pkg/provider/azure_wrap.go
/kind bug
fix: consolidate logs for instance not found error
- Ignore the instance not found error when cleaning up unwanted nodes from LB backend pool
- Log node name when "instance not found" errors happen
Fixes #789 
```release-note
fix: consolidate logs for instance not found error
```
```docs
```
=> fix: consolidate logs for instance not found error

pkg/provider/azure_vmss.go
/kind feature
feat: reduce vmss cache refresh in parallel disk attach/detach
This PR adds a lock in get vmss operation, in 1K disk attach/detach load test, it could reduce ~20%(67/338=20%) vmss cache refresh operations. It's not necessary to refresh cache every  time when nodeName is not found in vmss cache, especially in parallel workloads.
Fixes #
/hold
```release-note
feat: reduce vmss cache refresh in parallel disk attach/detach
```
```docs
feat: reduce vmss cache refresh in parallel disk attach/detach
```
=> feat: reduce vmss cache refresh in parallel disk attach/detach

pkg/retry/azure_retry.go, pkg/retry/azure_retry_test.go
/kind bug
cherry-pick of #718: avoid wrapping RawError twice
Fixes #
```release-note
fix: avoid wrapping RawError twice
```
```docs
```
=> cherry-pick of #718: avoid wrapping RawError twice

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
(cherry picked from commit 433503c691806b02948749ae8526bf8e481cf9fc)
/kind bug
fix: ignore the case when comparing azure tags in service annotation
Ref #658
```release-note
fix: ignore the case when comparing azure tags in service annotation
```
```docs
```
=> Cherry pick of #791 to release 1.0: fix: ignore the case when comparing azure tags in service annotation

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
(cherry picked from commit 433503c691806b02948749ae8526bf8e481cf9fc)
/kind bug
fix: ignore the case when comparing azure tags in service annotation
Ref #658
```release-note
fix: ignore the case when comparing azure tags in service annotation
```
```docs
```
=> Cherry pick of #791 to release 1.1: fix: ignore the case when comparing azure tags in service annotation

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go, tests/e2e/network/service_annotations.go
/kind feature
feat: add prefix 'k8s-azure-' for cloud provider managed tags
Legacy Tag | New Tag | Comment
-- | -- | --
service | k8s-azure-service | Applied on public IP
kubernetes-cluster-name | k8s-azure-cluster-name | Applied on public IP
kubernetes-dns-label-service | k8s-azure-dns-label-service | Applied on public IP
Fixes #788
```release-note
Prefix 'k8s-azure-' has been added to the following tags:
Legacy Tag | New Tag | Comment
-- | -- | --
service | k8s-azure-service | Applied on public IP
kubernetes-cluster-name | k8s-azure-cluster-name | Applied on public IP
kubernetes-dns-label-service | k8s-azure-dns-label-service | Applied on public IP
To keep backward compability, the legacy tags on existing public IP would not be removed, but newly created public IPs would only get the …
```
=> feat: add prefix 'k8s-azure-' for cloud provider managed tags

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
fix: skip not found nodes when reconciling LB backend address pools, this is because nothing should be done for VMs that have already been deleted on Azure.
Fixes #787
#794 has improved the log message for "instance not found" error.
```release-note
fix: skip not found nodes when reconciling LB backend address pools
```
```docs
```
=> fix: skip not found nodes when reconciling LB backend address pools

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug 
cherry-pick of #816: skip not found nodes when reconciling LB backend address pools
Fixes #
```release-note
fix: skip not found nodes when reconciling LB backend address pools
```
```docs
```
=> cherry-pick of #816: skip not found nodes when reconciling LB backend address pools

pkg/provider/azure_routes_test.go, pkg/provider/azure_wrap.go
/kind cleanup
fix: report an error when route table name is not configured. Without this fix, cloud controller manager would crash on such scenarios.
Fixes #756
```release-note
fix: report an error when route table name is not configured
```
```docs
```
=> fix: report an error when route table name is not configured

Makefile
/kind feature
Adds windows server 2022 to build
Fixes #
ltsc2022 is the MCR tag for Windows Server 2022
https://hub.docker.com/_/microsoft-windows-nanoserver
There is a PR for the same thing here:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1030
https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/756
https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/660
```release-note
feat: Adds windows server 2022 build
```
```docs
```
=> feat: Adds windows server 2022

cmd/cloud-node-manager/app/config/config.go, cmd/cloud-node-manager/app/init_others.go, cmd/cloud-node-manager/app/init_windows.go, cmd/cloud-node-manager/app/nodemanager.go, cmd/cloud-node-manager/app/options/init_others.go, cmd/cloud-node-manager/app/options/init_windows.go, cmd/cloud-node-manager/app/options/options.go, go.mod, hack/boilerplate/boilerplate.py, pkg/windows/service/service.go, vendor/golang.org/x/sys/windows/svc/event.go, vendor/golang.org/x/sys/windows/svc/go12.c, vendor/golang.org/x/sys/windows/svc/go12.go, vendor/golang.org/x/sys/windows/svc/go13.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/golang.org/x/sys/windows/svc/sys_windows_386.s, vendor/golang.org/x/sys/windows/svc/sys_windows_amd64.s, vendor/golang.org/x/sys/windows/svc/sys_windows_arm.s, vendor/golang.org/x/sys/windows/svc/sys_windows_arm64.s, vendor/modules.txt
/kind feature
This PR adds support for running the Cloud Node Manager as a Windows Service. This is useful in scenarios where you cannot run the node manager via a daemonset, eg for security or licensing reasons.
In windows builds only, a new flag, defaulted to false, determines whether or not the windows binary should run as a windows service initialiser rather than running as a normal windows exe.
Fixes #800 
This is mainly copied from the kube-proxy implementation linked in the original issue. I have yet to get this tested as I don't have access to windows right now. Will make sure to get this appropriately tested before we merge.
```release-note
Adds support for the Cloud Node Manager to run as a Windows Service. This can be enabled using the --windows-service flag.
```
```docs
```
=> Add Windows Service initialisation support for Cloud Node Manager

pkg/provider/azure.go, pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_zones.go, pkg/provider/azure_zones_test.go
/kind cleanup
chore: make metadata as public field
I found `isCurrentInstance` does not work for windows containerized driver since hostname in windows container is pod name, not equal to hostname on the node, so expose metadata as public field, for handling such issue on Windows separately:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0e8ef48b6c170202b697428f94b94a57b19ff791/pkg/provider/azure_instances.go#L299-L319
Fixes #
```release-note
chore: make metadata as public field
```
```docs
chore: make metadata as public field
```
=> chore: make metadata as public field

pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go
/kind feature
feat: add disk online resize support
Fixes #
```release-note
feat: add disk online resize support
```
```docs
feat: add disk online resize support
```
=> feat: add disk online resize support

tests/kubemark/templates/hollow-node.yaml
/kind cleanup
The --log-file parameter will be deprecated as of Kubernetes 1.23 and should be
avoided. The replacement for distroless images is the image with go-runner, a
tool that handles output redirection.
Fixes https://github.com/kubernetes/kubernetes/issues/106103
This is the same change as in
https://github.com/kubernetes/kubernetes/pull/106150/files#diff-142166782be7d6e83af6f3179f9a5dfd8eb69ea6585f03da6a5260e466325f9c
The assumption is that these templates are going to be used with a recent kubemark image, one which has go-runner.
```release-note
NONE
```
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2845
```
=> kubemark: replace deprecated --log-file parameter

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes.go, pkg/provider/azure_utils.go, site/content/en/install/configs.md, site/content/en/topics/tagging-resources.md, tests/e2e/network/service_annotations.go
/kind feature
Normally we don't support special characters such as `=` or `,` in key-value pairs. These characters will be treated as separator and will not be included in the key/value literal. To solve this problem, `tagsMap` is introduced, in which a JSON-style tag is acceptable.
```json
{
"tags": "a=b,c=d",
"tagsMap": {"e": "f", "g=h": "i,j"}
}
```
`tags` and `tagsMap` will be merged, and similarly, they are case-insensitive.
Fixes #887
```release-note
feat: support json style tags
```
```docs
```
=> feat: support json style tags

pkg/provider/azure_instances.go, pkg/provider/azure_standard.go
/kind bug
fix: panic due to nil pointer
This PR fixes panic in two places: 1) `VMSet` when initialize cloud config failed 2) `HardwareProfile` on standard VM
Fixes #
```release-note
fix: panic due to nil pointer
```
```docs
fix: panic due to nil pointer
```
=> fix: panic due to nil pointer

tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go
cherry-pick of #841: fix test failures on capz clusters
Fixes #
```release-note
NONE
```
```docs
```
=> cherry-pick of #841: fix test failures on capz clusters

README.md, examples/out-of-tree/cloud-controller-manager.yaml, examples/out-of-tree/cloud-node-manager.yaml, site/content/en/blog/releases/v0.7.10.md, site/content/en/blog/releases/v1.0.7.md, site/content/en/blog/releases/v1.1.3.md
doc: release v0.7.10, v1.0.7 and v1.1.3
Fixes #
```release-note
NONE
```
```docs
```
=> doc: release v0.7.10, v1.0.7 and v1.1.3

cloud-node-manager.Dockerfile
/kind perf
After #855, a new issue occurred: building `arm` and `arm64` images costs lots of time (sample: [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/894/pull-cloud-provider-azure-e2e-ccm/1465158916143845376/build-log.txt) and search `GOARCH=arm go build`). The previous Dockerfile had specified the build platform as the same as the target platform which makes it compile the `arm` and `arm64` images with the help of `QEMU`.
And this PR try to use `linux/amd64` as the unified build platform, and the benchmark is as follows:
| Build ARCH | Target ARCH | Cost Time | Remark |
| --- | --- | --- | --- |
| amd64 | amd64 | ~20s |  |
| arm64 | arm64 | ~700s | with QEMU |
| arm | arm | ~3000s | with QEMU |
| amd64 | arm64 | ~20s | …
=> build: cross-compile under linux/amd64 platform

pkg/consts/consts.go, pkg/provider/azure_controller_common.go
/kind bug
fix: detach disk should return error when throttled
Original case is that when there is detach disk batch operation, the rest detach disk(with empty operation) may return success even it's throttled.
Fixes #
```release-note
fix: detach disk should return error when throttled
```
```docs
fix: detach disk should return error when throttled
```
=> fix: detach disk should return error when throttled

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind feature
Currently we bind the VM/VMSS to the LB by attaching their NICs to the LB which needs to call the API of VM/VMSS. This PR introduces a new config `loadBalancerBackendPoolConfigurationType` and it can be set to `nodeIPConfiguration` (default) or `nodeIP`. If set to `nodeIPConfiguration`, everything will keep unchanged. If set to `nodeIP`, the cloud provider will call the LB API to attach the node private IPs to the LB instead of linking the NICs to the LB.
Fixes #
```release-note
Introduce a new config `loadBalancerBackendPoolConfigurationType` and it can be set to `nodeIPConfiguration` (default) or `nodeIP`. If set to `nodeIPConfiguration`, everything will keep unchanged. If set to `vmIP`, the cloud provider will call the LB API to attach the node private IPs to the LB …
```
=> feat: support attaching node private IP to the load balancer backendpools

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
Signed-off-by: Shangxiang Fan <shafan@microsoft.com>
/kind feature
Fixes #948 
```release-note
Two new annotations are added in order to customize health probe behavior
service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "15"
service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe: "2"
```
```docs
```
=> Add numOfProbe and probeInterval in health probe configuration

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_vmss.go
/kind cleanup
The `reconcileSharedLoadBalancer` concerns two things: deleting unwanted dedicated SLBs and adding the vmSets that are supposed to share the primary SLBs to the backend pools of them. The latter is unnecessary because these vms/vmSets will be added to the corresponding LB's backend pools later in `reconcileLoadBalancer`.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: simplify reconcileSharedLoadBalancer

pkg/provider/azure_controller_common.go, pkg/provider/azure_storageaccount.go
/kind cleanup
chore: add vnetRG, vnetName, subnetName in account settings
these 3 settings could be read from `azure.json`, while in some k8s clusters, e.g. ARO, these settings are not defined, and moreover, there are more than 1 subnet in one cluster, in such scenario, we should allow users to define those settings in storage class, one cloud config file could not define anything, and if it's not defined in storage class, still read default settings from cloud config file.
Fixes #
```release-note
chore: add vnetRG, vnetName, subnetName in account settings
```
```docs
chore: add vnetRG, vnetName, subnetName in account settings
```
=> chore: add vnetRG, vnetName, subnetName in account settings

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json, tests/k8s-azure/manifest/linux-ipv6.json
/kind cleanup
- Uses containerd for dual-stack and ipv6 jobs. Fixes cluster creation failures that are caused because dockershim is removed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-dualstack-azure-e2e-master-iptables/1477969941817724928
Fixes #
```release-note
NONE
```
```docs
```
=> chore: use containerd for dual-stack and ipv6

tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go
(cherry picked from commit 77e321f896a6ebd3300c3c03e59d642434e01840)
Cherry pick of #841 to release-1.0: test: fix test failures on capz clusters
Fixes #833
```release-note
NONE
```
```docs
```
=> test: fix test failures on capz clusters

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/armclient/interface.go, pkg/azureclients/armclient/mockarmclient/interface.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/azureclients/vmssvmclient/interface.go, pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go, pkg/provider/azure.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
(cherry picked from commit d9edcd6ec1429d8995d985b1ebddbce77bfd25ad)
/kind feature
Cherry pick of #953: feat: support sending sync requests concurrently in batches when putting vmss vm
Fixes #
```release-note
Introduce a configuration option `putVMSSVMBatchSize`. If set, the sync requests will be sent concurrently in batches when putting vmss vms.
```
```docs
```
=> feat: support sending sync requests concurrently in batches when putting vmss vm

tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json
/kind cleanup
- Sets the `networkPlugin` to `azure` for dual-stack jobs
Fixes #
```release-note
NONE
```
```docs
```
=> chore: use azurecni for dual-stack

pkg/consts/consts.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, site/content/en/topics/tagging-resources.md, tests/e2e/e2e_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
Cherry-pick #607, #627 and #841 to branch release-0.7 to solve flaky tests.
Fixes #
```release-note
Cherry-pick #607 to solve flaky tests:
* should add all nodes in different agent pools to backends [MultipleAgentPools]: fail to find `backendAddressPoolID` in `lbBackendAddressPoolsIDMap`
* Found no or more than 1 virtual network in resource group same as cluster name
* cannot obtain the master node
Failures e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/969/pull-cloud-provider-azure-e2e-ccm-capz-1-20/1479028839588827136
Cherry-pick #627 to solve "get outbound rules" issue
Cherry-pick #841 to solve "not equal 0" issue
Failures e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/982/pull- …
```
=> Cherry-pick #607, #627 and #841 to branch release-0.7

tests/kubemark/build-kubemark.sh
This PR helps solve failure in ci-kubernetes-kubemark-100-azure-test. It was using an old aks-engine that doesn't support K8s v1.19.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-azure-test/1480408092028964864/build-log.txt
/kind bug
Upgrade aks-engine to v0.66.1 used in build-kubemark.sh. It solves ci-kubernetes-kubemark-100-azure-test failure.
Fixes #
```release-note
This PR helps solve failure in ci-kubernetes-kubemark-100-azure-test. It was using an old aks-engine that doesn't support K8s v1.19.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-azure-test/1480408092028964864/build-log.txt
```
```docs
```
=> Upgrade aks-engine used in build-kubemark.sh to v0.66.1

Makefile, README.md, cloud-node-manager-windows.Dockerfile, cloudbuild.yaml, site/content/en/development/custom-images.md, site/content/en/development/e2e/e2e-tests.md, site/content/en/development/future.md, site/content/en/development/image-building.md
Changes included in this PR:
- address part of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/829, as arm64 windows image support cannot be achieved as mentioned as a limitation of arm64 support for the Windows nanoserver and servercore images.
- unify both Linux and windows node images with the same repository name, like `gcr.io/k8s-staging-provider-azure/azure-cloud-node-manager`, and is distinguished by different tag naming patterns. Linux is with tag `$TAG-linux-$ARCH`, while windows are with tag `$TAG-windows-$OSVERSION-$ARCH`, for example:
```
qingchuanhao.azurecr.io/cloud-provider-azure/azure-cloud-node-manager:v1.1.3-linux-amd64
qingchuanhao.azurecr.io/cloud-provider-azure/azure-cloud-node-manager:v1.1.3-windows-1809-amd64
```
Fixes #
```release-note
null
``` …
=> chore: Polish node manager image building

cmd/cloud-node-manager/app/options/options.go, pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go, pkg/provider/azure.go
/kind cleanup
Refer the codes below, cloud-node-manager is querying the node every 5 minutes to reconcile its addresses, but this API call is not actually required as there's already informers:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0e8ef48b6c170202b697428f94b94a57b19ff791/pkg/nodemanager/nodemanager.go#L178-L181
Hence, this PR replaces the node LIST with informer LIST, which would reduce the API calls to apiserver.
Fixes #
```release-note
chore: reduce node LIST APIs in cloud-node-manager
```
```docs
```
=> chore: reduce node LIST APIs in cloud-node-manager

pkg/auth/azure_auth.go, pkg/provider/azure.go, pkg/provider/azure_standard.go
/kind bug
Update tenantid or subscription id when network resource is in different tenant or subscription
Fixes #984 
```release-note
NONE
```
```docs
```
=> Override subscription and tenant configs when network resources is in different tenant or subscriptions

pkg/auth/azure_auth.go, pkg/provider/azure.go, pkg/provider/azure_standard.go
/kind bug
backport pr 1005 to release 1.1
Fixes #984 
```release-note
NONE
```
```docs
```
=> Backport 1.0:Override subscription and tenant configs when network resources is in different tenant or subscription 

pkg/auth/azure_auth.go, pkg/provider/azure.go, pkg/provider/azure_standard.go
/kind bug
backport pr 1005 to release 1.1
Fixes #984 
```release-note
NONE
```
```docs
```
=> Backport 1.1:Override subscription and tenant configs when network resources is in different tenant or subscription

pkg/auth/azure_auth.go, pkg/provider/azure.go, pkg/provider/azure_standard.go
/kind bug
backport pr 1005 to release 1.1
Fixes #984 
```release-note
NONE
```
```docs
```
=> Backport 1.23:Override subscription and tenant configs when network resources is in different tenant or subscription 

Makefile, hack/test_k8s_e2e_capz.sh
* test_k8s_e2e_capz.sh is for tests with capz
* It fits TOT capz, test-infra and kubernetes
* Add exec permission for test_k8s_e2e*.sh
Fixes #
```release-note
NONE
```
```docs
```
=> Add test_k8s_e2e_capz.sh

pkg/azureclients/interfaceclient/interface.go, pkg/azureclients/loadbalancerclient/interface.go, pkg/azureclients/publicipclient/interface.go, pkg/azureclients/routeclient/interface.go, pkg/azureclients/routetableclient/interface.go, pkg/azureclients/securitygroupclient/interface.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_interface_utils.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/route_table_utils.go, tests/e2e/utils/service_utils.go
/kind bug
Cherry pick of #1070 to release-1.1:
fix: use zones in the pre-existing frontend IP configurations for internal LBs
chore: bump network api version from 2020-08-01 to 2021-02-01
Fixes #
```release-note
fix: use zones in the pre-existing frontend IP configurations for internal LBs
```
```docs
```
=> [release-1.1] Cherry pick of #1070 to release-1.1

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
fixes #1087
Fixes #
```release-note
This code change fixes the bug that UDP services would trigger unnecessary LoadBalancer updates. The root cause is that a field not working for non-TCP protocols is considered.
```
```docs
```
=> Fix incorrect EnableTCPReset for non-TCP protocols

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind cleanup
Refactor armclient and move retry on regional endpoint to SendDecorator
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor : move retry on regional endpoint to SendDecorator

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
Fixes #1087 
```release-note
This code change fixes the bug that UDP services would trigger unnecessary LoadBalancer updates. The root cause is that a field not working for non-TCP protocols is considered.
ref: #1090
```
```docs
```
=> Cherry-pick: Fix incorrect EnableTCPReset for non-TCP protocols

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, tests/e2e/network/service_annotations.go
/kind bug
Health probe configuration should be per-port specific. 
Tcpreset feature is deleted. And test cases should changed accordingly.
set idletimeoutinminutes to 4
Fixes #949 
when traffic policy is local, lbrule will follow the following pattern instead: svcprefix-tcp-HealthCheckNodePort
Test cases of Tcpreset feature has been removed
A function is added to convert deprecated annotation to new annotations and alter the service object accordingly. 
Generate testsuit.go for e2e test cases
User should adopt new annotation and spec field to configure health probe of load balancer.
```release-note
Following  configuration will be applied to the all ports of service.
"service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol" …
```
=> Fix: health probe config should be port-specific

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, tests/e2e/network/service_annotations.go
/kind bug
/kind feature
backport pr963 to release-1.0
Fixes #949 #948
Please pay special attention to changes in loadbalancer_test.go because it may introduce break change.
```release-note
Following  configuration will be applied to the all ports of service.
"service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-interval"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path"
If health probe is needed, user should specify AppProtocol in port object of Service spec.
And following protocols are supported: http, tcp, https
Additional annotations are added. where port is the port number of port object …
```
=> [release-0.7]Fix: health probe config should be port-specific 

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, tests/e2e/network/service_annotations.go
/kind bug
/kind feature
backport pr963 to release-1.0
Fixes #949 #948
```release-note
Following  configuration will be applied to the all ports of service.
"service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-interval"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe"
"service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path"
If health probe is needed, user should specify AppProtocol in port object of Service spec.
And following protocols are supported: http, tcp, https
Additional annotations are added. where port is the port number of port object
service.beta.kubernetes.io/port_{port}_health-probe_interval
service.beta.kubernetes.io/port_{port}_health-probe_num-of-probe …
```
=> [release-1.0]Fix: health probe config should be port-specific

hack/test_k8s_e2e_capz.sh
Correct k8s repo path is: "${GOPATH}/src/k8s.io/kubernetes",
instead of "${GOPATH}/src/k8s.io/kubernetes/kubernetes"
Fixes #
```release-note
NONE
```
```docs
```
=> Fix test_k8s_e2e_capz.sh

pkg/credentialprovider/azure_acr_helper.go
increase Azure ACR credential provider timeout
from 1.22, connection timeout to ACR is set as 10s, which in some cases, 10s is not enough, would cause following timeout:
```
Feb 16 10:05:09 aks-pdweappool02-29359546-vmss000002 kubelet[28475]: E0216 10:05:09.652945   28475 azure_credentials.go:326] failed to receive challenge: error reaching registry endpoint https://xxx.azurecr.io/v2/, error: Get "https://xxx.azurecr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)Feb 16 10:05:09 aks-pdweappool02-29359546-vmss000002 kubelet[28475]: E0216 10:05:09.652966   28475 azure_credentials.go:264] error getting credentials from ACR for xxx.azurecr.io error reaching registry endpoint https://xxx.azurecr.io/v2/, error: Get …
```
=> fix: increase Azure ACR credential provider timeout

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
/kind bug
Existing code just logs an error when node manager failed to get `providerID` and leaves the field empty. But in reality,
there are other control-plane components requiring `providerID` to not be empty. So node manager should at least retry
to get `providerID` and report error.
This fix allows node manager try 20 times with a time backoff and panic if still failing. UT is also added. 
Fixes #1155 
```release-note
NONE
```
```docs
Current behavior when node manager not able to get providerID (node manager log):
E0228 03:55:11.893444       1 runtime.go:78] Observed a panic: &fmt.wrapError{msg:"failed to initialize node providertest2-vmss-1000001 at cloudprovider: failed to set node provider id: no credentials provided for Azure cloud provider", err:(*fmt.wrapError)(0xc0002d8a20)} …
```
=> Node manager should retry when not able to get providerID

hack/ensure-clusterctl.sh
/kind api-change
With the old `clusterctl` version, running `make deploy-cluster` script will report error:
```
Installing cert-manager Version="v1.5.3"
Error: action failed after 10 attempts: failed to get cert-manager object /, Kind=, /: Object 'Kind' is missing in 'unstructured object has no kind'
make: *** [deploy-cluster] Error 1
```
This issue is known here: https://cluster-api.sigs.k8s.io/user/troubleshooting.html#failed-clusterctl-init---failed-to-get-cert-manager-object.
Solution is to upgrade clusterctl version.
Fixes #
```release-note
NONE
```
```docs
```
=> Update clusterctl minimum version to v1.1.1

pkg/nodemanager/nodemanager.go, pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
This PR makes sure that nodes that are not in the ready state get removed from Azure load balancer backend pools.
Fixes #1194
```release-note
NONE
```
=> fix: exclude non-ready nodes from azure load balancer

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: add tags matching in storage account search for azure file and blob csi drivers.
This PR adds the tags matching in storage account search for azure file and blob csi drivers.
Fixes #
```release-note
fix: add tags matching in storage account search for azure file and blob csi drivers.
```
```docs
fix: add tags matching in storage account search for azure file and blob csi drivers.
```
=> fix: add tags matching in storage account search

pkg/azureclients/armclient/azure_armclient.go
/kind bug
fix: armclient panic when response is nil
<details>
```
2022-03-08T04:31:40.4980663Z stderr F I0308 04:31:40.497552    3996 utils.go:76] GRPC call: /csi.v1.Node/NodeStageVolume
2022-03-08T04:31:40.4980663Z stderr F I0308 04:31:40.498066    3996 utils.go:77] GRPC request: {"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-5803bec1-eb0b-4c69-ad8f-149884af0ec8\\globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","mfsymlinks","cache=strict","nosharesock","actimeo=30"]}},"access_mode":{"mode":5}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-5803bec1-eb0b-4c69-ad8f-149884af0ec8","csi.storage.k8s.io/pvc/name":"pvc-azurefile","csi.storage.k8s.io/pvc/namespace":"default","secretnamespace":"default", …
```
=> fix: armclient panic when response is nil

pkg/metrics/azure_metrics.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_routes.go, pkg/provider/azure_standard.go, pkg/provider/azure_vmss.go
/kind cleanup
chore: add verbose logs for latency and operation start timestamps
Sample logs:
```
I0314 12:57:28.635713       1 azure_metrics.go:113] "Observed Request Latency" latency_seconds=27.475052838 request="services_ensure_loadbalancer_deleted" resource_group="ccm" subscription_id="<subscription>" source="default/http" result_code="succeeded"
I0314 12:57:59.014313       1 azure_metrics.go:113] "Observed Request Latency" latency_seconds=0.08678909 request="services_vmss_ensure_hosts_in_pool" resource_group="ccm" subscription_id="<subscription>" source="default/http" result_code="succeeded"
I0314 12:58:03.099604       1 azure_metrics.go:113] "Observed Request Latency" latency_seconds=9.610200225 request="services_ensure_loadbalancer" resource_group="ccm" …
```
=> chore: add verbose logs for latency and operation start timestamps

pkg/provider/azure_backoff.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
When the service is being deleted, ListManagedLBs will return all LBs in the resource group, including unmanaged LBs. These unmanaged ones may be deleted later in the reconcileSharedLoadBalancer. Although this function can only run once, the ccm may restart right after the service was being deleted, so this unexpected scenario may happen. This PR skips the function if the service is being deleted.
Fixes #
```release-note
fix: skip reconcileSharedLoadBalancer if the service is being deleted
```
```docs
```
=> fix: skip reconcileSharedLoadBalancer if the service is being deleted

cmd/cloud-node-manager/app/nodemanager.go
/kind bug
When running `azure-cloud-node-manager` with the `--port` flag, it panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x199847c]
goroutine 1 [running]:
k8s.io/controller-manager/app.NewBaseHandler(0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/controller-manager/app/serve.go:61 +0x9c
sigs.k8s.io/cloud-provider-azure/cmd/cloud-node-manager/app.Run(0xc000500d80, 0xc000114360, 0x0, 0x0)
/go/src/sigs.k8s.io/cloud-provider-azure/cmd/cloud-node-manager/app/nodemanager.go:111 +0x245
sigs.k8s.io/cloud-provider-azure/cmd/cloud-node-manager/app.NewCloudNodeManagerCommand.func1(0xc000712280, 0xc000511d60, 0x0, 0xa) …
```
=> Avoid Panic when using `--port`

pkg/provider/azure_backoff.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
(cherry picked from commit fac209a6e08645ab3f2a064f0aa79687251b5a5f)
/kind bug
Cherry pick of #1254 to release-1.23: fix: skip reconcileSharedLoadBalancer if the service is being deleted
Fixes #
```release-note
fix: skip reconcileSharedLoadBalancer if the service is being deleted
```
```docs
```
=> [release-1.23] fix: skip reconcileSharedLoadBalancer if the service is being deleted

README.md, examples/out-of-tree/cloud-controller-manager.yaml, site/content/en/install/azure-ccm.md, site/content/en/install/configs.md, site/content/en/topics/availability-zones.md, site/content/en/topics/credential-provider.md, site/content/en/topics/cross-resource-group-nodes.md, tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
Fixes #
```release-note
Use deployment for CCM in example yaml
```
```docs
```
=> Use deployment for CCM in example yaml

tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1227 added `LegacyServiceAccountTokenNoAutoGeneration=false` feature flag to controller manager config. The same config is used for < 1.24 as well which fails. Duplicating the config and removing `LegacyServiceAccountTokenNoAutoGeneration` feature flag, so we can use this new config for jobs running < 1.24 for dual-stack.
Fixes #
```release-note
NONE
```
```docs
```
=> test: add dual-stack manifest for < 1.24

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
/kind bug
Only check service-owned frontend IP config when reconciling frontend IP configs.
Fixes #1311
```release-note
fix: only check the frontend IP config that is owned by the service
```
```docs
```
=> fix: only check the frontend IP config that is owned by the service

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
Signed-off-by: GitHub <noreply@github.com>
/kind bug
Fixes #
```release-note
Fixed a bug in health probe generator. Probe related configuration is not updated due to variable scope
```
```docs
```
=> Hotfix: fix probe missing when external traffic is local with multiple port opened.

pkg/cache/azure_cache.go, pkg/provider/azure_vmss_cache.go
/kind feature
remove k/client-go/tools/cache dependency and provide a more performant cache.
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor store and use sync.map as data store

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
(cherry picked from commit c12a25c0f63467d9100d431ed6ecac24a702b733)
/kind bug
Cherry pick of #1315 to release-1.1: fix: only check the frontend IP config that is owned by the service
Fixes #
```release-note
fix: only check the frontend IP config that is owned by the service
```
```docs
```
=> [release-1.1] fix: only check the frontend IP config that is owned by the service

cloudbuild.yaml
/kind bug
The new image upgrades golang from 1.16 to 1.17, then the
post-push-image job should be recovered. Windows cnm image
build should work now.
https://console.cloud.google.com/gcr/images/k8s-staging-test-infra/GLOBAL/gcb-docker-gcloud
Fixes #
```release-note
NONE
```
```docs
```
=> [cloud build] Bump gcb-docker-gcloud version

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
(cherry picked from commit c12a25c0f63467d9100d431ed6ecac24a702b733)
/kind bug
Cherry pick of #1315 to release-1.23: fix: only check the frontend IP config that is owned by the service
Fixes #
```release-note
fix: only check the frontend IP config that is owned by the service
```
```docs
```
=> [release-1.23] fix: only check the frontend IP config that is owned by the service

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
(cherry picked from commit c12a25c0f63467d9100d431ed6ecac24a702b733)
/kind bug
Cherry pick of #1315 to release-1.0: fix: only check the frontend IP config that is owned by the service
Fixes #
```release-note
fix: only check the frontend IP config that is owned by the service
```
```docs
```
=> [release-1.0] fix: only check the frontend IP config that is owned by the service

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
/kind bug
fix: always check result code even returns http 200 success in VM update
There are cases that vm update returns `200` httpStatusCode, while it actually failed with `OperationPreempted`, vm update operation should return failure in such condition. Original code only checks http response which is incorrect.
```
resultType httpStatusCode resultCode	                         errorDetails
1	          200	            OperationPreempted		Operation execution has been preempted by a more recent operation.
```
Fixes #
```release-note
fix: disk attach/detach failure when operation is preempted
```
```docs
fix: disk attach/detach failure when operation is preempted
```
=> fix: disk attach/detach failure when operation is preempted

pkg/auth/azure_auth.go, pkg/auth/azure_auth_test.go
/kind feature
Support Azure resource ID as `userAssignedIdentityID`. This makes it a bit more convenient as resource ID is more user-friendly.
Fixes #
```release-note
Support ARM resource ID as `userAssignedIdentityID`
```
```docs
```
=> Support Azure resource ID as `userAssignedIdentityID`

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind bug
In pre-configured mode, we are not responsible for adding node ip/ipconfiguration to lb.
Then similarly we should not remove unused ones otherwise they will never
come back.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: don't remove unused node ip/ipconfiguration if backend pool is pre-configured

Makefile
Support customized cnm multi-arch-os image build
Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1358
```release-note
NONE
```
```docs
```
=> Support customized cnm multi-arch-os image build

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, site/content/en/topics/loadbalancer.md
/kind bug
Fixes #
```release-note
```
```docs
```
=> Fix: fallback to tcp if appprotocol is not supported

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.1]fix: fallback to tcp if appprotocol is not supported

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-0.7]Fix: fallback to tcp if appprotocol is not supported

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.23]fix: fallback to tcp if appprotocol is not supported

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.0]fix: fallback to tcp if appprotocol is not supported

Makefile, cloudbuild.yaml, variants.yaml
Cloudbuild used to serially build cloud-controller-manager and
cloud-node-manager images, which takes too much time. Now, with
variants.yaml, cloudbuild builds both images in parallel.
Cloudbuild used to serially build cloud-controller-manager and
cloud-node-manager images, which takes too much time. Now, with
variants.yaml, cloudbuild builds both images in parallel.
Fixes #
```release-note
NONE
```
```docs
```
=> Reduce build time for cloudbuild

site/content/en/topics/tagging-resources.md, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go
/kind testing
We need to add e2e test case to cover the scenario in which a service with multiple ports is applied. 
and backport https://github.com/kubernetes-sigs/cloud-provider-azure/pull/627
Fixes #1318
```release-note
NONE
```
```docs
```
=> [release 1.0]Tests: e2e add multiport service test and backport #627

pkg/cache/azure_cache.go, pkg/provider/azure_vmss_cache.go
/kind bug
cocurrent get requests are generated if sync.map is used. 
Fixes #
As @jwtty @nilo19 mentioned, The code change may introduce a regression bug.
update entry logic doesn't fulfill the requirement documented here 
More than one routine will update cache store at the same time.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/4f83f549efd056c3ed9cc5cbacab2915c6374b6a/pkg/cache/azure_cache.go#L144-L147
The original code had held a Mutex lock before entered into update section.
```release-note
NONE
```
```docs
```
=> Rollback pr #1300 Refactor store and use sync.map as data store

pkg/azureclients/storageaccountclient/azure_storageaccountclient.go, pkg/azureclients/storageaccountclient/azure_storageaccountclient_test.go, pkg/azureclients/storageaccountclient/interface.go, pkg/azureclients/storageaccountclient/mockstorageaccountclient/interface.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
chore: add subsID parameter in storage account client
Fixes #
```release-note
chore: add subsID parameter in storage account client
```
```docs
chore: add subsID parameter in storage account client
```
=> chore: add subsID parameter in storage account client

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, tests/e2e/network/service_annotations.go
* Frontend PIP config name may end with invalid char like '-'
* Add a UT and update an e2e testcase
/kind bug
* Frontend PIP config name may end with invalid char like '-'.
* Add a UT and update an e2e testcase
Error message with TOT code:
```
Warning  SyncLoadBalancerFailed  10s (x2 over 15s)  service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
"error": {
"code": "InvalidResourceName",
"message": "Resource name a7964223528ca4537bf03ec169304d1d-a---------------------------------------------- is invalid. The name can be up to 80 characters long. It must begin with a word …
```
=> Fix possibly incorrect last char of frontend PIP config name

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: account tags matching in account search
in account searching, `k8s-azure-created-by=azure` is the tag created by azure file driver, should be included in account searching tag matching process
Fixes #
```release-note
fix: account tags matching in account search
```
```docs
fix: account tags matching in account search
```
=> fix: account tags matching issue in account search

pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go, pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient_test.go, pkg/azureclients/privatelinkserviceclient/interface.go, pkg/azureclients/privatelinkserviceclient/mockprivatelinkserviceclient/interface.go
/kind feature
When deleting a PLS, need to delete all existing PE connections first. So add this client interface.
Fixes #
```release-note
Add azure private link service client interface to delete a private endpoint connection.
```
```docs
```
=> Add DeletePEConnection to plsClient

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: disable match tags by default in account search when creating file share
From azure file csi driver v1.13.0, there is tags matching, unfortunately there is a bug in tags matching which would lead to creating a new account every time when creating a new file share, this PR fixes the issue by disabling match tags by default in account search when creating file share. Tag matching is only enabled when it's specified explicitly.
Fixes #
```release-note
fix: disable match tags by default in account search when creating file share
```
```docs
fix: disable match tags by default in account search when creating file share
```
=> fix: disable match tags by default in account search when creating file share

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go
/kind feature
In current code, `ListPIP` is called every time in `determinePublicIPName()` function when service specifies loadBalancerIP. This function can be called in multiple loops when reconciling loadBalancer and may cause throttling. 
Please find origin issue #1136 
Fixes #
```release-note
Reduce ListPublicIPAddress call count by avoiding each call in loops
```
```docs
```
=> Reduce listPIP calls

pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go
/kind bug
Fixes #1390 
Should add unit tests for interfaces of cloudprovider afterwards.
```release-note
fix InstanceV2.InstanceExists: it should return false<bool> instead of ErrInstanceNotFound<error>
```
```docs
```
=> fix(instance-v2): use false<bool> representing ErrInstanceNotFound<errror>

pkg/provider/azure_storageaccount.go
/kind cleanup
Fixes #
```release-note
chore: fail earlier if creating virutal link failed before account creation
```
```docs
none
```
=> chore: fail earlier if creating virutal link failed before account creation

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
If VMSS VM in cache is nil, it leads to invalid memory panic.
Fix the bug and add UT.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1494/pull-cloud-provider-azure-e2e-ccm-vmss/1518760519601754112/artifacts/k8s-master-35603851-0/cloud-controller-manager-k8s-master-35603851-0_kube-system_cloud-controller-manager-1549902e5c6968ce99be6547178c14978075a88b4c14a37efabb80725a112cae.log
Fixes #
```release-note
Fix possible nil VMSS VM in VMSS cache
```
```docs
```
=> Fix possible nil VMSS VM in VMSS cache

tests/e2e/node/vmss.go
ValidateClusterNodesMatchVMSSInstances before next test.
/kind flake
Fix flaky vmss tests. ValidateClusterNodesMatchVMSSInstances before next test.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Fix flaky vmss tests

pkg/azureclients/interfaceclient/azure_interfaceclient.go, pkg/azureclients/interfaceclient/azure_interfaceclient_test.go
/kind bug
Fix "expand" is not used in getNetworkInterface()
Fixes #
```release-note
Fix "expand" is not used in getNetworkInterface()
```
```docs
```
=> Fix "expand" is not used in getNetworkInterface()

pkg/provider/azure_backoff.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss_cache.go
/kind bug
The Etag could be different when updating LB backend pool in bi.EnsureHostsInPool after updating the LB, as the Etags of the backend pool and the LB are the same. This PR refreshes the LB object in the code after updating it.
Also, this PR downgrade the verbosity of some logs due to their huge number in large-scale clusters.
Fixes #
```release-note
fix: always get LB after updating it
```
```docs
```
=> fix: always get LB after updating it

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix: ensure TCP probe is used by default for backward compatibility. 
When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
Fixes #
```release-note
fix: ensure TCP probe is used by default for backward compatibility. When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
```
```docs
```
=> fix: ensure TCP probe is used by default for backward compatibility

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix-0.7: update probe when protocol or request path change
Fixes #
```release-note
fix-0.7: update probe when protocol or request path change
```
```docs
```
=> fix-1.1: update probe when protocol or request path change

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix-0.7: update probe when protocol or request path change
Fixes #
```release-note
fix-0.7: update probe when protocol or request path change
```
```docs
```
=> fix-1.0: update probe when protocol or request path change

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix: ensure TCP probe is used by default for backward compatibility. 
When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
Fixes #
```release-note
fix: ensure TCP probe is used by default for backward compatibility. When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
```
```docs
```
=> fix-1.0: ensure TCP probe is used by default for backward compatibility

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix: ensure TCP probe is used by default for backward compatibility. 
When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
Fixes #
```release-note
fix: ensure TCP probe is used by default for backward compatibility. When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
```
```docs
```
=> fix-1.23: ensure TCP probe is used by default for backward compatibility

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
fix: ensure TCP probe is used by default for backward compatibility. 
When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
Fixes #
```release-note
fix: ensure TCP probe is used by default for backward compatibility. When appProtocol is set to HTTP/HTTPS, continue to use TCP as probe protocol by default. The probe protocol would be changed same to appProtocol in 1.24 release version.
```
```docs
```
=> fix-1.1: ensure TCP probe is used by default for backward compatibility

pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go
/kind feature
feat: add DiskEncryptionType in CreateDisk
Fixes #
```release-note
feat: add DiskEncryptionType in CreateDisk
```
```docs
feat: add DiskEncryptionType in CreateDisk
```
=> feat: add DiskEncryptionType in CreateDisk

pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go, pkg/azureclients/deploymentclient/azure_deploymentclient_test.go, pkg/azureclients/publicipclient/azure_publicipclient_test.go, pkg/azureclients/routeclient/azure_routeclient_test.go, pkg/azureclients/routetableclient/azure_routetableclient_test.go, pkg/azureclients/securitygroupclient/azure_securitygroupclient_test.go, pkg/azureclients/snapshotclient/azure_snapshotclient_test.go, pkg/azureclients/subnetclient/azure_subnetclient_test.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmssclient/azure_vmssclient_test.go
Use GetThrottlingError() and GetRateLimitError() in azureclients
/kind cleanup
Use GetThrottlingError() and GetRateLimitError() in azureclients
Fixes #
```release-note
NONE
```
```docs
```
=> Refactor: Use existing GetXXXError methods

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go, pkg/azureclients/privateendpointclient/doc.go, pkg/azureclients/privateendpointclient/interface.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/doc.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/interface.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient_test.go, pkg/azureclients/virtualnetworklinksclient/doc.go, pkg/azureclients/virtualnetworklinksclient/interface.go, pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/interface.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind cleanup
Re-implement privateEndpointClient and virtualNetworkLinkClient to use armclient. This can facilitate ARG integration in the near future.
Fixes #
```release-note
Azure privateEndpointClient APIs are changed:
1. Get() and CreateOrUpdate() return *retry.Error instead of error
2. Add etag argument for CreateOrUpdate() function.
```
```docs
```
=> Refactor: Use armclient for privateEndpointClient and virtualNetworkLinkClient

pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
In Azure LoadBalancers, secondary IPs on a VM do not work with floating IP. In dual-stack clusters, the IPv6 IP is always set as a secondary IP. Therefore, IPv6 LoadBalancer services in Kubernetes that use internal LBs (ILB) need to disable floating IP and set the destination port to the service `NodePort`. This will ensure that the packet lands on the node with the dst IP and port as `nodeIP:nodePort`
Fixes https://github.com/Azure/AKS/issues/2919
```release-note
Fixes bug when using dual-stack in AKS that prevents IPv6 services from using ILB.
```
- [Azure Floating IP docs](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-floating-ip#limitations)
=> Disable floating IP on ILB IPv6 rule

Makefile, cmd/cloud-controller-manager/app/controllermanager.go, pkg/version/base.go
/kind bug
* Print whole version var in ccm log
Version: v1.24.0-22-g4ff19d66e
->
Version: version.Info{Major:"1", Minor:"24+",
GitVersion:"v1.24.0-19-g87cfaf2d3",
GitCommit:"87cfaf2d36e1b51f1e1627dc132651383f26d9ff", GitTreeState:"",
BuildDate:"2022-05-10T09:33:33Z", GoVersion:"go1.18.1", Compiler:"gc",
Platform:"linux/amd64"}
* Don't print stderr when docker buildx inspect img-buidler
"error: no builder "img-builder" found" -> NONE
Fixes #
```release-note
* Print whole version var in ccm log
Version: v1.23.0-466-g0b76f0943
->
Version: version.Info{Major:"1", Minor:"24+",
GitVersion:"v1.24.0-19-g87cfaf2d3",
GitCommit:"87cfaf2d36e1b51f1e1627dc132651383f26d9ff", GitTreeState:"",
BuildDate:"2022-05-10T09:33:33Z", GoVersion:"go1.18.1", …
```
=> Improve ccm printing version and docker buildx logs

cmd/cloud-controller-manager/app/core.go, pkg/consts/consts.go, pkg/provider/azure.go, tests/k8s-azure/manifest/linux-dual-stack-iptables-kubenet.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet-1.23.json, tests/k8s-azure/manifest/linux-dual-stack-ipvs-kubenet.json, tests/k8s-azure/manifest/windows-dual-stack.json
/kind cleanup
This PR removes references to the `IPv6DualStack` feature-gate as it is now locked to true and GA in upstream Kubernetes.
See:
- https://github.com/kubernetes/kubernetes/pull/109435
This change will break any future v0.7 releases of cloud-provider-azure because the feature-flag was not default to true until 1.21.0, so we'll have to be careful when we cherry-pick changes there. I observe that we are still releasing that version:
- https://github.com/kubernetes-sigs/cloud-provider-azure/releases/tag/v0.7.21
Fixes #
```release-note
remove GA IPv6DualStack feature-gate
```
```docs
```
=> chore: remove GA IPv6DualStack feature-gate

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go, pkg/azureclients/privateendpointclient/doc.go, pkg/azureclients/privateendpointclient/interface.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/doc.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/interface.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient_test.go, pkg/azureclients/virtualnetworklinksclient/doc.go, pkg/azureclients/virtualnetworklinksclient/interface.go, pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/interface.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind cleanup
Re-implement privateEndpointClient and virtualNetworkLinkClient to use armclient. This can facilitate ARG integration in the near future.
Cherry pick into release-1.1
Fixes #
related #1576 
```release-note
Azure privateEndpointClient APIs are changed:
1. Get() and CreateOrUpdate() return *retry.Error instead of error
2. Add etag argument for CreateOrUpdate() function.
```
```docs
```
=> [release-1.1]refactor: privateendpointclient and virtualnetworklinkclient change

tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go
/kind cleanup
* If failure to get a private link service, GetPrivateLinkService returns error with "not found"
* When checking azure-pip-tags, ignore "kubernetes-cluster-name" and "service"
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Improve pls and azure-pip-tags tests

tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go
/kind cleanup
* If failure to get a private link service, GetPrivateLinkService returns error with "not found"
* When checking azure-pip-tags, ignore "kubernetes-cluster-name" and "service"
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.0][e2e] Improve pls and azure-pip-tags tests

tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go
/kind cleanup
* If failure to get a private link service, GetPrivateLinkService returns error with "not found"
* When checking azure-pip-tags, ignore "kubernetes-cluster-name" and "service"
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1][e2e] Improve pls and azure-pip-tags tests

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient.go, pkg/azureclients/privateendpointclient/azure_privateendpointclient_test.go, pkg/azureclients/privateendpointclient/doc.go, pkg/azureclients/privateendpointclient/interface.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/doc.go, pkg/azureclients/privateendpointclient/mockprivateendpointclient/interface.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient.go, pkg/azureclients/virtualnetworklinksclient/azure_virtualnetworklinksclient_test.go, pkg/azureclients/virtualnetworklinksclient/doc.go, pkg/azureclients/virtualnetworklinksclient/interface.go, pkg/azureclients/virtualnetworklinksclient/mockvirtualnetworklinksclient/interface.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind cleanup
Re-implement privateEndpointClient and virtualNetworkLinkClient to use armclient. This can facilitate ARG integration in the near future.
Cherry pick into release-1.24
Fixes #
related #1576 
```release-note
Azure privateEndpointClient APIs are changed:
1. Get() and CreateOrUpdate() return *retry.Error instead of error
2. Add etag argument for CreateOrUpdate() function.
```
```docs
```
=> [release-1.24]refactor: privateendpointclient and virtualnetworklinkclient change

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: panic when create private endpoint using azurefile NFS
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1037
```release-note
fix: panic when create private endpoint using azurefile NFS
```
```docs
fix: panic when create private endpoint using azurefile NFS
```
=> fix: panic when create private endpoint using azurefile NFS

tests/e2e/network/standard_lb.go
"should add all nodes in different agent pools to backends" testcase
should work in a non-vmss aks-engine cluster.
/kind cleanup
"should add all nodes in different agent pools to backends" testcase
should work in a non-vmss aks-engine cluster.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Improve a slb testcase compatiblity

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Fix unexpected managed PLS deletion when ccm restarts.
When service has ILB subnet specified, LB frontend subnet config name is checked during reconciliation.
However, in actual LB config, only subnet ID is set while name is left as empty. So the comparation always fails and old frontend gets deleted and recreated even though nothing changed. PLS associated with the victim frontend also gets deleted and recreated.
Fix: compare subnet ID instead of subnet name.
Fixes #1825 
```release-note
Fix unexpected managed PLS deletion issue when ILB subnet is specified.
```
```docs
```
=> Fix unexpected pls deletion issue

tests/e2e/utils/vmss_utils.go
/kind cleanup
[e2e] Allow ListVMSSVMs returns empty list. CAPZ VMSS clusters may have empty VMSS resource.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Allow ListVMSSVMs returns empty list

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind cleanup
Fixes #
```release-note
NONE
```
```docs
```
=> test: Recycle pip-prefix after test

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
Fix empty $expand value in GetResourceWithExpandAPIVersionQuery()
Fixes #
```release-note
NONE
```
```docs
```
=> Fix empty $expand value in GetResourceWithExpandAPIVersionQuery()

pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go
/kind bug
Remove redundant restriction on pls autoApproval and visibility.
User can specify a list of subscriptions for visibility and a subset of this list for autoApproval.
Fixes #1859 
```release-note
Remove redundant restriction on pls autoApproval and visibility.
User can specify a list of subscriptions for visibility (e.g. "sub1 sub2") and a subset of this list for autoApproval (e.g. "sub1").
```
```docs
```
=> fix: remove auto approval restriction

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind cleanup
Cherrypick 1864 1865
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] Cherrypick 1864 1865

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind cleanup
Cherrypick 1864 1865
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.0] Cherrypick 1864 1865

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind cleanup
[release-1.1] Cherry-pick 1864 1865
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] Cherry-pick 1864 1865

tests/e2e/network/service_annotations.go, tests/e2e/utils/network_utils.go
/kind cleanup
[release-1.23] Cherrypick 1864 1865
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] Cherrypick 1864 1865

hack/log-dump/log-dump.sh
/kind bug
Ignores errors dumping logs from ephemeral pods like Job pods. The log may be deleted between the time the log directory is listed and the file is dumped.
Original filed as kubernetes-sigs/azuredisk-csi-driver#1392.
Fixes #1935 
```release-note
NONE
```
```docs
```
=> fix: Ignore errors dumping logs after listing

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/pod_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind cleanup
* Use agnhost image to support Windows Service validation.
nginx image is only for Linux. Allocate it to control plane node
* Customize deployment's port configuration to support
more testcases (tcp + udp)
* Replace curl with nc to test UDP traffic
* Unify validate connectivity methods for external & internal IP
* Bug fix: validate connectivity should also consider
non-80 port, instead of skipping
* Use HostExecPod's IP as LoadBalancerSourceRanges to
validate rule
* Use 2 deployments & services for shared pls test
* refactor
Fixes #705
```release-note
NONE
```
```docs
```
=> [e2e][Windows] Adjust Service validation for Windows cluster

pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go
/kind bug
Invalidate vmssVMCache when rg is not found, so that node lifecycle controller can detect node does not exist any more 
and stop querying vmss list in a loop.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: Invalidate vmssVMCache when rg is not found

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go
/kind feature
Floating IP is currently set to be always enabled on load balancers. 
In some scenarios, this configuration is ignored and treat as if floating IP is disabled. Example of this is traffic coming from 1st-party Private Link. Load balancer rule should be set properly in such scenarios such that traffic can be accepted within the cluster
Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1659
```release-note
A new service annotation `service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip` has been added to disable floating IPs in load balancer rule. 
If annotation is omitted or if the annotation is set to be "false", then floating IP will be enabled.
If the annotation is set to be "true", then floating IP will be disabled.
```
=> Add service annotation to disable floating IP in load balancer rule

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
For replication latency, it is possible contentLength is 0 and http
status code is 200
/kind bug
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
Fixes #
```release-note
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
```
```docs
```
=> [release-1.23] Improve the error handling for ARM APIs

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
For replication latency, it is possible contentLength is 0 and http
status code is 200
/kind bug
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
Fixes #
```release-note
Improve the error handling for ARM APIs. For replication latency, it is possible contentLength is 0 and http
status code is 200
```
```docs
```
=> [release-1.0] Improve the error handling for ARM APIs

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Do not compare privateIPAllocationMethod when checking if frontend config needs update. Just check if frontend ip matches service spec to avoid unnecessary LB frontend recreation.
Fixes #
```release-note
Fix: Do not compare privateIPAllocationMethod when checking if frontend config needs update. Just check if frontend ip matches service spec to avoid unnecessary LB frontend recreation.
```
```docs
```
=> fix: Ignore privateIPAllocationMethod when comparing frontend config

go.mod, pkg/metrics/azure_metrics.go, pkg/metrics/azure_metrics_test.go
/kind cleanup
When errors happen, the current result_code is always "failed" in ObserveOperationWithResult func.
Now the result_code turns to something like "failed_create_route",  "failed_ensure_loadbalancer" and so on.
Fixes #1986 
```release-note
Result_code in latency logs is more detailed.
```
```docs
```
=> Add detailed error reuslt_code in ObserveOperationWithResult func

tests/e2e/e2e_test.go
/kind flake
/kind cleanup
Skip slb outbound e2e test for capz clusters because capz doesn't use slb to setup node outbound connection.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: skip slb outbound e2e test for capz clusters

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
When deleting the service, we check which VMSS should be decoupled from the LB by parsing the IP config IDs in the backend pool. But in some cases, there is no such IDs in the pool (for example, the previous operation decoupled all VMSS VMs from the LB but failed to decouple the VMSS), so the VMSS decoupling operation will be skipped, which is unexpected. This PR switches the order of decoupling VMSS and VMSS VMs to make sure the VMSS can be decoupled.
Fixes #2027
```release-note
fix: decouple the LB from the VMSS before VMSS VMs
```
```docs
```
=> fix: decouple the LB from the VMSS before VMSS VMs

pkg/provider/azure_vmss_cache.go
/kind bug
fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling
When VM is in Deleting state, original behavior is setting as nil, and then with this PR(https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1578), Deleting state VM will be not found in cache, then it would trigger VMSSList again, found VM is still in Deleting state, return nil, trigger VMSSList again and again, finally get VMSSList throttling.
Fixes #
```release-note
fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling
```
```docs
fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling
```
=> fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/armclient/interface.go, pkg/azureclients/armclient/mockarmclient/interface.go
/kind feature
This PR add a new function GetResourceWithQueries(ctx context.Context, resourceID string, queries map[string]interface{}) (*http.Response, *retry.Error) in pkg/azureclients/armclient/interface.go and add an implementation of it in azure_armclient.go.  
This function supports querying Azure resource with a list of query parameters. 
This function will be used to query VMs under a VMSS Flex in batch behavior: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all
Refer to #639
```release-note
NONE
```
```docs
```
=> VMSS Flex support: Add GetResourceWithQueries function in azure_armclient.go

pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go
/kind feature
Allow external service with floating ip disabled to create PLS.
Fixes #
related #2073 
```release-note
Allow external service with floating ip disabled to create PLS.
```
```docs
```
=> [release-1.0] Allow external service with floating ip disabled to use PLS

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmclient/interface.go, pkg/azureclients/vmclient/mockvmclient/interface.go
/kind feature
This PR adds two functions in azure_vmclient.go to support batch querying VMSS Flex VMs and their InstanceView:
- ListVmssFlexVMsWithoutInstanceView(ctx context.Context, vmssFlexID string) ([]compute.VirtualMachine, *retry.Error): gets a list of VirtualMachine in the VMSS Flex without InstanceView
- ListVmssFlexVMsWithOnlyInstanceView(ctx context.Context, vmssFlexID string) ([]compute.VirtualMachine, *retry.Error): gets a list of VirtualMachine in the VMSS Flex with only InstanceView
Restful API used: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all
Refer to #639
Similar to VMSS Uniform, we can use batch query to retrieve all VMs inside a VMSS Flex. 
Different from VMSS Uniform, we need to make two separate calls to get both the VM properties and …
=> Vmss flex support: Add two functions in azure_vmclient.go to support batch querying VMSS Flex VMs and their InstanceView

.golangci.yml, cmd/cloud-controller-manager/app/core.go, cmd/cloud-controller-manager/app/testing/testserver.go, hack/verify-golint.sh, pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/privatelinkserviceclient/azure_privatelinkserviceclient.go, pkg/node/node.go, pkg/node/nodearm.go, pkg/nodeipam/ipam/doc.go, pkg/nodemanager/nodemanager.go, pkg/provider/azure_instances.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_routes.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_wrap.go, pkg/retry/azure_retry.go, tests/e2e/utils/node_utils.go
/kind testing
Less mem usage for golangci-lint by less concurrency 
Each linter is consuming a lot of memory usage so it is better to run them separately. It still uses golangci-lint's `--config` option because it is hard to do the same with other command line options.
Fixes #
```release-note
NONE
```
```docs
```
=> Less mem usage for golangci-lint by less concurrency

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
/kind cleanup
Lower verbosity in ci template due to the limitation of logging space. By doing so, we can record more logs in the following link.
https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-azure-conformance-serial-vmss-capz/1554527456629624832/artifacts/clusters/capz-7aod6t/kube-system/kube-controller-manager-capz-7aod6t-control-plane-5mdcz/kube-controller-manager.log
Fixes #
```release-note
NONE
```
```docs
```
=> lower verbosity in ci template due to the limitation of logging space

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_fakes.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache.go, pkg/provider/azure_vmssflex_cache_test.go
/kind feature
This PR is to support using VMSS Flex VMs as K8s cluster nodes. This PR added caches used for VMSS Flex nodes
This PR does the following things:
-  Define a FlexScaleSet struct to be used for managing VMSS Flex nodes
- Define the caches needed for VMSS Flex and the operations to query VMSS Flex VM info and VMSS Flex info from the caches
- Unit tests for functions to query vmss Flex related caches.
Refer to #639 
Similar to VMSS Uniform, 2 types of caches are used for VMSS Flex:
- cache for list of VMSS Flex: vmssFlexCache
- cache for list of VMSS Flex VMs: vmssFlexVMCache, vmssFlexVMStatusCache
Both of the above caches are populated in batch behavior.
Note:
1. Batch query needed
VMSS Uniform API support query VM properties and IntanceView with one single API:
GET …
=> VMSS Flex Support: Add vmssflex_cache.go and unit tests

pkg/provider/azure_backoff.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
add encryption setting in storage account creation
Fixes #
```release-note
add encryption setting in storage account creation
```
```docs
add encryption setting in storage account creation
```
=> add encryption setting in storage account creation

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
Reverts kubernetes-sigs/cloud-provider-azure#2060
This PR returns InstanceNotFound when vm in cache is nil, this PR would fix following issue in another way:
When VM is in Deleting state, original behavior is setting as nil, and then with this PR(https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1578), Deleting state VM will be not found in cache, then it would trigger VMSSList again, found VM is still in Deleting state, return nil, trigger VMSSList again and again, finally get VMSSList throttling.
```release-note
none
```
```docs
none
```
=> Revert "fix: don't set vm entry as nil in cache when vm is in Deleting state to avoid VMSSList throttling"

pkg/auth/azure_auth.go
/kind cleanup
cleanup: don't print error logging for user assigned client id
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1290/files#r944238069
I got this error now, from current code logic, looks like it's just an info log, I think we need to refine the logging, otherwise there will be following error as long as User Assigned MSI ID is client ID
```
[pod/csi-blob-node-8trh8/blob] I0812 03:15:51.934107       1 azure_auth.go:245] Using AzurePublicCloud environment
[pod/csi-blob-node-8trh8/blob] I0812 03:15:51.934127       1 azure_auth.go:96] azure: using managed identity extension to retrieve access token
[pod/csi-blob-node-8trh8/blob] I0812 03:15:51.934131       1 azure_auth.go:102] azure: using User Assigned MSI ID to retrieve access token …
```
=> cleanup: don't print error logging for user assigned client id

.pipelines/scripts/run-e2e.sh, hack/test-ccm-e2e.sh, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind cleanup
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2162 use CCM_E2E_ARGS to setup -flake-attempts. But this will conflict settings in the [test-infra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L248). This PR hard-codes the -flake-attempts.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: hard-code -flake-attempts instead of using CCM_E2E_ARGS

pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache.go, pkg/provider/azure_vmssflex_cache_test.go
use hostName rather than VMName as nodeName
/kind feature
No matter how the node is provisioned, this always applies: K8s nodeName == hostname ==  compute.VirtualMachine.OSProfile.ComputerName
When VMSS Flex is used, the behavior is more complex, as there are two approaches to provision VMs inside the VMSS Flex, and the different provisioning approaches affect how the node is named:
Case 1: When VMSS Flex is created with default VM profile, VM can be created by increasing the VMSS capacity. In this case, VM name is not equal to hostname (nodeName). (@Jack’s capz implementation)
Case 2: When VMSS Flex is created without default VM profile, VMs can be individually created and attached to the existing VMSS Flex. In this case, VM Name == hostname. (@Juan-Lee’s capz implementation)
To find out …
=> VMSS Flex Support: Computer hostName rather than VMName should be used as nodeName

pkg/provider/azure_standard.go, pkg/provider/azure_vmss.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind cleanup
This PR converts the existing `convertResourceGroupNameToLower` func in the `pkg/provider` library to be exportable: `ConvertResourceGroupNameToLower`.
The reason for this is that this string transformation logic is intrinsic to how cloud-provider-azure identifies a node's `providerID` property, and capz needs to be able to similarly recognize node `providerID` data. If this func is exportable that means that capz can simply import it and use it, to ensure that it will always be up-to-date with how cloud-provider-azure performs this work.
Refer to this capz PR which is manually duplicating this logic:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2536
Once this PR lands, we can convert the above capz surface area to simply call this exported …
=> make ConvertResourceGroupNameToLower exportable

pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_vmssflex_cache.go, pkg/provider/azure_vmssflex_cache_test.go
/kind feature
This PR is the second part of FlexScaleSet implementation of VMSet, mainly focus on VMSS Flex VM disk attach / detach
Refer to #639 
```release-note
NONE
```
```docs
```
=> VMSS Flex Support: FlexScaleSet implementation of VMSet: part 2 -- Disk attach / detacch

pkg/azureclients/armclient/util.go
/kind cleanup
there is `Send.sendRegionalRequest on ResourceGroupNotFound error` error with every call, set as log level 6 to reduce such uncessary logs:
```
I0818 15:43:54.257575       1 azure_storageaccount.go:391] Creating private dns zone(privatelink.file.core.windows.net) in resourceGroup (capz-okgxn5)
I0818 15:43:55.601327       1 util.go:158] Send.sendRegionalRequest on ResourceGroupNotFound error. Retrying regional host: eastus.management.azure.com
I0818 15:43:55.601405       1 util.go:170] Send.sendRegionalRequest failed to get response from regional host, error: 'EOF'. Ignoring the result.
I0818 15:44:25.729825       1 azure_storageaccount.go:405] Creating virtual link for vnet(f0db159c5e6db45e8bdaf6e-vnetlink) and DNS Zone(privatelink.file.core.windows.net) in …
```
=> chore: increase log level in arm client to reduce logs

pkg/provider/azure_storageaccount.go
/kind feature
chore: refine storage account encryption setting
This PR adds more default setting in storage account encryption setting
Fixes #
```release-note
none
```
```docs
none
```
=> chore: add more default setting in storage account encryption setting

pkg/nodemanager/nodemanager.go
/kind bug
fix: correct condition message for NodeNetworkUnavailable
Fixes #
```release-note
fix: correct condition message for NodeNetworkUnavailable
```
```docs
```
=> fix: correct condition message for NodeNetworkUnavailable

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_test.go
/kind bug
When service has floating ip disabled, all backend private IPs are added in nsg rule as destination addresses.
In a dual stack cluster, this includes both IPv4 and IPv6 addresses that nsg does not support.
So in this scenario, we only select private IPs with the same version as service LB IP to be included in nsg.
Fixes #2218 
```release-note
Fix nsg reconciliation failure for floating-ip-disabled services in dual-stack clusters.
```
```docs
```
=> fix: NSG destination IP version same as LB IP for floating ip disabled services

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache_test.go, pkg/provider/azure_vmssflex_test.go
/kind feature
FlexScaleSet implementation of VMSet interface for adding LB backend pool to vmss flex VMs related functions
Refer To #639 
- VMSS Flex does not support Basic load balancer
- If the VMSS Flex does not have default VM profile, then we only add SLB backend pool to vmss flex vm (similar to how AvaialbilitySet works)
- If the VMSS has the default VM profile, then we add SLB backend pool to both vmss flex vm and vmss flex (similar to how vmss uniform works)
```release-note
NONE
```
```docs
```
=> VMSS Flex Support: Part 6 of FlexScaleSet implementation of VMSet interface for adding LB backend pool to vmss flex VMs related functions

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind testing
* disabling floating ip case:
When checking if floating IP is disabled in LB rules, only
the corresponding one should be checked.
* service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probe,
service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol,
and
ExternalTrafficPolicy
When checking probe in LB, only the corresponding one
should be checked.
* remove tests about updating services between internal and public since
the one in k8s e2e has been recovered
Fixes #
```release-note
NONE
```
```docs
```
=> Improve flaky e2e tests

cloudbuild.yaml
This version uses golang 1.19
/kind testing
Bump gcb-docker-gcloud to v20220830-45cbff55bc
related: https://github.com/kubernetes/test-infra/pull/27268
Fixes #
```release-note
NONE
```
```docs
```
=> Bump gcb-docker-gcloud to v20220830-45cbff55bc

pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go
/kind feature
This PR is the Part 7 of VMSet implementation, mainly focus on removing LB backend pool from VMSS Flex VM related functions
Refer to #639 
```release-note
NONE
```
```docs
```
=> VMSS Flex Support: Part 7 of VMSet implementation: removing LB backend pool from VMSS Flex VM related functions

pkg/provider/azure_managedDiskController.go
/kind feature
feat: add Location field in DiskOptions
Fixes #
```release-note
feat: add Location field in DiskOptions
```
```docs
feat: add Location field in DiskOptions
```
=> feat: add Location field in DiskOptions

pkg/consts/consts.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind feature
It reads tag `aks-managed-coordination` from VMSS, and then only invoke parallel network profile update APIs when the tag exists (tag value could be omitted)
Fixes #
```release-note
NONE
```
```docs
```
=> Invoke VMSS parallel update API when vmss tag exists

pkg/consts/consts.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind feature
This is a cherry-pick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2275
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] Invoke VMSS parallel update API when vmss tag exists

pkg/azureclients/fileclient/azure_fileclient.go, pkg/azureclients/fileclient/interface.go, pkg/azureclients/fileclient/mockfileclient/interface.go, pkg/provider/azure_file.go, pkg/provider/azure_storage.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_storageaccount.go
/kind bug
As the description in the issue https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1083, here we reuse the context from external-provisioner to cancel the context when timeout. Then the volume won't be locked in driver.
Now, we update the parameters in cloud provider azure. Then we will update azurefile csi driver repo to consume the new parameters.
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1083
None
```release-note
None
```
```docs
None
```
=> Pass the context for AzureFile

pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/armclient/util.go
/kind bug
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
Fixes #2296
```release-note
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
```
```docs
```
=> Retry if response StatusCode 200 and ContentLength -1

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
Fixes #
```release-note
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
```
```docs
```
=> [release-1.1] Retry if response StatusCode 200 and ContentLength -1

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
Fixes #
```release-note
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
```
```docs
```
=> [release-1.23] Retry if response StatusCode 200 and ContentLength -1

pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/armclient/util.go
/kind bug
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
Fixes #
```release-note
ARM will possibly return StatusCode 200 and ContentLength -1 which is a bug. However, cloudprovider can handle it better by retrying.
```
```docs
```
=> [release-1.24] Retry if response StatusCode 200 and ContentLength -1

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go, pkg/azureclients/armclient/util.go
/kind bug
Only check response body length when request is GET.
related #2296 
```release-note
Only check response body length when request is GET. Avoids unnecessary retry when deleting an LB.
```
```docs
```
=> fix: Do not retry regional when request is not GET

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
Cherry pick PR #2363 
Fixes #
```release-note
Only check response body length when request is GET. Avoids unnecessary retry when deleting an LB.
```
```docs
```
=> [release-1.23] fix: Do not retry regional when request is not GET

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/consts/consts.go, pkg/provider/azure_vmss_test.go
/kind bug
- Skip VMSS VM update operations when:
1. PUT request returns ParentResourceNotFound error;
2. PUT request returns InstanceIdsListInstanceIdNotActiveVM error;
- Set the retryAfter to 5s when PUT failed due to concurrent operation conflict.
Fixes #2356
```release-note
fix: Skip VMSS VM update operations if the VMs are not in good state
fix: Set the retryAfter to 5s when PUT failed due to concurrent operation conflict.
```
```docs
```
=> fix: Skip VMSS VM update operations if the VMs are not in good state

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Avoid race condition between node-sync-loop routine and service reconcile routine.
Avoid UpdateLoadBalancer() using stale service spec to update Load Balancers.
Fixes #
```release-note
Avoid race condition between node-sync-loop routine and service reconcile routine.
Avoid UpdateLoadBalancer() using stale service spec to update Load Balancers.
```
```docs
```
=> Get latest service before UpdateLoadBalancer and serialize LB reconcile

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind testing
Add missing e2e tests for following service annotations:
1. `ServiceAnnotationAdditionalPublicIPs`
2. `ServiceAnnotationLoadBalancerEnableHighAvailabilityPorts`
3. `ServiceAnnotationLoadBalancerHealthProbeInterval`
Fixes #
Note that improving test for annotation `ServiceAnnotationLoadBalancerMode` needs to change cloud-config. I will implement that in the next PR.
```release-note
NONE
```
```docs
```
=> add e2e tests for service annotations

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind cleanup
Get node private IPs from cache but NIC to reduce API calls to the NIC.
Fixes #2355
```release-note
chore: get node private IPs from cache but NIC
```
```docs
```
=> chore: get node private IPs from cache but NIC

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go
/kind bug
When a service is changed from LoadBalancer type to any others, cloud provider should make sure both ELB and ILB are cleaned up.
Fixes #2357 
```release-note
```
```docs
```
=> GetLoadBalancer and EnsureLoadBalancerDeleted should check both ELB and ILB

pkg/provider/azure_instance_metadata.go, pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go
/kind feature
Error Description:
When using VMSS Flex as K8s nodes, if the VM is created by using the VMSS default VM profile and increasing the capacity, then Cloud Node Manager (CNM) will generate the wrong ProviderID for the node.
Root Causes:
There are 2 issues in the existing CNM code that cause the error:
Issue 1: CNM UNSAFELY distinguishes Uniform VM and Non Uniform VM by just checking if the VM name contains underscore (_): if the VM name contains underscore, then CNM treats the VM as VMSS Uniform node, then further assumes the part before underscore is vmss name; if the VM name does not contain underscore, then CNM treats the VM as non Uniform node : [https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_instances.go#L394-L403](https://nam06.safeli …
=> VMSS Flex Support: Cloud Node Manager should query resourceId field of IMDS endpoint to retrieve providerID

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, site/content/en/topics/pls-integration.md, site/content/en/topics/shared-ip.md, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go
/kind cleanup
/kind feature
/kind deprecation
Deprecate LoadBalancerIP with Servie LB IP annotation
* Add service.beta.kubernetes.io/azure-load-balancer-ipv4
and service.beta.kubernetes.io/azure-load-balancer-ipv6
* Add an e2e test
* Support retrieve Service CIDR in e2e framework
related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/814
Fixes #
```release-note
Deprecate LoadBalancerIP with Servie LB IP annotation. Add service.beta.kubernetes.io/azure-load-balancer-ipv4 and service.beta.kubernetes.io/azure-load-balancer-ipv6
```
```docs
```
=> Deprecate LoadBalancerIP with Servie LB IP annotation

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: add AccessTier and SMB MultiChannel support in storage account creation
Fixes #
```release-note
feat: add AccessTier and SMB MultiChannel support in storage account creation
```
```docs
feat: add AccessTier and SMB MultiChannel support in storage account creation
```
=> feat: add AccessTier and SMB MultiChannel support in storage account creation

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, site/content/en/topics/pls-integration.md, site/content/en/topics/shared-ip.md, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/kubectl.go, tests/e2e/utils/network_utils.go
* Add service.beta.kubernetes.io/azure-load-balancer-ipv4 and service.beta.kubernetes.io/azure-load-balancer-ipv6
* Add an e2e test
* Support retrieve Service CIDR in e2e framework
/kind cleanup
/kind feature
/kind deprecation
Deprecate LoadBalancerIP with Servie LB IP annotation
Fixes #
```release-note
Deprecate LoadBalancerIP with Servie LB IP annotation
```
```docs
```
=> [release-1.1] Deprecate LoadBalancerIP with Servie LB IP annotation

pkg/provider/azure_storageaccount.go
/kind cleanup
- cleanup: fix logging error
- chore: refactor SetServiceProperties logic in storage account creation
Fixes #
```release-note
none
```
```docs
none
```
=> chore: refactor SetServiceProperties logic in storage account creation

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Check internal lb ip in subnet before keeping it, so cx can change their lb subnet
Fixes #2511 
```release-note
Check internal lb ip in subnet before keeping it, so users can change their lb subnet.
```
```docs
```
=> fix: check internal lb ip in subnet before keeping it

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
/kind bug
We parse the id of ipConfigs in the lb backend pool to determine what vmss are needed to be decoupled from the lb. But for those with 0 instance, they cannot be decoupled since there is no corresponding ipConfigs in the lb. This PR checks all cached vmss, if it is bound with the lb, we decouple it.
Fixes #2443 
```release-note
fix: decouple vmss with 0 instance from lb when deleting the service
```
```docs
```
=> [release-1.25] fix: decouple vmss with 0 instance from lb when deleting the service

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
/kind bug
We parse the id of ipConfigs in the lb backend pool to determine what vmss are needed to be decoupled from the lb. But for those with 0 instance, they cannot be decoupled since there is no corresponding ipConfigs in the lb. This PR checks all cached vmss, if it is bound with the lb, we decouple it.
Fixes #2443 
```release-note
fix: decouple vmss with 0 instance from lb when deleting the service
```
```docs
```
=> [release-1.24] fix: decouple vmss with 0 instance from lb when deleting the service

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_controller_common.go
/kind feature
Currently, the CCM first checks the node type then chooses the correct VMSet implementation for the corresponding operation. It mantains a cache for the ndoe type and refreshes the cache by calling an Azure API every time the cache expires. In pure vmssflex node cluster, the node type check can be bypassed to reduce the API calls to Azure.
Fixes #639 
```release-note
NONE
```
```docs
```
=> VMSS Flex Support: Add a new vmType for pure VMSS Flex cluster to bypass the node type check

tests/e2e/network/service_annotations.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/pod_utils.go
/kind testing
Fix e2e code compatibility for aks-engine clusters
* Remove unnecessary delete PIP function
* Use Linux selector for exec-agnhost-pod
Fixes #
```release-note
NONE
```
```docs
```
=> Fix e2e code compatibility for aks-engine clusters

go.mod, pkg/provider/azure_controller_common.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go
/kind bug
fix: avoid recreate vmss cache in race condition
In race condition, there could be duplicated `getVMSSVMCache` calls, and it would end up with creating two vmss cache objects, related logs:
<details>
```
I1018 03:18:45.242671       1 azure_vmss.go:204] Couldn't find VMSS VM with nodeName aks-agentpool-34156162-vmss00000j, refreshing the cache(vmss: aks-agentpool-34156162-vmss, rg: aksdiskscaleai2f68d-nodegroup)
I1018 03:18:45.242671       1 azure_vmss.go:204] Couldn't find VMSS VM with nodeName aks-agentpool-34156162-vmss00000j, refreshing the cache(vmss: aks-agentpool-34156162-vmss, rg: aksdiskscaleai2f68d-nodegroup)
I1018 03:18:47.272599       1 azure_vmss.go:204] Couldn't find VMSS VM with nodeName aks-agentpool-34156162-vmss00000x, refreshing the cache(vmss: …
```
=> fix: avoid recreate vmss cache in race condition

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go
/kind bug
We parse the id of ipConfigs in the lb backend pool to determine what vmss are needed to be decoupled from the lb. But for those with 0 instance, they cannot be decoupled since there is no corresponding ipConfigs in the lb. This PR checks all cached vmss, if it is bound with the lb, we decouple it.
Fixes #2443 
```release-note
fix: decouple vmss with 0 instance from lb when deleting the service
```
```docs
```
=> [release-1.1] fix: decouple vmss with 0 instance from lb when deleting the service

pkg/azureclients/fileclient/azure_fileclient.go, pkg/azureclients/fileclient/interface.go, pkg/azureclients/fileclient/mockfileclient/interface.go, pkg/provider/azure_file.go, pkg/provider/azure_storage_test.go
/kind feature
feat: support snapshot with management api
Fixes #
```release-note
feat: support snapshot with management api
```
```docs
```
=> feat: support snapshot with management api

tests/e2e/network/network_security_group.go, tests/e2e/utils/pod_utils.go
Use node os label to select node for ExecAgnhostPod Fix azure-deny-all-except-load-balancer-source-ranges test bug Check lb type before pip-prefix-id test
(cherry picked from commit 21a6572fca7bc25aa6a3f0672a28fc31709030d1)
Fix the bug in the e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.1] Dump Pod describe if WaitPodTo() fails

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex_cache.go, pkg/util/deepcopy/deepcopy.go, pkg/util/deepcopy/deepcopy_test.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> Deepcopy results of cache Get()

pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go
/kind bug
When using https://github.com/kubernetes-sigs/azuredisk-csi-driver with Flex VMSS, I observed that it fails to attach and detach disks from VMs. This is due to it trying to use k8s Node name instead of VM name when interacting with Azure APIs. This PR updates this logic to use a correct name.
```release-note
Fixed a bug that prevents disks from being attached and detached for VMs in a Flex VMSS
```
=> Use VM name instead of Node name for disk operations with Flex VMSS

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind bug
fix: should update dns label if target pip already have one and it needs update
Fixes #
```release-note
Fix an issue when DNS label of public ip is not updated when service.beta.kubernetes.io/azure-dns-label-name is changed. 
```
```docs
```
=> fix: should update dns label if target pip already have one and it needs update

pkg/provider/azure_vmssflex.go
/kind bug
In the current code, CCM fails to add/delete LB backendPool from VMSS Flex with error:
```
E1101 21:37:22.222983 1 controller.go:320] error processing service default/elb (will retry): failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
"error": {
"details": [],
"code": "NetworkApiVersionMustBeSpecifiedWithNetworkInterfaceConfigurations",
"message": "Network api version in network profile of virtual machine /subscriptions/ccde0aa8-3434-40ee-8442-13c8e4160d62/resourceGroups/MIZHE-K8SFLEX/providers/Microsoft.Compute/virtualMachines/k8sflex-mp-079f5ae27-ce00-4aa4-a161-18803ce7a3d5 must be specified if network interface configurations are specified."
}
}
```
Below is the reponse from VMSS Flex team:
**"With VMSS Uniform, the …
=> Fix Bug: NetworkApiVersionMustBeSpecifiedWithNetworkInterfaceConfigurations for VMSS Flex Network Profile operation

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex_cache.go, pkg/util/deepcopy/deepcopy.go, pkg/util/deepcopy/deepcopy_test.go
/kind bug
cherrypicks: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2445
Fixes #
```release-note
```
```docs
```
=> [release-1.25] Deepcopy results of cache Get()

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/provider/azure_vmss_test.go, pkg/util/deepcopy/deepcopy.go, pkg/util/deepcopy/deepcopy_test.go
/kind bug
[release-1.24] Deepcopy results of cache Get()
#2445 
Fixes #
```release-note
```
```docs
```
=> [release-1.24] Deepcopy results of cache Get()

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
Cleanup PR
This is a PR to remove the deprecated [labels](https://learn.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels) and the tests testing those deprecated labels.
Fixes #[2453](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2453)
I am wondering if we want to remove the label reconciler too since its functionality depended on those labels? or we can keep it for future labels we might want to attach to the nodes.
```release-note
The following labels are removed on the nodes:
* "failure-domain.beta.kubernetes.io/zone" 
* "failure-domain.beta.kubernetes.io/region"
* "beta.kubernetes.io/instance-type"
```
=> Removed Deprecated labels from cloud-node-manager

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache_test.go, pkg/provider/azure_vmssflex_test.go
/kind bug
When deleting backend pool from VMSS, both VMSS Uniform and VMSS Flex are added into the same vmssNameMap: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_vmss.go#L1755.
However, CCM tries to find those VMSS from the VMSS Uniform cache: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_vmss.go#L2045. Because of that, VMSS Flex cannot be found and returns "Instance not found" error
This PR tries to fix this issue.
Fixes #2690 
```release-note
NONE
```
```docs
```
=> Fix issue: CCM fails to delete LB because updating VMSS Flex network profile fails

pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go, pkg/azureclients/vmssvmclient/interface.go, pkg/azureclients/vmssvmclient/mockvmssvmclient/interface.go, pkg/cache/azure_cache.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss_cache.go
/kind feature
This PR reduces the number of calls to the VMSSVMList by using the Update response to update the VMSSVMCache. This inherently increases the performance of AttachDisk, DetachDisk and UpateVM calls to VMSS vmtype.
Fixes #
```release-note
NONE
```
```docs
```
=> Fix: Updating vmssvmcache instead of invalidating vm entry on UpdateVM operation

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/util/deepcopy/deepcopy.go, pkg/util/deepcopy/deepcopy_test.go
/kind bug
[release-1.23] Deepcopy results of cache Get()
#2445 
Fixes #
```release-note
```
```docs
```
=> [release-1.23] Deepcopy results of cache Get()

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
We should add  get PrivateDNSZone and get VNetLink to make this func idempotent, so that even creation return failed, it should succeeded in next try
Fixes #
```release-note
fix: check private dns zone before creation
```
```docs
```
=> fix: check private dns zone before creation

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_cache_test.go, pkg/util/deepcopy/deepcopy.go, pkg/util/deepcopy/deepcopy_test.go
/kind bug
[release-1.1] Deepcopy results of cache Get()
#2445 
Fixes #
```release-note
```
```docs
```
=> [release-1.1] Deepcopy results of cache Get()

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, site/content/en/topics/loadbalancer.md
/kind feature
This adds `service.beta.kubernetes.io/port_<num>_health-probe_protocol` and `service.beta.kubernetes.io/port_<num>_health-probe_port` annotations for LoadBalancer Services. These allow overriding the health check port or protocol for a given port. This is useful for ports that cannot respond affirmatively to the health checks and expose health information elsewhere.
Fixes #1505 
This continues https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1508 and attempts to address the open issue with it. I rebased onto upstream master and added commits to de-duplicate checks and correct an apparent error in the original docs (`/` is the default check path, not `/healthz`).
I'm not quite sure I understand the duplication concern raised in …
=> Add support for specifying probe protocol / probe port via annotation per service port

kubetest2-aks/deployer/up.go
10 second is not enough.
/kind testing
Larger timeout for aks cluster creation
Fixes #
```release-note
NONE
```
```docs
```
=> Larger timeout for aks cluster creation

tests/e2e/autoscaling/autoscaler.go, tests/e2e/network/node.go, tests/e2e/network/standard_lb.go, tests/e2e/node/vmss.go, tests/e2e/utils/vmss_utils.go
/kind feature
This PR modifies E2E tests for VMSS Flex cluster
Refer to #2731 
Currently, 5 of 48 tests fails for VMSS Flex:
This PR tries to resolve the failed tests:
- Lifecycle of VMSS should add node object when VMSS instance allocated [VMSS]: This test is skipped for VMSS Flex since the test logic only works for VMSS Uniform
- Lifecycle of VMSS should delete node object when VMSS instance deallocated [VMSS]: This test is skipped for VMSS Flex since the test logic only works for VMSS Uniform
- [StandardLoadBalancer] Standard load balancer should add all nodes in different agent pools to backends [Multi-Nodepool]: Modify this test to work with both VMSS Flex and Uniform
- Azure node resources should set correct private IP address for every node [Node]: Modify this …
=> [E2E][VMSS Flex] Modify E2E tests for VMSS Flex cluster

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss.go
/kind bug
`safeDeleteLoadBalancer` uses `isLBBackendPoolTypeIPConfig` to determine if we should call `vmSet.EnsureBackendPoolDeleted`, because for IP-based backend pools, we don't need to decouple the vmss from the lb before we delete the lb. But `isLBBackendPoolTypeIPConfig` cannot tell the backend pool type if it is empty. In this case, the lb cannot be deleted if the vmss (not the vmss vms) is still referencing the lb. This PR removes the check. If the backend pool is IP-based, `vmSet.EnsureBackendPoolDeleted` will be a no-op.
Fixes #
```release-note
fix: remove lb from vmss when the backend pool is empty
```
```docs
```
=> fix: remove lb from vmss when the backend pool is empty

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
related #2707 
```release-note
```
```docs
```
=> [release-1.25] fix public ip list call reduce

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go
/kind bug
fix: add disk lun check in AttachDisk to avoid race condition
Fixes #
There is corner case that second disk attach would get a different LUN num and since disk is already attached to the other LUN num (first disk attach may already time out), second disk attach is returned with a wrong LUN num
```release-note
fix: add disk lun check in AttachDisk to avoid race condition
```
```docs
fix: add disk lun check in AttachDisk to avoid race condition
```
=> fix: add disk lun check in AttachDisk to avoid race condition

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go
/kind bug
fix: resource group issue in disk attach
Original behavior is using disk resource group as node resource group which is wrong, there would be issue when disk is not in node resource group, this PR fixes the issue.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c905fb10cb277916fb580fef75d276f328bc0d7c/pkg/provider/azure_controller_common.go#L270-L274
Fixes #
```release-note
fix: resource group issue in disk attach
```
```docs
fix: resource group issue in disk attach
```
=> fix: resource group issue in disk attach

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmsets.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go, pkg/provider/azure_wrap.go
/kind bug
/kind cleanup
1. We remove all backend pool refs from the vmss when the backend pool type is migrated from nic to IP. But we only do this when there are vms in the backend pool. If there is no VM in the pool, we ignore this operation, leaving the lb backend pool in the vmss model. In this case, if we scale the vmss up, the new VM will be automatically attached to the backend pool, which is not allowed because the pool is already ip-based. We hit the issue only when there is no node in the cluster and we try to migrate the backend pool type from nic to ip, which is not allowed in AKS, so only self-managed clusters are influenced. This PR ensures the vmss will be decoupled from the backend pool even when the pool is empty. If the vmss has already been decoupled, it will be a …
=> Refine ip-based backend pool logic

pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_vmssflex_cache_test.go
/kind bug
fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition
preceding fix of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2805
Fixes #
```release-note
fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition
```
```docs
fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition
```
=> fix: add disk lun check in VMSSFlex AttachDisk to avoid race condition

pkg/provider/azure_utils.go
Lock the entry to prevent dirty reading. Failed test log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/2834/pull-cloud-provider-azure-unit/1598185443239661568
Fixes #
We can use read-write mutex here but I don't the efficiency is the bottleneck of our project.
```release-note
NONE
```
```docs
```
=> fix: lock the entry when reading data

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_vmss.go
…vm is not found
/kind cleanup
There is a chance that the VM is deleted but its nic is still referred by the lb backend pool. This PR removes the orphaned nic references when the VM is not found to reduce API calls.
Fixes #
```release-note
chore: remove orphaned nic from lb backend pool if the corresponding VM is not found
```
```docs
```
=> [release-1.25] chore: remove orphaned nic from lb backend pool if the corresponding … 

.golangci-test.yml, pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind feature
add a new annotation service.beta.kubernetes.io/port_%d_health-probe_only
with this annotation applied, no lbrules will be create for the corresponding port. 
The user can create health probe rules without exposing health probe endpoint to public internet
behavior change in health probe rule generation:
the health probe rule will not be overwritten
the name of health probe rule has not changed because we don't want to trigger unnecessary lb update event after version upgrade.
Fixes #
docs will be updated after the changes has been cherry-picked.
```release-note
Add annotation service.beta.kubernetes.io/port_%d_no_lb_rule, with this annotation in svc manifest, no loud balancing rules will be created for the corresponding port and health status port will not be exposed to …
```
=> Feat:Add annotation service.beta.kubernetes.io/port_%d_health-probe_only

.gitignore, kubetest2-aks/README.md, kubetest2-aks/cluster-templates/autoscaling-multipool.json, kubetest2-aks/cluster-templates/autoscaling.json, kubetest2-aks/cluster-templates/basic-lb.json, kubetest2-aks/deployer/up.go
/kind feature
MSI is preferable over service principal in consideration of future maintenance and has been the default credential in AKS to manage AKS resource groups for a while.
This PR add system-assigned identity support to kubetest2-aks and remove credentials in the log output, which is better to be sanitized.
The test has been done:
- When SP is specified, AKS cluster is created with SP:
```
➜  kubetest2-aks git:(kube-aks-msi) ✗ kubetest2 aks --up --rgName aks-resource-group4 --location eastus --config cluster-templates/basic-lb.json --customConfig cluster-templates/customconfiguration.json
--clusterName aks-cluster --ccmImageTag abcdefg --k8sVersion 1.24.6
I1206 02:02:06.670723 1027879 app.go:61] The files in RunDir shall not be part of Artifacts
I1206 02:02:06.670785 1027879 …
```
=> feat: add system assigned identity support for kubetest2-aks

.golangci-test.yml, pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, site/content/en/topics/loadbalancer.md, tests/e2e/network/service_annotations.go
/kind feature
This adds service.beta.kubernetes.io/port_<num>_health-probe_protocol and service.beta.kubernetes.io/port_<num>_health-probe_port annotations for LoadBalancer Services. These allow overriding the health check port or protocol for a given port. This is useful for ports that cannot respond affirmatively to the health checks and expose health information elsewhere.
Fixes #
```release-note
Added: support for new annotations **service.beta.kubernetes.io/port_<num>_health-probe_protocol** and **service.beta.kubernetes.io/port_<num>_health-probe_port** to allow explicitly setting the health probe protocol individually for each service port. Useful for services like Istio which have health check seperate from the main service port.
```
```docs
```
=> [release-1.25]Add support for specifying probe protocol / probe port via annotation per service port

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/consts/helpers_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, site/content/en/topics/loadbalancer.md, tests/e2e/network/service_annotations.go
/kind feature
This adds service.beta.kubernetes.io/port_health-probe_protocol and service.beta.kubernetes.io/port_health-probe_port annotations for LoadBalancer Services. These allow overriding the health check port or protocol for a given port. This is useful for ports that cannot respond affirmatively to the health checks and expose health information elsewhere.
Fixes #
```release-note
Added: support for new annotations **service.beta.kubernetes.io/port_<num>_health-probe_protocol** and **service.beta.kubernetes.io/port_<num>_health-probe_port** to allow explicitly setting the health probe protocol individually for each service port. Useful for services like Istio which have health check seperate from the main service port.
```
```docs
```
=> [release-1.24]Add support for specifying probe protocol / probe port via annotation per service port 

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/service_utils.go
/kind bug
Fix k8s-azure-dns-label-service tag not deleted with Service
Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
Fixes #
```release-note
Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
```
```docs
```
=> Fix k8s-azure-dns-label-service tag not deleted with Service

go.mod, go.sum, vendor/golang.org/x/net/http2/hpack/encode.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
/kind bug
fix: CVE-2022-41717
```
──────────────────┬────────────────┬──────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                            Title                             │
├──────────────────┼────────────────┼──────────┼───────────────────┼───────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-[41](https://github.com/kubernetes-sigs/azurefile-csi-driver/actions/runs/3658032645/jobs/6182309696#step:6:42)717 │ UNKNOWN  │ v0.2.0            │ 0.4.0         │ An attacker can cause excessive memory growth in a Go …
```
=> fix: CVE-2022-41717

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient.go, pkg/azureclients/vmssvmclient/azure_vmssvmclient_test.go
/kind bug
Adds missing calls to close the response body in WaitForUpdateResult implementations, the lack of which was causing excessive memory usage during Azure Disk CSI Driver scale testing.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: close WaitForUpdateResult response

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/service_utils.go
/kind bug
Fix k8s-azure-dns-label-service tag not deleted with Service
Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
Fixes #
```release-note
Fix k8s-azure-dns-label-service tag not deleted with Service. Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
```
```docs
```
=> [release-1.25] Fix k8s-azure-dns-label-service tag not deleted with Service

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/service_utils.go
/kind bug
Fix k8s-azure-dns-label-service tag not deleted with Service
Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
Fixes #
```release-note
Fix k8s-azure-dns-label-service tag not deleted with Service. Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
```
```docs
```
=> [release-1.24] Fix k8s-azure-dns-label-service tag not deleted with Service

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/service_utils.go
Fix k8s-azure-dns-label-service tag not deleted with ServiceBug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
/kind bug
Fix k8s-azure-dns-label-service tag not deleted with Service
Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
Fixes #
```release-note
Fix k8s-azure-dns-label-service tag not deleted with Service. Bug: When a Service with DNS label is deleted, k8s-azure-dns-label-service tag won't be deleted and it leads to ensurePublicIPExists error.
```
```docs
```
=> [release-1.23] Fix k8s-azure-dns-label-service tag not deleted with Service

pkg/consts/consts.go, pkg/nodeipam/node_ipam_controller.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go, pkg/retry/azure_error.go
/kind cleanup
* This PR allows `cloud-provider-azure` to retry vm update on `OperationPreempted` error with http status code of 2xx, where storage config change has been committed but vm update has failed.
* This PR adds `PartialUpdateError` type to implement `error` interface to be returned for other VM update failures with status code of 2xx.
* This PR purports to address a reported customer issue where attaches fail due to `OperationPreempted` error.
Fixes #
```release-note
NONE
```
```docs
```
=> feat: detect errors that requires vm udpate retries and retry if detected

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap.go, tests/e2e/network/node.go, tests/e2e/node/vmss.go, tests/e2e/utils/consts.go, tests/e2e/utils/vmss_utils.go
Fixes #
```release-note
```
```docs
```
=> Use TimedCache.Get() for read-only resources

.github/workflows/release.yaml
/kind cleanup
When publishing a new minor version (e.g. v1.26.0), the release note should be generated against the last minor version (e.g. v1.25.0 - v1.26.0)
Fixes #
```release-note
NONE
```
```docs
```
=> build(release): generate release note from last minor version when release a new minor version

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: support PrivateDNSZone in sovereign cloud
Fixes #
```release-note
fix: support PrivateDNSZone in sovereign cloud
```
```docs
fix: support PrivateDNSZone in sovereign cloud
```
=> fix: create PrivateDNSZone error in sovereign cloud

pkg/provider/azure.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_storage.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_vmssflex.go
/kind cleanup
cleanup: remove unused controllerCommon fields
fileds in `controllerCommon` struct is copied from cloud struct, those are redundant fields, this PR removes those fields, make the logic simpler
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: remove unused controllerCommon fields

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmclient/interface.go, pkg/azureclients/vmclient/mockvmclient/interface.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmssflex_cache.go
/kind feature
feat: update cache support for starndard and vmss flex
This PR is a preceding fix of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2608, also refines original update cache logic in VMSS
Fixes #
```release-note
feat: update cache support for starndard and vmss flex
```
```docs
feat: update cache support for starndard and vmss flex
```
=> feat: update cache support for starndard and vmss flex

pkg/provider/azure_vmssflex_cache.go
/kind bug
Currently refreshing the cache for VMSS flex in `getNodeVmssFlexID` is very expensive as each scale set is refreshed despite only needing to get the scale set for the specified node - this often leads to hitting ARM rate limits in even small sized environments. 
- To reduce calls to ARM APIs here I try and work out the correct scaleset from the node name by stripping the last 6 characters (similar to how the uniform version of this works) - this works for VMs which are created in flex scalesets using scaling as the vmss name is used as the computer name prefix, for vm's which are added to a Flexible scale set this won't be useful. The results are either appended or prepended to a slice to provide an ordered list of vmss to check
- Using the above slice we continue to refresh the …
=> improvement: Flex - Reduce throttling on Attach/Detach disk operations

pkg/provider/azure_utils.go, pkg/provider/azure_vmss_test.go
/kind bug
fix: race condition in lockMap
`lm.Lock()` is intended for locking `lm.mutexMap`, while original logic in `LockEntry` does not lock `lm.mutexMap` well, in `lm.lockEntry(entry)`, it's still accessing `lm.mutexMap` outside of `lm.Lock()`  ... ``lm.Unlock()``
This PR removes `addEntry` func invoke, make `lm.mutexMap` access inside of `lm.Lock()`  ... ``lm.Unlock()``, and then lock ougside.
Fixes #
- original race condition logs in unit test with `go test -race`:
```
=== RUN   TestEnsureBackendPoolDeletedConcurrently
W1221 07:57:03.975735   26563 azure_vmssflex_cache.go:59] failed to get the ID of VMSS Flex
W1221 07:57:03.975783   26563 azure_vmssflex_cache.go:59] failed to get the ID of VMSS Flex
==================
WARNING: DATA RACE
Write at 0x00c000596510 by goroutine 719: …
```
=> fix: race condition in lockMap

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
Fixes #
```release-note
feat: Support private endpoint for blob-csi-driver
```
```docs
```
=> feat: Support privateendpoint for blob-csi-driver

pkg/azureclients/armclient/azure_armclient.go
/kind bug
set ForceAttemptHTTP2 as false to respect custom dialer, after setting as false, the RoleInstance distribution is balanced a lot, this could also reduce ARM/VMSS throttling since ARM RoleInstance handling is distributed.
```
While HTTP/2 has many advantages abstractly, we have not been able to put in in mainline use in the control plane so far primarily because it doesn’t mesh well with the load-balanced architecture. You’d have to invest quite a bit in connection health and load-balancing management on the client side to get the robustness of HTTP/1.1 with lots of concurrent connections. 
To nail this down, try forcing your client to use HTTP/1.1 and see if the requests start getting distributed across many ARM FEs.
```
- ForceAttemptHTTP2 as true
RoleInstance | userAgent | …
=> fix: set ForceAttemptHTTP2 to increase ARM throttling limit

.pipelines/scripts/run-e2e.sh
/kind bug
Fixes #
```release-note
None
```
```docs
```
=> fix: jq last returns null when no match

site/content/en/topics/loadbalancer.md
[Doc] Add Service Azure LB IPv4 & IPv6 to LB doc
Fixes #
```release-note
NONE
```
```docs
```
=> [Doc] Add Service Azure LB IPv4 & IPv6 to LB doc

.pipelines/scripts/run-e2e.sh, .pipelines/templates/customconfiguration-autoscaling.json
/kind testing
Set --skip-nodes-with-system-pods to false when running autoscaling tests
Currently without this option (default: true), it is possible that some deployments like metrics-server will be allocated to the new Node. In this case, when scaling down, no Nodes can be deleted.
https://github.com/Azure/AKS/issues/875#issuecomment-475486313
Fixes #
```release-note
NONE
```
```docs
```
=> Set --skip-nodes-with-system-pods to false when running autoscaling tests

go.mod, go.sum, pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, vendor/golang.org/x/sync/semaphore/semaphore.go, vendor/golang.org/x/sync/singleflight/singleflight.go, vendor/modules.txt
/kind bug
Since `TimedCache` relies on a per-entry `sync.Mutex` to serialize calls to the refresh function, `TimedCache.Update` **must** update the existing entry rather than replace it to ensure proper synchronization. Otherwise, it is possible for multiple concurrent calls to the refresh function to occurr.
Fixes #
```release-note
Fixes an issue in the `TimedCache` implementation that could result in multiple concurrent calls to the getter function.
```
```docs
```
=> fix: update rather than replace existing cache entry

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap.go, tests/e2e/network/node.go, tests/e2e/node/vmss.go, tests/e2e/utils/consts.go, tests/e2e/utils/vmss_utils.go
/kind bug
Cherry pick of #2949 against release-1.25: Use TimedCache.Get() for read-only resources
Fixes #
```release-note
fix: Use TimedCache.Get() for read-only resources
```
```docs
```
=> [release-1.25] Use TimedCache.Get() for read-only resources

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap.go, tests/e2e/network/node.go, tests/e2e/node/vmss.go, tests/e2e/utils/consts.go, tests/e2e/utils/vmss_utils.go
/kind bug
Cherry pick of #2949 against release-1.24: Use TimedCache.Get() for read-only resources
Fixes #
```release-note
fix: Use TimedCache.Get() for read-only resources
```
```docs
```
=> [release-1.24] Use TimedCache.Get() for read-only resources

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: add more account search options
a proceeding fix of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3082
Fixes #
```release-note
fix: add more account search options
```
```docs
fix: add more account search options
```
=> fix: add more account search options

tests/e2e/utils/vmss_utils.go
/kind testing
Fix VMSS scale test in multipool clusters
Fix an e2e test code bug: instanceSet should include all instances of all VMSSes and nodeSet also
includes Nodes of all VMSSes. So, when iterating expectedCap, instanceSet.Insert() shouldn't be skipped. Also, len of nodeSet shouldn't be compared with cap.
Fixes #
```release-note
NONE
```
```docs
```
=> Fix VMSS scale test in multipool clusters

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind feature
Use list pip ARM call to refresh pipcache, listing pip function queries from cache instead of making direct arm api call.
This can reduce pip list arm calls.
Fixes #
related #3088 
```release-note
NONE
```
```docs
```
=> [release-1.26] use pip list in pip cache

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind feature
Use list pip ARM call to refresh pipcache, listing pip function queries from cache instead of making direct arm api call.
This can reduce pip list arm calls.
Fixes #
related #3088 
```release-note
NONE
```
```docs
```
=> [release-1.25] use pip list in pip cache

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind feature
Use list pip ARM call to refresh pipcache, listing pip function queries from cache instead of making direct arm api call.
This can reduce pip list arm calls.
Fixes #
related #3088 
```release-note
NONE
```
```docs
```
=> [release-1.23] use pip list in pip cache

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind feature
Use list pip ARM call to refresh pipcache, listing pip function queries from cache instead of making direct arm api call.
This can reduce pip list arm calls.
Fixes #
related #3088 
```release-note
NONE
```
```docs
```
=> [release-1.24] use pip list in pip cache

pkg/azureclients/blobclient/azure_blobclient.go, pkg/azureclients/blobclient/interface.go, pkg/azureclients/blobclient/mockblobclient/interface.go, pkg/provider/azure_storage_test.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
support data protection for blob csi driver
Fixes #
```release-note
support data protection for blob csi driver
```
```docs
```
=> feat: support data protection for blob csi driver

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go
/kind cleanup
chore: refine logging for azure disk csi driver
Fixes #
```release-note
none
```
```docs
none
```
=> chore: refine logging for azure disk csi driver

.pipelines/scripts/run-e2e.sh
For release 1.23, go version is 1.17 but kubetest2-aks is 1.18. go mod tidy should use option -compa=1.17 to solve the mod selection problem.
/kind testing
Fix go 1.17 mod selection issue in run-e2e.sh
Fixes #
```release-note
NONE
```
```docs
```
=> Fix go 1.17 mod selection issue in run-e2e.sh

pkg/consts/consts.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/network_utils_test.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Support dual-stack - utils
* Support dual-stack in e2e utils functions and methods
* Adjust related e2e test code
* Define dual-stack Service annotations
Fixes #
Related #814
```release-note
NONE
```
```docs
```
=> [e2e] Support dual-stack - utils

Makefile
/kind cleanup
Disable provenance attestation to workaround docker buildx issue
related: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1712
Fixes #
For docker buildx build, set `--provenance=false` to workaround buildkit v0.11.0's enabling provenance attestation by default
```release-note
NONE
```
```docs
```
=> Disable provenance attestation to workaround docker buildx issue

cloudbuild.yaml
/kind cleanup
Bump gcb-docker-gcloud image version. New image has latest docker buildx.
related: https://github.com/kubernetes/test-infra/pull/28649
Fixes #
```release-note
NONE
```
```docs
```
=> Bump gcb-docker-gcloud image version

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, tests/e2e/network/network_security_group.go
/kind bug
Fix how getSecurityRuleName() handles IPv6 addr prefix
Error msg is like: `Resource name a29b3b265d9f84776b6c877408e7a519-TCP-80-2001:1234:5678:9abd::4_128 is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."`
* Bug fix
* Add UT and adjust e2e
Fixes #
```release-note
Fix incorrect security rule name with IPv6 address prefix
```
```docs
```
=> Fix how getSecurityRuleName() handles IPv6 addr prefix

pkg/retry/azure_retry_test.go
Fixes #
```release-note
```
```docs
```
=> Fix TestJitterWithNegativeMaxFactor UT

pkg/retry/azure_retry_test.go
/kind testing
Fix TestJitterWithNegativeMaxFactor UT
Gap between expected and actual value can be
negative but its absolute value is still < 1.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] Fix TestJitterWithNegativeMaxFactor UT

.github/workflows/release.yaml, hack/generate-release-note.sh, site/content/en/blog/releases/v1.23.28.md, site/content/en/blog/releases/v1.24.15.md, site/content/en/blog/releases/v1.25.9.md, site/content/en/blog/releases/v1.26.5.md
/kind cleanup
1. Fix the misuse of `end-sha` argument of `release-notes` CLI.
2. Regenerate `v1.26.5` release note.
3. Add script to generate release note:
```shell
$ ./hack/generate-release-note.sh
Usage: hack/generate-release-note.sh <release> [output] [update_site]
release: release tag, e.g. v1.21.0.
output: output file, default to release-notes.md.
update_site: update site content, default to false.
GITHUB_TOKEN: The GitHub token to use for API requests. (required environment variable)
Example: hack/generate-release-note.sh v1.21.0
Example: hack/generate-release-note.sh v1.21.0 release-notes.md true
$ ./hack/generate-release-note.sh v1.26.5 release-notes.md true
```
A [sample build](https://github.com/lodrem/cloud-provider-azure/actions/runs/4161844764/jobs/7200295157) in my local …
=> build: Excludes previous release tag commit when generating release notes

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, tests/e2e/network/network_security_group.go
/kind bug
Fix how getSecurityRuleName() handles IPv6 addr prefix
Error msg is like: Resource name a29b3b265d9f84776b6c877408e7a519-TCP-80-2001:1234:5678:9abd::4_128 is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
* Bug fix
* Add UT and adjust e2e
Fixes #
```release-note
Fix incorrect security rule name with IPv6 address prefix
```
```docs
```
=> [release-1.24] Fix how getSecurityRuleName() handles IPv6 addr prefix

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, tests/e2e/network/network_security_group.go
/kind bug
Fix how getSecurityRuleName() handles IPv6 addr prefix
Error msg is like: Resource name a29b3b265d9f84776b6c877408e7a519-TCP-80-2001:1234:5678:9abd::4_128 is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
* Bug fix
* Add UT and adjust e2e
Fixes #
```release-note
Fix incorrect security rule name with IPv6 address prefix
```
```docs
```
=> [release-1.23] Fix how getSecurityRuleName() handles IPv6 addr prefix

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, tests/e2e/network/network_security_group.go
/kind bug
Fix how getSecurityRuleName() handles IPv6 addr prefix
Error msg is like: Resource name a29b3b265d9f84776b6c877408e7a519-TCP-80-2001:1234:5678:9abd::4_128 is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
* Bug fix
* Add UT and adjust e2e
Fixes #
```release-note
Fix incorrect security rule name with IPv6 address prefix
```
```docs
```
=> [release-1.25] Fix how getSecurityRuleName() handles IPv6 addr prefix

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
/kind bug
remove shared security rule when no svc with shared-nsg annotation exists
Fixes #
```release-note
Fix: remove unsed shared nsg rule when there is no svc having azure-shared-securityrule annotations set
```
```docs
```
=> Fix: remove shared security rule when no svc with shared-nsg annotation exists

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
(cherry picked from commit a894df4b98dbf35f68ecc9372d728064b2eb3d47)
/kind bug
Fix: remove shared security rule when no svc with shared-nsg annotation exists 
Fixes #
```release-note
fix: remove shared security rule when no svc with shared-nsg annotation exists 
```
```docs
```
=> [release-1.24]Fix: remove shared security rule when no svc with shared-nsg annotation exists 

pkg/provider/azure_standard.go
/kind bug
Fix a loop pointer bug in EnsureBackendPoolDeleted
Fixes #
```release-note
Fix nic CreateOrUpdate bug when there are more than one nic.
```
```docs
```
=> Fix a loop pointer bug in EnsureBackendPoolDeleted

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind bug
fix: detach disk failure when there is throttling error
This PR would always check disk lun after disk detach complete, that could avoid detach disk failure when there is throttling error in batch operation, and I have run 100+ 1K disk attach/detach tests with throttling errors, all disk detach completes successfully!
Fixes #
```release-note
fix: detach disk failure when there is throttling
```
```docs
fix: detach disk failure when there is throttling
```
=> fix: detach disk failure when there is throttling

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind bug
When setting "cloud-provider: azure", the CAPZ will use in-tree kube-controller-manager rather than out-of-tree CCM and CNM. This will cause the ndoe providerID is set with wrong format for VMSS Flex VMs
Fixes #
```release-note
NONE
```
```docs
```
=> Change MachinePool to use extenral cloud-provider

tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml
/kind bug
The linux-vmss-ci-version.yaml file contains a windows pool with 0 instance.  If no OrchestrationMode is set for it, it will be a Uniform VMSS. This will cause the SLB E2E tests to go to the wrong logic of checking VMSS Uniform backend pool: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/network/standard_lb.go#L118~L120
This PR specifies its orchestrationMode to prevent this issue.
Fixes #
```release-note
NONE
```
```docs
```
=> add OrchestrationMode for windows pool

cmd/cloud-controller-manager/app/controllermanager.go
/kind bug
It is fairly normal in operation for the CCM to lose the lease, for example this could happen after a relatively short period of disruption to the API server connectivity. When it loses the connection, it should intentionally exit using an `os.Exit(1)` to prevent further execution.
Currently the code panics, which means you end up with a panic trace in the output, except, I would argue this shouldn't panic because it isn't a programmer error, there's no reason I would investigate the stack trace here.
Note, other providers use the core cloud-provider app and [exit in the way I'm suggesting here](https://github.com/kubernetes/cloud-provider/blob/4162b590014735c81ac6db5e3fbf7edaae3d4706/app/controllermanager.go#L258-L262).
We monitor code panicking within our CI to look for …
=> CCM should not panic when losing leader election lease

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
Fixes #
```release-note
NONE
```
```docs
```
=> fix: change the expected tags in aks e2e test

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.23] fix: change the expected tags in aks e2e test

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] fix: change the expected tags in aks e2e test

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24] fix: change the expected tags in aks e2e test

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] fix: change the expected tags in aks e2e test

tests/e2e/network/service_annotations.go
/kind testing
Enable azure-load-balancer-resource-group test. Before, there's an issue with upstream pipeline on ARM so it is only tested in AKS pipeline. Now, it seems recovered.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Enable azure-load-balancer-resource-group test

pkg/provider/azure_vmss.go
/kind bug
There is a corner case that the VMSS VM is deleted but it is still in the lb backend pool. In this case the cloud provider keep  searching this VM by refreshing the cache, which introduces a lot of unexpected API calls. This PR adds a nil entry to the cache for the not found VM so next time when we try to search the VM it will hit the nil entry and return without calling the LIST VMSS VM API.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: add a comment to address a potential bug that is introduced by orphaned ipconfigs on the lb

site/content/en/install/azure-ccm.md
/kind bug
This PR updates the `Deploy Cloud Controller Manager` page link. We need it to correct and maintain the documentation.
[3580](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/3580)
Sanity checks if the URL is opening for all browsers.
NONE
=> [#3580] - Link to cloud provider config is broken on docs 'Deploy Cloud Controller Manager' page --fixed

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
/kind bug
Fix nodeAddressesChangeDetected() bug when dual-stack. In a dual-stack cluster, a Node has 2 internal IPs but current logic doesn't distinguish between these 2. As a result, CNM always assumes that NodeAddresses changed.
Fixes #
```release-note
Fix nodeAddressesChangeDetected() bug when dual-stack. In a dual-stack cluster, a Node has 2 internal IPs but current logic doesn't distinguish between these 2. As a result, CNM always assumes that NodeAddresses changed.
```
```docs
```
=> Fix nodeAddressesChangeDetected() bug when dual-stack

tests/e2e/utils/node_utils.go
/kind testing
[e2e] Longer timeout for WaitAutoScaleNodes()
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Longer timeout for WaitAutoScaleNodes()

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind bug
Deprecate numberOfProbes and adopt ProbeThreshold to address a probe issue in nrp
Because numberofprobes never works and it is mentioned in https://learn.microsoft.com/en-us/azure/load-balancer/whats-new#known-issues
Fixes #
```release-note
Deprecate numberOfProbes and adopt ProbeThreshold in network api to address a probe issue in nrp
```
```docs
```
=> Deprecate numberOfProbes and adopt ProbeThreshold to address a probe issue in nrp

Makefile
Reverts kubernetes-sigs/cloud-provider-azure#3594
Reason:
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/3655
=> Revert "[release-1.25] Removing Windows SAC images from container builds"

pkg/provider/azure_instance_metadata.go, pkg/provider/azure_instance_metadata_test.go
/kind bug
[IPv6] Fix CNM not properly handling IPv6 from imds LB. imds LB returns IPv6 IPs wrapped by brackets so extra trimming is needed.
Fixes #3725
```release-note
[IPv6] Fix CNM not properly handling IPv6 from imds LB. imds LB returns IPv6 IPs wrapped by brackets so extra trimming is needed.
```
```docs
```
=> [IPv6] Fix CNM not properly handling IPv6 from imds LB

.pipelines/templates/autoscaling-multipool.json, .pipelines/templates/autoscaling.json, tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/vmss_utils.go
/kind testing
[e2e] Improve autoscaling e2e
* More instances in VMSS to avoid deallocating to 0 instance
* AfterEach: Should not simply delete Nodes when before and after are different since only the total count matters
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Improve autoscaling e2e

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache_test.go, pkg/provider/azure_vmssflex_test.go
/kind bug
Choose correct primary IP config in ensureBackendPoolDeletedFromNode(). Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
Fixes #
Related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/3707
```release-note
Choose correct primary IP config in ensureBackendPoolDeletedFromNode(). Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
```
```docs
```
=> [IPv6] Choose correct primary IP config

pkg/azureclients/armclient/azure_armclient.go, pkg/azureclients/armclient/azure_armclient_test.go
/kind bug
A regression was introduced by #1687 where the behavior of updating resources in batches changes from sending requests asynchonously to synchonously. This would lead to latencies when updating vmss vms, especially when the cluster size is huge. This unexpected change is reverted in this fix.
Fixes #
```release-note
fix: update resources in batches asynchonously
A regression was introduced by #1687 where the behavior of updating resources in batches changes from sending requests asynchonously to synchonously. This would lead to latencies when updating vmss vms, especially when the cluster size is huge. This unexpected change is reverted in this fix.
```
```docs
```
=> fix: update resources in batches asynchonously

cmd/acr-credential-provider/plugin.go, cmd/acr-credential-provider/plugin_test.go, pkg/credentialprovider/azure_credentials.go, site/content/en/topics/credential-provider.md
/kind cleanup
chore: upgrade credentialprovider-api-version to v1
Per https://kubernetes.io/blog/2022/12/22/kubelet-credential-providers/, kubelet credential provider has been GA since v1.26 and the API version has been promoted to `credentialprovider.kubelet.k8s.io/v1`. For GA of [acr-credential-provider](https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/cmd/acr-credential-provider), we need to 
* Upgrade the API version to `credentialprovider.kubelet.k8s.io/v1`
Fixes #3116
I have also manually verified on 1.26 node with following feature flag and config, external credential provider works, next will set up e2e test:
```
,KubeletCredentialProviders=true --image-credential-provider-bin-dir=/var/lib/kubelet/credential-provider …
```
=> chore: upgrade credentialprovider-api-version to v1

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind cleanup
ClusterConfig defaults loadBalancerSku to `basic`: https://cloud-provider-azure.sigs.k8s.io/install/configs/#cluster-config.
> On 30 September 2025, Basic SKU public IP addresses will be retired in Azure. You can continue to use your existing Basic SKU public IP addresses until then, however, you'll no longer be able to create new ones after 31 March 2025.
Basic SKU is being retired. We should not be defaulting to basic for LB and public IP SKUs.
Standard SKU public IP addresses offer significant [improvements](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses#sku), including:
- Access to a variety of other Azure products, including Standard Load Balancer, Azure Firewall, and NAT Gateway.
- Security by default—closed to inbound flows …
=> chore: set default loadBalancerSKU to Standard

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache_test.go, pkg/provider/azure_vmssflex_test.go
/kind bug
[IPv6] Choose correct primary IP config
Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend
address pool, IP config's IP version needs consideration.
Fixes #
```release-note
[IPv6] Choose correct primary IP config. Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
```
```docs
```
=> [release-1.26][IPv6] Choose correct primary IP config

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
[IPv6] Choose correct primary IP config. Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
Fixes #
```release-note
[IPv6] Choose correct primary IP config. Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
```
```docs
```
=> [release-1.24][IPv6] Choose correct primary IP config

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache_test.go, pkg/provider/azure_vmssflex_test.go
/kind bug
[IPv6] Choose correct primary IP config Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
Fixes #3707
```release-note
[IPv6] Choose correct primary IP config Regardless of IPv6 only or dualstack clusters, IPv4 IP config is always primary. So for IPv6 backend address pool, IP config's IP version needs consideration.
```
```docs
```
=> [release-1.25][IPv6] Choose correct primary IP config

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
Remove shared nsg rule immediately when no destinations left
Fixes #
```release-note
Fixed: Remove shared nsg rule immediately when no destinations left
```
```docs
```
=> Remove shared nsg rule immediately when no destinations prefixes are left

.pipelines/templates/autoscaling-multipool.json, .pipelines/templates/autoscaling.json, tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go, tests/e2e/utils/vmss_utils.go
/kind testing
[e2e][Autoscaling] Use user node pool. There're system pool NodeAffinity for coredns and metrics-server Deployments and using user node pool can avoid some Node deletion stuck problem.
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e][Autoscaling] Use user node pool

pkg/provider/azure.go, pkg/provider/azure_test.go, pkg/provider/config/azure_auth.go, pkg/provider/config/azure_auth_test.go
/kind feature
feat: support workload identity
Fixes #
```release-note
feat: support workload identity
```
```docs
feat: support workload identity
```
=> feat: support workload identity

pkg/provider/azure_managedDiskController.go, pkg/provider/azure_managedDiskController_test.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
This PR:
- add PickRandomMatchingAccount in account search
- add PublicNetworkAccess in disk creation
Fixes #
```release-note
- add PickRandomMatchingAccount in account search
- add PublicNetworkAccess in disk creation
```
```docs
- add PickRandomMatchingAccount in account search
- add PublicNetworkAccess in disk creation
```
=> feat: add PickRandomMatchingAccount in account search

pkg/consts/consts.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/network_utils_test.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Support dual-stack - utils
* Support dual-stack in e2e utils functions and methods
* Adjust related e2e test code
* Define some dual-stack Service annotations
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25][e2e] Support dual-stack - utils

pkg/consts/consts.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/network_utils_test.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Support dual-stack - utils
* Support dual-stack in e2e utils functions and methods
* Adjust related e2e test code
* Define some dual-stack Service annotations
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.24][e2e] Support dual-stack - utils

pkg/consts/consts.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/azure_test_client.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/network_utils_test.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Support dual-stack - utils
* Support dual-stack in e2e utils functions and methods
* Adjust related e2e test code
* Define some dual-stack Service annotations
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26][e2e] Support dual-stack - utils

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind cleanup
[DualStack] IPv6 PIP uses suffix only when DualStack. For CCM v1.27.1, the IPv6 PIP created has suffix. After CCM is upgraded, such PIP will be recreated.
Fixes #
```release-note
[DualStack] IPv6 PIP uses suffix only when DualStack. For CCM v1.27.1, the IPv6 PIP created has suffix. After CCM is upgraded, such PIP will be recreated.
```
```docs
```
=> [DualStack] IPv6 PIP uses suffix only when DualStack

site/content/en/development/e2e/e2e-tests.md
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396
```release-note
none
```
```docs
```
=> doc: use dl.k8s.io, not kubernetes-release bucket

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, site/content/en/topics/shared-ip.md, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: the pip without tags should be user-assigned

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, site/content/en/topics/shared-ip.md, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.25] fix: the pip without tags should be user-assigned

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, site/content/en/topics/shared-ip.md, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.27] fix: the pip without tags should be user-assigned

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, site/content/en/topics/shared-ip.md, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.26] fix: the pip without tags should be user-assigned

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, site/content/en/topics/shared-ip.md, tests/e2e/network/service_annotations.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.24] fix: the pip without tags should be user-assigned

cloudbuild.yaml
/kind cleanup
Set gcloud ver to 2023424. Latest is not working right now.
Fixes #
```release-note
NONE
```
```docs
```
=> Set gcloud ver to 2023424

cmd/cloud-node-manager/app/config/config.go, cmd/cloud-node-manager/app/nodemanager.go, cmd/cloud-node-manager/app/options/options.go, pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
/kind bug
/kind cleanup
#2653 removed the deprecated labels completely, however, other cloud providers have [not yet removed](https://github.com/kubernetes/cloud-provider/blob/9be8e26d3703a1461004f30951315283a88307e4/controllers/node/node_controller.go#L51-L86) these and there are a lot of people out there who are probably not ready to migrate. For example, the Azure Red Hat OpenShift offering has not announced removal of the labels and still supports the labels, even though Microsoft and AKS have removed them.
This PR introduces a softer change, allowing users to maintain the old behaviour should they wish to.
Commit wise, it does:
* Reverts 2653 to put things back to how they were
* Refactors the cloud node modifier code to clean that up ahead of later changes
* Switch priority from …
=> Allow deprecated beta topology labels to be applied for those not ready to migrate

pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind feature
apply the custom probe configs when externalTrafficPolicy is local and PLSProxyProtocol is enabled.
Fixes #
```release-note
apply the custom probe configs when externalTrafficPolicy is local and PLSProxyProtocol is enabled.
```
```docs
```
=> apply the custom probe configs when externalTrafficPolicy is local and PLSProxyProtocol is enabled.

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind bug
[IPv6] backend pool name should be case-insensitive
Fixes #
```release-note
[IPv6] backend pool name should be case-insensitive
```
```docs
```
=> [IPv6] backend pool name should be case-insensitive

site/content/en/topics/loadbalancer.md
doc: update documents for allocateLoadBalancerNodePorts.
This is because allocateLoadBalancerNodePorts=false is not supported on service with externalTrafficPolicy=Cluster.
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update documents for allocateLoadBalancerNodePorts

pkg/provider/azure_loadbalancer.go, tests/e2e/network/private_link_service.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/utils.go
Service annotation variables should be deep copied before used. Otherwise, if it is modified in other tests, its value is not expected.
Fixes #3885
```release-note
NONE
```
```docs
```
=> [e2e] Service annotation var should be deep copied

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, tests/e2e/network/network_security_group.go, tests/e2e/network/private_link_service.go, tests/e2e/network/standard_lb.go
/kind bug
[IPv6] Fix reconcileFrontendIPConfigs(). Current logic handles lb.FrontendIPConfigurations according to Service's IP family, which is incorrect. For an IPv6 cluster, there're still some IPv4 FIPs due to Azure limitation, which will be removed. For an IPv4 cluster, all resources are of IPv4, which is not affected.
Fixes #4038
```release-note
[IPv6] Fix reconcileFrontendIPConfigs(). Current logic handles lb.FrontendIPConfigurations according to Service's IP family, which is incorrect. For an IPv6 cluster, there're still some IPv4 FIPs due to Azure limitation, which will be removed. For an IPv4 cluster, all resources are of IPv4, which is not affected.
```
```docs
```
=> [IPv6] Fix reconcileFrontendIPConfigs()

hack/test-ccm-e2e.sh
/kind testing
Add CCM_E2E_TIMEOUT option for ginkgo running ccm e2e tests
refer: https://onsi.github.io/ginkgo/#interrupting-aborting-and-timing-out-suites
Fixes #
```release-note
NONE
```
```docs
```
=> Add CCM_E2E_TIMEOUT option for ginkgo running ccm e2e tests

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml
/kind testing
[Dual-Stack][CI] Add CAPZ templates
Fixes #
related: #814
```release-note
NONE
```
```docs
```
=> [Dual-Stack][CI] Add CAPZ templates

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
fix: replace deprecated labels with new labels in nodeCache update
Fixes #
```release-note
fix: replace deprecated labels with new labels in nodeCache update
```
```docs
fix: replace deprecated labels with new labels in nodeCache update
```
=> fix: replace deprecated labels with new labels in nodeCache update

go.mod, pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: add GetLatestAccountKey in account key fetch
related to requirement: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1218
This PR does not change the default behavior.
Fixes #
```release-note
feat: add GetLatestAccountKey in account key fetch
```
```docs
feat: add GetLatestAccountKey in account key fetch
```
=> feat: add GetLatestAccountKey in account key fetch

pkg/provider/azure_standard.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go
/kind bug
Fix vmssflex ensureBackendPoolDeletedFromNode
* Fix loop pointer issue
* Use lock on nicUpdated var
* Fix log format
Fixes #
```release-note
Fix vmssflex ensureBackendPoolDeletedFromNode
* Fix loop pointer issue
* Use lock on nicUpdated var
* Fix log format
```
```docs
```
=> Fix vmssflex ensureBackendPoolDeletedFromNode

Dockerfile, Makefile, cloud-node-manager.Dockerfile, e2e.Dockerfile, tests/e2e/network/service_annotations.go
/kind cleanup
Debian buster has been EOL for a while and its LTS is soon to be over. Reference:
- https://wiki.debian.org/DebianReleases
This PR updates Dockerfile references to build from buster + 1 --> bullseye.
Fixes #
```release-note
build images from debian bullseye
```
```docs
```
=> update to debian bullseye, buster EOL soon

pkg/azclient/client-gen/cmd/typescaffold/type_scaffold.go, pkg/azclient/interfaceclient/interface.go, pkg/azclient/interfaceclient/mock_interfaceclient/interface.go
/kind bug
add GetVirtualMachineScaleSetNetworkInterface for interface client
Fixes #
```release-note
NONE
```
```docs
```
=> track2 sdk:add GetVirtualMachineScaleSetNetworkInterface for interface client

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go
/kind feature
* Support NSG and clean LBs for dualstack
* Support related UTs for dualstack
* Refactor
Fixes #
```release-note
* Support NSG and clean LBs for dualstack
* Support related UTs for dualstack
* Refactor
```
```docs
```
=> [DualStack] Support NSG and clean LBs

pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go
/kind bug
We should remove deleted node IPs from the IP-based backend pools.
Fixes #
```release-note
fix: remove deleted node IP address from IP-based LB backend pools
```
```docs
```
=> [release-1.25] fix: remove deleted node IP address from IP-based LB backend pools

pkg/cache/azure_cache.go, pkg/cache/azure_cache_test.go, pkg/provider/azure.go, pkg/provider/azure_instance_metadata.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_cache.go, pkg/provider/azure_wrap.go
/kind feature
[ARG] Add an option to disable API call cache
New option: disableAPICallCache
When ARG is enabled, this option should be true.
Fixes #
```release-note
[ARG] Add an option to disable API call cache
New option: disableAPICallCache
When ARG is enabled, this option should be true.
```
```docs
```
=> [ARG] Add an option to disable API call cache

pkg/provider/azure_controller_common.go
/kind bug
PerformancePlus is not set correctly per https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1893, this PR fixes the issue.
Fixes #
<details>
```
Normal   ExternalProvisioning  11s              persistentvolume-controller                                                             waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
Normal   Provisioning          3s (x3 over 7s)  disk.csi.azure.com_aks-acstor-38086987-vmss000002_4639910e-7ba7-4378-b573-e903bbb56d17  External provisioner is provisioning volume for claim "default/pvc-azuredisk5"
Warning  ProvisioningFailed    3s (x3 over 6s)  disk.csi.azure.com_aks-acstor-38086987-vmss000002_4639910e-7ba7-4378-b573-e903bbb56d17  failed to …
```
=> fix: PerformancePlus setting issue

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: account search default values
default values of AllowBlobPublicAccess and AllowSharedKeyAccess is true in storage API, this PR set the same default as storage API.
Fixes #
```release-note
fix: storage account search default values
```
```docs
fix: storage account search default values
```
=> fix: storage account search default values

tests/e2e/utils/service_utils.go
/kind testing
[e2e] Delete Service if WaitServiceExposureAndValidateConnectivity() fails
Fixes #4137
```release-note
NONE
```
```docs
```
=> [e2e] Delete Service if WaitServiceExposureAndValidateConnectivity() fails

README.md
doc: update README for document links
Fixes #
```release-note
NONE
```
```docs
```
=> doc: update README for document links

pkg/provider/azure.go
/kind feature
feat: make vmType optional
vmType's default value is changed from 'standard' to 'vmss' since v1.28.
Fixes #3099
```release-note
vmType's default value is changed from 'standard' to 'vmss' since v1.28.
action required: if your cluster is not using any VMSS instances and 'vmType' is not configured in the cloud provider config file, please add vmType=standard in the config file before upgrading to v1.28.
```
```docs
```
=> feat: make vmType optional

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_healthprobe_test.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind bug
Support customization of numOfProbe and probeInterval when externaltrafficpolicy is local
Fixes #
move health probe related code to azure_loadbalancer_healthprobe*
```release-note
Support customization of numOfProbe and probeInterval when externaltrafficpolicy is local
```
```docs
```
=> Support customization of numOfProbe and probeInterval when externaltrafficpolicy is local

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/consts.go, tests/e2e/utils/node_utils.go
/kind testing
/kind bug
* Fix ensureBackendPoolDeleted for standalone VM
* Trigger Service reconcile for exclude-from-external-load-balancers e2e test
* Refactor e2e
* Add logs for exclude-from-external-load-balancers
Fixes #
```release-note
Fix ensureBackendPoolDeleted for standalone VM
```
```docs
```
=> Fix standalone VM EnsureBackendPoolDeleted

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go
/kind feature
Support node selection for multiple standard load balancers.
When nodes are created, each node will be evaluated to see what load balancer it should be placed into.  
Valid placement targets will be determined as follows (rules match from top to bottom, first match wins): 
1. If this node is in an agent pool that is selected as a primary agent pool for a load balancer, that load balancer will be the only potential placement target. 
2. If the nodeSelectors on any load balancer configurations match this node, then all load balancer configurations that match it will be potential placement targets. 
3. If no nodeSelectors on any load balancer configurations match this node, then all load balancers that do not have any nodeSelectors will be potential placement targets. 
After …
=> feat: support node selection for multiple standard load balancers

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
Issue https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4230 explains things in greater depth, but here's the TL;DR
https://github.com/kubernetes/kubernetes/pull/109706 stopped syncing load balancers when changes are observed to the readiness state of the Node object. Load balancers are essentially almost only re-synced whenever a Node is: added, deleted, has the exclusion label added. The service controller expectation is that the cloud-providers just accept the list of nodes provided through the `UpdateLoadBalancerHost` call and try to configure the load balancers with the entire set of nodes provided. Given that Azure performs additional filtering of the nodes and excludes `NotReady` nodes, there will be situations where the node which just transitioned to …
=> Issue 4230: remove readiness check for cache exclusion

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
[release-1.26] cherry-pick of #4234: Cloud provider won't exclude the NotReady nodes from SLB backend pools.
Fixes #
```release-note
Cloud provider won't exclude the NotReady nodes from SLB backend pools
```
```docs
```
=> [release-1.26] Issue 4230: remove readiness check for cache exclusion

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
[release-1.27] cherry-pick of #4234: Cloud provider won't exclude the NotReady nodes from SLB backend pools.
Fixes #
```release-note
Cloud provider won't exclude the NotReady nodes from SLB backend pools
```
```docs
```
=> [release-1.27] Issue 4230: remove readiness check for cache exclusion

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
[release-1.25] cherry-pick of #4234: Cloud provider won't exclude the NotReady nodes from SLB backend pools.
Fixes #
```release-note
Cloud provider won't exclude the NotReady nodes from SLB backend pools
```
```docs
```
=> [release-1.25] Issue 4230: remove readiness check for cache exclusion

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, tests/e2e/network/ensureloadbalancer.go
/kind feature
We used to support sharing one pip across services by setting the IP address. This PR supports sharing by pip name.
Fixes #4243
```release-note
feat: support sharing IP address across services by public IP name
```
```docs
```
=> [release-1.25] feat: support sharing IP address across services by public IP name

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_utils.go, tests/e2e/network/ensureloadbalancer.go
/kind feature
We used to support sharing one pip across services by setting the IP address. This PR supports sharing by pip name.
Fixes #4243
```release-note
feat: support sharing IP address across services by public IP name
```
```docs
```
=> [release-1.27] feat: support sharing IP address across services by public IP name

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind bug
[release-1.24] cherry-pick of #4234: Cloud provider won't exclude the NotReady nodes from SLB backend pools.
Fixes #
```release-note
Cloud provider won't exclude the NotReady nodes from SLB backend pools
```
```docs
```
=> [release-1.24] Issue 4230: remove readiness check for cache exclusion

pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go
/kind feature
Skip unmanaged Nodes for instancesV2
Fixes #
```release-note
Skip unmanaged Nodes for instancesV2
```
```docs
```
=> Skip unmanaged Nodes for instancesV2

pkg/provider/azure_instances.go, pkg/provider/azure_instances_test.go
/kind bug
Skip unmanaged Nodes for instancesV2
Fixes #
```release-note
Skip unmanaged Nodes for instancesV2
```
```docs
```
=> [release-1.26] Skip unmanaged Nodes for instancesV2

pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind bug
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted().
Fixes #
```release-note
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted(). Updated e2e code.
```
```docs
```
=> Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure

pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind bug
/kind testing
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure
* IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted(). Updated e2e code.
* Fix health probe e2e
Fixes #
```release-note
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted()
```
```docs
```
=> [release-1.26] Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure

pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go
/kind testing
/kind bug
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure
* IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted(). Updated e2e code.
* Fix health probe e2e
* Adjust exclude-from-lb test for basic-lb pipeline
Fixes #
```release-note
Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted().
```
```docs
```
=> [release-1.27] Cherry-pick 4317 4272

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_standard.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/consts.go, tests/e2e/utils/node_utils.go
/kind bug
/kind testing
* Fix ensureBackendPoolDeleted for standalone VM
* Trigger Service reconcile for exclude-from-external-load-balancers e2e test
* Refactor e2e
* Add logs for exclude-from-external-load-balancers
* Adjust exclude-from-lb test for basic-lb pipeline
* Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted(). Updated e2e code.
* Fix health probe e2e
Fixes #
```release-note
Fix ensureBackendPoolDeleted for standalone VM. Fix IPv6/dual-stack EnsureBackendPoolDeleted() failure. IP config of IPv6 is not primary, it should not be skipped in EnsureBackendPoolDeleted().
```
```docs
```
=> [release-1.25] Cherry-pick 4217 4261 4272

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/multiple_standard_lb.go, tests/e2e/utils/network_utils.go
/kind bug
1. `getServiceLoadBalancer` should return the existing lb object instead of creating a new one when a service is being moved from another lb to this one.
2. `existingLBs` should be updated when the lb is updated to prevent potential etag mismatches in `EnsureHostsInPool`.
3. Should skip non-existent lb when arranging nodes.
Fixes #
Related: [4013](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4013)
```release-note
fix: update the lb list after changing lb to prevent etag mismatches
fix: return the existing lb  it if the lb exists without creating a new lb when the service was moved to the lb
fix: should skip non-existent lb when arranging nodes
```
```docs
```
=> fix: fix bugs regarding multiple slbs

pkg/provider/azure_loadbalancer.go
/kind bug
Resolves #4360 by increasing the allowed limit inline with Azures updated limits
Fixes #4360
This limit has been increased on the Azure side and is documented now as 100 minutes maximum, links in the attached issue
```release-note
Increase limit for TCP Idle Timeout to 100 minutes
```
```docs
```
=> Increase service idle max timeout to 100 minutes

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_zones.go, pkg/provider/azure_zones_test.go
/kind feature
/kind bug
feat: add load balancer backend pool batch updater
fix a bug that the route updater and zone fetcher will not be exited every time the service reconciler restarts.
Fixes #
Related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4013
```release-note
feat: add load balancer backend pool batch updater
```
```docs
```
=> Feat: add load balancer backend pool batch updater

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_wrap.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/node.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/network/standard_lb.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go
/kind feature
[DualStack] Support NSG and clean LBs
* Support NSG and clean LBs for dualstack
* Support related UTs for dualstack
* Refactor
[IPv6] Fix reconcileFrontendIPConfigs()
Current logic handles lb.FrontendIPConfigurations according
to Service's IP family, which is incorrect. For an IPv6 cluster,
there're still some IPv4 FIPs due to Azure limitation, which
will be removed. For an IPv4 cluster, all resources are of IPv4,
which is not affected.
[e2e] Adjust for IPv6 VMSS
[DualStack] Support FrontendIPConfig and reconcileLB()
* DualStack feature code
* Refactor related functions and methods
* Refactor and add new UTs
[Refactor] Drop RG param in getXXXID()
Resource group name can be got from az.getLoadBalancerResourceGroup().
Fixes #
```release-note
[DualStack] Support …
```
=> [release-1.27] Cherrypick FIP, NSG dualstack change

pkg/provider/azure_vmss.go, tests/e2e/utils/service_utils.go
/kind cleanup
/kind testing
Improve e2e and ensureBackendPoolDeletedFromVmssUniform log
* vmSetName is for basic LB so move it to basic LB branch
* e2e: print Service describe info if exposure fails
Fixes #
```release-note
NONE
```
```docs
```
=> Improve e2e and ensureBackendPoolDeletedFromVmssUniform log

pkg/provider/azure_vmss.go, tests/e2e/utils/service_utils.go
/kind testing
/kind cleanup
Improve e2e and ensureBackendPoolDeletedFromVmssUniform log
* vmSetName is for basic LB so move it to basic LB branch
* e2e: print Service describe info if exposure fails
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Improve e2e and ensureBackendPoolDeletedFromVmssUniform log

pkg/provider/azure_vmss.go, tests/e2e/utils/service_utils.go
/kind testing
/kind cleanup
Improve e2e and ensureBackendPoolDeletedFromVmssUniform log
* vmSetName is for basic LB so move it to basic LB branch
* e2e: print Service describe info if exposure fails
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.25] Improve e2e and ensureBackendPoolDeletedFromVmssUniform log

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_routes.go, pkg/provider/azure_utils.go, tests/e2e/network/multiple_standard_lb.go, tests/e2e/network/node.go
/kind feature
In multiple slb mode, each local service owns a backend pool named after the service name. The backend pool will be created in the service reconciliation loop when the service is created or updated from external traffic policy cluster. It will be deleted in the service reconciliation loop when: 1, the service is deleted; 2, the service is changed to etp cluster; 3, the cluster is migrated from multi-slb to single-slb; and 4, the service is moved to another load balancer.
Besides the service reconciliation loop, an endpointslice informer is added in this pr. It watches all endpointslices of local services, monitors any updating events, and updates the corresponding backend pool. Considering local services may churn quickly, the informer will send backend pool updating …
=> feat: support local service in multiple standard load balancer mode

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
/kind testing
Remove KubeletCredentialProviders feature gate in template. Since k8s 1.28, this feature gate has been removed. https://github.com/kubernetes/kubernetes/pull/116901
Fixes #
Related https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2403
```release-note
NONE
```
```docs
```
=> Remove KubeletCredentialProviders feature gate in template

pkg/azureclients/armclient/util.go
/kind cleanup
cleanup: set response logging as log level 6
We have plenty of following logs in CSI drivers, set as 6 since it's mainly for debugging:
```
util.go:124] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length 1434
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1938/pull-azuredisk-csi-driver-e2e-capz/1693992105539538944/build-log.txt
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: set response logging as log level 6

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind feature
Add node.kubernetes.io/out-of-service when instance is shutdown so pods can be forcefully deleted. Implement the [node non-graceful shutdown feature](https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown).
There is a delay between the time node becomes NotReady and cloud provider detects node instance is shutdown, which is caused by cache refresh period. Current cache refresh period is 10min by default. So it can take at most 10min before node shutdown taint and node out-of-service taint are added.
Fixes #
related #4508 
```release-note
Implement node non-graceful shut down feature. Add "node.kubernetes.io/out-of-service" taint to node when cloud provider determines the node is shutdown.
```
```docs
```
=> [release-1.26] add node out-of-service taint when node is shutdown

pkg/provider/azure.go, pkg/provider/azure_test.go
/kind feature
Add node.kubernetes.io/out-of-service when instance is shutdown so pods can be forcefully deleted. Implement the [node non-graceful shutdown feature](https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown).
There is a delay between the time node becomes NotReady and cloud provider detects node instance is shutdown, which is caused by cache refresh period. Current cache refresh period is 10min by default. So it can take at most 10min before node shutdown taint and node out-of-service taint are added.
Fixes #
related #4508 
```release-note
Implement node non-graceful shut down feature. Add "node.kubernetes.io/out-of-service" taint to node when cloud provider determines the node is shutdown.
```
```docs
```
=> [release-1.27] add node out-of-service taint when node is shutdown

pkg/consts/consts.go, pkg/consts/helpers.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind feature
Add Service annotation `service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset` to support disable tcp reset.
Fixes #
```release-note
LoadBalancer tcp reset could be disabled with Service annotation "service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset=true"
```
```docs
```
=> feat: add support for disable tcp reset

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
chore: match account if PrivateEndpoint is not set in storage class
This PR change CreatePrivateEndpoint var as `*bool`, if it's not set, then it's nil
Fixes #
```release-note
none
```
```docs
none
```
=> fix: match account if PrivateEndpoint is not set in storage class

pkg/nodeipam/ipam/range_allocator.go, pkg/nodeipam/ipam/range_allocator_test.go, pkg/util/controller/testutil/test_utils.go, pkg/util/node/node.go
/kind bug
When node podCIDR patch request fails, we release the allocated CIDR but retry without claiming new ones. This PR fixes the issue by re-allocating new CIDR when updateNodeCIDR is retried.
Fixes #4556 
```release-note
Fix possible duplicate podCIDR allocation when node podCIDR patch request fails.
```
```docs
```
=> fix: fix duplicate podCIDR allocation when node patch request fails

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json, tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-short-cache-ttl.json
/kind testing
[CI] Cut cache TTL to half for VM
* cloud-config-vmss-default.json
* cloud-config-vmss-multi-slb.json
Fixes #
Related: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4594
```release-note
NONE
```
```docs
```
=> [CI] Cut cache TTL to half for VM

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind feature
support customizing probe config when ETP is local
Fixes #
```release-note
support customizing probe config when externalTrafficPolicy is local and health-probe_port annotation is defined for svc port
```
```docs
```
=> Support customizing probe config when ETP is local

pkg/consts/consts.go, pkg/nodemanager/nodemanager.go, pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_healthprobe_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss_test.go, tests/e2e/network/multiple_standard_lb.go
/kind bug
There are chances that the endpoints in an endpointslice updates slower than the actual state. This may bring an issue if the endpointslice updates after we update backend pool but before the service reconciliation finishes. In this case, the endpointslice update would be ignored. This PR checks the endpointslice state after updating backend pool, and reconciles the IPs in the backend pool for a second time to make sure they keep aligned with the endpoints in the endpointslice.
Fixes #
Related https://github.com/kubernetes-sigs/cloud-provider-azure/issues/4013
```release-note
fix: check endpoint slice update after backend pool update for local service to prevent mismatch
```
```docs
```
=> fix: check endpoint slice update after backend pool update for local service to prevent mismatch

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_healthprobe.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/service_annotations.go
/kind feature
support customizing probe config when ETP is local
Fixes #
```release-note
support customizing probe config when externalTrafficPolicy is local and health-probe_port annotation is defined for svc port
```
```docs
```
=> [release-1.27]support customizing probe config when ETP is local

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_repo.go, pkg/provider/azure_privatelinkservice_repo_test.go, pkg/provider/azure_privatelinkservice_test.go, tests/e2e/network/private_link_service.go
/kind feature
Add `ServiceAnnotationPLSResourceGroup = "service.beta.kubernetes.io/azure-pls-resource-group"` to control pls creation resource group.
Fixes #4608 
```release-note
By default, all managed private link service (PLS) are created in the resource group configured by azure config (az.privateLinkServiceResourceGroup or az.ResourceGroup).
Add `ServiceAnnotationPLSResourceGroup = "service.beta.kubernetes.io/azure-pls-resource-group"` to control a specific PLS creation resource group. 
```
```docs
```
=> feat: add annotation to control pls creation rg

pkg/consts/consts.go, pkg/provider/azure.go, pkg/provider/azure_backoff.go, pkg/provider/azure_backoff_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go, tests/e2e/network/private_link_service.go
/kind feature
cherry pick
Fixes #
related #4660 
```release-note
By default, all managed private link service (PLS) are created in the resource group configured by azure config (az.privateLinkServiceResourceGroup or az.ResourceGroup).
Add `ServiceAnnotationPLSResourceGroup = "service.beta.kubernetes.io/azure-pls-resource-group"` to control a specific PLS creation resource group.
```
```docs
```
=> [release-1.27] feat: add annotation to control pls creation rg

pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go
/kind bug
fix: skip tagging route table that is not in the cluster resource group.
Fixes #
```release-note
fix: skip tagging route table that is not in the cluster resource group.
```
```docs
```
=> fix: skip tagging route table that is not in the cluster resource group

pkg/provider/azure.go, pkg/provider/azure_instances.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go
/kind bug
When vmssVM instanceView or instanceView.Status is nil, it means the vm is under deleting, and GetPowerState() should not return powerStateStopped. This can result in a deleting vm being considered mistakenly as stopped and thus node shutdown/node out-of-service taints are added.
Fix log also.
Fixes #
```release-note
Fix the potential error that a deleting vmss instance is considered as shutdown.
```
```docs
```
=> report vmPowerStateUnknown when vmssVM intanceView is nil

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml
Reverts kubernetes-sigs/cloud-provider-azure#4812
=> Revert "Use CAAPH for credential-provider-capz template"

pkg/provider/azure_publicip_repo.go, pkg/provider/azure_publicip_repo_test.go
/kind bug
The key (pipName) of the pip cache should be case-insensitive.
Fixes #4814
```release-note
fix: pipName should be case-insensitive when querying pip cache
```
```docs
```
=> fix: pipName should be case-insensitive when querying pip cache

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind bug
#4839: fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
#4821: fix: pipName should be case-insensitive when querying pip cache
Fixes #4814 
```release-note
fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
fix: pipName should be case-insensitive when querying pip cache
```
```docs
```
=> Cherry pick #4839 and #4821 to release-1.27

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind bug
#4839: fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
#4821: fix: pipName should be case-insensitive when querying pip cache
Fixes #4814 
```release-note
fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
fix: pipName should be case-insensitive when querying pip cache
```
```docs
```
=> Cherry pick #4839 and #4821 to release-1.26

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_mock_loadbalancer_backendpool.go, pkg/provider/azure_test.go, pkg/provider/azure_wrap.go, pkg/provider/azure_wrap_test.go
/kind bug
#4839: fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
#4821: fix: pipName should be case-insensitive when querying pip cache
Fixes #4814 
```release-note
fix: refresh the load balancer object after updating backend pools to prevent etag mismatch error
fix: pipName should be case-insensitive when querying pip cache
```
```docs
```
=> Cherry pick #4839 and #4821 to release-1.25

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go, tests/e2e/network/network_security_group.go
/kind feature
Use cases:
``` yaml
apiVersion: v1
kind: Service
metadata:
name: test-lb
annotations:
spec:
type: LoadBalancer
ports:
- …
```
=> feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: add lock to avoid concurrent update on the cache
find more details here: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1556
Fixes #
```release-note
fix: add lock to avoid concurrent update on the cache
```
```docs
fix: add lock to avoid concurrent update on the cache
```
=> fix: add lock to avoid concurrent update on the cache

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_storageaccount_test.go
/kind cleanup
cleanup: expose InitDiskControllers as public function
We want to use this function in CSI drivers.
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: expose InitDiskControllers as public function

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind feature
feat: add occupiedLuns parameter in SetDiskLun func
this PR is for solving https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2000
Fixes #
```release-note
feat: add occupiedLuns parameter in SetDiskLun func
```
```docs
feat: add occupiedLuns parameter in SetDiskLun func
```
=> feat: add occupiedLuns parameter in SetDiskLun func

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-md.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-dualstack.yaml, tests/k8s-azure/manifest/cluster-api/linux-ipv6.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-multiple-vmss.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss.yaml, tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool-in-tree.yaml, tests/k8s-azure/manifest/cluster-api/vmss-multi-nodepool.yaml
/kind cleanup
This PR adds an appropriate calico `HelmChartProxy` resource spec for each custom CAPZ cluster template used by cloud-provider-azure test scenarios. This addition is to fulfill a new CAPZ `ci-entrypoint.sh` requirement to include the calico helm spec as a declarative `HelmChartProxy` resource. `ci-entrypoint.sh` no longer automatically installs calico manually by shelling out to the helm CLI as of CAPZ v1.12.0.
Fixes #
```release-note
NONE
```
```docs
```
=> test: update CAPZ test templates to include calico HelmChartProxy

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go, tests/e2e/network/network_security_group.go
/kind feature
Cherry pick #4762
Use cases:
``` yaml
apiVersion: v1
kind: Service
metadata:
name: test-lb
annotations:
spec:
type: …
```
=> [release-1.28] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go, tests/e2e/network/network_security_group.go
/kind feature
Cherry pick #4762
Use cases:
``` yaml
apiVersion: v1
kind: Service
metadata:
name: test-lb
annotations:
spec:
type: …
```
=> [release-1.26] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go, tests/e2e/network/network_security_group.go
/kind feature
Cherry pick #4762
Use cases:
``` yaml
apiVersion: v1
kind: Service
metadata:
name: test-lb
annotations:
spec:
type: …
```
=> [release-1.27] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`

pkg/provider/azure.go, pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go
/kind cleanup
cleanup: remove unused async attach functionality
async attach is never used in azure disk csi driver since it would lead to stale vm state issue, this PR removes the functionality, to make code logic more clear
Fixes #
```release-note
none
```
```docs
none
```
=> cleanup: remove unused async attach functionality

tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/private_link_service.go, tests/e2e/network/service_annotations.go, tests/e2e/utils/log.go, tests/e2e/utils/network_utils.go, tests/e2e/utils/service_utils.go, tests/e2e/utils/utils.go
/kind testing
[e2e] Print string instead of string pointer
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Print string instead of string pointer

pkg/provider/azure_controller_common.go, pkg/provider/azure_controller_common_test.go, pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go
/kind cleanup
Refactor: expose fields of AttachDiskOptions
Fixes #
With this change, managed disk controller can be moved to azuredisk csi driver. 
```release-note
NONE
```
```docs
```
=> Refactor: expose fields of AttachDiskOptions

pkg/provider/azure_loadbalancer.go
/kind bug
Summary:
The `service` object is always `nil` when code execution reaches [this line](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/b65c47cc857e4b915d75f718a35b629d23e872e8/pkg/provider/azure_loadbalancer.go#L272) and as such, logging `service.Name` will result in a nil pointer dereference panic (see [this panic log](https://gist.github.com/damdo/f11638dfa61edeb55a0bfd7a080bd216) (note that this comes from an older fork, so panic code lines might not exactly match)).
Analysis:
If `if !serviceExists` [is satisfied](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/b65c47cc857e4b915d75f718a35b629d23e872e8/pkg/provider/azure_loadbalancer.go#L270), we log a line with `service.Name`
But for the execution to branch into `if !serviceExists`, `serviceExists` …
=> fix: azure_loadbalancer.go: don't use service.Name, when service is nil

pkg/consts/consts.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind bug
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
Fixes #
```release-note
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
```
```docs
```
=> [release-1.26] Truncate lengthy PIP name

pkg/consts/consts.go, pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind bug
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
Fixes #
```release-note
Truncate lengthy PIP name. If PIP prefix is lengthy, the PIP name may be longer than 80. If so, the PIP name needs truncation.
```
```docs
```
=> [release-1.25] Truncate lengthy PIP name

pkg/consts/consts.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go, tests/e2e/network/network_security_group.go
/kind feature
Cherry pick #4762
Use cases:
``` yaml
apiVersion: v1
kind: Service
metadata:
name: test-lb
annotations:
spec:
type: …
```
=> [release-1.25] feat: Add annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges`

hack/deploy-cluster-capz.sh
/kind bug
"kind-" is repeated in the cluster name as MGMT_CLUSTER_CONTEXT already includes the prefix. Namespace name is missing while getting secret
Fixes #
```release-note
```
```docs
```
=> fix: Minor bugs in deploy-cluster-capz.sh

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, tests/e2e/network/network_security_group.go
/kind bug
Fixes #5366
```release-note
Fix creating NSG rule when access control enabled with IPv6 single stack
```
```docs
```
=> Fix creating NSG rule when access control enabled with IPv6 single stack

pkg/azureclients/fileclient/azure_fileclient.go
/kind bug
fix: fileshare snapshot does not require setting RequestGiB
RequestGiB is only required in file share creation, fileshare snapshot does not require setting RequestGiB
Fixes #
```release-note
fix: fileshare snapshot does not require setting RequestGiB
```
```docs
fix: fileshare snapshot does not require setting RequestGiB
```
=> fix: fileshare snapshot does not require setting RequestGiB

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap_test.go, pkg/provider/azure_zones_test.go, pkg/util/sets/string.go, pkg/util/sets/string_test.go
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
chore: Add case-insensitive string set utility
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28] chore: Add case-insensitive string set utility

pkg/provider/azure.go
/kind bug
fix: move lockMap initialization into InitializeCloudFromConfig func to fix panic
`InitializeCloudFromConfig` is more fundamental function and called by azure file driver directly, this PR fixes the panic in azure file driver:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c0a28b]
goroutine 148 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*LockMap).LockEntry(0x0, {0xc00077083f, 0x17})
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_utils.go:64 +0x2b
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).RemoveStorageAccountTag(0xc000548408, {0x2965f88, 0xc000283860}, {0xc00056c9c0, 0x24}, {0xc000770800, 0x3e}, …
```
=> fix: move lockMap initialization into InitializeCloudFromConfig func to fix panic

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_instances_test.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_routes_test.go, pkg/provider/azure_standard_test.go, pkg/provider/azure_test.go, pkg/provider/azure_utils.go, pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmss_test.go, pkg/provider/azure_wrap_test.go, pkg/provider/azure_zones_test.go, pkg/util/sets/string.go, pkg/util/sets/string_test.go
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
/kind cleanup
chore: Add case-insensitive string set utility
A new structure called IgnoreCaseSet has been introduced into the pkg/util/sets package. This constructs a set of strings that is case-insensitive, providing methods for applying standard set operations. It's beneficial for handling inputs where case sensitivity isn't important or might cause issues.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] chore: Add case-insensitive string set utility

tests/e2e/e2e_test.go, tests/e2e/network/ensureloadbalancer.go, tests/e2e/network/network_security_group.go, tests/e2e/network/standard_lb.go
/kind testing
Fix leftover IPv6 support in e2e
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.26] Fix leftover IPv6 support in e2e

pkg/provider/azure_storageaccount.go
/kind cleanup
chore: AddStorageAccountTags refine
since map is passing by pointer, it's better create a new map during map element compare
Fixes #
```release-note
chore: AddStorageAccountTags refine
```
```docs
chore: AddStorageAccountTags refine
```
=> chore: AddStorageAccountTags refine

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_standard_test.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmss_test.go, pkg/provider/azure_controller_vmssflex.go, pkg/provider/azure_controller_vmssflex_test.go, pkg/provider/azure_mock_vmsets.go, pkg/provider/azure_vmsets.go
/kind feature
feat: add forceDetach parameter in DetachDisk function
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/update?view=rest-compute-2023-10-02&tabs=HTTP#diskdetachoptiontypes
DiskDetachOptionTypes | Specifies the detach behavior to be used while detaching a disk or which is already in the process of detachment from the virtual machine. Supported values: ForceDetach. detachOption: ForceDetach is applicable only for managed data disks. If a previous detachment attempt of the data disk did not complete due to an unexpected failure from the virtual machine and the disk is still not released then use force-detach as a last resort option to detach the disk forcibly from the VM. All writes might not have been flushed when using this detach behavior. This feature is …
=> feat: add forceDetach parameter in DetachDisk function

.pipelines/run-autoscaling-e2e.yml, .pipelines/run-autoscaling-multipool-e2e.yml, tests/e2e/autoscaling/autoscaler.go, tests/e2e/utils/node_utils.go
/kind cleanup
/kind flake
Current autoscaling E2Es can be unreliable when trying to catch over-scaling, as it only checks once at the end. 
This has resulted in a Cluster Autoscaler image that contains over-scaling issue to get through the check unnoticed.
This PR aims to increase test coverage to cover the case where there are unexpected scale operations during and after standard scaling check.
Fixes #
```release-note
NONE
```
```docs
```
=> test: improve autoscaling E2E to prevent unexpected scale operations

Makefile
This change updates the makefile to allow an override of the $(PKG_CONFIG) target.
This allows for overriding of the generated ldflags from `hack/pkg-config.sh`.
/kind feature
We are trying to ship the acr-credential-provider with openshift. To do this we are building an RPM. The build system expects the version(s) to be settable from env vars so they are consistent across openshift (e.g 4.15). We don't want to use the git commit / version, or just pin to 'latest'. 
This allows setting ldflags without using the `hack/pkg-config.sh` script.
Currently, the options for setting version `ldflags` are:
-  Set everything to `latest` 
-  Rely on `git` being present in the build environment, and use the pkg-config script.
This change allows you to override the invocation of the pkg-config script, …
=> Updates Makefile to allow override of $(PKG_CONFIG)

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: nfs file share created in storage account that has smb file share
by default, this driver would search a storage account when creating a new nfs file share, while if storage account with matching sku already exists, this driver does not check EnableHTTPSTrafficOnly property in storage account, which means there is possibility that nfs file share is created in a storage account that has smb file share, finally lead to nfs file share mount permission error
```
// EnableHTTPSTrafficOnly - Allows https traffic only to storage service if sets to true. The default value is true since API version 2019-04-01.
EnableHTTPSTrafficOnly *bool `json:"supportsHttpsTrafficOnly,omitempty"`
```
Fixes #
```release-note
fix: nfs file share created in storage account that has smb file share
``` …
=> fix: nfs file share created in storage account that has smb file share

pkg/azclient/cloud.go, pkg/azclient/cloud_test.go
/kind bug
This change updates AzureCloudConfigFromURL to check that the URL (ResourceManagerEndpoint) that is used to build the config has been returned. If it has not, it sets it using the URL provided.
This avoids the case where the endpoint is used to build config, but does not return it's self - causing the created configuration to fail .
Fixes  https://github.com/kubernetes-sigs/cloud-provider-azure/issues/5558
```release-note
NONE
```
```docs
NONE
```
=> Handle endpoint not being rerturned in AzureCloudConfigFromURL

pkg/provider/azure_loadbalancer.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/configuration.go, pkg/provider/loadbalancer/configuration_test.go, pkg/provider/loadbalancer/iputil/prefix.go, pkg/provider/loadbalancer/iputil/prefix_test.go
/kind feature
When user-provided `LoadBalancerSourceRanges` or `azure-allowed-ip-ranges` are not valid network prefixes, cloud-controller-manager skips these invalid ranges, emits a warning event, and adds a deny-All rule in nsg.
Fixes #5599 
```release-note
When user-provided `LoadBalancerSourceRanges` or `azure-allowed-ip-ranges` are not valid network prefixes, cloud-controller-manager skips these invalid ranges, emits a warning event, and adds a deny-All rule in nsg.
```
```docs
```
=> feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules

tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind testing
Add a failureDomain for multiple zone templates. There's a new field called "trafficDistribution" in k/k, whose e2e test needs 3 zones.
feature: https://github.com/kubernetes/kubernetes/pull/123487
e2e: https://github.com/kubernetes/kubernetes/pull/123812
Fixes #
```release-note
NONE
```
```docs
```
=> Add a failureDomain for multiple zone templates

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go
/kind feature
cherry-picking #5650 
Fixes #
```release-note
When user-provided `LoadBalancerSourceRanges` or `azure-allowed-ip-ranges` are not valid network prefixes, cloud-controller-manager skips these invalid ranges, emits a warning event, and adds a deny-All rule in nsg.
```
```docs
```
=> [release-1.27] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go
/kind feature
cherry-picking #5650 
Fixes #
```release-note
When user-provided `LoadBalancerSourceRanges` or `azure-allowed-ip-ranges` are not valid network prefixes, cloud-controller-manager skips these invalid ranges, emits a warning event, and adds a deny-All rule in nsg.
```
```docs
```
=> [release-1.26] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/netip.go, pkg/provider/loadbalancer/netip_test.go
/kind feature
cherry-pick #5650 
Fixes #
```release-note
When user-provided `LoadBalancerSourceRanges` or `azure-allowed-ip-ranges` are not valid network prefixes, cloud-controller-manager skips these invalid ranges, emits a warning event, and adds a deny-All rule in nsg.
```
```docs
```
=> [release-1.28] feat: skip invalid LoadBalancerSourceRanges network CIDRs when provisioning nsg rules

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go
/kind bug
Fixes #5762
```release-note
Fix NSG DenyAll rule priority
```
```docs
```
=> [release-1.27] Reorder security rules to ensure 'DenyAll' rule appears after 'Allow' rule

pkg/provider/azure_zones.go
/kind bug
fix: get zone panic
```
I0330 02:55:06.555100       1 utils.go:78] GRPC request: {}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x184be5b]
goroutine 181 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).GetZone(0xc00064ea80, {0xc000905320?, 0xc00058a680?})
/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_zones.go:179 +0x2db
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).NodeGetInfo(0xc00091a000, {0x205aa20, 0xc000905050}, 0x253a955?)
/mnt/vss/_work/1/go/src/sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk/nodeserver.go:336 +0x13b
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeGetInfo_ …
```
=> fix: get zone panic

pkg/azclient/arm_conf.go, pkg/azclient/armauth/auxiliary_auth_policy.go, pkg/azclient/armauth/keyvault_credential.go, pkg/azclient/auth.go, pkg/azclient/auth_conf.go, pkg/azclient/go.mod, pkg/azclient/go.sum
/feature
This PR introduces KeyVaultCredential, which fetches tokens from the KeyVault secret. These tokens are used for accessing resources from NetworkTenant or as auxiliary tokens to access resources from MultiTenant.
Fixes #
```release-note
NONE
```
```docs
```
=> Introduce KeyVaultCredential for SDK v2

pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind bug
Optionally add one or more of the following kinds if applicable:
azure_credential provider uses a greedy registry expression, which make it difficult for using upstream ACRs
```release-note
NONE
```
```docs
```
=> Update Azure Credentials Provider Regex to be non-greedy

pkg/provider/loadbalancer/configuration.go, pkg/provider/loadbalancer/configuration_test.go
/kind bug
Allow space-separated load balancer source ranges in service annotation. Allow `service.beta.kubernetes.io/load-balancer-source-ranges` to be used together with `service.beta.kubernetes.io/azure-allowed-service-tags`.
Fixes #5883 
```release-note
Allow space-separated load balancer source ranges in service annotation. Allow `service.beta.kubernetes.io/load-balancer-source-ranges` to be used together with `service.beta.kubernetes.io/azure-allowed-service-tags`.
```
```docs
```
=> fix: allow space separated load balancer source ranges

pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
/kind bug
Fix cleaning legacy security rules while upgrading from versions that are 1.28 or older.
Fixes #
```release-note
Fix cleaning legacy security rules while upgrading from versions that are 1.28 or older.
```
```docs
```
=> Fix cleaning up stale security rules

pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go
/kind bug
cherry pick #5885 
Fixes #
```release-note
Allow space-separated load balancer source ranges in service annotation. Allow `service.beta.kubernetes.io/load-balancer-source-ranges` to be used together with `service.beta.kubernetes.io/azure-allowed-service-tags`.
```
```docs
```
=> [release-1.26] fix: allow space separated load balancer source ranges

pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go
/kind bug
cherry-pick #5885 
Fixes #
```release-note
Allow space-separated load balancer source ranges in service annotation. Allow `service.beta.kubernetes.io/load-balancer-source-ranges` to be used together with `service.beta.kubernetes.io/azure-allowed-service-tags`.
```
```docs
```
=> [release-1.28] fix: allow space separated load balancer source ranges

pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go
/kind bug
cherry pick #5885 
Fixes #
```release-note
Allow space-separated load balancer source ranges in service annotation. Allow `service.beta.kubernetes.io/load-balancer-source-ranges` to be used together with `service.beta.kubernetes.io/azure-allowed-service-tags`.
```
```docs
```
=> [release-1.27] fix: allow space separated load balancer source ranges

pkg/metrics/azure_metrics.go
/kind cleanup
chore: expose metrics log level
this PR does not change the default log level(3), this PR just exposes metrics log level, thus user could adjust the log level later
Fixes #
```release-note
none
```
```docs
none
```
=> chore: expose metrics log level

pkg/provider/azure_vmss_cache.go, pkg/provider/azure_vmssflex.go, pkg/provider/azure_vmssflex_test.go
/kind bug
Force cache refresh for getVMManagementTypeByIPConfigurationID(). The reason is that when a new standalone VM is included in the cluster, CCM cannot tell its VM type with stale cache.
Fixes #
```release-note
Force cache refresh for getVMManagementTypeByIPConfigurationID(). The reason is that when a new standalone VM is included in the cluster, CCM cannot tell its VM type with stale cache.
```
```docs
```
=> Fix getVMManagementTypeByIPConfigurationID()

.github/workflows/codeql-analysis.yml, .github/workflows/scorecards.yml, .github/workflows/trivy.yaml
/kind cleanup
This PR fixes an [issue](https://github.com/github/codeql-action/issues/1959#issuecomment-2087039558) with the [github/codeql-action](https://github.com/github/codeql-action) GitHub action which stopped it being able to be updated by Dependabot. It will also remove the Node.js 16 deprecation warning from the workflow runs.
Fixes #
```release-note
NONE
```
```docs
```
=> chore(deps): Fixed non-updatable CodeQL GH action

pkg/azureclients/vmclient/azure_vmclient.go, pkg/azureclients/vmclient/azure_vmclient_test.go, pkg/azureclients/vmclient/interface.go, pkg/azureclients/vmclient/mockvmclient/interface.go
/kind feature
/kind api-change
We are currently working on the autoscaling feature for single instance pool (vms pool) - CAS will scale down vms pool with Deallocate/Delete mode based on the agentpool's setting. We will need the power state of a VM to know whether it's running or being deallocated, which is located in the instance view of VM.
CAS (Cluster-Autoscaler) relies on cloud provider to list VMs in the node resource group. This PR add a new ListWithInstanceView method to list all VMs in a resource group with expanded instance view.
Fixes #
```release-note
No breaking change on existing behavior.
```
```docs
```
=> Add ListWithInstanceView to Azure vm client

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, tests/e2e/network/network_security_group.go
/kind cleanup
Fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-dualstack-vmss-capz/1787935535004651520
Fixes #
```release-note
NONE
```
```docs
```
=> [e2e] Support dual stack for NSG test case

pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/fnutil/slice.go, pkg/provider/loadbalancer/testutil/fixture/azure_publicip.go, pkg/provider/loadbalancer/testutil/fixture/kubernetes.go, tests/e2e/network/network_security_group.go
/kind bug
bug: When creating LoadBalancer services with a shared BYO public IP, the NSG rules are not generated correctly.
how to reproduce:
1. create 1 BYO public IP
2. creating 2 services with `service.beta.kubernetes.io/azure-pip-name: {the PIP name}`
3. check NSG rules
This PR would list all services and then filter by IP address instead of using PIP tags when checking for services with a shared PIP.
```release-note
Fix generating NSG rules while using shared BYO public IP
```
```docs
```
=> Fix generating NSG rules while using shared BYO public IP

hack/test-ccm-e2e.sh, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go, pkg/provider/loadbalancer/securitygroup/securityrule.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go, tests/e2e/network/network_security_group.go
/kind bug
If you’ve got NSG rules set up like the one below, trying to apply a service will throw an error because you can’t set `destinationAddressPrefixes` to `["*"]`. This PR fixes that by using `destinationAddressPrefix` when there’s just one destination prefix.
```json
{
"id": "/subscriptions/b48b8ebc-3e57-47ff-8603-408c05a7f2ba/resourceGroups/mc_e2erg-runner-pkqtqwafxgdpcaish_e2eaks-tgc_eastus/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-40253661-nsg/securityRules/NRMS-Rule-105",
"name": "NRMS-Rule-105",
"properties": {
"access": "Deny",
"description": "DO NOT DELETE - Will result in ICM Sev 2 - Azure Core Security, see aka.ms/cainsgpolicy",
"destinationAddressPrefix": "*",
"destinationPortRanges": [
"1433",
"1434",
"3306",
"4333",
"5432",
"6379",
"7000",
"7001", …
```
=> Fix setting single dst prefix for NSG rule

hack/test-ccm-e2e.sh, pkg/azclient/client-gen/go.mod, pkg/azclient/configloader/go.mod, pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go, pkg/provider/loadbalancer/securitygroup/securityrule.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go, tests/e2e/network/network_security_group.go, tests/kubemark/configs/experimental/storage/pod-startup/config.yaml
/kind bug
cherry-pick #6258 
Fixes #
```release-note
Fix setting single dst prefix for NSG rule
```
```docs
```
=> [release-1.30] Fix setting single dst prefix for NSG rule

hack/test-ccm-e2e.sh, pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go, pkg/provider/loadbalancer/securitygroup/securityrule.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go, tests/e2e/network/network_security_group.go, tests/kubemark/configs/experimental/storage/pod-startup/config.yaml
/kind bug
cherry-pick #6258 
Fixes #
```release-note
Fix setting single dst prefix for NSG rule
```
```docs
```
=> [release-1.29] Fix setting single dst prefix for NSG rule

pkg/nodemanager/nodemanager.go, pkg/nodemanager/nodemanager_test.go
/kind cleanup
Chores: fix spelling errors
Fixes #
```release-note
NONE
```
```docs
```
=> Chores: fix spelling errors

pkg/consts/consts.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
doesn't try to add Windows  2019 VMSS to IPv6 backend pools because 2019 will never support IPv6 so it shouldn't be added.
Fixes #6315 
```release-note
This only affects 1P, internal-to-Microsoft, customers. Windows 2019 with dual-stack is not possible otherwise.
```
```docs
```
=> fix: ignore Windows 2019 in `ensureVMSSInPool` for IPv6 backend pools only

pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go
/kind bug
Fixes https://github.com/Azure/AKS/issues/4254
```release-note
Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups
```
```docs
```
=> fix: Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups

pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go
/kind bug
cherry-pick #6331 
Fixes #
```release-note
Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups
```
```docs
```
=> [release-1.30] fix: Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups

Dockerfile, cloud-node-manager.Dockerfile, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/testutil/fixture/azure_securitygroup.go
/kind bug
cherry-pick #6331 
Fixes #
```release-note
Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups
```
```docs
```
=> [release-1.29] fix: Ensure NSG rules cleanup excludes DestinationApplicationSecurityGroups

README.md
Removes references to Kubernetes before v1.27 in the support matrices in README.md.
AKS won't provision v1.26 or earlier (and v1.27 will soon be unavailable), and v1.26 and earlier have been [unsupported](https://kubernetes.io/releases/patch-releases/#non-active-branch-history) by the Kubernetes community for months. It seems simpler and safer not to include historical versions in the support matrices.
N/A
```release-note
NONE
```
=> Remove unsupported versions from matrices

pkg/log/logger.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/loadbalancer/securitygroup/securitygroup.go, pkg/provider/loadbalancer/securitygroup/securitygroup_test.go
/kind cleanup
Start using contextual logging in parts of cloudprovider’s LoadBalancer interfaces. No function or business logic should be affected.
part of #1575 
```release-note
NONE
```
```docs
```
=> Refactor: replace with contextual logging in LoadBalancer interfaces

pkg/consts/consts.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
doesn't try to add Windows  2019 VMSS to IPv6 backend pools because 2019 will never support IPv6 so it shouldn't be added.
Fixes #6315 
```release-note
This only affects 1P, internal-to-Microsoft, customers. Windows 2019 with dual-stack is not possible otherwise.
```
```docs
```
=> [release-1.28] fix: ignore Windows 2019 in ensureVMSSInPool for IPv6 backend pools only

pkg/consts/consts.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
doesn't try to add Windows  2019 VMSS to IPv6 backend pools because 2019 will never support IPv6 so it shouldn't be added.
Fixes #6315 
```release-note
This only affects 1P, internal-to-Microsoft, customers. Windows 2019 with dual-stack is not possible otherwise.
```
```docs
```
=> [release-1.27] fix: ignore Windows 2019 in ensureVMSSInPool for IPv6 backend pools only

content/en/development/deploy-cluster.md
doc: Enrich deploy-cluster.md
Partly Fixes #6550
```release-note
NONE
```
```docs
```
=> doc: Enrich deploy-cluster.md

pkg/provider/azure_storageaccount.go
/kind bug
fix: not listing all accounts by default
this could reduce GetServiceProperties throttling when there are 200+ accounts in one resource group
Fixes #
```release-note
fix: not listing all accounts by default
```
```docs
fix: not listing all accounts by default
```
=> fix: not listing all accounts by default

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: return error when GetServiceProperties fails in account search
when `GetServiceProperties` failed in account search, original behavior is return false, thus new account will always be created when throttling error happens, this PR returns error when GetServiceProperties fails in account search, thus account search would fail when throttling error happens which is the expected behavior.
Fixes #
```release-note
fix: return error when GetServiceProperties in account search
```
```docs
fix: return error when GetServiceProperties in account search
```
=> fix: return error when GetServiceProperties fails in account search

tests/e2e/utils/azure_auth.go, tests/e2e/utils/container_registry_utils.go
/kind cleanup
This PR 
1. modifies an `az login` command invoked from the e2e tests to use a federated token when available instead of always trying to use a service principal password.
2. support workload identity in e2e test.
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] Support workload identity in e2e test

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_storageaccount.go, pkg/provider/azure_subnet_repo.go
fix: subnet update issue when vnetResourceGroup is specified in azure file storage class
this PR adds a new parameter `vnetResourceGroup` into `getSubnet` func, if `vnetResourceGroup` is provided, then use it, otherwise use `vnetResourceGroup` from cloud provider config which keeps the same logic
<summary> related config and error msg </summary>
<details>
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: my-azurefile
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict
- actimeo=30
- nobrl
parameters:
networkEndpointType: privateEndpoint
skuName: Premium_LRS
subnetName: default
vnetName: my-vnet  # this is the name of the private vnet created on step 3
vnetResourceGroup: aks-ds-rg
provisioner: file.csi.azure.com
reclaimPolicy: …
```
=> fix: subnet update issue when vnetResourceGroup is specified

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: VirtualNetworkRule match issue during account search
original code logic does not check every VirtualNetworkResourceID in the account, thus the matching is incomplete, this PR fixes the issue.
Fixes #
```release-note
fix: VirtualNetworkRule match issue during account search
```
```docs
fix: VirtualNetworkRule match issue during account search
```
=> fix: VirtualNetworkRule match issue during account search

pkg/provider/azure_storageaccount.go
/kind cleanup
chore: refine logging in AreVNetRulesEqual func
/hold
Fixes #
```release-note
none
```
```docs
none
```
=> chore: refine logging in AreVNetRulesEqual func

tests/e2e/auth/cred.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/container_registry_utils.go
fix: Keep auth envs when building e2e azure clients
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.27] fix: Keep auth envs when building e2e azure clients

tests/e2e/auth/cred.go, tests/e2e/utils/azure_auth.go, tests/e2e/utils/container_registry_utils.go
fix: Keep auth envs when building e2e azure clients
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.28] fix: Keep auth envs when building e2e azure clients

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go, pkg/provider/azure_subnet_repo.go
/kind bug
fix: support mulltiple subnet when creating private endpoints
when specifying "networkEndpointType: privateEndpoint" in storage class, only first subnet is associated with a new private endpoint, this does not work when there are multiple subnets. Ideally when there are multiple subnets, multiple private endpoints should be created, every private endpoint is associated with one subnet, and only one dns zone will be created mapping to vnet and multiple private endpoints
For example, in csi logs below, there are two subnets(aks-subnet, subnet2), two private endpoint(f0240127bc91d4905903342-pvtendpoint-0, f0240127bc91d4905903342-pvtendpoint-1) will be created and one private DNS zone group(f0240127bc91d4905903342-dnszonegroup) will be created. 
csi logs:
```
I0809 10:44:20.264799 …
```
=> fix: support mulltiple subnet when creating private endpoints

azure-pipelines.yml, pkg/nodeipam/ipam/range_allocator.go, pkg/nodeipam/ipam/range_allocator_test.go
/kind bug
This PR fixes a crash that is caused when custercidr is mismatched with nodecidrs.
When the cloud-controller manager detects a mismatch between the clustercidr provided to it via argument and node.spec.podcidrs of existing nodes, it assumes this is a fatal condition and halts its execution and crash. This mismatch is not a fatal condition, controller manager should tolerate this mismatch and keep trying to reconcile instead of crashing. The side-effect of crashing is that when a new node joins the cluster, its not able to get the new podcidr from controller manager because its been crashing. If controller-manager tolerates this mismatch, we can have old nodes running old podcidr and new nodes running new podcidr and that's a perfectly ok condition to be in. In fact when a user …
=> Fix: Failure to Enforce clustercidr on nodes with exisiting cidr should not be treated as a fatal error

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/iputil/prefix.go, pkg/provider/loadbalancer/iputil/prefix_test.go, pkg/provider/loadbalancer/iputil/prefix_tree.go, pkg/provider/loadbalancer/iputil/prefix_tree_test.go, tests/e2e/network/network_security_group.go
/kind bug
This PR introduces a prefix tree to aggregate overlapping allowed source ranges. Without it, customers have to merge the CIDR manually; otherwise, the Azure NSG operation will fail.
Fixes #6775 
```
goos: darwin
goarch: arm64
pkg: sigs.k8s.io/cloud-provider-azure/pkg/provider/loadbalancer/iputil
BenchmarkAggregatePrefixes/IPv4-100-10             72164             16502 ns/op  // with 100 IPv4 CIDRs
BenchmarkAggregatePrefixes/IPv6-100-10             71418             16706 ns/op
BenchmarkAggregatePrefixes/IPv4-IPv6-200-10        22771             52537 ns/op
BenchmarkAggregatePrefixes/IPv4-1000-10             7576            160325 ns/op  // with 1k IPv4 CIDRs
BenchmarkAggregatePrefixes/IPv6-1000-10             7062            159379 ns/op …
```
=> Aggregate overlapping allowed source ranges

cmd/acr-credential-provider/main.go, examples/out-of-tree/credential-provider-config.yaml, pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind feature
[credential provider] Add a flag mirrorMapping. This flag is to mirror registry A to B when fetching credential.
Fixes #6845
```release-note
[credential provider] Add a flag mirrorMapping. This flag is to mirror registry A to B when fetching credential.
```
```docs
```
=> [credential provider] Add a flag mirrorMapping

cmd/cloud-controller-manager/app/controllermanager.go, cmd/cloud-controller-manager/controller-manager.go, pkg/log/flag.go, pkg/log/logger.go, pkg/log/slog.go, pkg/log/std.go
/kind cleanup
It adds a CLI flag `--log-format` to cloud-controller-manager, which supports a new logging format JSON. When --log-format=json is set, the loggers of both klog and slog will print log messages as JSON. Structured logging is easier to query and filter.
**NOTE**
1. The verbosity of `klog.V(N)` will be attached to the log key-value with the name `v`, as in `{"level":"info", "msg":"foo", "v":"5"}`. But logs with `level=error` always have a verbosity of 0.
2. slog will be used as the klog backend iff JSON is enabled.
3. Plain text remains the default log format if not set.
**Sample Output**
```
{"level":"INFO","source":{"function":"sigs.k8s.io/cloud-provider-azure/cmd/cloud-controller-manager/app.startControllers","file":"/go/src/sigs.k8s.io/cloud-provider-azure/cmd/cloud-control …
```
=> Add support for JSON-formatted logging

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go
/kind bug
Fix two issues when changing service type from lb to externalName.
1. ExternalName service has no ipFamilies, we should not panic this.
2. We should not use `v4Enabled, v6Enabled := getIPFamiliesEnabled(service)` to check what backend pools should be deleted from the vmss.
Fixes #7503
```release-note
fix: Support switching from loadbalancer to externalName for services
```
```docs
```
=> fix: Support switching from loadbalancer to externalName for services

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go
/kind bug
Fix two issues when changing service type from lb to externalName.
1. ExternalName service has no ipFamilies, we should not panic this.
2. We should not use `v4Enabled, v6Enabled := getIPFamiliesEnabled(service)` to check what backend pools should be deleted from the vmss.
Fixes #7503
```release-note
fix: Support switching from loadbalancer to externalName for services
```
```docs
```
=> [release-1.29] fix: Support switching from loadbalancer to externalName for services

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/azure_vmss.go
/kind bug
Fix two issues when changing service type from lb to externalName.
1. ExternalName service has no ipFamilies, we should not panic this.
2. We should not use `v4Enabled, v6Enabled := getIPFamiliesEnabled(service)` to check what backend pools should be deleted from the vmss.
Fixes #7503
```release-note
fix: Support switching from loadbalancer to externalName for services
```
```docs
```
=> [release-1.28] fix: Support switching from loadbalancer to externalName for services

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_utils.go
/kind bug
1. All endpointslices of a local service should be included in local backend pool updater, instead of only the first endpointslice.
2. In some rare cases, migration from NIC to IP-based LB can be in a middle state where the NIC references are removed, but those IPConfigs in the backend pool are not. In this case, we should manually exclude those IPConfigs from the request body.
3. localServiceOwnsBackendPool should compare the full backend pool name, not just prefix, because two service names can share the same prefix.
4. There is a corner case when the cluster is being updated to multi-slb from classic NIC-based single lb, not from an IP-based cluster. In this case, if the service being reconciled is local, the cloud provider will try to update a NIC pool to IP-based pool …
=> Multi-slb related bug fixes

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_backendpool.go, pkg/provider/azure_loadbalancer_backendpool_test.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_local_services.go, pkg/provider/azure_local_services_test.go, pkg/provider/azure_standard.go, pkg/provider/azure_utils.go
/kind bug
1. All endpointslices of a local service should be included in local backend pool updater, instead of only the first endpointslice.
2. In some rare cases, migration from NIC to IP-based LB can be in a middle state where the NIC references are removed, but those IPConfigs in the backend pool are not. In this case, we should manually exclude those IPConfigs from the request body.
3. localServiceOwnsBackendPool should compare the full backend pool name, not just prefix, because two service names can share the same prefix.
4. There is a corner case when the cluster is being updated to multi-slb from classic NIC-based single lb, not from an IP-based cluster. In this case, if the service being reconciled is local, the cloud provider will try to update a NIC pool to IP-based pool …
=> [release-1.30] Multi-slb related bug fixes

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: match source account as first priority in snapshot restore and volume clone scenarios, this could speed up the snapshot restore and volume clone performance in azure file and blob csi drivers
Fixes #
```release-note
feat: match source account as first priority in snapshot restore and volume clone scenarios
```
```docs
feat: match source account as first priority in snapshot restore and volume clone scenarios
```
=> feat: match source account as first priority in snapshot restore and volume clone scenarios

pkg/provider/azure.go
/kind bug
fix: cloud provider should only generate userAgent if it's not provided
Fixes #
```release-note
fix: cloud provider should only generate userAgent if it's not provided
```
```docs
fix: cloud provider should only generate userAgent if it's not provided
```
=> fix: cloud provider should only generate userAgent if it's not provided

go.mod
/kind bug
Revert to go 1.22 windows filesystem behavior building with go 1.23 until use of Stat/Lstat/EvalSymlinks adjusts to go1.23 behavior
for more details, refer to https://github.com/kubernetes/kubernetes/issues/129080
Fixes #
```release-note
fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23
```
```docs
fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23
```
=> fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23

pkg/azclient/arm_conf.go, pkg/azclient/backendaddresspoolclient/custom_test.go, pkg/azclient/client-gen/generator/clientfactory.go, pkg/azclient/cloud.go, pkg/azclient/cloud_test.go, pkg/azclient/factory_gen.go
/kind feature
Track2 sdk: fetch acr login server and storage suffix from env/resourcemanager
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: fetch acr login server and storage suffix from env/arm metadata service

pkg/azclient/fileshareclient/custom.go, pkg/azclient/fileshareclient/custom_test.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
/kind feature
Track2 sdk: add filter parameter in list function of fileshare client
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: add filter parameter in list function of fileshare client

pkg/provider/securitygroup/securityrule.go
On special (aka undetermined) cases, the Azure API may return an empty string for security group's `DestinationAddressPrefixes`. For example:
```
...
"destinationAddressPrefix": "",
"destinationAddressPrefixes": [
"20.23.46.159"
],
...
"destinationAddressPrefix": "",
"destinationAddressPrefixes": [
"20.31.182.144",
"20.103.204.84",
"20.93.254.98",
...
```
As a result, the request to update the NSG may contain incorrect DAP prefixes resulting to an error like the following:
```
{
"name": "k8s-azure-lb_allow_IPv4_a4dbc5c93f3bdd7a058a3939da862f9c",
"properties": {
"access": "Allow",
"destinationAddressPrefixes": [
"", <--------------- not supported -------------
"20.101.205.120",
"20.101.205.84",
"20.103.202.213",
],
"destinationPortRange": "",
"destinationPortRanges": [
"15021",
"443",
"80" …
```
=> fix empty string NSG's DestinationAddressPrefix

pkg/provider/azure_local_services.go
/kind bug
Makes sure that the `cache.DeletedFinalStateUnknown` event is handled correctly, when an informer for endpoint slices becomes temporarily disconnected and misses an event.
Updates the logic to correctly type assert and avoid panicking if the event is not as expected.
Fixes #7775
```release-note
NONE
```
```docs
```
=> Prevent panic when informer receives cache.DeletedFinalStateUnknown

pkg/azclient/fileshareclient/custom.go, pkg/azclient/fileshareclient/custom_test.go, pkg/azclient/fileshareclient/fileshareclient_test.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go, pkg/azclient/fileshareclient/zz_generated_client.go
/kind cleanup
Track2 sdk: expose get option in fileshareclient
Fixes #
```release-note
NONE
```
```docs
```
=> Track2 sdk: expose get option in fileshareclient

.github/workflows/codeql-analysis.yml
/kind cleanup
Chores:ignore mock files in coverage report
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:ignore mock files in coverage report

pkg/provider/config/azure.go
/kind cleanup
Chores:move DisableAzureStackCloud to azclient package
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:move DisableAzureStackCloud to azclient package

hack/generate-release-note.sh
/kind cleanup
Chores:fetch acutal commit id when generate release note
Fixes #
```release-note
NONE
```
```docs
```
=> Chores:fetch acutal commit id when generate release note

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/config/azure.go
/kind cleanup
Chore: set batch size to great or equal to 1
Fixes #
```release-note
NONE
```
```docs
```
=> Chore: set batch size to great or equal to 1

content/en/development/design-docs/blb-migration.md
doc: Add design doc for blb migration
Fixes #
```release-note
NONE
```
```docs
```
=> doc: Add design doc for blb migration

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, tests/e2e/network/service_annotations.go
/kind bug 
**Context:**
Previously, when adding tags to Azure resources (e.g., when creating a new load balancer service, the new Public IP (PIP) inherits tags from AKS), we would remove any leading or trailing whitespace from the tag keys and values.
However, since Azure itself does not remove whitespace characters when assigning tags, this behavior could result in invalid tag values during subsequent inheritance or updates.
**Problem:**
If a tag value is initially set as `" null "` or `" NuLL "` (with leading/trailing spaces), it is successfully assigned because the whitespace prevents it from being interpreted as the reserved value "null".
However, during tag inheritance or updates, our process trims the whitespace, resulting in tag values like `"null"` or `"NuLL"`. These values are …
=> [relase-1.30] Fix: Preserve Whitespace for Tag Values Resembling "null" to Prevent ARM Assignment Errors

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go, pkg/provider/config/azure.go
/kind bug
In the logic for updating tags, if we define `systemTags`, any tags not included in `systemTags` will be deleted. However, this behavior can cause some AKS-managed tags to be mistakenly deleted. Adding all AKS-managed tags individually to `systemTags` would make `systemTags` excessively long and difficult to maintain.
This PR enhances the comparison logic between tags and `systemTags` by introducing prefix matching. With this change, we can add a prefix like `aks-managed` to `systemTags`, and any tags starting with `aks-managed`, such as `aks-managed-cluster-name` or `aks-managed-cluster-rg`, will be successfully matched and retained, preventing accidental deletion.
This approach reduces the size of `systemTags` while maintaining flexibility and ensuring that AKS-managed tags …
=> Fix : Enable system tag support prefix match

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind feature
feat: always match source account in restore and volume clone scenarios
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/7699
Fixes #
```release-note
feat: always match source account in restore and volume clone scenarios
```
```docs
feat: always match source account in restore and volume clone scenarios
```
=> [release-1.30] feat: always match source account in restore and volume clone scenarios

pkg/provider/azure_storageaccount.go, pkg/provider/azure_storageaccount_test.go
/kind bug
fix: VirtualNetworkRule match issue during account search
chore: refine logging in AreVNetRulesEqual func
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6741, https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6744
Fixes #
```release-note
fix: VirtualNetworkRule match issue during account search
```
```docs
fix: VirtualNetworkRule match issue during account search
```
=> [release-1.30] fix: VirtualNetworkRule match issue during account search

pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_repo.go, pkg/provider/virtualmachine/virtualmachine.go
/kind bug
We can call it a bug if Etag is assumed to be supported in vmss, and it can be a feature if etag support in vmss  and vms is not annouced.
Fixes #
```release-note
NONE
```
```docs
```
=> fix: add Etag field to request body to let Etag work

pkg/provider/azure.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind bug
In the logic for updating tags, if we define `systemTags`, any tags not included in `systemTags` will be deleted. However, this behavior can cause some AKS-managed tags to be mistakenly deleted. Adding all AKS-managed tags individually to `systemTags` would make `systemTags` excessively long and difficult to maintain.
This PR enhances the comparison logic between tags and `systemTags` by introducing prefix matching. With this change, we can add a prefix like `aks-managed` to `systemTags`, and any tags starting with `aks-managed`, such as `aks-managed-cluster-name` or `aks-managed-cluster-rg`, will be successfully matched and retained, preventing accidental deletion.
This approach reduces the size of `systemTags` while maintaining flexibility and ensuring that AKS-managed tags …
=> [release-1.28] Fix : Enable system tag support prefix match

pkg/provider/azure.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind bug
In the logic for updating tags, if we define `systemTags`, any tags not included in `systemTags` will be deleted. However, this behavior can cause some AKS-managed tags to be mistakenly deleted. Adding all AKS-managed tags individually to `systemTags` would make `systemTags` excessively long and difficult to maintain.
This PR enhances the comparison logic between tags and `systemTags` by introducing prefix matching. With this change, we can add a prefix like `aks-managed` to `systemTags`, and any tags starting with `aks-managed`, such as `aks-managed-cluster-name` or `aks-managed-cluster-rg`, will be successfully matched and retained, preventing accidental deletion.
This approach reduces the size of `systemTags` while maintaining flexibility and ensuring that AKS-managed tags …
=> [release-1.29] Fix : Enable system tag support prefix match

pkg/provider/azure.go, pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind bug
In the logic for updating tags, if we define `systemTags`, any tags not included in `systemTags` will be deleted. However, this behavior can cause some AKS-managed tags to be mistakenly deleted. Adding all AKS-managed tags individually to `systemTags` would make `systemTags` excessively long and difficult to maintain.
This PR enhances the comparison logic between tags and `systemTags` by introducing prefix matching. With this change, we can add a prefix like `aks-managed` to `systemTags`, and any tags starting with `aks-managed`, such as `aks-managed-cluster-name` or `aks-managed-cluster-rg`, will be successfully matched and retained, preventing accidental deletion.
This approach reduces the size of `systemTags` while maintaining flexibility and ensuring that AKS-managed tags …
=> [release-1.30] Fix : Enable system tag support prefix match

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind test
This PR is a follow-up of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8106 to add Etag in ensureBackendPoolDeletedFromNode, and add UT to protect the input fields, like Etag, of vmss and vmss vm put operations.
I think a better test will be on top of service controller, which can retry on EtagMismatch error by mocking the go SDK. But this level of test is not covered in cloud-provider-azure yet, and we can put this into future test enhancement if necessary.
Fixes #
```release-note
None
```
```docs
```
=> test: add vm etag in ensureBackendPoolDeletedFromNode and add UT

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go
/kind bug
fix: disk attach/detach failure with track2 sdk
location field is also essential in standard vm disk attach/detach:
```
E0206 11:32:58.995844       1 controllerserver.go:617] Could not detach volume /subscriptions/4xxx/resourceGroups/capz-pq67w2/providers/Microsoft.Compute/disks/pvc-d29d0f4c-2223-4675-bc23-e875e49b1945 from node capz-pq67w2-md-0-sk4w6-sj8wv: PUT https://management.azure.com/subscriptions/xxx/resourceGroups/capz-pq67w2/providers/Microsoft.Compute/virtualMachines/capz-pq67w2-md-0-sk4w6-sj8wv
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: LocationRequired
--------------------------------------------------------------------------------
{
"error": {
"code": "LocationRequired",
"message": "The …
```
=> fix: disk attach/detach failure with track2 sdk

pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind bug
There's a potential spoofing when the image 
"<my-test>.azurecr.io.example.com/ubuntu2:latest" is sent to the credential provider plugin, it will fetch credential from <my-test>.azurecr.io unexpectedly.
Currently it's not possible considering kubelet will not call credential provider plugin since the "<my-test>.azurecr.io.example.com/ubuntu2:latest" does not match the matchImages defined below.
Also the credential provider plugin as a binary is installed on k8s node, is currently only called by kubelet if there's no manual operation.
```
apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
- name: acr-credential-provider
matchImages:
- "*.azurecr.io"
- "*.azurecr.cn"
- "*.azurecr.de"
- "*.azurecr.us"
defaultCacheDuration: "10m" // follow in-tree setting …
```
=> fix(credential-provider): check acr pattern to avoid spoofing

cloudbuild.yaml
/kind bug
godebug directive is introduced in golang 1.23 and used in go.mod, thus building images under golang1.23 will raise `unknown directive: godebug` issue, which blocks upstream image publishing https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-provider-azure-push-images/1889593820727742464.
golang 1.23 is  introduced to gcb-docker-gcloud by https://github.com/kubernetes/test-infra/pull/34159, and published by https://testgrid.k8s.io/sig-testing-image-pushes#gcb-docker-gcloud, and gcb-docker-gcloud defined in https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/cloudbuild.yaml is finally used to build and publish images
Fixes #
```release-note
NONE
```
```docs
```
=> bump golang in gcb-docker-gcloud to 1.23.4

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go, pkg/provider/config/multi_slb.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> fix: Empty node selector should work after non-empty node selector

pkg/azclient/utils/transport.go, pkg/azclient/utils/transport_test.go
/kind bug
Configure timeouts for HTTP/2
* http2.ReadIdleTimeout - The interval of health check for idle connections.
* http2.PingTimeout - The timeout for server to respond to a client ping.
Also added a unit test for the default transport.
Fixes #
```release-note
NONE
```
```docs
```
=> chore: configure timeouts for HTTP/2

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go, pkg/provider/config/multi_slb.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.31] fix: Empty node selector should work after non-empty node selector

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.30] fix: Empty node selector should work after non-empty node selector

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.29] fix: Empty node selector should work after non-empty node selector

pkg/provider/azure.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_utils.go
/kind bug
Fixes #
```release-note
```
```docs
```
=> [release-1.28] fix: Empty node selector should work after non-empty node selector

pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go
/kind bug
When a delete route operation comes in, not only the route with exactly the name should be deleted, but also all routes that have the node name as prefix should be deleted.
Fixes #8175
To reduce the potential impact, I separate the two deletion logic by adding a new for loop, instead of integrating them into one loop.
```release-note
fix: Remove all routes that have the node name as prefix
```
```docs
```
=> fix: Remove all routes that have the node name as prefix

pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go
/kind bug
When a delete route operation comes in, not only the route with exactly the name should be deleted, but also all routes that have the node name as prefix should be deleted.
Fixes #8175
To reduce the potential impact, I separate the two deletion logic by adding a new for loop, instead of integrating them into one loop.
```release-note
fix: Remove all routes that have the node name as prefix
```
```docs
```
=> [release-1.29] fix: Remove all routes that have the node name as prefix (#8427)

pkg/provider/azure.go
/kind bug
fix: incorrect cloud provider setting in sovereign cloud
the cloud provider with track2 sdk does not work in Azure China cloud, error is like following:
```
E0304 04:59:58.032152       1 utils.go:110] GRPC error: rpc error: code = Internal desc = ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
--------------------------------------------------------------------------------
{
"error": "invalid_resource",
"error_description": "AADSTS500011: The resource principal named https://management.core.windows.net/ was not found in the tenant named …
```
=> fix: incorrect cloud provider setting in sovereign cloud

pkg/provider/azure_routes.go, pkg/provider/azure_routes_test.go
/kind bug
When a delete route operation comes in, not only the route with exactly the name should be deleted, but also all routes that have the node name as prefix should be deleted.
Fixes #8175
To reduce the potential impact, I separate the two deletion logic by adding a new for loop, instead of integrating them into one loop.
```release-note
fix: Remove all routes that have the node name as prefix
```
```docs
```
=> [release-1.30] fix: Remove all routes that have the node name as prefix (#8427)

pkg/azclient/managedclusterclient/custom_test.go
Potential fix for [https://github.com/kubernetes-sigs/cloud-provider-azure/security/code-scanning/195](https://github.com/kubernetes-sigs/cloud-provider-azure/security/code-scanning/195)
To fix the problem, we need to increase the RSA key size from 1024 bits to 2048 bits. This change will ensure that the key meets the recommended security standards. The change should be made in the `pkg/azclient/managedclusterclient/custom_test.go` file, specifically on line 42 where the RSA key is generated. No additional methods or imports are needed to implement this change.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 195: Use of a weak cryptographic key

.github/workflows/codeql-analysis.yml, .github/workflows/codeql-azclient.yml, .github/workflows/lint-azclient.yaml, .github/workflows/release.yaml, .github/workflows/trivy.yaml, .github/workflows/update-vendor-license.yml, Dockerfile, cloud-node-manager.Dockerfile, cloudbuild.yaml, e2e.Dockerfile, go.mod, health-probe-proxy/go.mod, kubetest2-aks/go.mod, pkg/azclient/cache/go.mod, pkg/azclient/client-gen/go.mod, pkg/azclient/configloader/go.mod, pkg/azclient/go.mod, pkg/azclient/trace/go.mod, tests/go.mod
/kind testing
Chores: set go to 1.23.6
Fixes #8535 
```release-note
NONE
```
```docs
```
=> Chores: set go.mod in main to 1.24 and one in azclient to 1.23

internal/testutil/fixture/fixture.go
/kind testing
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/8521/pull-cloud-provider-azure-unit-1-31/1897178703616544768
The root cause of the flaky test is that the random fixture occasionally generates overlapping or mergeable CIDRs, which disrupts the comparison and assertions in the test. This PR resolves the issue in the access control flaky test by generating CIDRs with a larger bit size, ensuring that no overlapping CIDRs are produced in a single run—sufficient for the existing test case.
Fixes #
```release-note
NONE
```
```docs
```
=> [flaky test] Generate non-overlapping and non-mergable CIDRs with best effort

pkg/provider/azure_controller_vmss.go
/kind bug
fix: reduce get disk call in disk attach/detach on VMSS, original code has a bug that when it's NotFound error, it would call getdisk, that's wrong, this PR fixes the issue.
<details>
```
I0314 13:36:11.257464       1 azure_armclient.go:380] Received error in WaitForAsyncOperationResult: '{"error":{"code":"ParentResourceNotFound","message":"Failed to perform 'read' on resource(s) of type 'virtualMachineScaleSets/virtualMachines', because the parent resource '/subscriptions/xxx/resourceGroups/subscription-81db8cb7-nodes/providers/Microsoft.Compute/virtualMachineScaleSets/aks-elastic-19571921-vmss' could not be found."}}', response code 404
I0314 13:36:11.257534       1 azure_vmssvmclient.go:346] Received error in vmssvm.put.request: resourceID: …
```
=> fix: reduce get disk calls in disk attach/detach on VMSS

pkg/provider/azure_controller_vmss.go
/kind bug
fix: reduce get disk calls in disk attach/detach on VMSS
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8623
Fixes #
```release-note
fix: reduce get disk calls in disk attach/detach on VMSS
```
```docs
fix: reduce get disk calls in disk attach/detach on VMSS
```
=> [release-1.31] fix: reduce get disk calls in disk attach/detach on VMSS

pkg/provider/azure_controller_vmss.go
/kind bug
fix: reduce get disk calls in disk attach/detach on VMSS
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8623
Fixes #
```release-note
fix: reduce get disk calls in disk attach/detach on VMSS
```
```docs
fix: reduce get disk calls in disk attach/detach on VMSS
```
=> [release-1.30] fix: reduce get disk calls in disk attach/detach on VMSS

pkg/provider/loadbalancer/securitygroup/securityrule.go
/kind bug
cherry-pick #7854 
Fixes #
```release-note
Fix a bug that prevented patches to NSGs when the Azure API responded with empty strings for `DestinationAddressPrefix`
```
```docs
```
=> [release-1.29] fix empty string on DAP (#7854)

cmd/acr-credential-provider/main.go, pkg/credentialprovider/azure_acr_helper.go, pkg/credentialprovider/azure_credentials.go, pkg/credentialprovider/azure_credentials_test.go
/kind bug
Run the binary will return error log `Invalid registry mirror format` without real harm since registryMirrorStr defaults to emtpy.
Fix this by checking the emptiness of registryMirrorStr and return when it's empty.
Besides this change, I added 3 small but debug-friendly changes in this PR to reduce the cherry-pick PR numbers.
- add klog verobse level flag `-v`
- add version flag `--version`
- add debug level log for correlationID.
- verbose log
```
The acr credential provider is responsible for providing ACR credentials for kubelet
Usage:
acr-credential-provider configFile [flags]
Flags:
-h, --help                           help for acr-credential-provider
--log-flush-frequency duration   Maximum number of seconds between log flushes (default 5s)
-r, --registry-mirror string …
```
=> fix(credential-provider): check empty mirror mapping and add debugging info

pkg/azclient/auth.go, pkg/azclient/auth_fake_test.go, pkg/azclient/auth_func.go, pkg/azclient/auth_func_test.go, pkg/azclient/auth_option.go, pkg/azclient/auth_option_test.go, pkg/azclient/auth_test.go, pkg/azclient/go.mod, pkg/azclient/go.sum
/kind cleanup
Refactor the AuthProvider to remove the `MultiTenantCredential`, as the `ComputeCredential` would work the same and provide the client options while using the auxiliary token provider.
Fixes #
```release-note
NONE
```
```docs
```
=> [azclient] Refactor AuthProvider multi-tenant token credential

.github/workflows/codeql-analysis.yml, .github/workflows/codeql-azclient.yml, .github/workflows/lint-azclient.yaml, .github/workflows/lint.yaml, .github/workflows/scorecards.yml, .github/workflows/trivy.yaml
Reverts kubernetes-sigs/cloud-provider-azure#8717 because the linter is broken after this update.
=> Revert "build(deps): bump the all group with 2 updates"

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
If the vm is not found from the cache, we would skip returning the not found error and in this case, the code will move on with a nil vm, causing a panic. This PR skips ensuring the host in the pool if the vm is not found.
Fixes #
```release-note
fix: Skip ensuring host in pool if the vm is not found
```
```docs
```
=> fix: Skip ensuring host in pool if the vm is not found

internal/testutil/fixture/fixture.go
/kind testing
cherry pick #8587 
Fixes #
```release-note
NONE
```
```docs
```
=> [release-1.31] Generate non-overlapping and non-mergable CIDRs with best effort (#8587)

pkg/provider/securitygroup/securityrule.go
/kind bug
cherry-pick #7854 
Fixes #
```release-note
Fix a bug that prevented patches to NSGs when the Azure API responded with empty strings for `DestinationAddressPrefix`
```
```docs
```
=> [release-1.30] fix empty string on DAP (#7854)

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
If the vm is not found from the cache, we would skip returning the not found error and in this case, the code will move on with a nil vm, causing a panic. This PR skips ensuring the host in the pool if the vm is not found.
Fixes #
```release-note
fix: Skip ensuring host in pool if the vm is not found
```
```docs
```
=> [release-1.29] fix: Skip ensuring host in pool if the vm is not found

pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go
/kind bug
If the vm is not found from the cache, we would skip returning the not found error and in this case, the code will move on with a nil vm, causing a panic. This PR skips ensuring the host in the pool if the vm is not found.
Fixes #
```release-note
fix: Skip ensuring host in pool if the vm is not found
```
```docs
```
=> [release-1.31] fix: Skip ensuring host in pool if the vm is not found

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
/kind feature
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be migrated to the newly created standard load balancer, with their ip addresses unchanged. This operation may cause downtime.
Fixes #
```release-note
feat: Support migration from basic to standard load balancer
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be …
```
=> [release-1.30] feat: Support migration from basic to standard load balancer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
/kind feature
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be migrated to the newly created standard load balancer, with their ip addresses unchanged. This operation may cause downtime.
Fixes #
```release-note
feat: Support migration from basic to standard load balancer
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be …
```
=> [release-1.29] feat: Support migration from basic to standard load balancer

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_repo.go, pkg/provider/azure_loadbalancer_repo_test.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_standard.go
/kind feature
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be migrated to the newly created standard load balancer, with their ip addresses unchanged. This operation may cause downtime.
Fixes #
```release-note
feat: Support migration from basic to standard load balancer
Introducing a new feature to migrate from basic to standard sku load balancer. To trigger the migration, switch `loadBalancerSKU` in the cloud provider configuration from `basic` to `standard`. The basic load balancer will be removed automatically, and service workloads on it will be …
```
=> [release-1.31] feat: Support migration from basic to standard load balancer

pkg/provider/azure_standard.go, pkg/provider/azure_standard_test.go
/kind bug
Azure Stack does not support the API Version, 2020-12-01, for PlatformFaultDomain, and therefore panics when we run the cloud provider on Azure Stack. This avoids the panic and sets the default fault domain.
Fixes #8754 
```release-note
NONE
```
```docs
```
=> Fix panic for GetZoneByNodeName on Azure Stack

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go
/kind bug
- Correct the AzureStackCloud condition check.
Generally on Azure stack hub, the `Environment.Name` is `HybridEnvironment`, from the source codes we expected using the cloud name `AzureStackCloud` compares with its `utils.AzureStackCloudName`.
```console
$ cat $AZURE_ENVIRONMENT_FILEPATH
{
"name": "HybridEnvironment",
"managementPortalURL": "",
"publishSettingsURL": "",
"serviceManagementEndpoint": "",
"resourceManagerEndpoint": "https://management.XXXXXX.com",
"activeDirectoryEndpoint": "https://login.microsoftonline.com/",
"galleryEndpoint": "https://providers.azs2.local:30016/",
"keyVaultEndpoint": "https://vault.XXXXXX.com",
"managedHSMEndpoint": "",
"graphEndpoint": "https://graph.windows.net/",
"serviceBusEndpoint": "",
"batchManagementEndpoint": "", …
```
=> fix: azure stack hub volume detach failed

pkg/provider/azure_controller_standard.go, pkg/provider/azure_controller_vmss.go, pkg/provider/azure_controller_vmssflex.go
/kind cleanup
fix: remove unnecessary get vmss call during disk attach
cherrypick of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8874
Fixes #
```release-note
fix: remove unnecessary get vmss call during disk attach
```
```docs
fix: remove unnecessary get vmss call during disk attach
```
=> [release-1.32] fix: remove unnecessary get vmss call during disk attach

pkg/provider/azure_controller_vmss.go
/kind bug
fix: reduce get disk calls in disk attach/detach on VMSS#2
add missing fix of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8623
Fixes #
```release-note
fix: reduce get disk calls in disk attach/detach on VMSS#2
```
```docs
fix: reduce get disk calls in disk attach/detach on VMSS#2
```
=> [release-1.32] fix: reduce get disk calls in disk attach/detach on VMSS#2

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
We should ignore cases when comparing lb names in shouldChangeLoadBalancer, as in some cases the lb name would be all upper-case for unknown reason.
Fixes #
```release-note
fix: Ignore cases when comparing load balancer names
```
```docs
```
=> fix: Ignore cases when comparing load balancer names

pkg/provider/storage/azure_storageaccount.go, pkg/provider/storage/azure_storageaccount_test.go
/kind feature
feat: add VNetLinkName and PublicNetworkAccess in account creation
Fixes #
```release-note
feat: add VNetLinkName and PublicNetworkAccess in account creation
```
```docs
feat: add VNetLinkName and PublicNetworkAccess in account creation
```
=> feat: add VNetLinkName and PublicNetworkAccess in account creation

pkg/consts/consts.go
/kind bug
fix: ResourceNotFound error
in some error code, the ResourceNotFound error is actually  `ERROR CODE: NotFound`, this PR could cover this error now
```
failed to ensure storage account: get virtual link for vnet(aks-vnet-24437392) and DNS Zone(privatelink.file.core.windows.net) in resourceGroup(MC_andy-aks131euap_andy-aks131euap_eastus2euap) returned with GET https://management.azure.com/subscriptions/xxx/resourceGroups/MC_andy-aks131euap_andy-aks131euap_eastus2euap/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net/virtualNetworkLinks/customvnetlink
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: NotFound
----------------------------------------------------------------------------- …
```
=> fix: ResourceNotFound error

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
We should ignore cases when comparing lb names in shouldChangeLoadBalancer, as in some cases the lb name would be all upper-case for unknown reason.
Fixes #
```release-note
fix: Ignore cases when comparing load balancer names
```
```docs
```
=> [release-1.29] fix: Ignore cases when comparing load balancer names

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go
/kind bug
We should ignore cases when comparing lb names in shouldChangeLoadBalancer, as in some cases the lb name would be all upper-case for unknown reason.
Fixes #
```release-note
fix: Ignore cases when comparing load balancer names
```
```docs
```
=> [release-1.30] fix: Ignore cases when comparing load balancer names

.github/dependabot.yml
/kind testing
Chore: add dependabot job for release-1.33 branch
Fixes #
```release-note
NONE
```
```docs
```
=> Chore: add dependabot job for release-1.33 branch

pkg/azclient/arm_conf.go, pkg/azclient/go.mod, pkg/azclient/go.sum, pkg/azclient/policy/retryaftermin/retryaftermin.go, pkg/azclient/policy/retryaftermin/retryaftermin_test.go
/kind feature
There is a CRP Extension bug that adversely impacts csi-driver's attach/detach latency. The symptom of the issue is that a high retry-after value of 37 seconds is returned on 4th GET request for async operation tracking. To mitigate the impact, we need to issue GET requests with more delay in between. So, this PR adds option to add custom retry policy that will remove the retry-after header from the http response if the value is lower than the configured minimum.
Example HTTP Header:
Headers:
{
Retry-After: 37
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetOperationResource;41
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetOperationSubscriptionMaximum;14994
x-ms-need-to-refresh-epl-cache: False
Content-Type: application/json; charset=utf-8
}
Fixes # …
=> feat: add option to override ARM retry-after if the value is lower than the configured minimum

pkg/azclient/fileshareclient/custom.go, pkg/azclient/fileshareclient/interface.go, pkg/azclient/fileshareclient/mock_fileshareclient/interface.go
/kind bug
Track2 sdk: replace expand with deleteoption in delete func of fileshare client
Fixes #
```release-note
NONE
```
```docs
Track2 sdk: replace expand with deleteoption in delete func of fileshare client
```
=> Track2 sdk: replace expand with deleteoption in delete func of fileshare client

pkg/provider/azure_utils.go, pkg/provider/azure_utils_test.go
/kind bug
In some cases service.spec.ipfamilies would be empty, and we need to set a default value.
Fixes #9097
```release-note
fix: Set default ipfamilies to ipv4 if the field is empty
```
```docs
```
=> fix: Set default ipfamilies to ipv4 if the field is empty

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_test.go
/kind bug
The LB ETag would change after deleting PLS, causing 412 error when putting the load balancer. This PR retries reconcileLoadBalancer function immediately after removing PLS. In the next run, lb will be re-listed so the latest ETag would be fetched.
Fixes #9108
```release-note
fix: Retry reconcileLoadBalancer after removing PLS
```
```docs
```
=> fix: Retry reconcileLoadBalancer after removing PLS

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_test.go
/kind bug
The LB ETag would change after deleting PLS, causing 412 error when putting the load balancer. This PR retries reconcileLoadBalancer function immediately after removing PLS. In the next run, lb will be re-listed so the latest ETag would be fetched.
Fixes #9108
```release-note
fix: Retry reconcileLoadBalancer after removing PLS
```
```docs
```
=> [release-1.30] fix: Retry reconcileLoadBalancer after removing PLS

pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_test.go, pkg/provider/azure_privatelinkservice.go, pkg/provider/azure_privatelinkservice_test.go, pkg/provider/azure_test.go
/kind bug
The LB ETag would change after deleting PLS, causing 412 error when putting the load balancer. This PR retries reconcileLoadBalancer function immediately after removing PLS. In the next run, lb will be re-listed so the latest ETag would be fetched.
Fixes #9108
```release-note
fix: Retry reconcileLoadBalancer after removing PLS
```
```docs
```
=> [release-1.31] fix: Retry reconcileLoadBalancer after removing PLS

pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go
/kind cleanup
When the annotation `service.beta.kubernetes.io/azure-allowed-ip-ranges` or the field `spec.LoadBalancerSourceRanges` is set to `0.0.0.0/0` or `::/0`, adding the Internet service tag to the security group becomes unnecessary, as the specified IP ranges already permit all traffic. This approach can significantly reduce the number of security rules required.
Fixes #
```release-note
Skip adding Internet service tag if IP ranges allow all
```
```docs
```
=> Skip adding Internet service tag if IP ranges allow all

pkg/provider/storage/azure_storageaccount.go
/kind bug
fix: don't change subnet.PrivateEndpointNetworkPolicies setting if it's already set
Fixes #
```release-note
fix: don't change subnet.PrivateEndpointNetworkPolicies setting if it's already set
```
```docs
fix: don't change subnet.PrivateEndpointNetworkPolicies setting if it's already set
```
=> fix: don't change subnet.PrivateEndpointNetworkPolicies setting if it's already set

pkg/azclient/loadbalancerclient/interface.go, pkg/azclient/loadbalancerclient/zz_generated_client.go
/kind chore
The current AzureStackCloud API version for the LoadBalancerClient, 2018-11-01, is
too old to view the `privateIPAddressVersion` on FrontEndIPConfiguration.
Bump to the latest API model.
`privateIPAddressVersion` was added in [2019-04-01](https://github.com/Azure/azure-rest-api-specs/blob/dfb1837bab3c6940fb0a0e745ee1db9bdbd440b3/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/loadBalancer.json#L1165C10-L1165C33). 
Fixes #
```release-note
chore: bump lbclient to latest API version for AzureStackCloud
```
```docs
chore: bump lbclient to latest API version for AzureStackCloud
```
=> chore: bump lbclient to latest API version for AzureStackCloud

tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ci-version-oot-credential-provider.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-dual-stack-mp.yaml, tests/k8s-azure/manifest/cluster-api/cluster-template-prow-ipv6-mp.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win-local.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-no-win.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, tests/k8s-azure/manifest/cluster-api/linux-vmss-multiple-zones-ci-version.yaml
/kind bug
This PR follows up from #7519 to remove feature gates that have graduated to GA and are no longer valid, causing control plane components to fail to start. Specifically the `HPAContainerMetrics` (removed in 1.32, default true since v1.27) and `WindowsHostProcessContainers` (removed in 1.28) are removed from cluster definitions.
It should improve the state of these CI jobs:
- https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-conformance-multiple-zones-vmss-capz
- https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-dualstack-vmss-capz
- https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-ipv6-vmss-capz
- …
=> test: Delete removed feature gates from CAPZ templates

pkg/provider/azure_vmsets_repo.go, pkg/provider/azure_vmss.go, pkg/provider/azure_vmss_test.go, pkg/provider/config/azure_cache.go
/kind bug
There are 2 API calls for [VMSS VM List](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list?view=rest-compute-2025-02-01&tabs=HTTP); however, the sdk only implements the one with instance-view parameter. 
VMSS VM List API with instance-view parameter times out when a cluster zone is not available and is not reliable for scenarios that require zonal redundance. I am adding an option of selecting which API to call to populate the cache in order to accommodate all scenarios. 
Fixes # The implemented VMSS VM List API times out when a zone becomes unavailable. 
```release-note
chore: add option to list vmss vms without instance view
```
```docs
chore: add option to list vmss vms without instance view
```
=> chore: add option to list vmss vms without instance view

pkg/provider/azure.go, pkg/provider/azure_fakes.go, pkg/provider/azure_loadbalancer.go, pkg/provider/azure_loadbalancer_accesscontrol.go, pkg/provider/azure_loadbalancer_accesscontrol_test.go, pkg/provider/loadbalancer/accesscontrol.go, pkg/provider/loadbalancer/accesscontrol_test.go, pkg/provider/securitygroup/securitygroup.go, pkg/provider/securitygroup/securitygroup_test.go, pkg/provider/securitygroup/securityrule.go, pkg/provider/securitygroup/securityrule_test.go
/kind bug
cherry-pick #9417 
Fixes #
```release-note
Clean backend pool node destination while reconciling security group
```
```docs
```
=> [release-1.34] Clean backend pool node destination while reconciling security group
